/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("core") @:is_resource(false) @:is_node(false) extern class AccessibilityServer extends godot.Object {
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_supported")
	public static function is_supported():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3846965249.)
	@:hash_compatibility(null)
	@:nativeName("create_element")
	@:argMeta(0, ":meta"("int32"))
	public static function create_element(@:meta("int32") window_id:Int, role:godot.AccessibilityServer_AccessibilityRole):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1151690429)
	@:hash_compatibility(null)
	@:nativeName("create_sub_element")
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("-1"))
	#if gdscript @:argMeta(2, ":noNullPad"("-1")) #end
	public static function create_sub_element(parent_rid:godot.RID, role:godot.AccessibilityServer_AccessibilityRole, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end insert_pos:Int = -1):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2702009895.)
	@:hash_compatibility(null)
	@:nativeName("create_sub_text_edit_elements")
	@:argMeta(2, ":meta"("float"))
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(3, ":default_value"("-1"))
	#if gdscript @:argMeta(3, ":noNullPad"("-1")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public static function create_sub_text_edit_elements(parent_rid:godot.RID, shaped_text:godot.RID, @:meta("float") min_height:Float, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end insert_pos:Int = -1, @:default_value("false") #if gdscript @:noNullPad("false") #end is_last_line:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("has_element")
	public static function has_element(id:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_element")
	public static function free_element(id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175752987.)
	@:hash_compatibility(null)
	@:nativeName("element_set_meta")
	public static function element_set_meta(id:godot.RID, meta:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4171304767.)
	@:hash_compatibility(null)
	@:nativeName("element_get_meta")
	public static function element_get_meta(id:godot.RID):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2386961724.)
	@:hash_compatibility(null)
	@:nativeName("set_window_rect")
	@:argMeta(0, ":meta"("int32"))
	public static function set_window_rect(@:meta("int32") window_id:Int, rect_out:godot.Rect2, rect_in:godot.Rect2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_window_focused")
	@:argMeta(0, ":meta"("int32"))
	public static function set_window_focused(@:meta("int32") window_id:Int, focused:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("update_set_focus")
	public static function update_set_focus(id:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(495598643)
	@:hash_compatibility(null)
	@:nativeName("get_window_root")
	@:argMeta(0, ":meta"("int32"))
	public static function get_window_root(@:meta("int32") window_id:Int):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3747886520.)
	@:hash_compatibility(null)
	@:nativeName("update_set_role")
	public static function update_set_role(id:godot.RID, role:godot.AccessibilityServer_AccessibilityRole):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_name")
	public static function update_set_name(id:godot.RID, name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_braille_label")
	public static function update_set_braille_label(id:godot.RID, name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_braille_role_description")
	public static function update_set_braille_role_description(id:godot.RID, description:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_extra_info")
	public static function update_set_extra_info(id:godot.RID, name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_description")
	public static function update_set_description(id:godot.RID, description:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_value")
	public static function update_set_value(id:godot.RID, value:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_tooltip")
	public static function update_set_tooltip(id:godot.RID, tooltip:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1378122625)
	@:hash_compatibility(null)
	@:nativeName("update_set_bounds")
	public static function update_set_bounds(id:godot.RID, rect:godot.Rect2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1246044741)
	@:hash_compatibility(null)
	@:nativeName("update_set_transform")
	public static function update_set_transform(id:godot.RID, transform:godot.Transform2D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_child")
	public static function update_add_child(id:godot.RID, child_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_related_controls")
	public static function update_add_related_controls(id:godot.RID, related_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_related_details")
	public static function update_add_related_details(id:godot.RID, related_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_related_described_by")
	public static function update_add_related_described_by(id:godot.RID, related_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_related_flow_to")
	public static function update_add_related_flow_to(id:godot.RID, related_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_related_labeled_by")
	public static function update_add_related_labeled_by(id:godot.RID, related_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_add_related_radio_group")
	public static function update_add_related_radio_group(id:godot.RID, related_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_set_active_descendant")
	public static function update_set_active_descendant(id:godot.RID, other_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_set_next_on_line")
	public static function update_set_next_on_line(id:godot.RID, other_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_set_previous_on_line")
	public static function update_set_previous_on_line(id:godot.RID, other_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_set_member_of")
	public static function update_set_member_of(id:godot.RID, group_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_set_in_page_link_target")
	public static function update_set_in_page_link_target(id:godot.RID, other_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("update_set_error_message")
	public static function update_set_error_message(id:godot.RID, other_id:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2993365237.)
	@:hash_compatibility(null)
	@:nativeName("update_set_live")
	public static function update_set_live(id:godot.RID, live:godot.AccessibilityServer_AccessibilityLiveMode):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3960092835.)
	@:hash_compatibility(null)
	@:nativeName("update_add_action")
	public static function update_add_action(id:godot.RID, action:godot.AccessibilityServer_AccessibilityAction, callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4153150897.)
	@:hash_compatibility(null)
	@:nativeName("update_add_custom_action")
	@:argMeta(1, ":meta"("int32"))
	public static function update_add_custom_action(id:godot.RID, @:meta("int32") action_id:Int, action_description:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_table_row_count")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_table_row_count(id:godot.RID, @:meta("int32") count:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_table_column_count")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_table_column_count(id:godot.RID, @:meta("int32") count:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_table_row_index")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_table_row_index(id:godot.RID, @:meta("int32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_table_column_index")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_table_column_index(id:godot.RID, @:meta("int32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4288446313.)
	@:hash_compatibility(null)
	@:nativeName("update_set_table_cell_position")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function update_set_table_cell_position(id:godot.RID, @:meta("int32") row_index:Int, @:meta("int32") column_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4288446313.)
	@:hash_compatibility(null)
	@:nativeName("update_set_table_cell_span")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function update_set_table_cell_span(id:godot.RID, @:meta("int32") row_span:Int, @:meta("int32") column_span:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_list_item_count")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_list_item_count(id:godot.RID, @:meta("int32") size:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_list_item_index")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_list_item_index(id:godot.RID, @:meta("int32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("update_set_list_item_level")
	@:argMeta(1, ":meta"("int32"))
	public static function update_set_list_item_level(id:godot.RID, @:meta("int32") level:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("update_set_list_item_selected")
	public static function update_set_list_item_selected(id:godot.RID, selected:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("update_set_list_item_expanded")
	public static function update_set_list_item_expanded(id:godot.RID, expanded:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(690307634)
	@:hash_compatibility(null)
	@:nativeName("update_set_popup_type")
	public static function update_set_popup_type(id:godot.RID, popup:godot.AccessibilityServer_AccessibilityPopupType):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("update_set_checked")
	public static function update_set_checked(id:godot.RID, checekd:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("update_set_num_value")
	@:argMeta(1, ":meta"("double"))
	public static function update_set_num_value(id:godot.RID, @:meta("double") position:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2513314492.)
	@:hash_compatibility(null)
	@:nativeName("update_set_num_range")
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("double"))
	public static function update_set_num_range(id:godot.RID, @:meta("double") min:Float, @:meta("double") max:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("update_set_num_step")
	@:argMeta(1, ":meta"("double"))
	public static function update_set_num_step(id:godot.RID, @:meta("double") step:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("update_set_num_jump")
	@:argMeta(1, ":meta"("double"))
	public static function update_set_num_jump(id:godot.RID, @:meta("double") jump:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("update_set_scroll_x")
	@:argMeta(1, ":meta"("double"))
	public static function update_set_scroll_x(id:godot.RID, @:meta("double") position:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2513314492.)
	@:hash_compatibility(null)
	@:nativeName("update_set_scroll_x_range")
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("double"))
	public static function update_set_scroll_x_range(id:godot.RID, @:meta("double") min:Float, @:meta("double") max:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("update_set_scroll_y")
	@:argMeta(1, ":meta"("double"))
	public static function update_set_scroll_y(id:godot.RID, @:meta("double") position:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2513314492.)
	@:hash_compatibility(null)
	@:nativeName("update_set_scroll_y_range")
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("double"))
	public static function update_set_scroll_y_range(id:godot.RID, @:meta("double") min:Float, @:meta("double") max:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(457503484)
	@:hash_compatibility(null)
	@:nativeName("update_set_text_decorations")
	@:argMeta(4, ":default_value"("Color(0, 0, 0, 1)"))
	#if gdscript @:argMeta(4, ":noNullPad"("Color(0, 0, 0, 1)")) #end
	public static function update_set_text_decorations(id:godot.RID, underline:Bool, strikethrough:Bool, overline:Bool, @:default_value("Color(0, 0, 0, 1)") #if gdscript @:noNullPad("Color(0, 0, 0, 1)") #end ?color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3725995085.)
	@:hash_compatibility(null)
	@:nativeName("update_set_text_align")
	public static function update_set_text_align(id:godot.RID, align:godot.HorizontalAlignment):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3119144029.)
	@:hash_compatibility(null)
	@:nativeName("update_set_text_selection")
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(4, ":meta"("int32"))
	public static function update_set_text_selection(id:godot.RID, text_start_id:godot.RID, @:meta("int32") start_char:Int, text_end_id:godot.RID, @:meta("int32") end_char:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1473043386)
	@:hash_compatibility(null)
	@:nativeName("update_set_flag")
	public static function update_set_flag(id:godot.RID, flag:godot.AccessibilityServer_AccessibilityFlags, value:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_classname")
	public static function update_set_classname(id:godot.RID, classname:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_placeholder")
	public static function update_set_placeholder(id:godot.RID, placeholder:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_language")
	public static function update_set_language(id:godot.RID, language:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("update_set_text_orientation")
	public static function update_set_text_orientation(id:godot.RID, vertical:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("update_set_list_orientation")
	public static function update_set_list_orientation(id:godot.RID, vertical:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_shortcut")
	public static function update_set_shortcut(id:godot.RID, shortcut:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_url")
	public static function update_set_url(id:godot.RID, url:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_role_description")
	public static function update_set_role_description(id:godot.RID, description:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("update_set_state_description")
	public static function update_set_state_description(id:godot.RID, description:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2948539648.)
	@:hash_compatibility(null)
	@:nativeName("update_set_color_value")
	public static function update_set_color_value(id:godot.RID, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2948539648.)
	@:hash_compatibility(null)
	@:nativeName("update_set_background_color")
	public static function update_set_background_color(id:godot.RID, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2948539648.)
	@:hash_compatibility(null)
	@:nativeName("update_set_foreground_color")
	public static function update_set_foreground_color(id:godot.RID, color:godot.Color):Void;
}