/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class Animation extends godot.Resource {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_length")
	@:setter("set_length")
	public var length(get, set) : Float;
#else

	@:index(null)
	@:getter("get_length")
	@:setter("set_length")
	public var length : Float;
#end
#if !use_properties
	@:index(null)
	@:getter("get_loop_mode")
	@:setter("set_loop_mode")
	public var loop_mode : Int;
#end
#if use_properties
	@:index(null)
	@:getter("get_step")
	@:setter("set_step")
	public var step(get, set) : Float;
#else

	@:index(null)
	@:getter("get_step")
	@:setter("set_step")
	public var step : Float;
#end
#if use_properties
	@:index(null)
	@:getter("is_capture_included")
	@:setter(null)
	public var capture_included(get, never) : Bool;
#else

	@:index(null)
	@:getter("is_capture_included")
	@:setter(null)
	public var capture_included : Bool;
#end
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3843682357.)
	@:hash_compatibility([2393815928.])
	@:nativeName("add_track")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public function add_track(type:godot.Animation_TrackType, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end at_position:Int = -1):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_track")
	@:argMeta(0, ":meta"("int32"))
	public function remove_track(@:meta("int32") track_idx:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_track_count")
	public function get_track_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3445944217.)
	@:hash_compatibility(null)
	@:nativeName("track_get_type")
	@:argMeta(0, ":meta"("int32"))
	public function track_get_type(@:meta("int32") track_idx:Int):godot.Animation_TrackType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("track_get_path")
	@:argMeta(0, ":meta"("int32"))
	public function track_get_path(@:meta("int32") track_idx:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2761262315.)
	@:hash_compatibility(null)
	@:nativeName("track_set_path")
	@:argMeta(0, ":meta"("int32"))
	public function track_set_path(@:meta("int32") track_idx:Int, path:godot.NodePath):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(245376003)
	@:hash_compatibility(null)
	@:nativeName("find_track")
	public function find_track(path:godot.NodePath, type:godot.Animation_TrackType):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("track_move_up")
	@:argMeta(0, ":meta"("int32"))
	public function track_move_up(@:meta("int32") track_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("track_move_down")
	@:argMeta(0, ":meta"("int32"))
	public function track_move_down(@:meta("int32") track_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("track_move_to")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_move_to(@:meta("int32") track_idx:Int, @:meta("int32") to_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("track_swap")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_swap(@:meta("int32") track_idx:Int, @:meta("int32") with_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("track_set_imported")
	@:argMeta(0, ":meta"("int32"))
	public function track_set_imported(@:meta("int32") track_idx:Int, imported:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("track_is_imported")
	@:argMeta(0, ":meta"("int32"))
	public function track_is_imported(@:meta("int32") track_idx:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("track_set_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function track_set_enabled(@:meta("int32") track_idx:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("track_is_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function track_is_enabled(@:meta("int32") track_idx:Int):Bool;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2540608232.)
	@:hash_compatibility(null)
	@:nativeName("position_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function position_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, position:godot.Vector3):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4165004800.)
	@:hash_compatibility(null)
	@:nativeName("rotation_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function rotation_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, rotation:godot.Quaternion):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2540608232.)
	@:hash_compatibility(null)
	@:nativeName("scale_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function scale_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, scale:godot.Vector3):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1534913637)
	@:hash_compatibility(null)
	@:nativeName("blend_shape_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("float"))
	public function blend_shape_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, @:meta("float") amount:Float):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3530011197.)
	@:hash_compatibility([3285246857.])
	@:nativeName("position_track_interpolate")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function position_track_interpolate(@:meta("int32") track_idx:Int, @:meta("double") time_sec:Float, @:default_value("false") #if gdscript @:noNullPad("false") #end backward:Bool = false):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915876792.)
	@:hash_compatibility([1988711975])
	@:nativeName("rotation_track_interpolate")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function rotation_track_interpolate(@:meta("int32") track_idx:Int, @:meta("double") time_sec:Float, @:default_value("false") #if gdscript @:noNullPad("false") #end backward:Bool = false):godot.Quaternion;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3530011197.)
	@:hash_compatibility([3285246857.])
	@:nativeName("scale_track_interpolate")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function scale_track_interpolate(@:meta("int32") track_idx:Int, @:meta("double") time_sec:Float, @:default_value("false") #if gdscript @:noNullPad("false") #end backward:Bool = false):godot.Vector3;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2482365182.)
	@:hash_compatibility([1900462983])
	@:nativeName("blend_shape_track_interpolate")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function blend_shape_track_interpolate(@:meta("int32") track_idx:Int, @:meta("double") time_sec:Float, @:default_value("false") #if gdscript @:noNullPad("false") #end backward:Bool = false):Float;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(808952278)
	@:hash_compatibility([1985425300])
	@:nativeName("track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("1"))
	#if gdscript @:argMeta(3, ":noNullPad"("1")) #end
	public function track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, key:Dynamic, @:meta("float") @:default_value("1") #if gdscript @:noNullPad("1") #end transition:Float = 1.):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("track_remove_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_remove_key(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("track_remove_key_at_time")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function track_remove_key_at_time(@:meta("int32") track_idx:Int, @:meta("double") time:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2060538656)
	@:hash_compatibility(null)
	@:nativeName("track_set_key_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_set_key_value(@:meta("int32") track_idx:Int, @:meta("int32") key:Int, value:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("track_set_key_transition")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function track_set_key_transition(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, @:meta("float") transition:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("track_set_key_time")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("double"))
	public function track_set_key_time(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, @:meta("double") time:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("track_get_key_transition")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_get_key_transition(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Float;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("track_get_key_count")
	@:argMeta(0, ":meta"("int32"))
	public function track_get_key_count(@:meta("int32") track_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(678354945)
	@:hash_compatibility(null)
	@:nativeName("track_get_key_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_get_key_value(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Dynamic;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("track_get_key_time")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function track_get_key_time(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Float;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4230953007.)
	@:hash_compatibility([3245197284., 3898229885.])
	@:nativeName("track_find_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":default_value"("Animation.FindMode.FIND_MODE_NEAREST"))
	#if gdscript @:argMeta(2, ":noNullPad"("Animation.FindMode.FIND_MODE_NEAREST")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public function track_find_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, @:default_value("Animation.FindMode.FIND_MODE_NEAREST") #if gdscript @:noNullPad("Animation.FindMode.FIND_MODE_NEAREST") #end find_mode:godot.Animation_FindMode = godot.Animation_FindMode.FIND_MODE_NEAREST, @:default_value("false") #if gdscript @:noNullPad("false") #end limit:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end backward:Bool = false):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4112932513.)
	@:hash_compatibility(null)
	@:nativeName("track_set_interpolation_type")
	@:argMeta(0, ":meta"("int32"))
	public function track_set_interpolation_type(@:meta("int32") track_idx:Int, interpolation:godot.Animation_InterpolationType):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530756894)
	@:hash_compatibility(null)
	@:nativeName("track_get_interpolation_type")
	@:argMeta(0, ":meta"("int32"))
	public function track_get_interpolation_type(@:meta("int32") track_idx:Int):godot.Animation_InterpolationType;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("track_set_interpolation_loop_wrap")
	@:argMeta(0, ":meta"("int32"))
	public function track_set_interpolation_loop_wrap(@:meta("int32") track_idx:Int, interpolation:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("track_get_interpolation_loop_wrap")
	@:argMeta(0, ":meta"("int32"))
	public function track_get_interpolation_loop_wrap(@:meta("int32") track_idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("track_is_compressed")
	@:argMeta(0, ":meta"("int32"))
	public function track_is_compressed(@:meta("int32") track_idx:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2854058312.)
	@:hash_compatibility(null)
	@:nativeName("value_track_set_update_mode")
	@:argMeta(0, ":meta"("int32"))
	public function value_track_set_update_mode(@:meta("int32") track_idx:Int, mode:godot.Animation_UpdateMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1440326473)
	@:hash_compatibility(null)
	@:nativeName("value_track_get_update_mode")
	@:argMeta(0, ":meta"("int32"))
	public function value_track_get_update_mode(@:meta("int32") track_idx:Int):godot.Animation_UpdateMode;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(747269075)
	@:hash_compatibility([491147702])
	@:nativeName("value_track_interpolate")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function value_track_interpolate(@:meta("int32") track_idx:Int, @:meta("double") time_sec:Float, @:default_value("false") #if gdscript @:noNullPad("false") #end backward:Bool = false):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(351665558)
	@:hash_compatibility(null)
	@:nativeName("method_track_get_name")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function method_track_get_name(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2345056839.)
	@:hash_compatibility(null)
	@:nativeName("method_track_get_params")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function method_track_get_params(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):GodotArray;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3656773645.)
	@:hash_compatibility([1057544502])
	@:nativeName("bezier_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("float"))
	@:argMeta(3, ":default_value"("Vector2(0, 0)"))
	#if gdscript @:argMeta(3, ":noNullPad"("Vector2(0, 0)")) #end
	@:argMeta(4, ":default_value"("Vector2(0, 0)"))
	#if gdscript @:argMeta(4, ":noNullPad"("Vector2(0, 0)")) #end
	public function bezier_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, @:meta("float") value:Float, @:default_value("Vector2(0, 0)") #if gdscript @:noNullPad("Vector2(0, 0)") #end ?in_handle:godot.Vector2, @:default_value("Vector2(0, 0)") #if gdscript @:noNullPad("Vector2(0, 0)") #end ?out_handle:godot.Vector2):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("bezier_track_set_key_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function bezier_track_set_key_value(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, @:meta("float") value:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1719223284)
	@:hash_compatibility([1028302688])
	@:nativeName("bezier_track_set_key_in_handle")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("1.0"))
	#if gdscript @:argMeta(3, ":noNullPad"("1.0")) #end
	public function bezier_track_set_key_in_handle(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, in_handle:godot.Vector2, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end balanced_value_time_ratio:Float = 1.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1719223284)
	@:hash_compatibility([1028302688])
	@:nativeName("bezier_track_set_key_out_handle")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("1.0"))
	#if gdscript @:argMeta(3, ":noNullPad"("1.0")) #end
	public function bezier_track_set_key_out_handle(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, out_handle:godot.Vector2, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end balanced_value_time_ratio:Float = 1.):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("bezier_track_get_key_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function bezier_track_get_key_value(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3016396712.)
	@:hash_compatibility(null)
	@:nativeName("bezier_track_get_key_in_handle")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function bezier_track_get_key_in_handle(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3016396712.)
	@:hash_compatibility(null)
	@:nativeName("bezier_track_get_key_out_handle")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function bezier_track_get_key_out_handle(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):godot.Vector2;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1900462983)
	@:hash_compatibility(null)
	@:nativeName("bezier_track_interpolate")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function bezier_track_interpolate(@:meta("int32") track_idx:Int, @:meta("double") time:Float):Float;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4021027286.)
	@:hash_compatibility([3489962123.])
	@:nativeName("audio_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	@:argMeta(4, ":meta"("float"))
	@:argMeta(4, ":default_value"("0"))
	#if gdscript @:argMeta(4, ":noNullPad"("0")) #end
	public function audio_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, stream:godot.Resource, @:meta("float") @:default_value("0") #if gdscript @:noNullPad("0") #end start_offset:Float = 0., @:meta("float") @:default_value("0") #if gdscript @:noNullPad("0") #end end_offset:Float = 0.):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3886397084.)
	@:hash_compatibility(null)
	@:nativeName("audio_track_set_key_stream")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function audio_track_set_key_stream(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, stream:godot.Resource):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("audio_track_set_key_start_offset")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function audio_track_set_key_start_offset(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, @:meta("float") offset:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("audio_track_set_key_end_offset")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function audio_track_set_key_end_offset(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, @:meta("float") offset:Float):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(635277205)
	@:hash_compatibility(null)
	@:nativeName("audio_track_get_key_stream")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function audio_track_get_key_stream(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):godot.Resource;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("audio_track_get_key_start_offset")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function audio_track_get_key_start_offset(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("audio_track_get_key_end_offset")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function audio_track_get_key_end_offset(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("audio_track_set_use_blend")
	@:argMeta(0, ":meta"("int32"))
	public function audio_track_set_use_blend(@:meta("int32") track_idx:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("audio_track_is_use_blend")
	@:argMeta(0, ":meta"("int32"))
	public function audio_track_is_use_blend(@:meta("int32") track_idx:Int):Bool;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(158676774)
	@:hash_compatibility(null)
	@:nativeName("animation_track_insert_key")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function animation_track_insert_key(@:meta("int32") track_idx:Int, @:meta("double") time:Float, animation:godot.StringName):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(117615382)
	@:hash_compatibility(null)
	@:nativeName("animation_track_set_key_animation")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function animation_track_set_key_animation(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int, animation:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(351665558)
	@:hash_compatibility(null)
	@:nativeName("animation_track_get_key_animation")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function animation_track_get_key_animation(@:meta("int32") track_idx:Int, @:meta("int32") key_idx:Int):godot.StringName;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4135858297.)
	@:hash_compatibility(null)
	@:nativeName("add_marker")
	@:argMeta(1, ":meta"("double"))
	public function add_marker(name:godot.StringName, @:meta("double") time:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("remove_marker")
	public function remove_marker(name:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("has_marker")
	public function has_marker(name:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4079494655.)
	@:hash_compatibility(null)
	@:nativeName("get_marker_at_time")
	@:argMeta(0, ":meta"("double"))
	public function get_marker_at_time(@:meta("double") time:Float):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4079494655.)
	@:hash_compatibility(null)
	@:nativeName("get_next_marker")
	@:argMeta(0, ":meta"("double"))
	public function get_next_marker(@:meta("double") time:Float):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4079494655.)
	@:hash_compatibility(null)
	@:nativeName("get_prev_marker")
	@:argMeta(0, ":meta"("double"))
	public function get_prev_marker(@:meta("double") time:Float):godot.StringName;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2349060816.)
	@:hash_compatibility(null)
	@:nativeName("get_marker_time")
	public function get_marker_time(name:godot.StringName):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_marker_names")
	public function get_marker_names():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3742943038.)
	@:hash_compatibility(null)
	@:nativeName("get_marker_color")
	public function get_marker_color(name:godot.StringName):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4260178595.)
	@:hash_compatibility(null)
	@:nativeName("set_marker_color")
	public function set_marker_color(name:godot.StringName, color:godot.Color):Void;
#if use_properties
	public extern inline function set_length(v: Float): Float {
		set_length_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_length")
	@:native("set_length")
	@:argMeta(0, ":meta"("double"))
	public function set_length_impl(@:meta("double") time_sec:Float):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_length")
	@:argMeta(0, ":meta"("double"))
	public function set_length(@:meta("double") time_sec:Float):Void;

#end
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_length")
	public function get_length():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3155355575.)
	@:hash_compatibility(null)
	@:nativeName("set_loop_mode")
	public function set_loop_mode(loop_mode:godot.Animation_LoopMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1988889481)
	@:hash_compatibility(null)
	@:nativeName("get_loop_mode")
	public function get_loop_mode():godot.Animation_LoopMode;
#if use_properties
	public extern inline function set_step(v: Float): Float {
		set_step_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_step")
	@:native("set_step")
	@:argMeta(0, ":meta"("float"))
	public function set_step_impl(@:meta("float") size_sec:Float):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_step")
	@:argMeta(0, ":meta"("float"))
	public function set_step(@:meta("float") size_sec:Float):Void;

#end
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_step")
	public function get_step():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(148001024)
	@:hash_compatibility(null)
	@:nativeName("copy_track")
	@:argMeta(0, ":meta"("int32"))
	public function copy_track(@:meta("int32") track_idx:Int, to_animation:godot.Animation):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3303583852.)
	@:hash_compatibility(null)
	@:nativeName("optimize")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(0, ":default_value"("0.01"))
	#if gdscript @:argMeta(0, ":noNullPad"("0.01")) #end
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("0.01"))
	#if gdscript @:argMeta(1, ":noNullPad"("0.01")) #end
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("3"))
	#if gdscript @:argMeta(2, ":noNullPad"("3")) #end
	public function optimize(@:meta("float") @:default_value("0.01") #if gdscript @:noNullPad("0.01") #end allowed_velocity_err:Float = 0.01, @:meta("float") @:default_value("0.01") #if gdscript @:noNullPad("0.01") #end allowed_angular_err:Float = 0.01, @:meta("int32") @:default_value("3") #if gdscript @:noNullPad("3") #end precision:Int = 3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3608408117.)
	@:hash_compatibility(null)
	@:nativeName("compress")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(0, ":default_value"("8192"))
	#if gdscript @:argMeta(0, ":noNullPad"("8192")) #end
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("120"))
	#if gdscript @:argMeta(1, ":noNullPad"("120")) #end
	@:argMeta(2, ":meta"("float"))
	@:argMeta(2, ":default_value"("4.0"))
	#if gdscript @:argMeta(2, ":noNullPad"("4.0")) #end
	public function compress(@:meta("uint32") @:default_value("8192") #if gdscript @:noNullPad("8192") #end page_size:Int = 8192, @:meta("uint32") @:default_value("120") #if gdscript @:noNullPad("120") #end fps:Int = 120, @:meta("float") @:default_value("4.0") #if gdscript @:noNullPad("4.0") #end split_tolerance:Float = 4.):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_capture_included")
	@:native("is_capture_included")
	public function get_capture_included():Bool;
}