/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class AStar3D extends godot.RefCounted {
	public function new();
#if use_properties
	@:index(null)
	@:getter("is_neighbor_filter_enabled")
	@:setter("set_neighbor_filter_enabled")
	public var neighbor_filter_enabled(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_neighbor_filter_enabled")
	@:setter("set_neighbor_filter_enabled")
	public var neighbor_filter_enabled : Bool;
#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2522259332.)
	@:hash_compatibility(null)
	@:nativeName("_filter_neighbor")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	public function _filter_neighbor(@:meta("int64") from_id:Int, @:meta("int64") neighbor_id:Int):Bool;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("_estimate_cost")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	public function _estimate_cost(@:meta("int64") from_id:Int, @:meta("int64") end_id:Int):Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("_compute_cost")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	public function _compute_cost(@:meta("int64") from_id:Int, @:meta("int64") to_id:Int):Float;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_available_point_id")
	public function get_available_point_id():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1038703438)
	@:hash_compatibility([2920922839.])
	@:nativeName("add_point")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("float"))
	@:argMeta(2, ":default_value"("1.0"))
	#if gdscript @:argMeta(2, ":noNullPad"("1.0")) #end
	public function add_point(@:meta("int64") id:Int, position:godot.Vector3, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end weight_scale:Float = 1.):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_point_position")
	@:argMeta(0, ":meta"("int64"))
	public function get_point_position(@:meta("int64") id:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530502735)
	@:hash_compatibility(null)
	@:nativeName("set_point_position")
	@:argMeta(0, ":meta"("int64"))
	public function set_point_position(@:meta("int64") id:Int, position:godot.Vector3):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_point_weight_scale")
	@:argMeta(0, ":meta"("int64"))
	public function get_point_weight_scale(@:meta("int64") id:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_point_weight_scale")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("float"))
	public function set_point_weight_scale(@:meta("int64") id:Int, @:meta("float") weight_scale:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_point")
	@:argMeta(0, ":meta"("int64"))
	public function remove_point(@:meta("int64") id:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("has_point")
	@:argMeta(0, ":meta"("int64"))
	public function has_point(@:meta("int64") id:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2865087369.)
	@:hash_compatibility(null)
	@:nativeName("get_point_connections")
	@:argMeta(0, ":meta"("int64"))
	public function get_point_connections(@:meta("int64") id:Int):godot.PackedInt64Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3851388692.)
	@:hash_compatibility(null)
	@:nativeName("get_point_ids")
	public function get_point_ids():godot.PackedInt64Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(972357352)
	@:hash_compatibility([4023243586.])
	@:nativeName("set_point_disabled")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public function set_point_disabled(@:meta("int64") id:Int, @:default_value("true") #if gdscript @:noNullPad("true") #end disabled:Bool = true):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_point_disabled")
	@:argMeta(0, ":meta"("int64"))
	public function is_point_disabled(@:meta("int64") id:Int):Bool;
#if use_properties
	public extern inline function set_neighbor_filter_enabled(v: Bool): Bool {
		set_neighbor_filter_enabled_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_neighbor_filter_enabled")
	@:native("set_neighbor_filter_enabled")
	public function set_neighbor_filter_enabled_impl(enabled:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_neighbor_filter_enabled")
	public function set_neighbor_filter_enabled(enabled:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_neighbor_filter_enabled")
	@:native("is_neighbor_filter_enabled")
	public function get_neighbor_filter_enabled():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3710494224.)
	@:hash_compatibility([3785370599.])
	@:nativeName("connect_points")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":default_value"("true"))
	#if gdscript @:argMeta(2, ":noNullPad"("true")) #end
	public function connect_points(@:meta("int64") id:Int, @:meta("int64") to_id:Int, @:default_value("true") #if gdscript @:noNullPad("true") #end bidirectional:Bool = true):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3710494224.)
	@:hash_compatibility([3785370599.])
	@:nativeName("disconnect_points")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":default_value"("true"))
	#if gdscript @:argMeta(2, ":noNullPad"("true")) #end
	public function disconnect_points(@:meta("int64") id:Int, @:meta("int64") to_id:Int, @:default_value("true") #if gdscript @:noNullPad("true") #end bidirectional:Bool = true):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2288175859.)
	@:hash_compatibility([4063588998.])
	@:nativeName("are_points_connected")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":default_value"("true"))
	#if gdscript @:argMeta(2, ":noNullPad"("true")) #end
	public function are_points_connected(@:meta("int64") id:Int, @:meta("int64") to_id:Int, @:default_value("true") #if gdscript @:noNullPad("true") #end bidirectional:Bool = true):Bool;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_point_count")
	public function get_point_count():Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_point_capacity")
	public function get_point_capacity():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("reserve_space")
	@:argMeta(0, ":meta"("int64"))
	public function reserve_space(@:meta("int64") num_nodes:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3241074317.)
	@:hash_compatibility(null)
	@:nativeName("get_closest_point")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function get_closest_point(to_position:godot.Vector3, @:default_value("false") #if gdscript @:noNullPad("false") #end include_disabled:Bool = false):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(192990374)
	@:hash_compatibility(null)
	@:nativeName("get_closest_position_in_segment")
	public function get_closest_position_in_segment(to_position:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1562654675)
	@:hash_compatibility([880819742])
	@:nativeName("get_point_path")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function get_point_path(@:meta("int64") from_id:Int, @:meta("int64") to_id:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end allow_partial_path:Bool = false):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3136199648.)
	@:hash_compatibility([3404614526.])
	@:nativeName("get_id_path")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function get_id_path(@:meta("int64") from_id:Int, @:meta("int64") to_id:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end allow_partial_path:Bool = false):godot.PackedInt64Array;
}