/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class AudioServer extends godot.Object {
#if use_properties
	@:index(null)
	@:getter("get_bus_count")
	@:setter("set_bus_count")
	public static var bus_count(get, set) : Int;
#else

	@:index(null)
	@:getter("get_bus_count")
	@:setter("set_bus_count")
	public static var bus_count : Int;
#end
#if use_properties
	@:index(null)
	@:getter("get_output_device")
	@:setter("set_output_device")
	@:reassignOnSubfieldEdit(set_output_device_impl)
	public static var output_device(get, set) : String;
#else

	@:index(null)
	@:getter("get_output_device")
	@:setter("set_output_device")
	public static var output_device : String;
#end
#if use_properties
	@:index(null)
	@:getter("get_input_device")
	@:setter("set_input_device")
	@:reassignOnSubfieldEdit(set_input_device_impl)
	public static var input_device(get, set) : String;
#else

	@:index(null)
	@:getter("get_input_device")
	@:setter("set_input_device")
	public static var input_device : String;
#end
#if use_properties
	@:index(null)
	@:getter("get_playback_speed_scale")
	@:setter("set_playback_speed_scale")
	public static var playback_speed_scale(get, set) : Float;
#else

	@:index(null)
	@:getter("get_playback_speed_scale")
	@:setter("set_playback_speed_scale")
	public static var playback_speed_scale : Float;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_bus_count")
	@:argMeta(0, ":meta"("int32"))
	public static function set_bus_count(@:meta("int32") amount:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_count")
	public static function get_bus_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_bus")
	@:argMeta(0, ":meta"("int32"))
	public static function remove_bus(@:meta("int32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025054187)
	@:hash_compatibility(null)
	@:nativeName("add_bus")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public static function add_bus(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end at_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("move_bus")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function move_bus(@:meta("int32") index:Int, @:meta("int32") to_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_bus_name")
	@:argMeta(0, ":meta"("int32"))
	public static function set_bus_name(@:meta("int32") bus_idx:Int, name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_bus_name")
	@:argMeta(0, ":meta"("int32"))
	public static function get_bus_name(@:meta("int32") bus_idx:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2458036349.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_index")
	public static function get_bus_index(bus_name:godot.StringName):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_bus_channels")
	@:argMeta(0, ":meta"("int32"))
	public static function get_bus_channels(@:meta("int32") bus_idx:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_bus_volume_db")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public static function set_bus_volume_db(@:meta("int32") bus_idx:Int, @:meta("float") volume_db:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_volume_db")
	@:argMeta(0, ":meta"("int32"))
	public static function get_bus_volume_db(@:meta("int32") bus_idx:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_bus_volume_linear")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public static function set_bus_volume_linear(@:meta("int32") bus_idx:Int, @:meta("float") volume_linear:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_volume_linear")
	@:argMeta(0, ":meta"("int32"))
	public static function get_bus_volume_linear(@:meta("int32") bus_idx:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3780747571.)
	@:hash_compatibility(null)
	@:nativeName("set_bus_send")
	@:argMeta(0, ":meta"("int32"))
	public static function set_bus_send(@:meta("int32") bus_idx:Int, send:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(659327637)
	@:hash_compatibility(null)
	@:nativeName("get_bus_send")
	@:argMeta(0, ":meta"("int32"))
	public static function get_bus_send(@:meta("int32") bus_idx:Int):godot.StringName;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_bus_solo")
	@:argMeta(0, ":meta"("int32"))
	public static function set_bus_solo(@:meta("int32") bus_idx:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_bus_solo")
	@:argMeta(0, ":meta"("int32"))
	public static function is_bus_solo(@:meta("int32") bus_idx:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_bus_mute")
	@:argMeta(0, ":meta"("int32"))
	public static function set_bus_mute(@:meta("int32") bus_idx:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_bus_mute")
	@:argMeta(0, ":meta"("int32"))
	public static function is_bus_mute(@:meta("int32") bus_idx:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_bus_bypass_effects")
	@:argMeta(0, ":meta"("int32"))
	public static function set_bus_bypass_effects(@:meta("int32") bus_idx:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_bus_bypassing_effects")
	@:argMeta(0, ":meta"("int32"))
	public static function is_bus_bypassing_effects(@:meta("int32") bus_idx:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4068819785.)
	@:hash_compatibility([4147765248.])
	@:nativeName("add_bus_effect")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("-1"))
	#if gdscript @:argMeta(2, ":noNullPad"("-1")) #end
	public static function add_bus_effect(@:meta("int32") bus_idx:Int, effect:godot.AudioEffect, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end at_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("remove_bus_effect")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function remove_bus_effect(@:meta("int32") bus_idx:Int, @:meta("int32") effect_idx:Int):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_effect_count")
	@:argMeta(0, ":meta"("int32"))
	public static function get_bus_effect_count(@:meta("int32") bus_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(726064442)
	@:hash_compatibility(null)
	@:nativeName("get_bus_effect")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function get_bus_effect(@:meta("int32") bus_idx:Int, @:meta("int32") effect_idx:Int):godot.AudioEffect;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1829771234)
	@:hash_compatibility([2887144608.])
	@:nativeName("get_bus_effect_instance")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	public static function get_bus_effect_instance(@:meta("int32") bus_idx:Int, @:meta("int32") effect_idx:Int, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end channel:Int = 0):godot.AudioEffectInstance;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1649997291)
	@:hash_compatibility(null)
	@:nativeName("swap_bus_effects")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function swap_bus_effects(@:meta("int32") bus_idx:Int, @:meta("int32") effect_idx:Int, @:meta("int32") by_effect_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1383440665)
	@:hash_compatibility(null)
	@:nativeName("set_bus_effect_enabled")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function set_bus_effect_enabled(@:meta("int32") bus_idx:Int, @:meta("int32") effect_idx:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2522259332.)
	@:hash_compatibility(null)
	@:nativeName("is_bus_effect_enabled")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function is_bus_effect_enabled(@:meta("int32") bus_idx:Int, @:meta("int32") effect_idx:Int):Bool;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_peak_volume_left_db")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function get_bus_peak_volume_left_db(@:meta("int32") bus_idx:Int, @:meta("int32") channel:Int):Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_bus_peak_volume_right_db")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function get_bus_peak_volume_right_db(@:meta("int32") bus_idx:Int, @:meta("int32") channel:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_playback_speed_scale")
	@:argMeta(0, ":meta"("float"))
	public static function set_playback_speed_scale(@:meta("float") scale:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_playback_speed_scale")
	public static function get_playback_speed_scale():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("lock")
	public static function lock():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("unlock")
	public static function unlock():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2549190337.)
	@:hash_compatibility(null)
	@:nativeName("get_speaker_mode")
	public static function get_speaker_mode():godot.AudioServer_SpeakerMode;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_mix_rate")
	public static function get_mix_rate():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_input_mix_rate")
	public static function get_input_mix_rate():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_driver_name")
	public static function get_driver_name():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("get_output_device_list")
	public static function get_output_device_list():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("get_output_device")
	public static function get_output_device():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("set_output_device")
	public static function set_output_device(name:String):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_time_to_next_mix")
	public static function get_time_to_next_mix():Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_time_since_last_mix")
	public static function get_time_since_last_mix():Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_output_latency")
	public static function get_output_latency():Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("get_input_device_list")
	public static function get_input_device_list():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("get_input_device")
	public static function get_input_device():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("set_input_device")
	public static function set_input_device(name:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1413768114)
	@:hash_compatibility(null)
	@:nativeName("set_input_device_active")
	public static function set_input_device_active(active:Bool):godot.Error;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_input_frames_available")
	public static function get_input_frames_available():Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_input_buffer_length_frames")
	public static function get_input_buffer_length_frames():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2649534757.)
	@:hash_compatibility(null)
	@:nativeName("get_input_frames")
	@:argMeta(0, ":meta"("int32"))
	public static function get_input_frames(@:meta("int32") frames:Int):godot.PackedVector2Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3319058824.)
	@:hash_compatibility(null)
	@:nativeName("set_bus_layout")
	public static function set_bus_layout(bus_layout:godot.AudioBusLayout):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3769973890.)
	@:hash_compatibility(null)
	@:nativeName("generate_bus_layout")
	public static function generate_bus_layout():godot.AudioBusLayout;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_enable_tagging_used_audio_streams")
	public static function set_enable_tagging_used_audio_streams(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(500225754)
	@:hash_compatibility(null)
	@:nativeName("is_stream_registered_as_sample")
	public static function is_stream_registered_as_sample(stream:godot.AudioStream):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2210767741.)
	@:hash_compatibility(null)
	@:nativeName("register_stream_as_sample")
	public static function register_stream_as_sample(stream:godot.AudioStream):Void;
}