/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class AudioStreamPlayback extends godot.RefCounted {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_start")
	@:argMeta(0, ":meta"("double"))
	public function _start(@:meta("double") from_pos:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_stop")
	public function _stop():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_playing")
	public function _is_playing():Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_loop_count")
	public function _get_loop_count():Int;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_playback_position")
	public function _get_playback_position():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_seek")
	@:argMeta(0, ":meta"("double"))
	public function _seek(@:meta("double") position:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_tag_used_streams")
	public function _tag_used_streams():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3776071444.)
	@:hash_compatibility(null)
	@:nativeName("_set_parameter")
	public function _set_parameter(name:godot.StringName, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2760726917.)
	@:hash_compatibility(null)
	@:nativeName("_get_parameter")
	public function _get_parameter(name:godot.StringName):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3195455091.)
	@:hash_compatibility(null)
	@:nativeName("set_sample_playback")
	public function set_sample_playback(playback_sample:godot.AudioSamplePlayback):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3482738536.)
	@:hash_compatibility(null)
	@:nativeName("get_sample_playback")
	public function get_sample_playback():godot.AudioSamplePlayback;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3341291446.)
	@:hash_compatibility(null)
	@:nativeName("mix_audio")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(1, ":meta"("int32"))
	public function mix_audio(@:meta("float") rate_scale:Float, @:meta("int32") frames:Int):godot.PackedVector2Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1958160172)
	@:hash_compatibility(null)
	@:nativeName("start")
	@:argMeta(0, ":meta"("double"))
	@:argMeta(0, ":default_value"("0.0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0.0")) #end
	public function start(@:meta("double") @:default_value("0.0") #if gdscript @:noNullPad("0.0") #end from_pos:Float = 0.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1958160172)
	@:hash_compatibility(null)
	@:nativeName("seek")
	@:argMeta(0, ":meta"("double"))
	@:argMeta(0, ":default_value"("0.0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0.0")) #end
	public function seek(@:meta("double") @:default_value("0.0") #if gdscript @:noNullPad("0.0") #end time:Float = 0.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("stop")
	public function stop():Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_loop_count")
	public function get_loop_count():Int;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_playback_position")
	public function get_playback_position():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_playing")
	public function is_playing():Bool;
}