/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class BoneConstraint3D extends godot.SkeletonModifier3D {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_amount")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_amount(@:meta("int32") index:Int, @:meta("float") amount:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_amount")
	@:argMeta(0, ":meta"("int32"))
	public function get_amount(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_apply_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_apply_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_apply_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_apply_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_apply_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_apply_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_apply_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_apply_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1830520418)
	@:hash_compatibility(null)
	@:nativeName("set_reference_type")
	@:argMeta(0, ":meta"("int32"))
	public function set_reference_type(@:meta("int32") index:Int, type:godot.BoneConstraint3D_ReferenceType):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3456416152.)
	@:hash_compatibility(null)
	@:nativeName("get_reference_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_type(@:meta("int32") index:Int):godot.BoneConstraint3D_ReferenceType;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_reference_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_reference_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_reference_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_reference_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_reference_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_reference_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2761262315.)
	@:hash_compatibility(null)
	@:nativeName("set_reference_node")
	@:argMeta(0, ":meta"("int32"))
	public function set_reference_node(@:meta("int32") index:Int, node:godot.NodePath):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_reference_node")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_node(@:meta("int32") index:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_setting_count")
	@:argMeta(0, ":meta"("int32"))
	public function set_setting_count(@:meta("int32") count:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_setting_count")
	public function get_setting_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_setting")
	public function clear_setting():Void;
}