/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class BoneTwistDisperser3D extends godot.SkeletonModifier3D {
	public function new();
#if use_properties
	@:index(null)
	@:getter("are_bone_axes_mutable")
	@:setter("set_mutable_bone_axes")
	public var mutable_bone_axes(get, set) : Bool;
#else

	@:index(null)
	@:getter("are_bone_axes_mutable")
	@:setter("set_mutable_bone_axes")
	public var mutable_bone_axes : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count(get, set) : Int;
#else

	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count : Int;
#end
#if use_properties
	public extern inline function set_setting_count(v: Int): Int {
		set_setting_count_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_setting_count")
	@:native("set_setting_count")
	@:argMeta(0, ":meta"("int32"))
	public function set_setting_count_impl(@:meta("int32") count:Int):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_setting_count")
	@:argMeta(0, ":meta"("int32"))
	public function set_setting_count(@:meta("int32") count:Int):Void;

#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_setting_count")
	public function get_setting_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_settings")
	public function clear_settings():Void;
#if use_properties
	public extern inline function set_mutable_bone_axes(v: Bool): Bool {
		set_mutable_bone_axes_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_mutable_bone_axes")
	@:native("set_mutable_bone_axes")
	public function set_mutable_bone_axes_impl(enabled:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_mutable_bone_axes")
	public function set_mutable_bone_axes(enabled:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("are_bone_axes_mutable")
	@:native("are_bone_axes_mutable")
	public function get_mutable_bone_axes():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_root_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_root_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_root_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_root_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_root_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_root_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_root_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_root_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_end_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_end_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone(@:meta("int32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_reference_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_bone_name(@:meta("int32") index:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_reference_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_extend_end_bone")
	@:argMeta(0, ":meta"("int32"))
	public function set_extend_end_bone(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_end_bone_extended")
	@:argMeta(0, ":meta"("int32"))
	public function is_end_bone_extended(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2838484201.)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_direction")
	@:argMeta(0, ":meta"("int32"))
	public function set_end_bone_direction(@:meta("int32") index:Int, bone_direction:godot.SkeletonModifier3D_BoneDirection):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1843036459)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_direction")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_direction(@:meta("int32") index:Int):godot.SkeletonModifier3D_BoneDirection;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_twist_from_rest")
	@:argMeta(0, ":meta"("int32"))
	public function set_twist_from_rest(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_twist_from_rest")
	@:argMeta(0, ":meta"("int32"))
	public function is_twist_from_rest(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2823819782.)
	@:hash_compatibility(null)
	@:nativeName("set_twist_from")
	@:argMeta(0, ":meta"("int32"))
	public function set_twist_from(@:meta("int32") index:Int, from:godot.Quaternion):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(476865136)
	@:hash_compatibility(null)
	@:nativeName("get_twist_from")
	@:argMeta(0, ":meta"("int32"))
	public function get_twist_from(@:meta("int32") index:Int):godot.Quaternion;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2954194337.)
	@:hash_compatibility(null)
	@:nativeName("set_disperse_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_disperse_mode(@:meta("int32") index:Int, disperse_mode:godot.BoneTwistDisperser3D_DisperseMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1326397005)
	@:hash_compatibility(null)
	@:nativeName("get_disperse_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_disperse_mode(@:meta("int32") index:Int):godot.BoneTwistDisperser3D_DisperseMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_weight_position")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_weight_position(@:meta("int32") index:Int, @:meta("float") weight_position:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_weight_position")
	@:argMeta(0, ":meta"("int32"))
	public function get_weight_position(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1447180063)
	@:hash_compatibility(null)
	@:nativeName("set_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function set_damping_curve(@:meta("int32") index:Int, curve:godot.Curve):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(747537754)
	@:hash_compatibility(null)
	@:nativeName("get_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function get_damping_curve(@:meta("int32") index:Int):godot.Curve;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1391810591)
	@:hash_compatibility(null)
	@:nativeName("get_joint_bone_name")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_bone_name(@:meta("int32") index:Int, @:meta("int32") joint:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_bone(@:meta("int32") index:Int, @:meta("int32") joint:Int):Int;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_twist_amount")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_twist_amount(@:meta("int32") index:Int, @:meta("int32") joint:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_twist_amount")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function set_joint_twist_amount(@:meta("int32") index:Int, @:meta("int32") joint:Int, @:meta("float") twist_amount:Float):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_joint_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_joint_count(@:meta("int32") index:Int):Int;
}