/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class ClassDB extends godot.Object {
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_class_list")
	public static function get_class_list():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1761182771)
	@:hash_compatibility(null)
	@:nativeName("get_inheriters_from_class")
	public static function get_inheriters_from_class(_class:godot.StringName):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1965194235)
	@:hash_compatibility(null)
	@:nativeName("get_parent_class")
	public static function get_parent_class(_class:godot.StringName):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("class_exists")
	public static function class_exists(_class:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("is_parent_class")
	public static function is_parent_class(_class:godot.StringName, inherits:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("can_instantiate")
	public static function can_instantiate(_class:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2760726917.)
	@:hash_compatibility(null)
	@:nativeName("instantiate")
	public static function instantiate(_class:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2475317043.)
	@:hash_compatibility(null)
	@:nativeName("class_get_api_type")
	public static function class_get_api_type(_class:godot.StringName):godot.ClassDB_APIType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("class_has_signal")
	public static function class_has_signal(_class:godot.StringName, signal:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3061114238.)
	@:hash_compatibility(null)
	@:nativeName("class_get_signal")
	public static function class_get_signal(_class:godot.StringName, signal:godot.StringName):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3504980660.)
	@:hash_compatibility(null)
	@:nativeName("class_get_signal_list")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function class_get_signal_list(_class:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3504980660.)
	@:hash_compatibility(null)
	@:nativeName("class_get_property_list")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function class_get_property_list(_class:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3770832642.)
	@:hash_compatibility(null)
	@:nativeName("class_get_property_getter")
	public static function class_get_property_getter(_class:godot.StringName, property:godot.StringName):godot.StringName;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3770832642.)
	@:hash_compatibility(null)
	@:nativeName("class_get_property_setter")
	public static function class_get_property_setter(_class:godot.StringName, property:godot.StringName):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2498641674.)
	@:hash_compatibility(null)
	@:nativeName("class_get_property")
	@:argMeta(0, ":meta"("required"))
	public static function class_get_property(@:meta("required") object:godot.Object, property:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1690314931)
	@:hash_compatibility(null)
	@:nativeName("class_set_property")
	@:argMeta(0, ":meta"("required"))
	public static function class_set_property(@:meta("required") object:godot.Object, property:godot.StringName, value:Dynamic):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2718203076.)
	@:hash_compatibility(null)
	@:nativeName("class_get_property_default_value")
	public static function class_get_property_default_value(_class:godot.StringName, property:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3860701026.)
	@:hash_compatibility(null)
	@:nativeName("class_has_method")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function class_has_method(_class:godot.StringName, method:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3885694822.)
	@:hash_compatibility(null)
	@:nativeName("class_get_method_argument_count")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function class_get_method_argument_count(_class:godot.StringName, method:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3504980660.)
	@:hash_compatibility(null)
	@:nativeName("class_get_method_list")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function class_get_method_list(_class:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(true)
	@:is_virtual(false)
	@:hash(3344196419.)
	@:hash_compatibility(null)
	@:nativeName("class_call_static")
	public static function class_call_static(_class:godot.StringName, method:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3031669221.)
	@:hash_compatibility(null)
	@:nativeName("class_get_integer_constant_list")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function class_get_integer_constant_list(_class:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("class_has_integer_constant")
	public static function class_has_integer_constant(_class:godot.StringName, name:godot.StringName):Bool;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2419549490.)
	@:hash_compatibility(null)
	@:nativeName("class_get_integer_constant")
	public static function class_get_integer_constant(_class:godot.StringName, name:godot.StringName):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3860701026.)
	@:hash_compatibility(null)
	@:nativeName("class_has_enum")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function class_has_enum(_class:godot.StringName, name:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3031669221.)
	@:hash_compatibility(null)
	@:nativeName("class_get_enum_list")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function class_get_enum_list(_class:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(661528303)
	@:hash_compatibility(null)
	@:nativeName("class_get_enum_constants")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function class_get_enum_constants(_class:godot.StringName, _enum:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2457504236.)
	@:hash_compatibility(null)
	@:nativeName("class_get_integer_constant_enum")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function class_get_integer_constant_enum(_class:godot.StringName, name:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3860701026.)
	@:hash_compatibility(null)
	@:nativeName("is_class_enum_bitfield")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function is_class_enum_bitfield(_class:godot.StringName, _enum:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end no_inheritance:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("is_class_enabled")
	public static function is_class_enabled(_class:godot.StringName):Bool;
}