/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class ConvertTransformModifier3D extends godot.BoneConstraint3D {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count(get, set) : Int;
#else

	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1386463405)
	@:hash_compatibility(null)
	@:nativeName("set_apply_transform_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_apply_transform_mode(@:meta("int32") index:Int, transform_mode:godot.ConvertTransformModifier3D_TransformMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3234663511.)
	@:hash_compatibility(null)
	@:nativeName("get_apply_transform_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_apply_transform_mode(@:meta("int32") index:Int):godot.ConvertTransformModifier3D_TransformMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(776736805)
	@:hash_compatibility(null)
	@:nativeName("set_apply_axis")
	@:argMeta(0, ":meta"("int32"))
	public function set_apply_axis(@:meta("int32") index:Int, axis:godot.Vector3_Axis):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4131134770.)
	@:hash_compatibility(null)
	@:nativeName("get_apply_axis")
	@:argMeta(0, ":meta"("int32"))
	public function get_apply_axis(@:meta("int32") index:Int):godot.Vector3_Axis;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_apply_range_min")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_apply_range_min(@:meta("int32") index:Int, @:meta("float") range_min:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_apply_range_min")
	@:argMeta(0, ":meta"("int32"))
	public function get_apply_range_min(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_apply_range_max")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_apply_range_max(@:meta("int32") index:Int, @:meta("float") range_max:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_apply_range_max")
	@:argMeta(0, ":meta"("int32"))
	public function get_apply_range_max(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1386463405)
	@:hash_compatibility(null)
	@:nativeName("set_reference_transform_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_reference_transform_mode(@:meta("int32") index:Int, transform_mode:godot.ConvertTransformModifier3D_TransformMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3234663511.)
	@:hash_compatibility(null)
	@:nativeName("get_reference_transform_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_transform_mode(@:meta("int32") index:Int):godot.ConvertTransformModifier3D_TransformMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(776736805)
	@:hash_compatibility(null)
	@:nativeName("set_reference_axis")
	@:argMeta(0, ":meta"("int32"))
	public function set_reference_axis(@:meta("int32") index:Int, axis:godot.Vector3_Axis):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4131134770.)
	@:hash_compatibility(null)
	@:nativeName("get_reference_axis")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_axis(@:meta("int32") index:Int):godot.Vector3_Axis;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_reference_range_min")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_reference_range_min(@:meta("int32") index:Int, @:meta("float") range_min:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_reference_range_min")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_range_min(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_reference_range_max")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_reference_range_max(@:meta("int32") index:Int, @:meta("float") range_max:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_reference_range_max")
	@:argMeta(0, ":meta"("int32"))
	public function get_reference_range_max(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_relative")
	@:argMeta(0, ":meta"("int32"))
	public function set_relative(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_relative")
	@:argMeta(0, ":meta"("int32"))
	public function is_relative(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_additive")
	@:argMeta(0, ":meta"("int32"))
	public function set_additive(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_additive")
	@:argMeta(0, ":meta"("int32"))
	public function is_additive(@:meta("int32") index:Int):Bool;
}