/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class CopyTransformModifier3D extends godot.BoneConstraint3D {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count(get, set) : Int;
#else

	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2252507859.)
	@:hash_compatibility(null)
	@:nativeName("set_copy_flags")
	@:argMeta(0, ":meta"("int32"))
	public function set_copy_flags(@:meta("int32") index:Int, copy_flags:godot.CopyTransformModifier3D_TransformFlag):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1685185931)
	@:hash_compatibility(null)
	@:nativeName("get_copy_flags")
	@:argMeta(0, ":meta"("int32"))
	public function get_copy_flags(@:meta("int32") index:Int):godot.CopyTransformModifier3D_TransformFlag;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2044211897)
	@:hash_compatibility(null)
	@:nativeName("set_axis_flags")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_flags(@:meta("int32") index:Int, axis_flags:godot.CopyTransformModifier3D_AxisFlag):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(992162046)
	@:hash_compatibility(null)
	@:nativeName("get_axis_flags")
	@:argMeta(0, ":meta"("int32"))
	public function get_axis_flags(@:meta("int32") index:Int):godot.CopyTransformModifier3D_AxisFlag;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2044211897)
	@:hash_compatibility(null)
	@:nativeName("set_invert_flags")
	@:argMeta(0, ":meta"("int32"))
	public function set_invert_flags(@:meta("int32") index:Int, axis_flags:godot.CopyTransformModifier3D_AxisFlag):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(992162046)
	@:hash_compatibility(null)
	@:nativeName("get_invert_flags")
	@:argMeta(0, ":meta"("int32"))
	public function get_invert_flags(@:meta("int32") index:Int):godot.CopyTransformModifier3D_AxisFlag;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_copy_position")
	@:argMeta(0, ":meta"("int32"))
	public function set_copy_position(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_position_copying")
	@:argMeta(0, ":meta"("int32"))
	public function is_position_copying(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_copy_rotation")
	@:argMeta(0, ":meta"("int32"))
	public function set_copy_rotation(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_rotation_copying")
	@:argMeta(0, ":meta"("int32"))
	public function is_rotation_copying(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_copy_scale")
	@:argMeta(0, ":meta"("int32"))
	public function set_copy_scale(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_scale_copying")
	@:argMeta(0, ":meta"("int32"))
	public function is_scale_copying(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_axis_x_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_x_enabled(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_axis_x_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function is_axis_x_enabled(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_axis_y_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_y_enabled(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_axis_y_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function is_axis_y_enabled(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_axis_z_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_z_enabled(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_axis_z_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function is_axis_z_enabled(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_axis_x_inverted")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_x_inverted(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_axis_x_inverted")
	@:argMeta(0, ":meta"("int32"))
	public function is_axis_x_inverted(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_axis_y_inverted")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_y_inverted(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_axis_y_inverted")
	@:argMeta(0, ":meta"("int32"))
	public function is_axis_y_inverted(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_axis_z_inverted")
	@:argMeta(0, ":meta"("int32"))
	public function set_axis_z_inverted(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_axis_z_inverted")
	@:argMeta(0, ":meta"("int32"))
	public function is_axis_z_inverted(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_relative")
	@:argMeta(0, ":meta"("int32"))
	public function set_relative(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_relative")
	@:argMeta(0, ":meta"("int32"))
	public function is_relative(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_additive")
	@:argMeta(0, ":meta"("int32"))
	public function set_additive(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_additive")
	@:argMeta(0, ":meta"("int32"))
	public function is_additive(@:meta("int32") index:Int):Bool;
}