/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(false) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorExportPlatform extends godot.RefCounted {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_os_name")
	public function get_os_name():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2572397818.)
	@:hash_compatibility(null)
	@:nativeName("create_preset")
	public function create_preset():godot.EditorExportPreset;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2248993622.)
	@:hash_compatibility(null)
	@:nativeName("find_export_template")
	public function find_export_template(template_file_name:String):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("get_current_presets")
	public function get_current_presets():GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3420080977.)
	@:hash_compatibility(null)
	@:nativeName("save_pack")
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public function save_pack(preset:godot.EditorExportPreset, debug:Bool, path:String, @:default_value("false") #if gdscript @:noNullPad("false") #end embed:Bool = false):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1485052307)
	@:hash_compatibility(null)
	@:nativeName("save_zip")
	public function save_zip(preset:godot.EditorExportPreset, debug:Bool, path:String):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1485052307)
	@:hash_compatibility(null)
	@:nativeName("save_pack_patch")
	public function save_pack_patch(preset:godot.EditorExportPreset, debug:Bool, path:String):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1485052307)
	@:hash_compatibility(null)
	@:nativeName("save_zip_patch")
	public function save_zip_patch(preset:godot.EditorExportPreset, debug:Bool, path:String):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2976483270.)
	@:hash_compatibility(null)
	@:nativeName("gen_export_flags")
	public function gen_export_flags(flags:godot.EditorExportPlatform_DebugFlags):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1063735070)
	@:hash_compatibility([425454869])
	@:nativeName("export_project_files")
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	public function export_project_files(preset:godot.EditorExportPreset, debug:Bool, save_cb:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?shared_cb:godot.Callable):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1201906210)
	@:hash_compatibility([3879521245.])
	@:nativeName("export_project")
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	@:argMeta(4, ":default_value"("true"))
	#if gdscript @:argMeta(4, ":noNullPad"("true")) #end
	public function export_project(preset:godot.EditorExportPreset, debug:Bool, path:String, @:default_value("0") #if gdscript @:noNullPad("0") #end ?flags:godot.EditorExportPlatform_DebugFlags, @:default_value("true") #if gdscript @:noNullPad("true") #end notify:Bool = true):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3879521245.)
	@:hash_compatibility(null)
	@:nativeName("export_pack")
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function export_pack(preset:godot.EditorExportPreset, debug:Bool, path:String, @:default_value("0") #if gdscript @:noNullPad("0") #end ?flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3879521245.)
	@:hash_compatibility(null)
	@:nativeName("export_zip")
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function export_zip(preset:godot.EditorExportPreset, debug:Bool, path:String, @:default_value("0") #if gdscript @:noNullPad("0") #end ?flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(608021658)
	@:hash_compatibility(null)
	@:nativeName("export_pack_patch")
	@:argMeta(3, ":default_value"("PackedStringArray()"))
	#if gdscript @:argMeta(3, ":noNullPad"("PackedStringArray()")) #end
	@:argMeta(4, ":default_value"("0"))
	#if gdscript @:argMeta(4, ":noNullPad"("0")) #end
	public function export_pack_patch(preset:godot.EditorExportPreset, debug:Bool, path:String, @:default_value("PackedStringArray()") #if gdscript @:noNullPad("PackedStringArray()") #end ?patches:godot.PackedStringArray, @:default_value("0") #if gdscript @:noNullPad("0") #end ?flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(608021658)
	@:hash_compatibility(null)
	@:nativeName("export_zip_patch")
	@:argMeta(3, ":default_value"("PackedStringArray()"))
	#if gdscript @:argMeta(3, ":noNullPad"("PackedStringArray()")) #end
	@:argMeta(4, ":default_value"("0"))
	#if gdscript @:argMeta(4, ":noNullPad"("0")) #end
	public function export_zip_patch(preset:godot.EditorExportPreset, debug:Bool, path:String, @:default_value("PackedStringArray()") #if gdscript @:noNullPad("PackedStringArray()") #end ?patches:godot.PackedStringArray, @:default_value("0") #if gdscript @:noNullPad("0") #end ?flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_messages")
	public function clear_messages():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(782767225)
	@:hash_compatibility(null)
	@:nativeName("add_message")
	public function add_message(type:godot.EditorExportPlatform_ExportMessageType, category:String, message:String):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_message_count")
	public function get_message_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2667287293.)
	@:hash_compatibility(null)
	@:nativeName("get_message_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_message_type(@:meta("int32") index:Int):godot.EditorExportPlatform_ExportMessageType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_message_category")
	@:argMeta(0, ":meta"("int32"))
	public function get_message_category(@:meta("int32") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_message_text")
	@:argMeta(0, ":meta"("int32"))
	public function get_message_text(@:meta("int32") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2580557466.)
	@:hash_compatibility(null)
	@:nativeName("get_worst_message_type")
	public function get_worst_message_type():godot.EditorExportPlatform_ExportMessageType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3163734797.)
	@:hash_compatibility(null)
	@:nativeName("ssh_run_on_remote")
	@:argMeta(4, ":default_value"("[]"))
	#if gdscript @:argMeta(4, ":noNullPad"("[]")) #end
	@:argMeta(5, ":meta"("int32"))
	@:argMeta(5, ":default_value"("-1"))
	#if gdscript @:argMeta(5, ":noNullPad"("-1")) #end
	public function ssh_run_on_remote(host:String, port:String, ssh_arg:godot.PackedStringArray, cmd_args:String, @:default_value("[]") #if gdscript @:noNullPad("[]") #end ?output:GodotArray, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end port_fwd:Int = -1):godot.Error;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3606362233.)
	@:hash_compatibility(null)
	@:nativeName("ssh_run_on_remote_no_wait")
	@:argMeta(4, ":meta"("int32"))
	@:argMeta(4, ":default_value"("-1"))
	#if gdscript @:argMeta(4, ":noNullPad"("-1")) #end
	public function ssh_run_on_remote_no_wait(host:String, port:String, ssh_args:godot.PackedStringArray, cmd_args:String, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end port_fwd:Int = -1):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(218756989)
	@:hash_compatibility(null)
	@:nativeName("ssh_push_to_remote")
	public function ssh_push_to_remote(host:String, port:String, scp_args:godot.PackedStringArray, src_file:String, dst_file:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(89550086)
	@:hash_compatibility(null)
	@:nativeName("get_internal_export_files")
	public function get_internal_export_files(preset:godot.EditorExportPreset, debug:Bool):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1939331020)
	@:hash_compatibility([2981934095.])
	@:nativeName("get_forced_export_files")
	@:argMeta(0, ":default_value"("null"))
	#if gdscript @:argMeta(0, ":noNullPad"("null")) #end
	public static function get_forced_export_files(@:default_value("null") #if gdscript @:noNullPad("null") #end preset:godot.EditorExportPreset = null):godot.PackedStringArray;
}