/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorExportPlatformExtension extends godot.EditorExportPlatform {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1387456631)
	@:hash_compatibility(null)
	@:nativeName("_get_preset_features")
	public function _get_preset_features(preset:godot.EditorExportPreset):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_is_executable")
	public function _is_executable(path:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_export_options")
	public function _get_export_options():Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_should_update_export_options")
	public function _should_update_export_options():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(969350244)
	@:hash_compatibility(null)
	@:nativeName("_get_export_option_visibility")
	public function _get_export_option_visibility(preset:godot.EditorExportPreset, option:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(805886795)
	@:hash_compatibility(null)
	@:nativeName("_get_export_option_warning")
	public function _get_export_option_warning(preset:godot.EditorExportPreset, option:godot.StringName):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_os_name")
	public function _get_os_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_name")
	public function _get_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3635182373.)
	@:hash_compatibility(null)
	@:nativeName("_get_logo")
	public function _get_logo():godot.Texture2D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_poll_export")
	public function _poll_export():Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_options_count")
	public function _get_options_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_options_tooltip")
	public function _get_options_tooltip():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3536238170.)
	@:hash_compatibility([3991065292.])
	@:nativeName("_get_option_icon")
	@:argMeta(0, ":meta"("int32"))
	public function _get_option_icon(@:meta("int32") device:Int):godot.Texture2D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_option_label")
	@:argMeta(0, ":meta"("int32"))
	public function _get_option_label(@:meta("int32") device:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_option_tooltip")
	@:argMeta(0, ":meta"("int32"))
	public function _get_option_tooltip(@:meta("int32") device:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_device_architecture")
	@:argMeta(0, ":meta"("int32"))
	public function _get_device_architecture(@:meta("int32") device:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_cleanup")
	public function _cleanup():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1726914928)
	@:hash_compatibility(null)
	@:nativeName("_run")
	@:argMeta(1, ":meta"("int32"))
	public function _run(preset:godot.EditorExportPreset, @:meta("int32") device:Int, debug_flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3635182373.)
	@:hash_compatibility(null)
	@:nativeName("_get_run_icon")
	public function _get_run_icon():godot.Texture2D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(493961987)
	@:hash_compatibility(null)
	@:nativeName("_can_export")
	public function _can_export(preset:godot.EditorExportPreset, debug:Bool):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(493961987)
	@:hash_compatibility(null)
	@:nativeName("_has_valid_export_configuration")
	public function _has_valid_export_configuration(preset:godot.EditorExportPreset, debug:Bool):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3117166915.)
	@:hash_compatibility(null)
	@:nativeName("_has_valid_project_configuration")
	public function _has_valid_project_configuration(preset:godot.EditorExportPreset):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1387456631)
	@:hash_compatibility(null)
	@:nativeName("_get_binary_extensions")
	public function _get_binary_extensions(preset:godot.EditorExportPreset):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1328957260)
	@:hash_compatibility(null)
	@:nativeName("_export_project")
	public function _export_project(preset:godot.EditorExportPreset, debug:Bool, path:String, flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1328957260)
	@:hash_compatibility(null)
	@:nativeName("_export_pack")
	public function _export_pack(preset:godot.EditorExportPreset, debug:Bool, path:String, flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1328957260)
	@:hash_compatibility(null)
	@:nativeName("_export_zip")
	public function _export_zip(preset:godot.EditorExportPreset, debug:Bool, path:String, flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(454765315)
	@:hash_compatibility(null)
	@:nativeName("_export_pack_patch")
	public function _export_pack_patch(preset:godot.EditorExportPreset, debug:Bool, path:String, patches:godot.PackedStringArray, flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(454765315)
	@:hash_compatibility(null)
	@:nativeName("_export_zip_patch")
	public function _export_zip_patch(preset:godot.EditorExportPreset, debug:Bool, path:String, patches:godot.PackedStringArray, flags:godot.EditorExportPlatform_DebugFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_platform_features")
	public function _get_platform_features():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_debug_protocol")
	public function _get_debug_protocol():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_initialize")
	public function _initialize():Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3089850668.)
	@:hash_compatibility(null)
	@:nativeName("set_config_error")
	public function set_config_error(error_text:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_config_error")
	public function get_config_error():String;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1695273946)
	@:hash_compatibility(null)
	@:nativeName("set_config_missing_templates")
	public function set_config_missing_templates(missing_templates:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("get_config_missing_templates")
	public function get_config_missing_templates():Bool;
}