/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("editor") @:is_resource(false) @:is_node(true) extern class EditorPlugin extends godot.Node {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1062211774)
	@:hash_compatibility(null)
	@:nativeName("_forward_canvas_gui_input")
	public function _forward_canvas_gui_input(event:godot.InputEvent):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("_forward_canvas_draw_over_viewport")
	public function _forward_canvas_draw_over_viewport(viewport_control:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("_forward_canvas_force_draw_over_viewport")
	public function _forward_canvas_force_draw_over_viewport(viewport_control:godot.Control):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1018736637)
	@:hash_compatibility(null)
	@:nativeName("_forward_3d_gui_input")
	public function _forward_3d_gui_input(viewport_camera:godot.Camera3D, event:godot.InputEvent):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("_forward_3d_draw_over_viewport")
	public function _forward_3d_draw_over_viewport(viewport_control:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("_forward_3d_force_draw_over_viewport")
	public function _forward_3d_force_draw_over_viewport(viewport_control:godot.Control):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_plugin_name")
	public function _get_plugin_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3635182373.)
	@:hash_compatibility(null)
	@:nativeName("_get_plugin_icon")
	public function _get_plugin_icon():godot.Texture2D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_has_main_screen")
	public function _has_main_screen():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_make_visible")
	public function _make_visible(visible:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3975164845.)
	@:hash_compatibility(null)
	@:nativeName("_edit")
	public function _edit(object:godot.Object):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(397768994)
	@:hash_compatibility(null)
	@:nativeName("_handles")
	public function _handles(object:godot.Object):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3102165223.)
	@:hash_compatibility(null)
	@:nativeName("_get_state")
	public function _get_state():godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155329257.)
	@:hash_compatibility(null)
	@:nativeName("_set_state")
	public function _set_state(state:godot.Dictionary):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_clear")
	public function _clear():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("_get_unsaved_status")
	public function _get_unsaved_status(for_scene:String):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_save_external_data")
	public function _save_external_data():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_apply_changes")
	public function _apply_changes():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_breakpoints")
	public function _get_breakpoints():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(853519107)
	@:hash_compatibility(null)
	@:nativeName("_set_window_layout")
	public function _set_window_layout(configuration:godot.ConfigFile):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(853519107)
	@:hash_compatibility(null)
	@:nativeName("_get_window_layout")
	public function _get_window_layout(configuration:godot.ConfigFile):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_build")
	public function _build():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3911848509.)
	@:hash_compatibility(null)
	@:nativeName("_run_scene")
	public function _run_scene(scene:String, args:godot.PackedStringArray):godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_enable_plugin")
	public function _enable_plugin():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_disable_plugin")
	public function _disable_plugin():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(158651717)
	@:hash_compatibility(null)
	@:nativeName("add_dock")
	public function add_dock(dock:godot.EditorDock):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(158651717)
	@:hash_compatibility(null)
	@:nativeName("remove_dock")
	public function remove_dock(dock:godot.EditorDock):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3092750152.)
	@:hash_compatibility(null)
	@:nativeName("add_control_to_container")
	public function add_control_to_container(container:godot.EditorPlugin_CustomControlContainer, control:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3092750152.)
	@:hash_compatibility(null)
	@:nativeName("remove_control_from_container")
	public function remove_control_from_container(container:godot.EditorPlugin_CustomControlContainer, control:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2137474292)
	@:hash_compatibility(null)
	@:nativeName("add_tool_menu_item")
	public function add_tool_menu_item(name:String, callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1019428915)
	@:hash_compatibility(null)
	@:nativeName("add_tool_submenu_item")
	public function add_tool_submenu_item(name:String, submenu:godot.PopupMenu):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("remove_tool_menu_item")
	public function remove_tool_menu_item(name:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1775878644)
	@:hash_compatibility(null)
	@:nativeName("get_export_as_menu")
	public function get_export_as_menu():godot.PopupMenu;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1986814599)
	@:hash_compatibility(null)
	@:nativeName("add_custom_type")
	public function add_custom_type(type:String, base:String, script:godot.Script, icon:godot.Texture2D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("remove_custom_type")
	public function remove_custom_type(type:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2994930786.)
	@:hash_compatibility([3354871258.])
	@:nativeName("add_control_to_dock")
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public function add_control_to_dock(slot:godot.EditorPlugin_DockSlot, control:godot.Control, @:default_value("null") #if gdscript @:noNullPad("null") #end shortcut:godot.Shortcut = null):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("remove_control_from_docks")
	public function remove_control_from_docks(control:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3450529724.)
	@:hash_compatibility(null)
	@:nativeName("set_dock_tab_icon")
	public function set_dock_tab_icon(control:godot.Control, icon:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(111032269)
	@:hash_compatibility([3526039376.])
	@:nativeName("add_control_to_bottom_panel")
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public function add_control_to_bottom_panel(control:godot.Control, title:String, @:default_value("null") #if gdscript @:noNullPad("null") #end shortcut:godot.Shortcut = null):godot.Button;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("remove_control_from_bottom_panel")
	public function remove_control_from_bottom_panel(control:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3186203200.)
	@:hash_compatibility(null)
	@:nativeName("add_autoload_singleton")
	public function add_autoload_singleton(name:String, path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("remove_autoload_singleton")
	public function remove_autoload_singleton(name:String):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("update_overlays")
	public function update_overlays():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1496901182)
	@:hash_compatibility(null)
	@:nativeName("make_bottom_panel_item_visible")
	public function make_bottom_panel_item_visible(item:godot.Control):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("hide_bottom_panel")
	public function hide_bottom_panel():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(773492341)
	@:hash_compatibility(null)
	@:nativeName("get_undo_redo")
	public function get_undo_redo():godot.EditorUndoRedoManager;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1611583062)
	@:hash_compatibility(null)
	@:nativeName("add_undo_redo_inspector_hook_callback")
	public function add_undo_redo_inspector_hook_callback(callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1611583062)
	@:hash_compatibility(null)
	@:nativeName("remove_undo_redo_inspector_hook_callback")
	public function remove_undo_redo_inspector_hook_callback(callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("queue_save_layout")
	public function queue_save_layout():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3116463128.)
	@:hash_compatibility(null)
	@:nativeName("add_translation_parser_plugin")
	public function add_translation_parser_plugin(parser:godot.EditorTranslationParserPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3116463128.)
	@:hash_compatibility(null)
	@:nativeName("remove_translation_parser_plugin")
	public function remove_translation_parser_plugin(parser:godot.EditorTranslationParserPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3113975762.)
	@:hash_compatibility(null)
	@:nativeName("add_import_plugin")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function add_import_plugin(importer:godot.EditorImportPlugin, @:default_value("false") #if gdscript @:noNullPad("false") #end first_priority:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2312482773.)
	@:hash_compatibility(null)
	@:nativeName("remove_import_plugin")
	public function remove_import_plugin(importer:godot.EditorImportPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2764104752.)
	@:hash_compatibility(null)
	@:nativeName("add_scene_format_importer_plugin")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function add_scene_format_importer_plugin(scene_format_importer:godot.EditorSceneFormatImporter, @:default_value("false") #if gdscript @:noNullPad("false") #end first_priority:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2637776123.)
	@:hash_compatibility(null)
	@:nativeName("remove_scene_format_importer_plugin")
	public function remove_scene_format_importer_plugin(scene_format_importer:godot.EditorSceneFormatImporter):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3492436322.)
	@:hash_compatibility(null)
	@:nativeName("add_scene_post_import_plugin")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function add_scene_post_import_plugin(scene_import_plugin:godot.EditorScenePostImportPlugin, @:default_value("false") #if gdscript @:noNullPad("false") #end first_priority:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3045178206.)
	@:hash_compatibility(null)
	@:nativeName("remove_scene_post_import_plugin")
	public function remove_scene_post_import_plugin(scene_import_plugin:godot.EditorScenePostImportPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4095952207.)
	@:hash_compatibility(null)
	@:nativeName("add_export_plugin")
	public function add_export_plugin(plugin:godot.EditorExportPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4095952207.)
	@:hash_compatibility(null)
	@:nativeName("remove_export_plugin")
	public function remove_export_plugin(plugin:godot.EditorExportPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3431312373.)
	@:hash_compatibility(null)
	@:nativeName("add_export_platform")
	public function add_export_platform(platform:godot.EditorExportPlatform):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3431312373.)
	@:hash_compatibility(null)
	@:nativeName("remove_export_platform")
	public function remove_export_platform(platform:godot.EditorExportPlatform):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1541015022)
	@:hash_compatibility(null)
	@:nativeName("add_node_3d_gizmo_plugin")
	public function add_node_3d_gizmo_plugin(plugin:godot.EditorNode3DGizmoPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1541015022)
	@:hash_compatibility(null)
	@:nativeName("remove_node_3d_gizmo_plugin")
	public function remove_node_3d_gizmo_plugin(plugin:godot.EditorNode3DGizmoPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(546395733)
	@:hash_compatibility(null)
	@:nativeName("add_inspector_plugin")
	public function add_inspector_plugin(plugin:godot.EditorInspectorPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(546395733)
	@:hash_compatibility(null)
	@:nativeName("remove_inspector_plugin")
	public function remove_inspector_plugin(plugin:godot.EditorInspectorPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2124849111)
	@:hash_compatibility(null)
	@:nativeName("add_resource_conversion_plugin")
	public function add_resource_conversion_plugin(plugin:godot.EditorResourceConversionPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2124849111)
	@:hash_compatibility(null)
	@:nativeName("remove_resource_conversion_plugin")
	public function remove_resource_conversion_plugin(plugin:godot.EditorResourceConversionPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("set_input_event_forwarding_always_enabled")
	public function set_input_event_forwarding_always_enabled():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("set_force_draw_over_forwarding_enabled")
	public function set_force_draw_over_forwarding_enabled():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1904221872)
	@:hash_compatibility(null)
	@:nativeName("add_context_menu_plugin")
	public function add_context_menu_plugin(slot:godot.EditorContextMenuPlugin_ContextMenuSlot, plugin:godot.EditorContextMenuPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2281511854.)
	@:hash_compatibility(null)
	@:nativeName("remove_context_menu_plugin")
	public function remove_context_menu_plugin(plugin:godot.EditorContextMenuPlugin):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4223731786.)
	@:hash_compatibility(null)
	@:nativeName("get_editor_interface")
	public function get_editor_interface():godot.EditorInterface;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3121871482.)
	@:hash_compatibility(null)
	@:nativeName("get_script_create_dialog")
	public function get_script_create_dialog():godot.ScriptCreateDialog;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3749880309.)
	@:hash_compatibility(null)
	@:nativeName("add_debugger_plugin")
	public function add_debugger_plugin(script:godot.EditorDebuggerPlugin):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3749880309.)
	@:hash_compatibility(null)
	@:nativeName("remove_debugger_plugin")
	public function remove_debugger_plugin(script:godot.EditorDebuggerPlugin):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_plugin_version")
	public function get_plugin_version():String;
}