/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorNode3DGizmoPlugin extends godot.Resource {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1905827158)
	@:hash_compatibility(null)
	@:nativeName("_has_gizmo")
	public function _has_gizmo(for_node_3d:godot.Node3D):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1418965287)
	@:hash_compatibility(null)
	@:nativeName("_create_gizmo")
	public function _create_gizmo(for_node_3d:godot.Node3D):godot.EditorNode3DGizmo;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_gizmo_name")
	public function _get_gizmo_name():String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_priority")
	public function _get_priority():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_can_be_hidden")
	public function _can_be_hidden():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_selectable_when_hidden")
	public function _is_selectable_when_hidden():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_can_commit_handle_on_click")
	public function _can_commit_handle_on_click():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(173330131)
	@:hash_compatibility(null)
	@:nativeName("_redraw")
	public function _redraw(gizmo:godot.EditorNode3DGizmo):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3888674840.)
	@:hash_compatibility(null)
	@:nativeName("_get_handle_name")
	@:argMeta(1, ":meta"("int32"))
	public function _get_handle_name(gizmo:godot.EditorNode3DGizmo, @:meta("int32") handle_id:Int, secondary:Bool):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2665780718.)
	@:hash_compatibility(null)
	@:nativeName("_is_handle_highlighted")
	@:argMeta(1, ":meta"("int32"))
	public function _is_handle_highlighted(gizmo:godot.EditorNode3DGizmo, @:meta("int32") handle_id:Int, secondary:Bool):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2887724832.)
	@:hash_compatibility(null)
	@:nativeName("_get_handle_value")
	@:argMeta(1, ":meta"("int32"))
	public function _get_handle_value(gizmo:godot.EditorNode3DGizmo, @:meta("int32") handle_id:Int, secondary:Bool):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3363704593.)
	@:hash_compatibility(null)
	@:nativeName("_begin_handle_action")
	@:argMeta(1, ":meta"("int32"))
	public function _begin_handle_action(gizmo:godot.EditorNode3DGizmo, @:meta("int32") handle_id:Int, secondary:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1249646868)
	@:hash_compatibility(null)
	@:nativeName("_set_handle")
	@:argMeta(1, ":meta"("int32"))
	public function _set_handle(gizmo:godot.EditorNode3DGizmo, @:meta("int32") handle_id:Int, secondary:Bool, camera:godot.Camera3D, screen_pos:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1939863962)
	@:hash_compatibility(null)
	@:nativeName("_commit_handle")
	@:argMeta(1, ":meta"("int32"))
	public function _commit_handle(gizmo:godot.EditorNode3DGizmo, @:meta("int32") handle_id:Int, secondary:Bool, restore:Dynamic, cancel:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1781916302)
	@:hash_compatibility(null)
	@:nativeName("_subgizmos_intersect_ray")
	public function _subgizmos_intersect_ray(gizmo:godot.EditorNode3DGizmo, camera:godot.Camera3D, screen_pos:godot.Vector2):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3514748524.)
	@:hash_compatibility(null)
	@:nativeName("_subgizmos_intersect_frustum")
	public function _subgizmos_intersect_frustum(gizmo:godot.EditorNode3DGizmo, camera:godot.Camera3D, frustum_planes:Array<godot.Plane>):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3700343508.)
	@:hash_compatibility(null)
	@:nativeName("_get_subgizmo_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _get_subgizmo_transform(gizmo:godot.EditorNode3DGizmo, @:meta("int32") subgizmo_id:Int):godot.Transform3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2435388792.)
	@:hash_compatibility(null)
	@:nativeName("_set_subgizmo_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _set_subgizmo_transform(gizmo:godot.EditorNode3DGizmo, @:meta("int32") subgizmo_id:Int, transform:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2282018236.)
	@:hash_compatibility(null)
	@:nativeName("_commit_subgizmos")
	public function _commit_subgizmos(gizmo:godot.EditorNode3DGizmo, ids:godot.PackedInt32Array, restores:Array<godot.Transform3D>, cancel:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3486012546.)
	@:hash_compatibility(null)
	@:nativeName("create_material")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public function create_material(name:String, color:godot.Color, @:default_value("false") #if gdscript @:noNullPad("false") #end billboard:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end on_top:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end use_vertex_color:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3804976916.)
	@:hash_compatibility([2976007329.])
	@:nativeName("create_icon_material")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	@:argMeta(3, ":default_value"("Color(1, 1, 1, 1)"))
	#if gdscript @:argMeta(3, ":noNullPad"("Color(1, 1, 1, 1)")) #end
	public function create_icon_material(name:String, texture:godot.Texture2D, @:default_value("false") #if gdscript @:noNullPad("false") #end on_top:Bool = false, @:default_value("Color(1, 1, 1, 1)") #if gdscript @:noNullPad("Color(1, 1, 1, 1)") #end ?color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2486475223.)
	@:hash_compatibility(null)
	@:nativeName("create_handle_material")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public function create_handle_material(name:String, @:default_value("false") #if gdscript @:noNullPad("false") #end billboard:Bool = false, @:default_value("null") #if gdscript @:noNullPad("null") #end texture:godot.Texture2D = null):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1374068695)
	@:hash_compatibility(null)
	@:nativeName("add_material")
	public function add_material(name:String, material:godot.StandardMaterial3D):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(974464017)
	@:hash_compatibility([3501703615.])
	@:nativeName("get_material")
	@:argMeta(1, ":default_value"("null"))
	#if gdscript @:argMeta(1, ":noNullPad"("null")) #end
	public function get_material(name:String, @:default_value("null") #if gdscript @:noNullPad("null") #end gizmo:godot.EditorNode3DGizmo = null):godot.StandardMaterial3D;
}