/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorNode3DGizmo extends godot.Node3DGizmo {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_redraw")
	public function _redraw():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1868713439)
	@:hash_compatibility(null)
	@:nativeName("_get_handle_name")
	@:argMeta(0, ":meta"("int32"))
	public function _get_handle_name(@:meta("int32") id:Int, secondary:Bool):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(361316320)
	@:hash_compatibility(null)
	@:nativeName("_is_handle_highlighted")
	@:argMeta(0, ":meta"("int32"))
	public function _is_handle_highlighted(@:meta("int32") id:Int, secondary:Bool):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2144196525)
	@:hash_compatibility(null)
	@:nativeName("_get_handle_value")
	@:argMeta(0, ":meta"("int32"))
	public function _get_handle_value(@:meta("int32") id:Int, secondary:Bool):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("_begin_handle_action")
	@:argMeta(0, ":meta"("int32"))
	public function _begin_handle_action(@:meta("int32") id:Int, secondary:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2210262157.)
	@:hash_compatibility(null)
	@:nativeName("_set_handle")
	@:argMeta(0, ":meta"("int32"))
	public function _set_handle(@:meta("int32") id:Int, secondary:Bool, camera:godot.Camera3D, point:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3655739840.)
	@:hash_compatibility(null)
	@:nativeName("_commit_handle")
	@:argMeta(0, ":meta"("int32"))
	public function _commit_handle(@:meta("int32") id:Int, secondary:Bool, restore:Dynamic, cancel:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2055005479)
	@:hash_compatibility(null)
	@:nativeName("_subgizmos_intersect_ray")
	public function _subgizmos_intersect_ray(camera:godot.Camera3D, point:godot.Vector2):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1653813165)
	@:hash_compatibility(null)
	@:nativeName("_subgizmos_intersect_frustum")
	public function _subgizmos_intersect_frustum(camera:godot.Camera3D, frustum:Array<godot.Plane>):godot.PackedInt32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3616898986.)
	@:hash_compatibility(null)
	@:nativeName("_set_subgizmo_transform")
	@:argMeta(0, ":meta"("int32"))
	public function _set_subgizmo_transform(@:meta("int32") id:Int, transform:godot.Transform3D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1965739696)
	@:hash_compatibility(null)
	@:nativeName("_get_subgizmo_transform")
	@:argMeta(0, ":meta"("int32"))
	public function _get_subgizmo_transform(@:meta("int32") id:Int):godot.Transform3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411059856.)
	@:hash_compatibility(null)
	@:nativeName("_commit_subgizmos")
	public function _commit_subgizmos(ids:godot.PackedInt32Array, restores:Array<godot.Transform3D>, cancel:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2910971437.)
	@:hash_compatibility([302451090])
	@:nativeName("add_lines")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	@:argMeta(3, ":default_value"("Color(1, 1, 1, 1)"))
	#if gdscript @:argMeta(3, ":noNullPad"("Color(1, 1, 1, 1)")) #end
	public function add_lines(lines:godot.PackedVector3Array, material:godot.Material, @:default_value("false") #if gdscript @:noNullPad("false") #end billboard:Bool = false, @:default_value("Color(1, 1, 1, 1)") #if gdscript @:noNullPad("Color(1, 1, 1, 1)") #end ?modulate:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1579955111)
	@:hash_compatibility([1868867708])
	@:nativeName("add_mesh")
	@:argMeta(1, ":default_value"("null"))
	#if gdscript @:argMeta(1, ":noNullPad"("null")) #end
	@:argMeta(2, ":default_value"("Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0)")) #end
	@:argMeta(3, ":default_value"("null"))
	#if gdscript @:argMeta(3, ":noNullPad"("null")) #end
	public function add_mesh(mesh:godot.Mesh, @:default_value("null") #if gdscript @:noNullPad("null") #end material:godot.Material = null, @:default_value("Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0)") #if gdscript @:noNullPad("Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0)") #end ?transform:godot.Transform3D, @:default_value("null") #if gdscript @:noNullPad("null") #end skeleton:godot.SkinReference = null):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(334873810)
	@:hash_compatibility(null)
	@:nativeName("add_collision_segments")
	public function add_collision_segments(segments:godot.PackedVector3Array):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(54901064)
	@:hash_compatibility(null)
	@:nativeName("add_collision_triangles")
	public function add_collision_triangles(triangles:godot.TriangleMesh):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(520007164)
	@:hash_compatibility([3719733075.])
	@:nativeName("add_unscaled_billboard")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("1"))
	#if gdscript @:argMeta(1, ":noNullPad"("1")) #end
	@:argMeta(2, ":default_value"("Color(1, 1, 1, 1)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Color(1, 1, 1, 1)")) #end
	public function add_unscaled_billboard(material:godot.Material, @:meta("float") @:default_value("1") #if gdscript @:noNullPad("1") #end default_scale:Float = 1., @:default_value("Color(1, 1, 1, 1)") #if gdscript @:noNullPad("Color(1, 1, 1, 1)") #end ?modulate:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2254560097.)
	@:hash_compatibility(null)
	@:nativeName("add_handles")
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public function add_handles(handles:godot.PackedVector3Array, material:godot.Material, ids:godot.PackedInt32Array, @:default_value("false") #if gdscript @:noNullPad("false") #end billboard:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end secondary:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1078189570)
	@:hash_compatibility(null)
	@:nativeName("set_node_3d")
	public function set_node_3d(node:godot.Node):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(151077316)
	@:hash_compatibility(null)
	@:nativeName("get_node_3d")
	public function get_node_3d():godot.Node3D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4250544552.)
	@:hash_compatibility(null)
	@:nativeName("get_plugin")
	public function get_plugin():godot.EditorNode3DGizmoPlugin;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_hidden")
	public function set_hidden(hidden:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_subgizmo_selected")
	@:argMeta(0, ":meta"("int32"))
	public function is_subgizmo_selected(@:meta("int32") id:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1930428628)
	@:hash_compatibility(null)
	@:nativeName("get_subgizmo_selection")
	public function get_subgizmo_selection():godot.PackedInt32Array;
}