/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorImportPlugin extends godot.ResourceImporter {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_importer_name")
	public function _get_importer_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_visible_name")
	public function _get_visible_name():String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_preset_count")
	public function _get_preset_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_preset_name")
	@:argMeta(0, ":meta"("int32"))
	public function _get_preset_name(@:meta("int32") preset_index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_recognized_extensions")
	public function _get_recognized_extensions():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(520498173)
	@:hash_compatibility(null)
	@:nativeName("_get_import_options")
	@:argMeta(1, ":meta"("int32"))
	public function _get_import_options(path:String, @:meta("int32") preset_index:Int):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_save_extension")
	public function _get_save_extension():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_resource_type")
	public function _get_resource_type():String;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_priority")
	public function _get_priority():Float;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_import_order")
	public function _get_import_order():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_format_version")
	public function _get_format_version():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(240466755)
	@:hash_compatibility(null)
	@:nativeName("_get_option_visibility")
	public function _get_option_visibility(path:String, option_name:godot.StringName, options:godot.Dictionary):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4108152118.)
	@:hash_compatibility(null)
	@:nativeName("_import")
	public function _import(source_file:String, save_path:String, options:godot.Dictionary, platform_variants:Array<String>, gen_files:Array<String>):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_can_import_threaded")
	public function _can_import_threaded():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(320493106)
	@:hash_compatibility([3645925746.])
	@:nativeName("append_import_external_resource")
	@:argMeta(1, ":default_value"("{}"))
	#if gdscript @:argMeta(1, ":noNullPad"("{}")) #end
	@:argMeta(2, ":default_value"("\"\""))
	#if gdscript @:argMeta(2, ":noNullPad"("\"\"")) #end
	@:argMeta(3, ":default_value"("null"))
	#if gdscript @:argMeta(3, ":noNullPad"("null")) #end
	public function append_import_external_resource(path:String, @:default_value("{}") #if gdscript @:noNullPad("{}") #end ?custom_options:godot.Dictionary, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end custom_importer:String = "\"\"", @:default_value("null") #if gdscript @:noNullPad("null") #end generator_parameters:Dynamic = null):godot.Error;
}