/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("editor") @:is_resource(false) @:is_node(false) extern class EditorInterface extends godot.Object {
#if use_properties
	@:index(null)
	@:getter("is_distraction_free_mode_enabled")
	@:setter("set_distraction_free_mode")
	public static var distraction_free_mode(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_distraction_free_mode_enabled")
	@:setter("set_distraction_free_mode")
	public static var distraction_free_mode : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("is_movie_maker_enabled")
	@:setter("set_movie_maker_enabled")
	public static var movie_maker_enabled(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_movie_maker_enabled")
	@:setter("set_movie_maker_enabled")
	public static var movie_maker_enabled : Bool;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3216645846.)
	@:hash_compatibility(null)
	@:nativeName("restart_editor")
	@:argMeta(0, ":default_value"("true"))
	#if gdscript @:argMeta(0, ":noNullPad"("true")) #end
	public static function restart_editor(@:default_value("true") #if gdscript @:noNullPad("true") #end save:Bool = true):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2471163807.)
	@:hash_compatibility(null)
	@:nativeName("get_command_palette")
	public static function get_command_palette():godot.EditorCommandPalette;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(780151678)
	@:hash_compatibility(null)
	@:nativeName("get_resource_filesystem")
	public static function get_resource_filesystem():godot.EditorFileSystem;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1595760068)
	@:hash_compatibility(null)
	@:nativeName("get_editor_paths")
	public static function get_editor_paths():godot.EditorPaths;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(943486957)
	@:hash_compatibility(null)
	@:nativeName("get_resource_previewer")
	public static function get_resource_previewer():godot.EditorResourcePreview;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2690272531.)
	@:hash_compatibility(null)
	@:nativeName("get_selection")
	public static function get_selection():godot.EditorSelection;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4086932459.)
	@:hash_compatibility(null)
	@:nativeName("get_editor_settings")
	public static function get_editor_settings():godot.EditorSettings;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3612675797.)
	@:hash_compatibility(null)
	@:nativeName("get_editor_toaster")
	public static function get_editor_toaster():godot.EditorToaster;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3819628421.)
	@:hash_compatibility(null)
	@:nativeName("get_editor_undo_redo")
	public static function get_editor_undo_redo():godot.EditorUndoRedoManager;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(878078554)
	@:hash_compatibility(null)
	@:nativeName("make_mesh_previews")
	@:argMeta(1, ":meta"("int32"))
	public static function make_mesh_previews(meshes:Array<godot.Mesh>, @:meta("int32") preview_size:Int):Array<godot.Texture2D>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2678287736.)
	@:hash_compatibility(null)
	@:nativeName("set_plugin_enabled")
	public static function set_plugin_enabled(plugin:String, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("is_plugin_enabled")
	public static function is_plugin_enabled(plugin:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3846893731.)
	@:hash_compatibility(null)
	@:nativeName("get_editor_theme")
	public static function get_editor_theme():godot.Theme;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2783021301.)
	@:hash_compatibility(null)
	@:nativeName("get_base_control")
	public static function get_base_control():godot.Control;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1706218421)
	@:hash_compatibility(null)
	@:nativeName("get_editor_main_screen")
	public static function get_editor_main_screen():godot.VBoxContainer;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(90868003)
	@:hash_compatibility(null)
	@:nativeName("get_script_editor")
	public static function get_script_editor():godot.ScriptEditor;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3750751911.)
	@:hash_compatibility(null)
	@:nativeName("get_editor_viewport_2d")
	public static function get_editor_viewport_2d():godot.SubViewport;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1970834490)
	@:hash_compatibility(null)
	@:nativeName("get_editor_viewport_3d")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public static function get_editor_viewport_3d(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end idx:Int = 0):godot.SubViewport;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("set_main_screen_editor")
	public static function set_main_screen_editor(name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_distraction_free_mode")
	public static function set_distraction_free_mode(enter:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_distraction_free_mode_enabled")
	public static function get_distraction_free_mode():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_multi_window_enabled")
	public static function is_multi_window_enabled():Bool;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_editor_scale")
	public static function get_editor_scale():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_editor_language")
	public static function get_editor_language():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_node_3d_snap_enabled")
	public static function is_node_3d_snap_enabled():Bool;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_node_3d_translate_snap")
	public static function get_node_3d_translate_snap():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_node_3d_rotate_snap")
	public static function get_node_3d_rotate_snap():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_node_3d_scale_snap")
	public static function get_node_3d_scale_snap():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2015770942)
	@:hash_compatibility([2478844058.])
	@:nativeName("popup_dialog")
	@:argMeta(1, ":default_value"("Rect2i(0, 0, 0, 0)"))
	#if gdscript @:argMeta(1, ":noNullPad"("Rect2i(0, 0, 0, 0)")) #end
	public static function popup_dialog(dialog:godot.Window, @:default_value("Rect2i(0, 0, 0, 0)") #if gdscript @:noNullPad("Rect2i(0, 0, 0, 0)") #end ?rect:godot.Rect2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(346557367)
	@:hash_compatibility([1723337679])
	@:nativeName("popup_dialog_centered")
	@:argMeta(1, ":default_value"("Vector2i(0, 0)"))
	#if gdscript @:argMeta(1, ":noNullPad"("Vector2i(0, 0)")) #end
	public static function popup_dialog_centered(dialog:godot.Window, @:default_value("Vector2i(0, 0)") #if gdscript @:noNullPad("Vector2i(0, 0)") #end ?minsize:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2093669136)
	@:hash_compatibility([1310934579])
	@:nativeName("popup_dialog_centered_ratio")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("0.8"))
	#if gdscript @:argMeta(1, ":noNullPad"("0.8")) #end
	public static function popup_dialog_centered_ratio(dialog:godot.Window, @:meta("float") @:default_value("0.8") #if gdscript @:noNullPad("0.8") #end ratio:Float = 0.8):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3763385571.)
	@:hash_compatibility([3433759678.])
	@:nativeName("popup_dialog_centered_clamped")
	@:argMeta(1, ":default_value"("Vector2i(0, 0)"))
	#if gdscript @:argMeta(1, ":noNullPad"("Vector2i(0, 0)")) #end
	@:argMeta(2, ":meta"("float"))
	@:argMeta(2, ":default_value"("0.75"))
	#if gdscript @:argMeta(2, ":noNullPad"("0.75")) #end
	public static function popup_dialog_centered_clamped(dialog:godot.Window, @:default_value("Vector2i(0, 0)") #if gdscript @:noNullPad("Vector2i(0, 0)") #end ?minsize:godot.Vector2i, @:meta("float") @:default_value("0.75") #if gdscript @:noNullPad("0.75") #end fallback_ratio:Float = 0.75):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_current_feature_profile")
	public static function get_current_feature_profile():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("set_current_feature_profile")
	public static function set_current_feature_profile(profile_name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2444591477.)
	@:hash_compatibility([2271411043.])
	@:nativeName("popup_node_selector")
	@:argMeta(1, ":default_value"("Array[StringName]([])"))
	#if gdscript @:argMeta(1, ":noNullPad"("[]")) #end
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public static function popup_node_selector(callback:godot.Callable, @:default_value("Array[StringName]([])") #if gdscript @:noNullPad("[]") #end ?valid_types:Array<godot.StringName>, @:default_value("null") #if gdscript @:noNullPad("null") #end current_value:godot.Node = null):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2955609011.)
	@:hash_compatibility([261221679])
	@:nativeName("popup_property_selector")
	@:argMeta(2, ":default_value"("PackedInt32Array()"))
	#if gdscript @:argMeta(2, ":noNullPad"("PackedInt32Array()")) #end
	@:argMeta(3, ":default_value"("\"\""))
	#if gdscript @:argMeta(3, ":noNullPad"("\"\"")) #end
	public static function popup_property_selector(object:godot.Object, callback:godot.Callable, @:default_value("PackedInt32Array()") #if gdscript @:noNullPad("PackedInt32Array()") #end ?type_filter:godot.PackedInt32Array, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end current_value:String = "\"\""):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3585505226.)
	@:hash_compatibility(null)
	@:nativeName("popup_method_selector")
	@:argMeta(2, ":default_value"("\"\""))
	#if gdscript @:argMeta(2, ":noNullPad"("\"\"")) #end
	public static function popup_method_selector(object:godot.Object, callback:godot.Callable, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end current_value:String = "\"\""):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2271411043.)
	@:hash_compatibility(null)
	@:nativeName("popup_quick_open")
	@:argMeta(1, ":default_value"("Array[StringName]([])"))
	#if gdscript @:argMeta(1, ":noNullPad"("[]")) #end
	public static function popup_quick_open(callback:godot.Callable, @:default_value("Array[StringName]([])") #if gdscript @:noNullPad("[]") #end ?base_types:Array<godot.StringName>):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(495277124)
	@:hash_compatibility(null)
	@:nativeName("popup_create_dialog")
	@:argMeta(1, ":default_value"("\"\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"\"")) #end
	@:argMeta(2, ":default_value"("\"\""))
	#if gdscript @:argMeta(2, ":noNullPad"("\"\"")) #end
	@:argMeta(3, ":default_value"("\"\""))
	#if gdscript @:argMeta(3, ":noNullPad"("\"\"")) #end
	@:argMeta(4, ":default_value"("Array[StringName]([])"))
	#if gdscript @:argMeta(4, ":noNullPad"("[]")) #end
	public static function popup_create_dialog(callback:godot.Callable, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end ?base_type:godot.StringName, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end current_type:String = "\"\"", @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end dialog_title:String = "\"\"", @:default_value("Array[StringName]([])") #if gdscript @:noNullPad("[]") #end ?type_blocklist:Array<godot.StringName>):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3751012327.)
	@:hash_compatibility(null)
	@:nativeName("get_file_system_dock")
	public static function get_file_system_dock():godot.FileSystemDock;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("select_file")
	public static function select_file(file:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_selected_paths")
	public static function get_selected_paths():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_current_path")
	public static function get_current_path():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_current_directory")
	public static function get_current_directory():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3517113938.)
	@:hash_compatibility(null)
	@:nativeName("get_inspector")
	public static function get_inspector():godot.EditorInspector;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(127962172)
	@:hash_compatibility([2564140749.])
	@:nativeName("inspect_object")
	@:argMeta(1, ":default_value"("\"\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"\"")) #end
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function inspect_object(object:godot.Object, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end for_property:String = "\"\"", @:default_value("false") #if gdscript @:noNullPad("false") #end inspector_only:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(968641751)
	@:hash_compatibility(null)
	@:nativeName("edit_resource")
	public static function edit_resource(resource:godot.Resource):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1078189570)
	@:hash_compatibility(null)
	@:nativeName("edit_node")
	public static function edit_node(node:godot.Node):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(219829402)
	@:hash_compatibility([3664508569.])
	@:nativeName("edit_script")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	@:argMeta(3, ":default_value"("true"))
	#if gdscript @:argMeta(3, ":noNullPad"("true")) #end
	public static function edit_script(script:godot.Script, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end line:Int = -1, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end column:Int = 0, @:default_value("true") #if gdscript @:noNullPad("true") #end grab_focus:Bool = true):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1168363258)
	@:hash_compatibility([83702148])
	@:nativeName("open_scene_from_path")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function open_scene_from_path(scene_filepath:String, @:default_value("false") #if gdscript @:noNullPad("false") #end set_inherited:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("reload_scene_from_path")
	public static function reload_scene_from_path(scene_filepath:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1462101905)
	@:hash_compatibility(null)
	@:nativeName("set_object_edited")
	public static function set_object_edited(object:godot.Object, edited:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(397768994)
	@:hash_compatibility(null)
	@:nativeName("is_object_edited")
	public static function is_object_edited(object:godot.Object):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_open_scenes")
	public static function get_open_scenes():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_unsaved_scenes")
	public static function get_unsaved_scenes():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("get_open_scene_roots")
	public static function get_open_scene_roots():Array<godot.Node>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3160264692.)
	@:hash_compatibility(null)
	@:nativeName("get_edited_scene_root")
	public static function get_edited_scene_root():godot.Node;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1078189570)
	@:hash_compatibility(null)
	@:nativeName("add_root_node")
	public static function add_root_node(node:godot.Node):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("save_scene")
	public static function save_scene():godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3647332257.)
	@:hash_compatibility([1168363258])
	@:nativeName("save_scene_as")
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public static function save_scene_as(path:String, @:default_value("true") #if gdscript @:noNullPad("true") #end with_preview:Bool = true):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("save_all_scenes")
	public static function save_all_scenes():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("close_scene")
	public static function close_scene():godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("mark_scene_as_unsaved")
	public static function mark_scene_as_unsaved():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("play_main_scene")
	public static function play_main_scene():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("play_current_scene")
	public static function play_current_scene():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("play_custom_scene")
	public static function play_custom_scene(scene_filepath:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("stop_playing_scene")
	public static function stop_playing_scene():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_playing_scene")
	public static function is_playing_scene():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_playing_scene")
	public static function get_playing_scene():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_movie_maker_enabled")
	public static function set_movie_maker_enabled(enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_movie_maker_enabled")
	public static function get_movie_maker_enabled():Bool;
}