/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorExportPlugin extends godot.RefCounted {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3533781844.)
	@:hash_compatibility(null)
	@:nativeName("_export_file")
	public function _export_file(path:String, type:String, features:godot.PackedStringArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2765511433.)
	@:hash_compatibility(null)
	@:nativeName("_export_begin")
	@:argMeta(3, ":meta"("uint32"))
	public function _export_begin(features:godot.PackedStringArray, is_debug:Bool, path:String, @:meta("uint32") flags:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_export_end")
	public function _export_end():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2678287736.)
	@:hash_compatibility(null)
	@:nativeName("_end_generate_apple_embedded_project")
	public function _end_generate_apple_embedded_project(path:String, will_build_archive:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1312023292)
	@:hash_compatibility(null)
	@:nativeName("_begin_customize_resources")
	public function _begin_customize_resources(platform:godot.EditorExportPlatform, features:godot.PackedStringArray):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(307917495)
	@:hash_compatibility(null)
	@:nativeName("_customize_resource")
	public function _customize_resource(resource:godot.Resource, path:String):godot.Resource;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1312023292)
	@:hash_compatibility(null)
	@:nativeName("_begin_customize_scenes")
	public function _begin_customize_scenes(platform:godot.EditorExportPlatform, features:godot.PackedStringArray):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(498701822)
	@:hash_compatibility(null)
	@:nativeName("_customize_scene")
	public function _customize_scene(scene:godot.Node, path:String):godot.Node;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_customization_configuration_hash")
	public function _get_customization_configuration_hash():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_end_customize_scenes")
	public function _end_customize_scenes():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_end_customize_resources")
	public function _end_customize_resources():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(488349689)
	@:hash_compatibility(null)
	@:nativeName("_get_export_options")
	public function _get_export_options(platform:godot.EditorExportPlatform):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2837326714.)
	@:hash_compatibility(null)
	@:nativeName("_get_export_options_overrides")
	public function _get_export_options_overrides(platform:godot.EditorExportPlatform):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1866233299)
	@:hash_compatibility(null)
	@:nativeName("_should_update_export_options")
	public function _should_update_export_options(platform:godot.EditorExportPlatform):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3537301980.)
	@:hash_compatibility(null)
	@:nativeName("_get_export_option_visibility")
	public function _get_export_option_visibility(platform:godot.EditorExportPlatform, option:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3340251247.)
	@:hash_compatibility(null)
	@:nativeName("_get_export_option_warning")
	public function _get_export_option_warning(platform:godot.EditorExportPlatform, option:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1057664154)
	@:hash_compatibility(null)
	@:nativeName("_get_export_features")
	public function _get_export_features(platform:godot.EditorExportPlatform, debug:Bool):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_name")
	public function _get_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1866233299)
	@:hash_compatibility(null)
	@:nativeName("_supports_platform")
	public function _supports_platform(platform:godot.EditorExportPlatform):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1057664154)
	@:hash_compatibility(null)
	@:nativeName("_get_android_dependencies")
	public function _get_android_dependencies(platform:godot.EditorExportPlatform, debug:Bool):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1057664154)
	@:hash_compatibility(null)
	@:nativeName("_get_android_dependencies_maven_repos")
	public function _get_android_dependencies_maven_repos(platform:godot.EditorExportPlatform, debug:Bool):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1057664154)
	@:hash_compatibility(null)
	@:nativeName("_get_android_libraries")
	public function _get_android_libraries(platform:godot.EditorExportPlatform, debug:Bool):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4013372917.)
	@:hash_compatibility(null)
	@:nativeName("_get_android_manifest_activity_element_contents")
	public function _get_android_manifest_activity_element_contents(platform:godot.EditorExportPlatform, debug:Bool):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4013372917.)
	@:hash_compatibility(null)
	@:nativeName("_get_android_manifest_application_element_contents")
	public function _get_android_manifest_application_element_contents(platform:godot.EditorExportPlatform, debug:Bool):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4013372917.)
	@:hash_compatibility(null)
	@:nativeName("_get_android_manifest_element_contents")
	public function _get_android_manifest_element_contents(platform:godot.EditorExportPlatform, debug:Bool):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3304965187.)
	@:hash_compatibility(null)
	@:nativeName("_update_android_prebuilt_manifest")
	public function _update_android_prebuilt_manifest(platform:godot.EditorExportPlatform, manifest_data:godot.PackedByteArray):godot.PackedByteArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3098291045.)
	@:hash_compatibility(null)
	@:nativeName("add_shared_object")
	public function add_shared_object(path:String, tags:godot.PackedStringArray, target:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(527928637)
	@:hash_compatibility(null)
	@:nativeName("add_file")
	public function add_file(path:String, file:godot.PackedByteArray, remap:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_project_static_lib")
	public function add_apple_embedded_platform_project_static_lib(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_framework")
	public function add_apple_embedded_platform_framework(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_embedded_framework")
	public function add_apple_embedded_platform_embedded_framework(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_plist_content")
	public function add_apple_embedded_platform_plist_content(plist_content:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_linker_flags")
	public function add_apple_embedded_platform_linker_flags(flags:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_bundle_file")
	public function add_apple_embedded_platform_bundle_file(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_apple_embedded_platform_cpp_code")
	public function add_apple_embedded_platform_cpp_code(code:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_project_static_lib")
	public function add_ios_project_static_lib(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_framework")
	public function add_ios_framework(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_embedded_framework")
	public function add_ios_embedded_framework(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_plist_content")
	public function add_ios_plist_content(plist_content:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_linker_flags")
	public function add_ios_linker_flags(flags:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_bundle_file")
	public function add_ios_bundle_file(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_ios_cpp_code")
	public function add_ios_cpp_code(code:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_macos_plugin_file")
	public function add_macos_plugin_file(path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("skip")
	public function skip():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2760726917.)
	@:hash_compatibility(null)
	@:nativeName("get_option")
	public function get_option(name:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1610607222)
	@:hash_compatibility(null)
	@:nativeName("get_export_preset")
	public function get_export_preset():godot.EditorExportPreset;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(282254641)
	@:hash_compatibility(null)
	@:nativeName("get_export_platform")
	public function get_export_platform():godot.EditorExportPlatform;
}