/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("editor") @:is_resource(false) @:is_node(false) extern class EditorVCSInterface extends godot.Object {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("_initialize")
	public function _initialize(project_path:String):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1336744649)
	@:hash_compatibility(null)
	@:nativeName("_set_credentials")
	public function _set_credentials(username:String, password:String, ssh_public_key_path:String, ssh_private_key_path:String, ssh_passphrase:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("_get_modified_files_data")
	public function _get_modified_files_data():Array<godot.Dictionary>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_stage_file")
	public function _stage_file(file_path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_unstage_file")
	public function _unstage_file(file_path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_discard_file")
	public function _discard_file(file_path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2678287736.)
	@:hash_compatibility([83702148])
	@:nativeName("_commit")
	public function _commit(msg:String, amend:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_allow_amends")
	public function _allow_amends():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1366379175)
	@:hash_compatibility(null)
	@:nativeName("_get_diff")
	@:argMeta(1, ":meta"("int32"))
	public function _get_diff(identifier:String, @:meta("int32") area:Int):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_shut_down")
	public function _shut_down():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("_get_vcs_name")
	public function _get_vcs_name():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1171824711)
	@:hash_compatibility(null)
	@:nativeName("_get_previous_commits")
	@:argMeta(0, ":meta"("int32"))
	public function _get_previous_commits(@:meta("int32") max_commits:Int):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("_get_branch_list")
	public function _get_branch_list():Array<String>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("_get_remotes")
	public function _get_remotes():Array<String>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_create_branch")
	public function _create_branch(branch_name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_remove_branch")
	public function _remove_branch(branch_name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3186203200.)
	@:hash_compatibility(null)
	@:nativeName("_create_remote")
	public function _create_remote(remote_name:String, remote_url:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_remove_remote")
	public function _remove_remote(remote_name:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("_get_current_branch_name")
	public function _get_current_branch_name():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("_checkout_branch")
	public function _checkout_branch(branch_name:String):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_pull")
	public function _pull(remote:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2678287736.)
	@:hash_compatibility(null)
	@:nativeName("_push")
	public function _push(remote:String, force:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_fetch")
	public function _fetch(remote:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2796572089.)
	@:hash_compatibility(null)
	@:nativeName("_get_line_diff")
	public function _get_line_diff(file_path:String, text:String):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2901184053.)
	@:hash_compatibility(null)
	@:nativeName("create_diff_line")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function create_diff_line(@:meta("int32") new_line_no:Int, @:meta("int32") old_line_no:Int, content:String, status:String):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3784842090.)
	@:hash_compatibility(null)
	@:nativeName("create_diff_hunk")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(3, ":meta"("int32"))
	public function create_diff_hunk(@:meta("int32") old_start:Int, @:meta("int32") new_start:Int, @:meta("int32") old_lines:Int, @:meta("int32") new_lines:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2723227684.)
	@:hash_compatibility(null)
	@:nativeName("create_diff_file")
	public function create_diff_file(new_file:String, old_file:String):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1075983584)
	@:hash_compatibility(null)
	@:nativeName("create_commit")
	@:argMeta(3, ":meta"("int64"))
	@:argMeta(4, ":meta"("int64"))
	public function create_commit(msg:String, author:String, id:String, @:meta("int64") unix_timestamp:Int, @:meta("int64") offset_minutes:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1083471673)
	@:hash_compatibility(null)
	@:nativeName("create_status_file")
	public function create_status_file(file_path:String, change_type:godot.EditorVCSInterface_ChangeType, area:godot.EditorVCSInterface_TreeArea):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4015243225.)
	@:hash_compatibility(null)
	@:nativeName("add_diff_hunks_into_diff_file")
	public function add_diff_hunks_into_diff_file(diff_file:godot.Dictionary, diff_hunks:Array<godot.Dictionary>):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4015243225.)
	@:hash_compatibility(null)
	@:nativeName("add_line_diffs_into_diff_hunk")
	public function add_line_diffs_into_diff_hunk(diff_hunk:godot.Dictionary, line_diffs:Array<godot.Dictionary>):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("popup_error")
	public function popup_error(msg:String):Void;
}