/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class ENetConnection extends godot.RefCounted {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1515002313)
	@:hash_compatibility([866250949])
	@:nativeName("create_host_bound")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("32"))
	#if gdscript @:argMeta(2, ":noNullPad"("32")) #end
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	@:argMeta(4, ":meta"("int32"))
	@:argMeta(4, ":default_value"("0"))
	#if gdscript @:argMeta(4, ":noNullPad"("0")) #end
	@:argMeta(5, ":meta"("int32"))
	@:argMeta(5, ":default_value"("0"))
	#if gdscript @:argMeta(5, ":noNullPad"("0")) #end
	public function create_host_bound(bind_address:String, @:meta("int32") bind_port:Int, @:meta("int32") @:default_value("32") #if gdscript @:noNullPad("32") #end max_peers:Int = 32, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end max_channels:Int = 0, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end in_bandwidth:Int = 0, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end out_bandwidth:Int = 0):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(117198950)
	@:hash_compatibility(null)
	@:nativeName("create_host")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("32"))
	#if gdscript @:argMeta(0, ":noNullPad"("32")) #end
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function create_host(@:meta("int32") @:default_value("32") #if gdscript @:noNullPad("32") #end max_peers:Int = 32, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end max_channels:Int = 0, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end in_bandwidth:Int = 0, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end out_bandwidth:Int = 0):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("destroy")
	public function destroy():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2171300490.)
	@:hash_compatibility([385984708])
	@:nativeName("connect_to_host")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function connect_to_host(address:String, @:meta("int32") port:Int, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end channels:Int = 0, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end data:Int = 0):godot.ENetPacketPeer;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2402345344.)
	@:hash_compatibility(null)
	@:nativeName("service")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public function service(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end timeout:Int = 0):GodotArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("flush")
	public function flush():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2302169788.)
	@:hash_compatibility(null)
	@:nativeName("bandwidth_limit")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	public function bandwidth_limit(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end in_bandwidth:Int = 0, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end out_bandwidth:Int = 0):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("channel_limit")
	@:argMeta(0, ":meta"("int32"))
	public function channel_limit(@:meta("int32") limit:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2772371345.)
	@:hash_compatibility(null)
	@:nativeName("broadcast")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function broadcast(@:meta("int32") channel:Int, packet:godot.PackedByteArray, @:meta("int32") flags:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2660215187.)
	@:hash_compatibility(null)
	@:nativeName("compress")
	public function compress(mode:godot.ENetConnection_CompressionMode):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1262296096)
	@:hash_compatibility(null)
	@:nativeName("dtls_server_setup")
	public function dtls_server_setup(server_options:godot.TLSOptions):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1966198364)
	@:hash_compatibility([3097527179.])
	@:nativeName("dtls_client_setup")
	@:argMeta(1, ":default_value"("null"))
	#if gdscript @:argMeta(1, ":noNullPad"("null")) #end
	public function dtls_client_setup(hostname:String, @:default_value("null") #if gdscript @:noNullPad("null") #end client_options:godot.TLSOptions = null):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("refuse_new_connections")
	public function refuse_new_connections(refuse:Bool):Void;
	@:return_value_meta("double")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2166904170.)
	@:hash_compatibility(null)
	@:nativeName("pop_statistic")
	public function pop_statistic(statistic:godot.ENetConnection_HostStatistic):Float;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_max_channels")
	public function get_max_channels():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_local_port")
	public function get_local_port():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("get_peers")
	public function get_peers():Array<godot.ENetPacketPeer>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1100646812)
	@:hash_compatibility(null)
	@:nativeName("socket_send")
	@:argMeta(1, ":meta"("int32"))
	public function socket_send(destination_address:String, @:meta("int32") destination_port:Int, packet:godot.PackedByteArray):Void;
}