/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class EngineDebugger extends godot.Object {
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_active")
	public static function is_active():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3651669560.)
	@:hash_compatibility(null)
	@:nativeName("register_profiler")
	public static function register_profiler(name:godot.StringName, profiler:godot.EngineProfiler):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("unregister_profiler")
	public static function unregister_profiler(name:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2041966384)
	@:hash_compatibility(null)
	@:nativeName("is_profiling")
	public static function is_profiling(name:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2041966384)
	@:hash_compatibility(null)
	@:nativeName("has_profiler")
	public static function has_profiler(name:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1895267858)
	@:hash_compatibility(null)
	@:nativeName("profiler_add_frame_data")
	public static function profiler_add_frame_data(name:godot.StringName, data:GodotArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3192561009.)
	@:hash_compatibility([438160728])
	@:nativeName("profiler_enable")
	@:argMeta(2, ":default_value"("[]"))
	#if gdscript @:argMeta(2, ":noNullPad"("[]")) #end
	public static function profiler_enable(name:godot.StringName, enable:Bool, @:default_value("[]") #if gdscript @:noNullPad("[]") #end ?arguments:GodotArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1874754934)
	@:hash_compatibility(null)
	@:nativeName("register_message_capture")
	public static function register_message_capture(name:godot.StringName, callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("unregister_message_capture")
	public static function unregister_message_capture(name:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2041966384)
	@:hash_compatibility(null)
	@:nativeName("has_capture")
	public static function has_capture(name:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("line_poll")
	public static function line_poll():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1209351045)
	@:hash_compatibility(null)
	@:nativeName("send_message")
	public static function send_message(message:String, data:GodotArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2751962654.)
	@:hash_compatibility(null)
	@:nativeName("debug")
	@:argMeta(0, ":default_value"("true"))
	#if gdscript @:argMeta(0, ":noNullPad"("true")) #end
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function debug(@:default_value("true") #if gdscript @:noNullPad("true") #end can_continue:Bool = true, @:default_value("false") #if gdscript @:noNullPad("false") #end is_error_breakpoint:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2442343672.)
	@:hash_compatibility(null)
	@:nativeName("script_debug")
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function script_debug(language:godot.ScriptLanguage, @:default_value("true") #if gdscript @:noNullPad("true") #end can_continue:Bool = true, @:default_value("false") #if gdscript @:noNullPad("false") #end is_error_breakpoint:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_lines_left")
	@:argMeta(0, ":meta"("int32"))
	public static function set_lines_left(@:meta("int32") lines:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_lines_left")
	public static function get_lines_left():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_depth")
	@:argMeta(0, ":meta"("int32"))
	public static function set_depth(@:meta("int32") depth:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_depth")
	public static function get_depth():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(921227809)
	@:hash_compatibility(null)
	@:nativeName("is_breakpoint")
	@:argMeta(0, ":meta"("int32"))
	public static function is_breakpoint(@:meta("int32") line:Int, source:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_skipping_breakpoints")
	public static function is_skipping_breakpoints():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3780747571.)
	@:hash_compatibility(null)
	@:nativeName("insert_breakpoint")
	@:argMeta(0, ":meta"("int32"))
	public static function insert_breakpoint(@:meta("int32") line:Int, source:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3780747571.)
	@:hash_compatibility(null)
	@:nativeName("remove_breakpoint")
	@:argMeta(0, ":meta"("int32"))
	public static function remove_breakpoint(@:meta("int32") line:Int, source:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_breakpoints")
	public static function clear_breakpoints():Void;
}