/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(false) @:api_type("core") @:is_resource(true) @:is_node(false) extern class FileAccess extends godot.RefCounted {
	public function new();
#if use_properties
	@:index(null)
	@:getter("is_big_endian")
	@:setter("set_big_endian")
	public var big_endian(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_big_endian")
	@:setter("set_big_endian")
	public var big_endian : Bool;
#end
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1247358404)
	@:hash_compatibility(null)
	@:nativeName("open")
	public static function open(path:String, flags:godot.FileAccess_ModeFlags):godot.FileAccess;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(788003459)
	@:hash_compatibility([1482131466])
	@:nativeName("open_encrypted")
	@:argMeta(3, ":default_value"("PackedByteArray()"))
	#if gdscript @:argMeta(3, ":noNullPad"("PackedByteArray()")) #end
	public static function open_encrypted(path:String, mode_flags:godot.FileAccess_ModeFlags, key:godot.PackedByteArray, @:default_value("PackedByteArray()") #if gdscript @:noNullPad("PackedByteArray()") #end ?iv:godot.PackedByteArray):godot.FileAccess;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(790283377)
	@:hash_compatibility(null)
	@:nativeName("open_encrypted_with_pass")
	public static function open_encrypted_with_pass(path:String, mode_flags:godot.FileAccess_ModeFlags, pass:String):godot.FileAccess;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3686439335.)
	@:hash_compatibility([2874458257.])
	@:nativeName("open_compressed")
	@:argMeta(2, ":default_value"("FileAccess.CompressionMode.COMPRESSION_FASTLZ"))
	#if gdscript @:argMeta(2, ":noNullPad"("FileAccess.CompressionMode.COMPRESSION_FASTLZ")) #end
	public static function open_compressed(path:String, mode_flags:godot.FileAccess_ModeFlags, @:default_value("FileAccess.CompressionMode.COMPRESSION_FASTLZ") #if gdscript @:noNullPad("FileAccess.CompressionMode.COMPRESSION_FASTLZ") #end compression_mode:godot.FileAccess_CompressionMode = godot.FileAccess_CompressionMode.COMPRESSION_FASTLZ):godot.FileAccess;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("get_open_error")
	public static function get_open_error():godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(171914364)
	@:hash_compatibility([3075606245.])
	@:nativeName("create_temp")
	@:argMeta(1, ":default_value"("\"\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"\"")) #end
	@:argMeta(2, ":default_value"("\"\""))
	#if gdscript @:argMeta(2, ":noNullPad"("\"\"")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public static function create_temp(mode_flags:godot.FileAccess_ModeFlags, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end prefix:String = "\"\"", @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end extension:String = "\"\"", @:default_value("false") #if gdscript @:noNullPad("false") #end keep:Bool = false):godot.FileAccess;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(659035735)
	@:hash_compatibility(null)
	@:nativeName("get_file_as_bytes")
	public static function get_file_as_bytes(path:String):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1703090593)
	@:hash_compatibility(null)
	@:nativeName("get_file_as_string")
	public static function get_file_as_string(path:String):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844576869)
	@:hash_compatibility(null)
	@:nativeName("resize")
	@:argMeta(0, ":meta"("int64"))
	public function resize(@:meta("int64") length:Int):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("flush")
	public function flush():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_path")
	public function get_path():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_path_absolute")
	public function get_path_absolute():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_open")
	public function is_open():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("seek")
	@:argMeta(0, ":meta"("uint64"))
	public function seek(@:meta("uint64") position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1995695955)
	@:hash_compatibility(null)
	@:nativeName("seek_end")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public function seek_end(@:meta("int64") @:default_value("0") #if gdscript @:noNullPad("0") #end position:Int = 0):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_position")
	public function get_position():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_length")
	public function get_length():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("eof_reached")
	public function eof_reached():Bool;
	@:return_value_meta("uint8")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_8")
	public function get_8():Int;
	@:return_value_meta("uint16")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_16")
	public function get_16():Int;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_32")
	public function get_32():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_64")
	public function get_64():Int;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_half")
	public function get_half():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_float")
	public function get_float():Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_double")
	public function get_double():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_real")
	public function get_real():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4131300905.)
	@:hash_compatibility(null)
	@:nativeName("get_buffer")
	@:argMeta(0, ":meta"("int64"))
	public function get_buffer(@:meta("int64") length:Int):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_line")
	public function get_line():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2358116058.)
	@:hash_compatibility(null)
	@:nativeName("get_csv_line")
	@:argMeta(0, ":default_value"("\",\""))
	#if gdscript @:argMeta(0, ":noNullPad"("\",\"")) #end
	public function get_csv_line(@:default_value("\",\"") #if gdscript @:noNullPad("\",\"") #end delim:String = "\",\""):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility([1162154673])
	@:nativeName("get_as_text")
	public function get_as_text():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1703090593)
	@:hash_compatibility(null)
	@:nativeName("get_md5")
	public static function get_md5(path:String):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1703090593)
	@:hash_compatibility(null)
	@:nativeName("get_sha256")
	public static function get_sha256(path:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_big_endian")
	@:native("is_big_endian")
	public function get_big_endian():Bool;
#if use_properties
	public extern inline function set_big_endian(v: Bool): Bool {
		set_big_endian_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_big_endian")
	@:native("set_big_endian")
	public function set_big_endian_impl(big_endian:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_big_endian")
	public function set_big_endian(big_endian:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3185525595.)
	@:hash_compatibility(null)
	@:nativeName("get_error")
	public function get_error():godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(189129690)
	@:hash_compatibility(null)
	@:nativeName("get_var")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_var(@:default_value("false") #if gdscript @:noNullPad("false") #end allow_objects:Bool = false):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility([1286410249])
	@:nativeName("store_8")
	@:argMeta(0, ":meta"("uint8"))
	public function store_8(@:meta("uint8") value:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility([1286410249])
	@:nativeName("store_16")
	@:argMeta(0, ":meta"("uint16"))
	public function store_16(@:meta("uint16") value:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility([1286410249])
	@:nativeName("store_32")
	@:argMeta(0, ":meta"("uint32"))
	public function store_32(@:meta("uint32") value:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility([1286410249])
	@:nativeName("store_64")
	@:argMeta(0, ":meta"("uint64"))
	public function store_64(@:meta("uint64") value:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(330693286)
	@:hash_compatibility([373806689])
	@:nativeName("store_half")
	@:argMeta(0, ":meta"("float"))
	public function store_half(@:meta("float") value:Float):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(330693286)
	@:hash_compatibility([373806689])
	@:nativeName("store_float")
	@:argMeta(0, ":meta"("float"))
	public function store_float(@:meta("float") value:Float):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(330693286)
	@:hash_compatibility([373806689])
	@:nativeName("store_double")
	@:argMeta(0, ":meta"("double"))
	public function store_double(@:meta("double") value:Float):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(330693286)
	@:hash_compatibility([373806689])
	@:nativeName("store_real")
	@:argMeta(0, ":meta"("float"))
	public function store_real(@:meta("float") value:Float):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(114037665)
	@:hash_compatibility([2971499966.])
	@:nativeName("store_buffer")
	public function store_buffer(buffer:godot.PackedByteArray):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility([83702148])
	@:nativeName("store_line")
	public function store_line(line:String):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1611473434)
	@:hash_compatibility([2173791505., 2217842308.])
	@:nativeName("store_csv_line")
	@:argMeta(1, ":default_value"("\",\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\",\"")) #end
	public function store_csv_line(values:godot.PackedStringArray, @:default_value("\",\"") #if gdscript @:noNullPad("\",\"") #end delim:String = "\",\""):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility([83702148])
	@:nativeName("store_string")
	public function store_string(string:String):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(117357437)
	@:hash_compatibility([738511890])
	@:nativeName("store_var")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function store_var(value:Dynamic, @:default_value("false") #if gdscript @:noNullPad("false") #end full_objects:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility([83702148])
	@:nativeName("store_pascal_string")
	public function store_pascal_string(string:String):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("get_pascal_string")
	public function get_pascal_string():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("close")
	public function close():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("file_exists")
	public static function file_exists(path:String):Bool;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1597066294)
	@:hash_compatibility(null)
	@:nativeName("get_modified_time")
	public static function get_modified_time(file:String):Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1597066294)
	@:hash_compatibility(null)
	@:nativeName("get_access_time")
	public static function get_access_time(file:String):Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1597066294)
	@:hash_compatibility(null)
	@:nativeName("get_size")
	public static function get_size(file:String):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(524341837)
	@:hash_compatibility(null)
	@:nativeName("get_unix_permissions")
	public static function get_unix_permissions(file:String):godot.FileAccess_UnixPermissionFlags;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(846038644)
	@:hash_compatibility(null)
	@:nativeName("set_unix_permissions")
	public static function set_unix_permissions(file:String, permissions:godot.FileAccess_UnixPermissionFlags):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("get_hidden_attribute")
	public static function get_hidden_attribute(file:String):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2892558115.)
	@:hash_compatibility(null)
	@:nativeName("set_hidden_attribute")
	public static function set_hidden_attribute(file:String, hidden:Bool):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2892558115.)
	@:hash_compatibility(null)
	@:nativeName("set_read_only_attribute")
	public static function set_read_only_attribute(file:String, ro:Bool):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("get_read_only_attribute")
	public static function get_read_only_attribute(file:String):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(955893464)
	@:hash_compatibility(null)
	@:nativeName("get_extended_attribute")
	public static function get_extended_attribute(file:String, attribute_name:String):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1218461987)
	@:hash_compatibility(null)
	@:nativeName("get_extended_attribute_string")
	public static function get_extended_attribute_string(file:String, attribute_name:String):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2643421469.)
	@:hash_compatibility(null)
	@:nativeName("set_extended_attribute")
	public static function set_extended_attribute(file:String, attribute_name:String, data:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(699024349)
	@:hash_compatibility(null)
	@:nativeName("set_extended_attribute_string")
	public static function set_extended_attribute_string(file:String, attribute_name:String, data:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("remove_extended_attribute")
	public static function remove_extended_attribute(file:String, attribute_name:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3538744774.)
	@:hash_compatibility(null)
	@:nativeName("get_extended_attributes_list")
	public static function get_extended_attributes_list(file:String):godot.PackedStringArray;
}