/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class GDScriptTextDocument extends godot.RefCounted {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("show_native_symbol_in_editor")
	public function show_native_symbol_in_editor(symbol_id:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1114965689)
	@:hash_compatibility(null)
	@:nativeName("didOpen")
	public function didOpen(params:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1114965689)
	@:hash_compatibility(null)
	@:nativeName("didClose")
	public function didClose(params:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1114965689)
	@:hash_compatibility(null)
	@:nativeName("didChange")
	public function didChange(params:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1114965689)
	@:hash_compatibility(null)
	@:nativeName("willSaveWaitUntil")
	public function willSaveWaitUntil(params:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1114965689)
	@:hash_compatibility(null)
	@:nativeName("didSave")
	public function didSave(params:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3762224011.)
	@:hash_compatibility(null)
	@:nativeName("nativeSymbol")
	public function nativeSymbol(params:godot.Dictionary):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("documentSymbol")
	public function documentSymbol(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("completion")
	public function completion(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1333564645)
	@:hash_compatibility(null)
	@:nativeName("resolve")
	public function resolve(params:godot.Dictionary):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1333564645)
	@:hash_compatibility(null)
	@:nativeName("rename")
	public function rename(params:godot.Dictionary):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3762224011.)
	@:hash_compatibility(null)
	@:nativeName("prepareRename")
	public function prepareRename(params:godot.Dictionary):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("references")
	public function references(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("foldingRange")
	public function foldingRange(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("codeLens")
	public function codeLens(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("documentLink")
	public function documentLink(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("colorPresentation")
	public function colorPresentation(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3762224011.)
	@:hash_compatibility(null)
	@:nativeName("hover")
	public function hover(params:godot.Dictionary):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3877611628.)
	@:hash_compatibility(null)
	@:nativeName("definition")
	public function definition(params:godot.Dictionary):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3762224011.)
	@:hash_compatibility(null)
	@:nativeName("declaration")
	public function declaration(params:godot.Dictionary):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3762224011.)
	@:hash_compatibility(null)
	@:nativeName("signatureHelp")
	public function signatureHelp(params:godot.Dictionary):Dynamic;
}