/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("Generic6DOFJoint3D.Param") #end @:is_bitfield(false) extern enum Generic6DOFJoint3D_Param {
	PARAM_LINEAR_LOWER_LIMIT();
	PARAM_LINEAR_UPPER_LIMIT();
	PARAM_LINEAR_LIMIT_SOFTNESS();
	PARAM_LINEAR_RESTITUTION();
	PARAM_LINEAR_DAMPING();
	PARAM_LINEAR_MOTOR_TARGET_VELOCITY();
	PARAM_LINEAR_MOTOR_FORCE_LIMIT();
	PARAM_LINEAR_SPRING_STIFFNESS();
	PARAM_LINEAR_SPRING_DAMPING();
	PARAM_LINEAR_SPRING_EQUILIBRIUM_POINT();
	PARAM_ANGULAR_LOWER_LIMIT();
	PARAM_ANGULAR_UPPER_LIMIT();
	PARAM_ANGULAR_LIMIT_SOFTNESS();
	PARAM_ANGULAR_DAMPING();
	PARAM_ANGULAR_RESTITUTION();
	PARAM_ANGULAR_FORCE_LIMIT();
	PARAM_ANGULAR_ERP();
	PARAM_ANGULAR_MOTOR_TARGET_VELOCITY();
	PARAM_ANGULAR_MOTOR_FORCE_LIMIT();
	PARAM_ANGULAR_SPRING_STIFFNESS();
	PARAM_ANGULAR_SPRING_DAMPING();
	PARAM_ANGULAR_SPRING_EQUILIBRIUM_POINT();
	PARAM_MAX();
}