/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class Geometry2D extends godot.Object {
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2929491703.)
	@:hash_compatibility(null)
	@:nativeName("is_point_in_circle")
	@:argMeta(2, ":meta"("float"))
	public static function is_point_in_circle(point:godot.Vector2, circle_position:godot.Vector2, @:meta("float") circle_radius:Float):Bool;
	@:return_value_meta("float")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1356928167)
	@:hash_compatibility(null)
	@:nativeName("segment_intersects_circle")
	@:argMeta(3, ":meta"("float"))
	public static function segment_intersects_circle(segment_from:godot.Vector2, segment_to:godot.Vector2, circle_position:godot.Vector2, @:meta("float") circle_radius:Float):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2058025344)
	@:hash_compatibility(null)
	@:nativeName("segment_intersects_segment")
	public static function segment_intersects_segment(from_a:godot.Vector2, to_a:godot.Vector2, from_b:godot.Vector2, to_b:godot.Vector2):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2058025344)
	@:hash_compatibility(null)
	@:nativeName("line_intersects_line")
	public static function line_intersects_line(from_a:godot.Vector2, dir_a:godot.Vector2, from_b:godot.Vector2, dir_b:godot.Vector2):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3344690961.)
	@:hash_compatibility(null)
	@:nativeName("get_closest_points_between_segments")
	public static function get_closest_points_between_segments(p1:godot.Vector2, q1:godot.Vector2, p2:godot.Vector2, q2:godot.Vector2):godot.PackedVector2Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4172901909.)
	@:hash_compatibility(null)
	@:nativeName("get_closest_point_to_segment")
	public static function get_closest_point_to_segment(point:godot.Vector2, s1:godot.Vector2, s2:godot.Vector2):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4172901909.)
	@:hash_compatibility(null)
	@:nativeName("get_closest_point_to_segment_uncapped")
	public static function get_closest_point_to_segment_uncapped(point:godot.Vector2, s1:godot.Vector2, s2:godot.Vector2):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025948137)
	@:hash_compatibility(null)
	@:nativeName("point_is_inside_triangle")
	public static function point_is_inside_triangle(point:godot.Vector2, a:godot.Vector2, b:godot.Vector2, c:godot.Vector2):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1361156557)
	@:hash_compatibility(null)
	@:nativeName("is_polygon_clockwise")
	public static function is_polygon_clockwise(polygon:godot.PackedVector2Array):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(738277916)
	@:hash_compatibility(null)
	@:nativeName("is_point_in_polygon")
	public static function is_point_in_polygon(point:godot.Vector2, polygon:godot.PackedVector2Array):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1389921771)
	@:hash_compatibility(null)
	@:nativeName("triangulate_polygon")
	public static function triangulate_polygon(polygon:godot.PackedVector2Array):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1389921771)
	@:hash_compatibility(null)
	@:nativeName("triangulate_delaunay")
	public static function triangulate_delaunay(points:godot.PackedVector2Array):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2004331998)
	@:hash_compatibility(null)
	@:nativeName("convex_hull")
	public static function convex_hull(points:godot.PackedVector2Array):godot.PackedVector2Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3982393695.)
	@:hash_compatibility(null)
	@:nativeName("decompose_polygon_in_convex")
	public static function decompose_polygon_in_convex(polygon:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3637387053.)
	@:hash_compatibility(null)
	@:nativeName("merge_polygons")
	public static function merge_polygons(polygon_a:godot.PackedVector2Array, polygon_b:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3637387053.)
	@:hash_compatibility(null)
	@:nativeName("clip_polygons")
	public static function clip_polygons(polygon_a:godot.PackedVector2Array, polygon_b:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3637387053.)
	@:hash_compatibility(null)
	@:nativeName("intersect_polygons")
	public static function intersect_polygons(polygon_a:godot.PackedVector2Array, polygon_b:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3637387053.)
	@:hash_compatibility(null)
	@:nativeName("exclude_polygons")
	public static function exclude_polygons(polygon_a:godot.PackedVector2Array, polygon_b:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3637387053.)
	@:hash_compatibility(null)
	@:nativeName("clip_polyline_with_polygon")
	public static function clip_polyline_with_polygon(polyline:godot.PackedVector2Array, polygon:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3637387053.)
	@:hash_compatibility(null)
	@:nativeName("intersect_polyline_with_polygon")
	public static function intersect_polyline_with_polygon(polyline:godot.PackedVector2Array, polygon:godot.PackedVector2Array):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1275354010)
	@:hash_compatibility([3837618924.])
	@:nativeName("offset_polygon")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(2, ":default_value"("Geometry2D.PolyJoinType.JOIN_SQUARE"))
	#if gdscript @:argMeta(2, ":noNullPad"("Geometry2D.PolyJoinType.JOIN_SQUARE")) #end
	public static function offset_polygon(polygon:godot.PackedVector2Array, @:meta("float") delta:Float, @:default_value("Geometry2D.PolyJoinType.JOIN_SQUARE") #if gdscript @:noNullPad("Geometry2D.PolyJoinType.JOIN_SQUARE") #end join_type:godot.Geometry2D_PolyJoinType = godot.Geometry2D_PolyJoinType.JOIN_SQUARE):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2328231778.)
	@:hash_compatibility([328033063])
	@:nativeName("offset_polyline")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(2, ":default_value"("Geometry2D.PolyJoinType.JOIN_SQUARE"))
	#if gdscript @:argMeta(2, ":noNullPad"("Geometry2D.PolyJoinType.JOIN_SQUARE")) #end
	@:argMeta(3, ":default_value"("Geometry2D.PolyEndType.END_SQUARE"))
	#if gdscript @:argMeta(3, ":noNullPad"("Geometry2D.PolyEndType.END_SQUARE")) #end
	public static function offset_polyline(polyline:godot.PackedVector2Array, @:meta("float") delta:Float, @:default_value("Geometry2D.PolyJoinType.JOIN_SQUARE") #if gdscript @:noNullPad("Geometry2D.PolyJoinType.JOIN_SQUARE") #end join_type:godot.Geometry2D_PolyJoinType = godot.Geometry2D_PolyJoinType.JOIN_SQUARE, @:default_value("Geometry2D.PolyEndType.END_SQUARE") #if gdscript @:noNullPad("Geometry2D.PolyEndType.END_SQUARE") #end end_type:godot.Geometry2D_PolyEndType = godot.Geometry2D_PolyEndType.END_SQUARE):Array<godot.PackedVector2Array>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1337682371)
	@:hash_compatibility(null)
	@:nativeName("make_atlas")
	public static function make_atlas(sizes:godot.PackedVector2Array):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1989391000)
	@:hash_compatibility(null)
	@:nativeName("bresenham_line")
	public static function bresenham_line(from:godot.Vector2i, to:godot.Vector2i):Array<godot.Vector2i>;
}