/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class Geometry3D extends godot.Object {
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1936902142)
	@:hash_compatibility(null)
	@:nativeName("compute_convex_mesh_points")
	public static function compute_convex_mesh_points(planes:Array<godot.Plane>):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3622277145.)
	@:hash_compatibility(null)
	@:nativeName("build_box_planes")
	public static function build_box_planes(extents:godot.Vector3):Array<godot.Plane>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(449920067)
	@:hash_compatibility([3142160516.])
	@:nativeName("build_cylinder_planes")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(1, ":meta"("float"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(3, ":default_value"("2"))
	#if gdscript @:argMeta(3, ":noNullPad"("2")) #end
	public static function build_cylinder_planes(@:meta("float") radius:Float, @:meta("float") height:Float, @:meta("int32") sides:Int, @:default_value("2") #if gdscript @:noNullPad("2") #end ?axis:godot.Vector3_Axis):Array<godot.Plane>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2113592876)
	@:hash_compatibility([410870045])
	@:nativeName("build_capsule_planes")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(1, ":meta"("float"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(4, ":default_value"("2"))
	#if gdscript @:argMeta(4, ":noNullPad"("2")) #end
	public static function build_capsule_planes(@:meta("float") radius:Float, @:meta("float") height:Float, @:meta("int32") sides:Int, @:meta("int32") lats:Int, @:default_value("2") #if gdscript @:noNullPad("2") #end ?axis:godot.Vector3_Axis):Array<godot.Plane>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1056373962)
	@:hash_compatibility(null)
	@:nativeName("get_closest_points_between_segments")
	public static function get_closest_points_between_segments(p1:godot.Vector3, p2:godot.Vector3, q1:godot.Vector3, q2:godot.Vector3):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2168193209.)
	@:hash_compatibility(null)
	@:nativeName("get_closest_point_to_segment")
	public static function get_closest_point_to_segment(point:godot.Vector3, s1:godot.Vector3, s2:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2168193209.)
	@:hash_compatibility(null)
	@:nativeName("get_closest_point_to_segment_uncapped")
	public static function get_closest_point_to_segment_uncapped(point:godot.Vector3, s1:godot.Vector3, s2:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1362048029)
	@:hash_compatibility(null)
	@:nativeName("get_triangle_barycentric_coords")
	public static function get_triangle_barycentric_coords(point:godot.Vector3, a:godot.Vector3, b:godot.Vector3, c:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1718655448)
	@:hash_compatibility(null)
	@:nativeName("ray_intersects_triangle")
	public static function ray_intersects_triangle(from:godot.Vector3, dir:godot.Vector3, a:godot.Vector3, b:godot.Vector3, c:godot.Vector3):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1718655448)
	@:hash_compatibility(null)
	@:nativeName("segment_intersects_triangle")
	public static function segment_intersects_triangle(from:godot.Vector3, to:godot.Vector3, a:godot.Vector3, b:godot.Vector3, c:godot.Vector3):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4080141172.)
	@:hash_compatibility(null)
	@:nativeName("segment_intersects_sphere")
	@:argMeta(3, ":meta"("float"))
	public static function segment_intersects_sphere(from:godot.Vector3, to:godot.Vector3, sphere_position:godot.Vector3, @:meta("float") sphere_radius:Float):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2361316491.)
	@:hash_compatibility(null)
	@:nativeName("segment_intersects_cylinder")
	@:argMeta(2, ":meta"("float"))
	@:argMeta(3, ":meta"("float"))
	public static function segment_intersects_cylinder(from:godot.Vector3, to:godot.Vector3, @:meta("float") height:Float, @:meta("float") radius:Float):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(537425332)
	@:hash_compatibility(null)
	@:nativeName("segment_intersects_convex")
	public static function segment_intersects_convex(from:godot.Vector3, to:godot.Vector3, planes:Array<godot.Plane>):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2603188319.)
	@:hash_compatibility(null)
	@:nativeName("clip_polygon")
	public static function clip_polygon(points:godot.PackedVector3Array, plane:godot.Plane):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1230191221)
	@:hash_compatibility(null)
	@:nativeName("tetrahedralize_delaunay")
	public static function tetrahedralize_delaunay(points:godot.PackedVector3Array):godot.PackedInt32Array;
}