/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class GLTFDocumentExtension extends godot.Resource {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(412946943)
	@:hash_compatibility(null)
	@:nativeName("_import_preflight")
	public function _import_preflight(state:godot.GLTFState, extensions:godot.PackedStringArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("_get_supported_extensions")
	public function _get_supported_extensions():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2067053794)
	@:hash_compatibility(null)
	@:nativeName("_parse_node_extensions")
	public function _parse_node_extensions(state:godot.GLTFState, gltf_node:godot.GLTFNode, extensions:godot.Dictionary):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3201673288.)
	@:hash_compatibility(null)
	@:nativeName("_parse_image_data")
	public function _parse_image_data(state:godot.GLTFState, image_data:godot.PackedByteArray, mime_type:String, ret_image:godot.Image):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("_get_image_file_extension")
	public function _get_image_file_extension():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1624327185)
	@:hash_compatibility(null)
	@:nativeName("_parse_texture_json")
	public function _parse_texture_json(state:godot.GLTFState, texture_json:godot.Dictionary, ret_gltf_texture:godot.GLTFTexture):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1446147484)
	@:hash_compatibility(null)
	@:nativeName("_import_object_model_property")
	public function _import_object_model_property(state:godot.GLTFState, split_json_pointer:godot.PackedStringArray, partial_paths:Array<godot.NodePath>):godot.GLTFObjectModelProperty;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1704600462)
	@:hash_compatibility(null)
	@:nativeName("_import_post_parse")
	public function _import_post_parse(state:godot.GLTFState):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1704600462)
	@:hash_compatibility(null)
	@:nativeName("_import_pre_generate")
	public function _import_pre_generate(state:godot.GLTFState):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3810899026.)
	@:hash_compatibility(null)
	@:nativeName("_generate_scene_node")
	public function _generate_scene_node(state:godot.GLTFState, gltf_node:godot.GLTFNode, scene_parent:godot.Node):godot.Node3D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4064279746.)
	@:hash_compatibility(null)
	@:nativeName("_import_node")
	public function _import_node(state:godot.GLTFState, gltf_node:godot.GLTFNode, json:godot.Dictionary, node:godot.Node):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(295478427)
	@:hash_compatibility(null)
	@:nativeName("_import_post")
	public function _import_post(state:godot.GLTFState, root:godot.Node):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(186716585)
	@:hash_compatibility(null)
	@:nativeName("_export_get_property_list")
	public function _export_get_property_list(root_node:godot.Node):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(295478427)
	@:hash_compatibility(null)
	@:nativeName("_export_preflight")
	public function _export_preflight(state:godot.GLTFState, root:godot.Node):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(147612932)
	@:hash_compatibility(null)
	@:nativeName("_convert_scene_node")
	public function _convert_scene_node(state:godot.GLTFState, gltf_node:godot.GLTFNode, scene_node:godot.Node):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(295478427)
	@:hash_compatibility(null)
	@:nativeName("_export_post_convert")
	public function _export_post_convert(state:godot.GLTFState, root:godot.Node):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1704600462)
	@:hash_compatibility(null)
	@:nativeName("_export_preserialize")
	public function _export_preserialize(state:godot.GLTFState):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4111022730.)
	@:hash_compatibility(null)
	@:nativeName("_export_object_model_property")
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(5, ":meta"("int32"))
	public function _export_object_model_property(state:godot.GLTFState, node_path:godot.NodePath, godot_node:godot.Node, @:meta("int32") gltf_node_index:Int, target_object:godot.Object, @:meta("int32") target_depth:Int):godot.GLTFObjectModelProperty;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("_get_saveable_image_formats")
	public function _get_saveable_image_formats():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(276886664)
	@:hash_compatibility(null)
	@:nativeName("_serialize_image_to_bytes")
	@:argMeta(4, ":meta"("float"))
	public function _serialize_image_to_bytes(state:godot.GLTFState, image:godot.Image, image_dict:godot.Dictionary, image_format:String, @:meta("float") lossy_quality:Float):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1844337242)
	@:hash_compatibility(null)
	@:nativeName("_save_image_at_path")
	@:argMeta(4, ":meta"("float"))
	public function _save_image_at_path(state:godot.GLTFState, image:godot.Image, file_path:String, image_format:String, @:meta("float") lossy_quality:Float):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2565166506.)
	@:hash_compatibility(null)
	@:nativeName("_serialize_texture_json")
	public function _serialize_texture_json(state:godot.GLTFState, texture_json:godot.Dictionary, gltf_texture:godot.GLTFTexture, image_format:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4064279746.)
	@:hash_compatibility(null)
	@:nativeName("_export_node")
	public function _export_node(state:godot.GLTFState, gltf_node:godot.GLTFNode, json:godot.Dictionary, node:godot.Node):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1704600462)
	@:hash_compatibility(null)
	@:nativeName("_export_post")
	public function _export_post(state:godot.GLTFState):godot.Error;
}