/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("builtin_classes") @:indexing_return_type("Variant") @:is_keyed(false) @:has_destructor(true) @:copyType @:noCompletion @:avoid_temporaries @:nativeName("Array") extern class GodotArray_Fields {
	@:overload(function(from:GodotArray):Void { })
	@:overload(function(base:GodotArray, type:Int, class_name:godot.StringName, script:Dynamic):Void { })
	@:overload(function(from:godot.PackedByteArray):Void { })
	@:overload(function(from:godot.PackedInt32Array):Void { })
	@:overload(function(from:godot.PackedInt64Array):Void { })
	@:overload(function(from:godot.PackedFloat32Array):Void { })
	@:overload(function(from:godot.PackedFloat64Array):Void { })
	@:overload(function(from:godot.PackedStringArray):Void { })
	@:overload(function(from:godot.PackedVector2Array):Void { })
	@:overload(function(from:godot.PackedVector3Array):Void { })
	@:overload(function(from:godot.PackedColorArray):Void { })
	@:overload(function(from:godot.PackedVector4Array):Void { })
	public function new();
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("size")
	public function size():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_empty")
	public function is_empty():Bool;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("clear")
	public function clear():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("hash")
	public function hash():Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(2307260970.)
	@:nativeName("assign")
	public function assign(@:default_value(null) array:GodotArray):Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(708700221)
	@:nativeName("get")
	public function get(@:default_value(null) index:Int):Dynamic;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3798478031.)
	@:nativeName("set")
	public function set(@:default_value(null) index:Int, @:default_value(null) value:Dynamic):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3316032543.)
	@:nativeName("push_back")
	public function push_back(@:default_value(null) value:Dynamic):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3316032543.)
	@:nativeName("push_front")
	public function push_front(@:default_value(null) value:Dynamic):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3316032543.)
	@:nativeName("append")
	public function append(@:default_value(null) value:Dynamic):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(2307260970.)
	@:nativeName("append_array")
	public function append_array(@:default_value(null) array:GodotArray):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(848867239)
	@:nativeName("resize")
	public function resize(@:default_value(null) size:Int):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3176316662.)
	@:nativeName("insert")
	public function insert(@:default_value(null) position:Int, @:default_value(null) value:Dynamic):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(2823966027.)
	@:nativeName("remove_at")
	public function remove_at(@:default_value(null) position:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3316032543.)
	@:nativeName("fill")
	public function fill(@:default_value(null) value:Dynamic):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3316032543.)
	@:nativeName("erase")
	public function erase(@:default_value(null) value:Dynamic):Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1460142086)
	@:nativeName("front")
	public function front():Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1460142086)
	@:nativeName("back")
	public function back():Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1460142086)
	@:nativeName("pick_random")
	public function pick_random():Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2336346817.)
	@:nativeName("find")
	public function find(@:default_value(null) what:Dynamic, @:default_value("0") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2145562546)
	@:nativeName("find_custom")
	public function find_custom(@:default_value(null) method:godot.Callable, @:default_value("0") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2336346817.)
	@:nativeName("rfind")
	public function rfind(@:default_value(null) what:Dynamic, @:default_value("-1") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2145562546)
	@:nativeName("rfind_custom")
	public function rfind_custom(@:default_value(null) method:godot.Callable, @:default_value("-1") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1481661226)
	@:nativeName("count")
	public function count(@:default_value(null) value:Dynamic):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3680194679.)
	@:nativeName("has")
	public function has(@:default_value(null) value:Dynamic):Bool;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(1321915136)
	@:nativeName("pop_back")
	public function pop_back():Dynamic;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(1321915136)
	@:nativeName("pop_front")
	public function pop_front():Dynamic;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3518259424.)
	@:nativeName("pop_at")
	public function pop_at(@:default_value(null) position:Int):Dynamic;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("sort")
	public function sort():Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3470848906.)
	@:nativeName("sort_custom")
	public function sort_custom(@:default_value(null) func:godot.Callable):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("shuffle")
	public function shuffle():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3372222236.)
	@:nativeName("bsearch")
	public function bsearch(@:default_value(null) value:Dynamic, @:default_value("true") ?before:Bool):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(161317131)
	@:nativeName("bsearch_custom")
	public function bsearch_custom(@:default_value(null) value:Dynamic, @:default_value(null) func:godot.Callable, @:default_value("true") ?before:Bool):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("reverse")
	public function reverse():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(636440122)
	@:nativeName("duplicate")
	public function duplicate(@:default_value("false") ?deep:Bool):GodotArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1949240801)
	@:nativeName("duplicate_deep")
	public function duplicate_deep(@:default_value("1") ?deep_subresources_mode:Int):GodotArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1393718243)
	@:nativeName("slice")
	public function slice(@:default_value(null) begin:Int, @:default_value("2147483647") ?end:Int, @:default_value("1") ?step:Int, @:default_value("false") ?deep:Bool):GodotArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4075186556.)
	@:nativeName("filter")
	public function filter(@:default_value(null) method:godot.Callable):GodotArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4075186556.)
	@:nativeName("map")
	public function map(@:default_value(null) method:godot.Callable):GodotArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4272450342.)
	@:nativeName("reduce")
	public function reduce(@:default_value(null) method:godot.Callable, @:default_value("null") ?accum:Dynamic):Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4129521963.)
	@:nativeName("any")
	public function any(@:default_value(null) method:godot.Callable):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4129521963.)
	@:nativeName("all")
	public function all(@:default_value(null) method:godot.Callable):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1460142086)
	@:nativeName("max")
	public function max():Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1460142086)
	@:nativeName("min")
	public function min():Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_typed")
	public function is_typed():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2988181878.)
	@:nativeName("is_same_typed")
	public function is_same_typed(@:default_value(null) array:GodotArray):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("get_typed_builtin")
	public function get_typed_builtin():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1825232092)
	@:nativeName("get_typed_class_name")
	public function get_typed_class_name():godot.StringName;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1460142086)
	@:nativeName("get_typed_script")
	public function get_typed_script():Dynamic;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("make_read_only")
	public function make_read_only():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_read_only")
	public function is_read_only():Bool;
}