/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class GraphNode extends godot.GraphElement {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_title")
	@:setter("set_title")
	@:reassignOnSubfieldEdit(set_title_impl)
	public var title(get, set) : String;
#else

	@:index(null)
	@:getter("get_title")
	@:setter("set_title")
	public var title : String;
#end
#if use_properties
	@:index(null)
	@:getter("is_ignoring_valid_connection_type")
	@:setter("set_ignore_invalid_connection_type")
	public var ignore_invalid_connection_type(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_ignoring_valid_connection_type")
	@:setter("set_ignore_invalid_connection_type")
	public var ignore_invalid_connection_type : Bool;
#end
#if !use_properties
	@:index(null)
	@:getter("get_slots_focus_mode")
	@:setter("set_slots_focus_mode")
	public var slots_focus_mode : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(93366828)
	@:hash_compatibility(null)
	@:nativeName("_draw_port")
	@:argMeta(0, ":meta"("int32"))
	public function _draw_port(@:meta("int32") slot_index:Int, position:godot.Vector2i, left:Bool, color:godot.Color):Void;
#if use_properties
	public extern inline function set_title(v: String): String {
		set_title_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("set_title")
	@:native("set_title")
	public function set_title_impl(title:String):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("set_title")
	public function set_title(title:String):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_title")
	public function get_title():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3590609951.)
	@:hash_compatibility(null)
	@:nativeName("get_titlebar_hbox")
	public function get_titlebar_hbox():godot.HBoxContainer;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2873310869.)
	@:hash_compatibility([902131739])
	@:nativeName("set_slot")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(5, ":meta"("int32"))
	@:argMeta(7, ":default_value"("null"))
	#if gdscript @:argMeta(7, ":noNullPad"("null")) #end
	@:argMeta(8, ":default_value"("null"))
	#if gdscript @:argMeta(8, ":noNullPad"("null")) #end
	@:argMeta(9, ":default_value"("true"))
	#if gdscript @:argMeta(9, ":noNullPad"("true")) #end
	public function set_slot(@:meta("int32") slot_index:Int, enable_left_port:Bool, @:meta("int32") type_left:Int, color_left:godot.Color, enable_right_port:Bool, @:meta("int32") type_right:Int, color_right:godot.Color, @:default_value("null") #if gdscript @:noNullPad("null") #end custom_icon_left:godot.Texture2D = null, @:default_value("null") #if gdscript @:noNullPad("null") #end custom_icon_right:godot.Texture2D = null, @:default_value("true") #if gdscript @:noNullPad("true") #end draw_stylebox:Bool = true):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_slot")
	@:argMeta(0, ":meta"("int32"))
	public function clear_slot(@:meta("int32") slot_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_all_slots")
	public function clear_all_slots():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_slot_enabled_left")
	@:argMeta(0, ":meta"("int32"))
	public function is_slot_enabled_left(@:meta("int32") slot_index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_slot_enabled_left")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_enabled_left(@:meta("int32") slot_index:Int, enable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_slot_type_left")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_slot_type_left(@:meta("int32") slot_index:Int, @:meta("int32") type:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_slot_type_left")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_type_left(@:meta("int32") slot_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_slot_color_left")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_color_left(@:meta("int32") slot_index:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3457211756.)
	@:hash_compatibility(null)
	@:nativeName("get_slot_color_left")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_color_left(@:meta("int32") slot_index:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(666127730)
	@:hash_compatibility(null)
	@:nativeName("set_slot_custom_icon_left")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_custom_icon_left(@:meta("int32") slot_index:Int, custom_icon:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3536238170.)
	@:hash_compatibility(null)
	@:nativeName("get_slot_custom_icon_left")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_custom_icon_left(@:meta("int32") slot_index:Int):godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2152698145.)
	@:hash_compatibility(null)
	@:nativeName("set_slot_metadata_left")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_metadata_left(@:meta("int32") slot_index:Int, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("get_slot_metadata_left")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_metadata_left(@:meta("int32") slot_index:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_slot_enabled_right")
	@:argMeta(0, ":meta"("int32"))
	public function is_slot_enabled_right(@:meta("int32") slot_index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_slot_enabled_right")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_enabled_right(@:meta("int32") slot_index:Int, enable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_slot_type_right")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_slot_type_right(@:meta("int32") slot_index:Int, @:meta("int32") type:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_slot_type_right")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_type_right(@:meta("int32") slot_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_slot_color_right")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_color_right(@:meta("int32") slot_index:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3457211756.)
	@:hash_compatibility(null)
	@:nativeName("get_slot_color_right")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_color_right(@:meta("int32") slot_index:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(666127730)
	@:hash_compatibility(null)
	@:nativeName("set_slot_custom_icon_right")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_custom_icon_right(@:meta("int32") slot_index:Int, custom_icon:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3536238170.)
	@:hash_compatibility(null)
	@:nativeName("get_slot_custom_icon_right")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_custom_icon_right(@:meta("int32") slot_index:Int):godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2152698145.)
	@:hash_compatibility(null)
	@:nativeName("set_slot_metadata_right")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_metadata_right(@:meta("int32") slot_index:Int, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("get_slot_metadata_right")
	@:argMeta(0, ":meta"("int32"))
	public function get_slot_metadata_right(@:meta("int32") slot_index:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_slot_draw_stylebox")
	@:argMeta(0, ":meta"("int32"))
	public function is_slot_draw_stylebox(@:meta("int32") slot_index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_slot_draw_stylebox")
	@:argMeta(0, ":meta"("int32"))
	public function set_slot_draw_stylebox(@:meta("int32") slot_index:Int, enable:Bool):Void;
#if use_properties
	public extern inline function set_ignore_invalid_connection_type(v: Bool): Bool {
		set_ignore_invalid_connection_type_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_ignore_invalid_connection_type")
	@:native("set_ignore_invalid_connection_type")
	public function set_ignore_invalid_connection_type_impl(ignore:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_ignore_invalid_connection_type")
	public function set_ignore_invalid_connection_type(ignore:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_ignoring_valid_connection_type")
	@:native("is_ignoring_valid_connection_type")
	public function get_ignore_invalid_connection_type():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3232914922.)
	@:hash_compatibility(null)
	@:nativeName("set_slots_focus_mode")
	public function set_slots_focus_mode(focus_mode:godot.Control_FocusMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2132829277)
	@:hash_compatibility(null)
	@:nativeName("get_slots_focus_mode")
	public function get_slots_focus_mode():godot.Control_FocusMode;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_input_port_count")
	public function get_input_port_count():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3114997196.)
	@:hash_compatibility(null)
	@:nativeName("get_input_port_position")
	@:argMeta(0, ":meta"("int32"))
	public function get_input_port_position(@:meta("int32") port_idx:Int):godot.Vector2;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_input_port_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_input_port_type(@:meta("int32") port_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2624840992.)
	@:hash_compatibility(null)
	@:nativeName("get_input_port_color")
	@:argMeta(0, ":meta"("int32"))
	public function get_input_port_color(@:meta("int32") port_idx:Int):godot.Color;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_input_port_slot")
	@:argMeta(0, ":meta"("int32"))
	public function get_input_port_slot(@:meta("int32") port_idx:Int):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_output_port_count")
	public function get_output_port_count():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3114997196.)
	@:hash_compatibility(null)
	@:nativeName("get_output_port_position")
	@:argMeta(0, ":meta"("int32"))
	public function get_output_port_position(@:meta("int32") port_idx:Int):godot.Vector2;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_output_port_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_output_port_type(@:meta("int32") port_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2624840992.)
	@:hash_compatibility(null)
	@:nativeName("get_output_port_color")
	@:argMeta(0, ":meta"("int32"))
	public function get_output_port_color(@:meta("int32") port_idx:Int):godot.Color;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_output_port_slot")
	@:argMeta(0, ":meta"("int32"))
	public function get_output_port_slot(@:meta("int32") port_idx:Int):Int;
}