/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class Image extends godot.Resource {
	public function new();
	public static var MAX_WIDTH : Int;
	public static var MAX_HEIGHT : Int;
#if !use_properties
	@:index(null)
	@:getter("_get_data")
	@:setter("_set_data")
	public var data : godot.Dictionary;
#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_width")
	public function get_width():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_height")
	public function get_height():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3690982128.)
	@:hash_compatibility(null)
	@:nativeName("get_size")
	public function get_size():godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_mipmaps")
	public function has_mipmaps():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3847873762.)
	@:hash_compatibility(null)
	@:nativeName("get_format")
	public function get_format():godot.Image_Format;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2362200018.)
	@:hash_compatibility(null)
	@:nativeName("get_data")
	public function get_data():godot.PackedByteArray;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_data_size")
	public function get_data_size():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2120693146)
	@:hash_compatibility(null)
	@:nativeName("convert")
	public function convert(format:godot.Image_Format):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_mipmap_count")
	public function get_mipmap_count():Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_mipmap_offset")
	@:argMeta(0, ":meta"("int32"))
	public function get_mipmap_offset(@:meta("int32") mipmap:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4189212329.)
	@:hash_compatibility(null)
	@:nativeName("resize_to_po2")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	@:argMeta(1, ":default_value"("Image.Interpolation.INTERPOLATE_BILINEAR"))
	#if gdscript @:argMeta(1, ":noNullPad"("Image.Interpolation.INTERPOLATE_BILINEAR")) #end
	public function resize_to_po2(@:default_value("false") #if gdscript @:noNullPad("false") #end square:Bool = false, @:default_value("Image.Interpolation.INTERPOLATE_BILINEAR") #if gdscript @:noNullPad("Image.Interpolation.INTERPOLATE_BILINEAR") #end interpolation:godot.Image_Interpolation = godot.Image_Interpolation.INTERPOLATE_BILINEAR):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(994498151)
	@:hash_compatibility([2461393748.])
	@:nativeName("resize")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":default_value"("Image.Interpolation.INTERPOLATE_BILINEAR"))
	#if gdscript @:argMeta(2, ":noNullPad"("Image.Interpolation.INTERPOLATE_BILINEAR")) #end
	public function resize(@:meta("int32") width:Int, @:meta("int32") height:Int, @:default_value("Image.Interpolation.INTERPOLATE_BILINEAR") #if gdscript @:noNullPad("Image.Interpolation.INTERPOLATE_BILINEAR") #end interpolation:godot.Image_Interpolation = godot.Image_Interpolation.INTERPOLATE_BILINEAR):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("shrink_x2")
	public function shrink_x2():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("crop")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function crop(@:meta("int32") width:Int, @:meta("int32") height:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("flip_x")
	public function flip_x():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("flip_y")
	public function flip_y():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1633102583)
	@:hash_compatibility(null)
	@:nativeName("generate_mipmaps")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function generate_mipmaps(@:default_value("false") #if gdscript @:noNullPad("false") #end renormalize:Bool = false):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_mipmaps")
	public function clear_mipmaps():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(986942177)
	@:hash_compatibility(null)
	@:nativeName("create")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function create(@:meta("int32") width:Int, @:meta("int32") height:Int, use_mipmaps:Bool, format:godot.Image_Format):godot.Image;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(986942177)
	@:hash_compatibility(null)
	@:nativeName("create_empty")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function create_empty(@:meta("int32") width:Int, @:meta("int32") height:Int, use_mipmaps:Bool, format:godot.Image_Format):godot.Image;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(299398494)
	@:hash_compatibility(null)
	@:nativeName("create_from_data")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function create_from_data(@:meta("int32") width:Int, @:meta("int32") height:Int, use_mipmaps:Bool, format:godot.Image_Format, data:godot.PackedByteArray):godot.Image;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2740482212.)
	@:hash_compatibility(null)
	@:nativeName("set_data")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_data(@:meta("int32") width:Int, @:meta("int32") height:Int, use_mipmaps:Bool, format:godot.Image_Format, data:godot.PackedByteArray):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_empty")
	public function is_empty():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166001499)
	@:hash_compatibility(null)
	@:nativeName("load")
	public function load(path:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(736337515)
	@:hash_compatibility(null)
	@:nativeName("load_from_file")
	public static function load_from_file(path:String):godot.Image;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2113323047)
	@:hash_compatibility(null)
	@:nativeName("save_png")
	public function save_png(path:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2362200018.)
	@:hash_compatibility(null)
	@:nativeName("save_png_to_buffer")
	public function save_png_to_buffer():godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2800019068.)
	@:hash_compatibility([578836491])
	@:nativeName("save_jpg")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("0.75"))
	#if gdscript @:argMeta(1, ":noNullPad"("0.75")) #end
	public function save_jpg(path:String, @:meta("float") @:default_value("0.75") #if gdscript @:noNullPad("0.75") #end quality:Float = 0.75):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(592235273)
	@:hash_compatibility(null)
	@:nativeName("save_jpg_to_buffer")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(0, ":default_value"("0.75"))
	#if gdscript @:argMeta(0, ":noNullPad"("0.75")) #end
	public function save_jpg_to_buffer(@:meta("float") @:default_value("0.75") #if gdscript @:noNullPad("0.75") #end quality:Float = 0.75):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2018602448)
	@:hash_compatibility([3108122999.])
	@:nativeName("save_exr")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("-1.0"))
	#if gdscript @:argMeta(3, ":noNullPad"("-1.0")) #end
	public function save_exr(path:String, @:default_value("false") #if gdscript @:noNullPad("false") #end grayscale:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end color_image:Bool = false, @:meta("float") @:default_value("-1.0") #if gdscript @:noNullPad("-1.0") #end max_linear_value:Float = -1.):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477518536)
	@:hash_compatibility([3178917920.])
	@:nativeName("save_exr_to_buffer")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	@:argMeta(2, ":meta"("float"))
	@:argMeta(2, ":default_value"("-1.0"))
	#if gdscript @:argMeta(2, ":noNullPad"("-1.0")) #end
	public function save_exr_to_buffer(@:default_value("false") #if gdscript @:noNullPad("false") #end grayscale:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end color_image:Bool = false, @:meta("float") @:default_value("-1.0") #if gdscript @:noNullPad("-1.0") #end max_linear_value:Float = -1.):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2113323047)
	@:hash_compatibility(null)
	@:nativeName("save_dds")
	public function save_dds(path:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2362200018.)
	@:hash_compatibility(null)
	@:nativeName("save_dds_to_buffer")
	public function save_dds_to_buffer():godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2781156876.)
	@:hash_compatibility([3594949219.])
	@:nativeName("save_webp")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	@:argMeta(2, ":meta"("float"))
	@:argMeta(2, ":default_value"("0.75"))
	#if gdscript @:argMeta(2, ":noNullPad"("0.75")) #end
	public function save_webp(path:String, @:default_value("false") #if gdscript @:noNullPad("false") #end lossy:Bool = false, @:meta("float") @:default_value("0.75") #if gdscript @:noNullPad("0.75") #end quality:Float = 0.75):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1214628238)
	@:hash_compatibility(null)
	@:nativeName("save_webp_to_buffer")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("0.75"))
	#if gdscript @:argMeta(1, ":noNullPad"("0.75")) #end
	public function save_webp_to_buffer(@:default_value("false") #if gdscript @:noNullPad("false") #end lossy:Bool = false, @:meta("float") @:default_value("0.75") #if gdscript @:noNullPad("0.75") #end quality:Float = 0.75):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2030116505)
	@:hash_compatibility(null)
	@:nativeName("detect_alpha")
	public function detect_alpha():godot.Image_AlphaMode;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_invisible")
	public function is_invisible():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2703139984.)
	@:hash_compatibility(null)
	@:nativeName("detect_used_channels")
	@:argMeta(0, ":default_value"("Image.CompressSource.COMPRESS_SOURCE_GENERIC"))
	#if gdscript @:argMeta(0, ":noNullPad"("Image.CompressSource.COMPRESS_SOURCE_GENERIC")) #end
	public function detect_used_channels(@:default_value("Image.CompressSource.COMPRESS_SOURCE_GENERIC") #if gdscript @:noNullPad("Image.CompressSource.COMPRESS_SOURCE_GENERIC") #end source:godot.Image_CompressSource = godot.Image_CompressSource.COMPRESS_SOURCE_GENERIC):godot.Image_UsedChannels;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2975424957.)
	@:hash_compatibility([4094210332.])
	@:nativeName("compress")
	@:argMeta(1, ":default_value"("Image.CompressSource.COMPRESS_SOURCE_GENERIC"))
	#if gdscript @:argMeta(1, ":noNullPad"("Image.CompressSource.COMPRESS_SOURCE_GENERIC")) #end
	@:argMeta(2, ":default_value"("Image.ASTCFormat.ASTC_FORMAT_4x4"))
	#if gdscript @:argMeta(2, ":noNullPad"("Image.ASTCFormat.ASTC_FORMAT_4x4")) #end
	public function compress(mode:godot.Image_CompressMode, @:default_value("Image.CompressSource.COMPRESS_SOURCE_GENERIC") #if gdscript @:noNullPad("Image.CompressSource.COMPRESS_SOURCE_GENERIC") #end source:godot.Image_CompressSource = godot.Image_CompressSource.COMPRESS_SOURCE_GENERIC, @:default_value("Image.ASTCFormat.ASTC_FORMAT_4x4") #if gdscript @:noNullPad("Image.ASTCFormat.ASTC_FORMAT_4x4") #end astc_format:godot.Image_ASTCFormat = godot.Image_ASTCFormat.ASTC_FORMAT_4x4):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4212890953.)
	@:hash_compatibility([279105990])
	@:nativeName("compress_from_channels")
	@:argMeta(2, ":default_value"("Image.ASTCFormat.ASTC_FORMAT_4x4"))
	#if gdscript @:argMeta(2, ":noNullPad"("Image.ASTCFormat.ASTC_FORMAT_4x4")) #end
	public function compress_from_channels(mode:godot.Image_CompressMode, channels:godot.Image_UsedChannels, @:default_value("Image.ASTCFormat.ASTC_FORMAT_4x4") #if gdscript @:noNullPad("Image.ASTCFormat.ASTC_FORMAT_4x4") #end astc_format:godot.Image_ASTCFormat = godot.Image_ASTCFormat.ASTC_FORMAT_4x4):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("decompress")
	public function decompress():godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_compressed")
	public function is_compressed():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1901204267)
	@:hash_compatibility(null)
	@:nativeName("rotate_90")
	public function rotate_90(direction:godot.ClockDirection):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("rotate_180")
	public function rotate_180():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("fix_alpha_edges")
	public function fix_alpha_edges():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("premultiply_alpha")
	public function premultiply_alpha():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("srgb_to_linear")
	public function srgb_to_linear():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("linear_to_srgb")
	public function linear_to_srgb():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("normal_map_to_xy")
	public function normal_map_to_xy():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(564927088)
	@:hash_compatibility(null)
	@:nativeName("rgbe_to_srgb")
	public function rgbe_to_srgb():godot.Image;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3423495036.)
	@:hash_compatibility(null)
	@:nativeName("bump_map_to_normal_map")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(0, ":default_value"("1.0"))
	#if gdscript @:argMeta(0, ":noNullPad"("1.0")) #end
	public function bump_map_to_normal_map(@:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end bump_scale:Float = 1.):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3080961247.)
	@:hash_compatibility(null)
	@:nativeName("compute_image_metrics")
	public function compute_image_metrics(compared_image:godot.Image, use_luma:Bool):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2903928755.)
	@:hash_compatibility(null)
	@:nativeName("blit_rect")
	public function blit_rect(src:godot.Image, src_rect:godot.Rect2i, dst:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3383581145.)
	@:hash_compatibility(null)
	@:nativeName("blit_rect_mask")
	public function blit_rect_mask(src:godot.Image, mask:godot.Image, src_rect:godot.Rect2i, dst:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2903928755.)
	@:hash_compatibility(null)
	@:nativeName("blend_rect")
	public function blend_rect(src:godot.Image, src_rect:godot.Rect2i, dst:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3383581145.)
	@:hash_compatibility(null)
	@:nativeName("blend_rect_mask")
	public function blend_rect_mask(src:godot.Image, mask:godot.Image, src_rect:godot.Rect2i, dst:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2920490490.)
	@:hash_compatibility(null)
	@:nativeName("fill")
	public function fill(color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(514693913)
	@:hash_compatibility(null)
	@:nativeName("fill_rect")
	public function fill_rect(rect:godot.Rect2i, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(410525958)
	@:hash_compatibility(null)
	@:nativeName("get_used_rect")
	public function get_used_rect():godot.Rect2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2601441065.)
	@:hash_compatibility(null)
	@:nativeName("get_region")
	public function get_region(region:godot.Rect2i):godot.Image;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(532598488)
	@:hash_compatibility(null)
	@:nativeName("copy_from")
	public function copy_from(src:godot.Image):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1532707496)
	@:hash_compatibility(null)
	@:nativeName("get_pixelv")
	public function get_pixelv(point:godot.Vector2i):godot.Color;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2165839948.)
	@:hash_compatibility(null)
	@:nativeName("get_pixel")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_pixel(@:meta("int32") x:Int, @:meta("int32") y:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(287851464)
	@:hash_compatibility(null)
	@:nativeName("set_pixelv")
	public function set_pixelv(point:godot.Vector2i, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3733378741.)
	@:hash_compatibility(null)
	@:nativeName("set_pixel")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_pixel(@:meta("int32") x:Int, @:meta("int32") y:Int, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2385087082.)
	@:hash_compatibility(null)
	@:nativeName("adjust_bcs")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(1, ":meta"("float"))
	@:argMeta(2, ":meta"("float"))
	public function adjust_bcs(@:meta("float") brightness:Float, @:meta("float") contrast:Float, @:meta("float") saturation:Float):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_png_from_buffer")
	public function load_png_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_jpg_from_buffer")
	public function load_jpg_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_webp_from_buffer")
	public function load_webp_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_tga_from_buffer")
	public function load_tga_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_bmp_from_buffer")
	public function load_bmp_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_ktx_from_buffer")
	public function load_ktx_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_dds_from_buffer")
	public function load_dds_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("load_exr_from_buffer")
	public function load_exr_from_buffer(buffer:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(311853421)
	@:hash_compatibility([1822513750])
	@:nativeName("load_svg_from_buffer")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("1.0"))
	#if gdscript @:argMeta(1, ":noNullPad"("1.0")) #end
	public function load_svg_from_buffer(buffer:godot.PackedByteArray, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end scale:Float = 1.):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3254053600.)
	@:hash_compatibility([1461766635])
	@:nativeName("load_svg_from_string")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("1.0"))
	#if gdscript @:argMeta(1, ":noNullPad"("1.0")) #end
	public function load_svg_from_string(svg_str:String, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end scale:Float = 1.):godot.Error;
}