/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class ImporterMesh extends godot.Resource {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1030647649)
	@:hash_compatibility(null)
	@:nativeName("merge_importer_meshes")
	@:argMeta(2, ":default_value"("true"))
	#if gdscript @:argMeta(2, ":noNullPad"("true")) #end
	public static function merge_importer_meshes(importer_meshes:Array<godot.ImporterMesh>, relative_transforms:Array<godot.Transform3D>, @:default_value("true") #if gdscript @:noNullPad("true") #end deduplicate_surfaces:Bool = true):godot.ImporterMesh;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("add_blend_shape")
	public function add_blend_shape(name:String):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_blend_shape_count")
	public function get_blend_shape_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_blend_shape_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_blend_shape_name(@:meta("int32") blend_shape_idx:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(227983991)
	@:hash_compatibility(null)
	@:nativeName("set_blend_shape_mode")
	public function set_blend_shape_mode(mode:godot.Mesh_BlendShapeMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(836485024)
	@:hash_compatibility(null)
	@:nativeName("get_blend_shape_mode")
	public function get_blend_shape_mode():godot.Mesh_BlendShapeMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740448849)
	@:hash_compatibility([4122361985.])
	@:nativeName("add_surface")
	@:argMeta(2, ":default_value"("Array[Array]([])"))
	#if gdscript @:argMeta(2, ":noNullPad"("[]")) #end
	@:argMeta(3, ":default_value"("{}"))
	#if gdscript @:argMeta(3, ":noNullPad"("{}")) #end
	@:argMeta(4, ":default_value"("null"))
	#if gdscript @:argMeta(4, ":noNullPad"("null")) #end
	@:argMeta(5, ":default_value"("\"\""))
	#if gdscript @:argMeta(5, ":noNullPad"("\"\"")) #end
	@:argMeta(6, ":meta"("uint64"))
	@:argMeta(6, ":default_value"("0"))
	#if gdscript @:argMeta(6, ":noNullPad"("0")) #end
	public function add_surface(primitive:godot.Mesh_PrimitiveType, arrays:GodotArray, @:default_value("Array[Array]([])") #if gdscript @:noNullPad("[]") #end ?blend_shapes:Array<GodotArray>, @:default_value("{}") #if gdscript @:noNullPad("{}") #end ?lods:godot.Dictionary, @:default_value("null") #if gdscript @:noNullPad("null") #end material:godot.Material = null, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end name:String = "\"\"", @:meta("uint64") @:default_value("0") #if gdscript @:noNullPad("0") #end flags:Int = 0):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_surface_count")
	public function get_surface_count():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3552571330.)
	@:hash_compatibility(null)
	@:nativeName("get_surface_primitive_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_surface_primitive_type(@:meta("int32") surface_idx:Int):godot.Mesh_PrimitiveType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_surface_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_surface_name(@:meta("int32") surface_idx:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("get_surface_arrays")
	@:argMeta(0, ":meta"("int32"))
	public function get_surface_arrays(@:meta("int32") surface_idx:Int):GodotArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2345056839.)
	@:hash_compatibility(null)
	@:nativeName("get_surface_blend_shape_arrays")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_surface_blend_shape_arrays(@:meta("int32") surface_idx:Int, @:meta("int32") blend_shape_idx:Int):GodotArray;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_surface_lod_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_surface_lod_count(@:meta("int32") surface_idx:Int):Int;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_surface_lod_size")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_surface_lod_size(@:meta("int32") surface_idx:Int, @:meta("int32") lod_idx:Int):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265128013)
	@:hash_compatibility(null)
	@:nativeName("get_surface_lod_indices")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_surface_lod_indices(@:meta("int32") surface_idx:Int, @:meta("int32") lod_idx:Int):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2897466400.)
	@:hash_compatibility(null)
	@:nativeName("get_surface_material")
	@:argMeta(0, ":meta"("int32"))
	public function get_surface_material(@:meta("int32") surface_idx:Int):godot.Material;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_surface_format")
	@:argMeta(0, ":meta"("int32"))
	public function get_surface_format(@:meta("int32") surface_idx:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_surface_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_surface_name(@:meta("int32") surface_idx:Int, name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3671737478.)
	@:hash_compatibility(null)
	@:nativeName("set_surface_material")
	@:argMeta(0, ":meta"("int32"))
	public function set_surface_material(@:meta("int32") surface_idx:Int, material:godot.Material):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2491878677.)
	@:hash_compatibility(null)
	@:nativeName("generate_lods")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(1, ":meta"("float"))
	public function generate_lods(@:meta("float") normal_merge_angle:Float, @:meta("float") normal_split_angle:Float, bone_transform_array:GodotArray):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1457573577)
	@:hash_compatibility(null)
	@:nativeName("get_mesh")
	@:argMeta(0, ":default_value"("null"))
	#if gdscript @:argMeta(0, ":noNullPad"("null")) #end
	public function get_mesh(@:default_value("null") #if gdscript @:noNullPad("null") #end base_mesh:godot.ArrayMesh = null):godot.ArrayMesh;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(283226343)
	@:hash_compatibility(null)
	@:nativeName("from_mesh")
	public static function from_mesh(mesh:godot.Mesh):godot.ImporterMesh;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1130785943)
	@:hash_compatibility(null)
	@:nativeName("set_lightmap_size_hint")
	public function set_lightmap_size_hint(size:godot.Vector2i):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3690982128.)
	@:hash_compatibility(null)
	@:nativeName("get_lightmap_size_hint")
	public function get_lightmap_size_hint():godot.Vector2i;
}