/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class InputMap extends godot.Object {
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("has_action")
	public static function has_action(action:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("get_actions")
	public static function get_actions():Array<godot.StringName>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1195233573)
	@:hash_compatibility([4100757082., 573731101])
	@:nativeName("add_action")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("0.2"))
	#if gdscript @:argMeta(1, ":noNullPad"("0.2")) #end
	public static function add_action(action:godot.StringName, @:meta("float") @:default_value("0.2") #if gdscript @:noNullPad("0.2") #end deadzone:Float = 0.2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("erase_action")
	public static function erase_action(action:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(957595536)
	@:hash_compatibility(null)
	@:nativeName("get_action_description")
	public static function get_action_description(action:godot.StringName):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4135858297.)
	@:hash_compatibility(null)
	@:nativeName("action_set_deadzone")
	@:argMeta(1, ":meta"("float"))
	public static function action_set_deadzone(action:godot.StringName, @:meta("float") deadzone:Float):Void;
	@:return_value_meta("float")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1391627649)
	@:hash_compatibility(null)
	@:nativeName("action_get_deadzone")
	public static function action_get_deadzone(action:godot.StringName):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(518302593)
	@:hash_compatibility(null)
	@:nativeName("action_add_event")
	@:argMeta(1, ":meta"("required"))
	public static function action_add_event(action:godot.StringName, @:meta("required") event:godot.InputEvent):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1185871985)
	@:hash_compatibility(null)
	@:nativeName("action_has_event")
	@:argMeta(1, ":meta"("required"))
	public static function action_has_event(action:godot.StringName, @:meta("required") event:godot.InputEvent):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(518302593)
	@:hash_compatibility(null)
	@:nativeName("action_erase_event")
	@:argMeta(1, ":meta"("required"))
	public static function action_erase_event(action:godot.StringName, @:meta("required") event:godot.InputEvent):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("action_erase_events")
	public static function action_erase_events(action:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(689397652)
	@:hash_compatibility(null)
	@:nativeName("action_get_events")
	public static function action_get_events(action:godot.StringName):Array<godot.InputEvent>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3193353650.)
	@:hash_compatibility(null)
	@:nativeName("event_is_action")
	@:argMeta(0, ":meta"("required"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function event_is_action(@:meta("required") event:godot.InputEvent, action:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("load_from_project_settings")
	public static function load_from_project_settings():Void;
}