/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("core") @:is_resource(false) @:is_node(false) extern class Input extends godot.Object {
#if !use_properties
	@:index(null)
	@:getter("get_mouse_mode")
	@:setter("set_mouse_mode")
	public static var mouse_mode : Int;
#end
#if use_properties
	@:index(null)
	@:getter("is_using_accumulated_input")
	@:setter("set_use_accumulated_input")
	public static var use_accumulated_input(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_using_accumulated_input")
	@:setter("set_use_accumulated_input")
	public static var use_accumulated_input : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("is_emulating_mouse_from_touch")
	@:setter("set_emulate_mouse_from_touch")
	public static var emulate_mouse_from_touch(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_emulating_mouse_from_touch")
	@:setter("set_emulate_mouse_from_touch")
	public static var emulate_mouse_from_touch : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("is_emulating_touch_from_mouse")
	@:setter("set_emulate_touch_from_mouse")
	public static var emulate_touch_from_mouse(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_emulating_touch_from_mouse")
	@:setter("set_emulate_touch_from_mouse")
	public static var emulate_touch_from_mouse : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("is_ignoring_joypad_on_unfocused_application")
	@:setter("set_ignore_joypad_on_unfocused_application")
	public static var ignore_joypad_on_unfocused_application(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_ignoring_joypad_on_unfocused_application")
	@:setter("set_ignore_joypad_on_unfocused_application")
	public static var ignore_joypad_on_unfocused_application : Bool;
#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_anything_pressed")
	public static function is_anything_pressed():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1938909964)
	@:hash_compatibility(null)
	@:nativeName("is_key_pressed")
	public static function is_key_pressed(keycode:godot.Key):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1938909964)
	@:hash_compatibility(null)
	@:nativeName("is_physical_key_pressed")
	public static function is_physical_key_pressed(keycode:godot.Key):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1938909964)
	@:hash_compatibility(null)
	@:nativeName("is_key_label_pressed")
	public static function is_key_label_pressed(keycode:godot.Key):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1821097125)
	@:hash_compatibility(null)
	@:nativeName("is_mouse_button_pressed")
	public static function is_mouse_button_pressed(button:godot.MouseButton):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(787208542)
	@:hash_compatibility(null)
	@:nativeName("is_joy_button_pressed")
	@:argMeta(0, ":meta"("int32"))
	public static function is_joy_button_pressed(@:meta("int32") device:Int, button:godot.JoyButton):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1558498928)
	@:hash_compatibility(null)
	@:nativeName("is_action_pressed")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function is_action_pressed(action:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1558498928)
	@:hash_compatibility(null)
	@:nativeName("is_action_just_pressed")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function is_action_just_pressed(action:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1558498928)
	@:hash_compatibility(null)
	@:nativeName("is_action_just_released")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function is_action_just_released(action:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(551972873)
	@:hash_compatibility(null)
	@:nativeName("is_action_just_pressed_by_event")
	@:argMeta(1, ":meta"("required"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function is_action_just_pressed_by_event(action:godot.StringName, @:meta("required") event:godot.InputEvent, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(551972873)
	@:hash_compatibility(null)
	@:nativeName("is_action_just_released_by_event")
	@:argMeta(1, ":meta"("required"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function is_action_just_released_by_event(action:godot.StringName, @:meta("required") event:godot.InputEvent, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Bool;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(801543509)
	@:hash_compatibility(null)
	@:nativeName("get_action_strength")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function get_action_strength(action:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(801543509)
	@:hash_compatibility(null)
	@:nativeName("get_action_raw_strength")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function get_action_raw_strength(action:godot.StringName, @:default_value("false") #if gdscript @:noNullPad("false") #end exact_match:Bool = false):Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1958752504)
	@:hash_compatibility(null)
	@:nativeName("get_axis")
	public static function get_axis(negative_action:godot.StringName, positive_action:godot.StringName):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2479607902.)
	@:hash_compatibility([1517139831])
	@:nativeName("get_vector")
	@:argMeta(4, ":meta"("float"))
	@:argMeta(4, ":default_value"("-1.0"))
	#if gdscript @:argMeta(4, ":noNullPad"("-1.0")) #end
	public static function get_vector(negative_x:godot.StringName, positive_x:godot.StringName, negative_y:godot.StringName, positive_y:godot.StringName, @:meta("float") @:default_value("-1.0") #if gdscript @:noNullPad("-1.0") #end deadzone:Float = -1.):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1168363258)
	@:hash_compatibility(null)
	@:nativeName("add_joy_mapping")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function add_joy_mapping(mapping:String, @:default_value("false") #if gdscript @:noNullPad("false") #end update_existing:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("remove_joy_mapping")
	public static function remove_joy_mapping(guid:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility(null)
	@:nativeName("is_joy_known")
	@:argMeta(0, ":meta"("int32"))
	public static function is_joy_known(@:meta("int32") device:Int):Bool;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4063175957.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_axis")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_axis(@:meta("int32") device:Int, axis:godot.JoyAxis):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(990163283)
	@:hash_compatibility(null)
	@:nativeName("get_joy_name")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_name(@:meta("int32") device:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_joy_guid")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_guid(@:meta("int32") device:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3485342025.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_info")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_info(@:meta("int32") device:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2522259332.)
	@:hash_compatibility(null)
	@:nativeName("should_ignore_device")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public static function should_ignore_device(@:meta("int32") vendor_id:Int, @:meta("int32") product_id:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("get_connected_joypads")
	public static function get_connected_joypads():Array<Int>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3114997196.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_vibration_strength")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_vibration_strength(@:meta("int32") device:Int):godot.Vector2;
	@:return_value_meta("float")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4025615559.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_vibration_duration")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_vibration_duration(@:meta("int32") device:Int):Float;
	@:return_value_meta("float")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4025615559.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_vibration_remaining_duration")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_vibration_remaining_duration(@:meta("int32") device:Int):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility(null)
	@:nativeName("is_joy_vibrating")
	@:argMeta(0, ":meta"("int32"))
	public static function is_joy_vibrating(@:meta("int32") device:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("has_joy_vibration")
	@:argMeta(0, ":meta"("int32"))
	public static function has_joy_vibration(@:meta("int32") device:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2576575033.)
	@:hash_compatibility([1890603622])
	@:nativeName("start_joy_vibration")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	@:argMeta(2, ":meta"("float"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public static function start_joy_vibration(@:meta("int32") device:Int, @:meta("float") weak_magnitude:Float, @:meta("float") strong_magnitude:Float, @:meta("float") @:default_value("0") #if gdscript @:noNullPad("0") #end duration:Float = 0.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("stop_joy_vibration")
	@:argMeta(0, ":meta"("int32"))
	public static function stop_joy_vibration(@:meta("int32") device:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(544894297)
	@:hash_compatibility([955504365])
	@:nativeName("vibrate_handheld")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("500"))
	#if gdscript @:argMeta(0, ":noNullPad"("500")) #end
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("-1.0"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1.0")) #end
	public static function vibrate_handheld(@:meta("int32") @:default_value("500") #if gdscript @:noNullPad("500") #end duration_ms:Int = 500, @:meta("float") @:default_value("-1.0") #if gdscript @:noNullPad("-1.0") #end amplitude:Float = -1.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_ignore_joypad_on_unfocused_application")
	public static function set_ignore_joypad_on_unfocused_application(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_ignoring_joypad_on_unfocused_application")
	public static function get_ignore_joypad_on_unfocused_application():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3360562783.)
	@:hash_compatibility(null)
	@:nativeName("get_gravity")
	public static function get_gravity():godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3360562783.)
	@:hash_compatibility(null)
	@:nativeName("get_accelerometer")
	public static function get_accelerometer():godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3360562783.)
	@:hash_compatibility(null)
	@:nativeName("get_magnetometer")
	public static function get_magnetometer():godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3360562783.)
	@:hash_compatibility(null)
	@:nativeName("get_gyroscope")
	public static function get_gyroscope():godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_joy_accelerometer")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_accelerometer(@:meta("int32") device:Int):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_joy_gravity")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_gravity(@:meta("int32") device:Int):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_joy_gyroscope")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_gyroscope(@:meta("int32") device:Int):godot.Vector3;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_motion_sensors_rate")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_motion_sensors_rate(@:meta("int32") device:Int):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_joy_motion_sensors_enabled")
	@:argMeta(0, ":meta"("int32"))
	public static function is_joy_motion_sensors_enabled(@:meta("int32") device:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_joy_motion_sensors_enabled")
	@:argMeta(0, ":meta"("int32"))
	public static function set_joy_motion_sensors_enabled(@:meta("int32") device:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("has_joy_motion_sensors")
	@:argMeta(0, ":meta"("int32"))
	public static function has_joy_motion_sensors(@:meta("int32") device:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("start_joy_motion_sensors_calibration")
	@:argMeta(0, ":meta"("int32"))
	public static function start_joy_motion_sensors_calibration(@:meta("int32") device:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("stop_joy_motion_sensors_calibration")
	@:argMeta(0, ":meta"("int32"))
	public static function stop_joy_motion_sensors_calibration(@:meta("int32") device:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_joy_motion_sensors_calibration")
	@:argMeta(0, ":meta"("int32"))
	public static function clear_joy_motion_sensors_calibration(@:meta("int32") device:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3485342025.)
	@:hash_compatibility(null)
	@:nativeName("get_joy_motion_sensors_calibration")
	@:argMeta(0, ":meta"("int32"))
	public static function get_joy_motion_sensors_calibration(@:meta("int32") device:Int):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(64545446)
	@:hash_compatibility(null)
	@:nativeName("set_joy_motion_sensors_calibration")
	@:argMeta(0, ":meta"("int32"))
	public static function set_joy_motion_sensors_calibration(@:meta("int32") device:Int, calibration_info:godot.Dictionary):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_joy_motion_sensors_calibrated")
	@:argMeta(0, ":meta"("int32"))
	public static function is_joy_motion_sensors_calibrated(@:meta("int32") device:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_joy_motion_sensors_calibrating")
	@:argMeta(0, ":meta"("int32"))
	public static function is_joy_motion_sensors_calibrating(@:meta("int32") device:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_gravity")
	public static function set_gravity(value:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_accelerometer")
	public static function set_accelerometer(value:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_magnetometer")
	public static function set_magnetometer(value:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_gyroscope")
	public static function set_gyroscope(value:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_joy_light")
	@:argMeta(0, ":meta"("int32"))
	public static function set_joy_light(@:meta("int32") device:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("has_joy_light")
	@:argMeta(0, ":meta"("int32"))
	public static function has_joy_light(@:meta("int32") device:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1497962370)
	@:hash_compatibility(null)
	@:nativeName("get_last_mouse_velocity")
	public static function get_last_mouse_velocity():godot.Vector2;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1497962370)
	@:hash_compatibility(null)
	@:nativeName("get_last_mouse_screen_velocity")
	public static function get_last_mouse_screen_velocity():godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2512161324.)
	@:hash_compatibility(null)
	@:nativeName("get_mouse_button_mask")
	public static function get_mouse_button_mask():godot.MouseButtonMask;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2228490894.)
	@:hash_compatibility(null)
	@:nativeName("set_mouse_mode")
	public static function set_mouse_mode(mode:godot.Input_MouseMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(965286182)
	@:hash_compatibility(null)
	@:nativeName("get_mouse_mode")
	public static function get_mouse_mode():godot.Input_MouseMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("warp_mouse")
	public static function warp_mouse(position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1713091165)
	@:hash_compatibility([573731101])
	@:nativeName("action_press")
	@:argMeta(1, ":meta"("float"))
	@:argMeta(1, ":default_value"("1.0"))
	#if gdscript @:argMeta(1, ":noNullPad"("1.0")) #end
	public static function action_press(action:godot.StringName, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end strength:Float = 1.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("action_release")
	public static function action_release(action:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2124816902)
	@:hash_compatibility(null)
	@:nativeName("set_default_cursor_shape")
	@:argMeta(0, ":default_value"("Input.CursorShape.CURSOR_ARROW"))
	#if gdscript @:argMeta(0, ":noNullPad"("Input.CursorShape.CURSOR_ARROW")) #end
	public static function set_default_cursor_shape(@:default_value("Input.CursorShape.CURSOR_ARROW") #if gdscript @:noNullPad("Input.CursorShape.CURSOR_ARROW") #end shape:godot.Input_CursorShape = godot.Input_CursorShape.CURSOR_ARROW):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3455658929.)
	@:hash_compatibility(null)
	@:nativeName("get_current_cursor_shape")
	public static function get_current_cursor_shape():godot.Input_CursorShape;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(703945977)
	@:hash_compatibility([3489634142.])
	@:nativeName("set_custom_mouse_cursor")
	@:argMeta(1, ":default_value"("Input.CursorShape.CURSOR_ARROW"))
	#if gdscript @:argMeta(1, ":noNullPad"("Input.CursorShape.CURSOR_ARROW")) #end
	@:argMeta(2, ":default_value"("Vector2(0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Vector2(0, 0)")) #end
	public static function set_custom_mouse_cursor(image:godot.Resource, @:default_value("Input.CursorShape.CURSOR_ARROW") #if gdscript @:noNullPad("Input.CursorShape.CURSOR_ARROW") #end shape:godot.Input_CursorShape = godot.Input_CursorShape.CURSOR_ARROW, @:default_value("Vector2(0, 0)") #if gdscript @:noNullPad("Vector2(0, 0)") #end ?hotspot:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3754044979.)
	@:hash_compatibility(null)
	@:nativeName("parse_input_event")
	@:argMeta(0, ":meta"("required"))
	public static function parse_input_event(@:meta("required") event:godot.InputEvent):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_use_accumulated_input")
	public static function set_use_accumulated_input(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_using_accumulated_input")
	public static function get_use_accumulated_input():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("flush_buffered_events")
	public static function flush_buffered_events():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_emulate_mouse_from_touch")
	public static function set_emulate_mouse_from_touch(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_emulating_mouse_from_touch")
	public static function get_emulate_mouse_from_touch():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_emulate_touch_from_mouse")
	public static function set_emulate_touch_from_mouse(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_emulating_touch_from_mouse")
	public static function get_emulate_touch_from_mouse():Bool;
}