/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class MeshDataTool extends godot.RefCounted {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2727020678.)
	@:hash_compatibility(null)
	@:nativeName("create_from_surface")
	@:argMeta(1, ":meta"("int32"))
	public function create_from_surface(mesh:godot.ArrayMesh, @:meta("int32") surface:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2021686445)
	@:hash_compatibility([3521099812.])
	@:nativeName("commit_to_surface")
	@:argMeta(1, ":meta"("uint64"))
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	public function commit_to_surface(mesh:godot.ArrayMesh, @:meta("uint64") @:default_value("0") #if gdscript @:noNullPad("0") #end compression_flags:Int = 0):godot.Error;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_format")
	public function get_format():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_count")
	public function get_vertex_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_edge_count")
	public function get_edge_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_face_count")
	public function get_face_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530502735)
	@:hash_compatibility(null)
	@:nativeName("set_vertex")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex(@:meta("int32") idx:Int, vertex:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_vertex")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex(@:meta("int32") idx:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530502735)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_normal")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_normal(@:meta("int32") idx:Int, normal:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_normal")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_normal(@:meta("int32") idx:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1104099133)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_tangent")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_tangent(@:meta("int32") idx:Int, tangent:godot.Plane):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1372055458)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_tangent")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_tangent(@:meta("int32") idx:Int):godot.Plane;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(163021252)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_uv")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_uv(@:meta("int32") idx:Int, uv:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_uv")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_uv(@:meta("int32") idx:Int):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(163021252)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_uv2")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_uv2(@:meta("int32") idx:Int, uv2:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_uv2")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_uv2(@:meta("int32") idx:Int):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_color")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_color(@:meta("int32") idx:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3457211756.)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_color")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_color(@:meta("int32") idx:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3500328261.)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_bones")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_bones(@:meta("int32") idx:Int, bones:godot.PackedInt32Array):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1706082319)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_bones")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_bones(@:meta("int32") idx:Int):godot.PackedInt32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1345852415)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_weights")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_weights(@:meta("int32") idx:Int, weights:godot.PackedFloat32Array):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1542882410)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_weights")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_weights(@:meta("int32") idx:Int):godot.PackedFloat32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2152698145.)
	@:hash_compatibility(null)
	@:nativeName("set_vertex_meta")
	@:argMeta(0, ":meta"("int32"))
	public function set_vertex_meta(@:meta("int32") idx:Int, meta:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_meta")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_meta(@:meta("int32") idx:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1706082319)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_edges")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_edges(@:meta("int32") idx:Int):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1706082319)
	@:hash_compatibility(null)
	@:nativeName("get_vertex_faces")
	@:argMeta(0, ":meta"("int32"))
	public function get_vertex_faces(@:meta("int32") idx:Int):godot.PackedInt32Array;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_edge_vertex")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_edge_vertex(@:meta("int32") idx:Int, @:meta("int32") vertex:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1706082319)
	@:hash_compatibility(null)
	@:nativeName("get_edge_faces")
	@:argMeta(0, ":meta"("int32"))
	public function get_edge_faces(@:meta("int32") idx:Int):godot.PackedInt32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2152698145.)
	@:hash_compatibility(null)
	@:nativeName("set_edge_meta")
	@:argMeta(0, ":meta"("int32"))
	public function set_edge_meta(@:meta("int32") idx:Int, meta:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("get_edge_meta")
	@:argMeta(0, ":meta"("int32"))
	public function get_edge_meta(@:meta("int32") idx:Int):Dynamic;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_face_vertex")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_face_vertex(@:meta("int32") idx:Int, @:meta("int32") vertex:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_face_edge")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_face_edge(@:meta("int32") idx:Int, @:meta("int32") edge:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2152698145.)
	@:hash_compatibility(null)
	@:nativeName("set_face_meta")
	@:argMeta(0, ":meta"("int32"))
	public function set_face_meta(@:meta("int32") idx:Int, meta:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("get_face_meta")
	@:argMeta(0, ":meta"("int32"))
	public function get_face_meta(@:meta("int32") idx:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_face_normal")
	@:argMeta(0, ":meta"("int32"))
	public function get_face_normal(@:meta("int32") idx:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2757459619.)
	@:hash_compatibility(null)
	@:nativeName("set_material")
	public function set_material(material:godot.Material):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(5934680)
	@:hash_compatibility(null)
	@:nativeName("get_material")
	public function get_material():godot.Material;
}