/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class MeshLibrary extends godot.Resource {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("create_item")
	@:argMeta(0, ":meta"("int32"))
	public function create_item(@:meta("int32") id:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_item_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_name(@:meta("int32") id:Int, name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(969122797)
	@:hash_compatibility(null)
	@:nativeName("set_item_mesh")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_mesh(@:meta("int32") id:Int, mesh:godot.Mesh):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3616898986.)
	@:hash_compatibility(null)
	@:nativeName("set_item_mesh_transform")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_mesh_transform(@:meta("int32") id:Int, mesh_transform:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3923400443.)
	@:hash_compatibility(null)
	@:nativeName("set_item_mesh_cast_shadow")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_mesh_cast_shadow(@:meta("int32") id:Int, shadow_casting_setting:godot.RenderingServer_ShadowCastingSetting):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3483353960.)
	@:hash_compatibility(null)
	@:nativeName("set_item_navigation_mesh")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_navigation_mesh(@:meta("int32") id:Int, navigation_mesh:godot.NavigationMesh):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3616898986.)
	@:hash_compatibility(null)
	@:nativeName("set_item_navigation_mesh_transform")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_navigation_mesh_transform(@:meta("int32") id:Int, navigation_mesh:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_item_navigation_layers")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("uint32"))
	public function set_item_navigation_layers(@:meta("int32") id:Int, @:meta("uint32") navigation_layers:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(537221740)
	@:hash_compatibility(null)
	@:nativeName("set_item_shapes")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_shapes(@:meta("int32") id:Int, shapes:GodotArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(666127730)
	@:hash_compatibility(null)
	@:nativeName("set_item_preview")
	@:argMeta(0, ":meta"("int32"))
	public function set_item_preview(@:meta("int32") id:Int, texture:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_item_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_name(@:meta("int32") id:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1576363275)
	@:hash_compatibility(null)
	@:nativeName("get_item_mesh")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_mesh(@:meta("int32") id:Int):godot.Mesh;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1965739696)
	@:hash_compatibility(null)
	@:nativeName("get_item_mesh_transform")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_mesh_transform(@:meta("int32") id:Int):godot.Transform3D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1841766007)
	@:hash_compatibility(null)
	@:nativeName("get_item_mesh_cast_shadow")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_mesh_cast_shadow(@:meta("int32") id:Int):godot.RenderingServer_ShadowCastingSetting;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2729647406.)
	@:hash_compatibility(null)
	@:nativeName("get_item_navigation_mesh")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_navigation_mesh(@:meta("int32") id:Int):godot.NavigationMesh;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1965739696)
	@:hash_compatibility(null)
	@:nativeName("get_item_navigation_mesh_transform")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_navigation_mesh_transform(@:meta("int32") id:Int):godot.Transform3D;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_item_navigation_layers")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_navigation_layers(@:meta("int32") id:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("get_item_shapes")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_shapes(@:meta("int32") id:Int):GodotArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3536238170.)
	@:hash_compatibility(null)
	@:nativeName("get_item_preview")
	@:argMeta(0, ":meta"("int32"))
	public function get_item_preview(@:meta("int32") id:Int):godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_item")
	@:argMeta(0, ":meta"("int32"))
	public function remove_item(@:meta("int32") id:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1321353865)
	@:hash_compatibility(null)
	@:nativeName("find_item_by_name")
	public function find_item_by_name(name:String):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1930428628)
	@:hash_compatibility(null)
	@:nativeName("get_item_list")
	public function get_item_list():godot.PackedInt32Array;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_item_count")
	public function get_item_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_last_unused_item_id")
	public function get_last_unused_item_id():Int;
}