/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class Mesh extends godot.Resource {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_lightmap_size_hint")
	@:setter("set_lightmap_size_hint")
	@:reassignOnSubfieldEdit(set_lightmap_size_hint_impl, x, y)
	public var lightmap_size_hint(get, set) : godot.Vector2i;
#else

	@:index(null)
	@:getter("get_lightmap_size_hint")
	@:setter("set_lightmap_size_hint")
	public var lightmap_size_hint : godot.Vector2i;
#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_surface_count")
	public function _get_surface_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_array_len")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_array_len(@:meta("int32") index:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_array_index_len")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_array_index_len(@:meta("int32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_arrays")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_arrays(@:meta("int32") index:Int):GodotArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_blend_shape_arrays")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_blend_shape_arrays(@:meta("int32") index:Int):Array<GodotArray>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3485342025.)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_lods")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_lods(@:meta("int32") index:Int):godot.Dictionary;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_format")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_format(@:meta("int32") index:Int):Int;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_primitive_type")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_primitive_type(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3671737478.)
	@:hash_compatibility(null)
	@:nativeName("_surface_set_material")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_set_material(@:meta("int32") index:Int, material:godot.Material):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2897466400.)
	@:hash_compatibility(null)
	@:nativeName("_surface_get_material")
	@:argMeta(0, ":meta"("int32"))
	public function _surface_get_material(@:meta("int32") index:Int):godot.Material;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_blend_shape_count")
	public function _get_blend_shape_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(659327637)
	@:hash_compatibility(null)
	@:nativeName("_get_blend_shape_name")
	@:argMeta(0, ":meta"("int32"))
	public function _get_blend_shape_name(@:meta("int32") index:Int):godot.StringName;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3780747571.)
	@:hash_compatibility(null)
	@:nativeName("_set_blend_shape_name")
	@:argMeta(0, ":meta"("int32"))
	public function _set_blend_shape_name(@:meta("int32") index:Int, name:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1068685055)
	@:hash_compatibility(null)
	@:nativeName("_get_aabb")
	public function _get_aabb():godot.AABB;
#if use_properties
	public extern inline function set_lightmap_size_hint(v: godot.Vector2i): godot.Vector2i {
		set_lightmap_size_hint_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1130785943)
	@:hash_compatibility(null)
	@:nativeName("set_lightmap_size_hint")
	@:native("set_lightmap_size_hint")
	public function set_lightmap_size_hint_impl(size:godot.Vector2i):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1130785943)
	@:hash_compatibility(null)
	@:nativeName("set_lightmap_size_hint")
	public function set_lightmap_size_hint(size:godot.Vector2i):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3690982128.)
	@:hash_compatibility(null)
	@:nativeName("get_lightmap_size_hint")
	public function get_lightmap_size_hint():godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1068685055)
	@:hash_compatibility(null)
	@:nativeName("get_aabb")
	public function get_aabb():godot.AABB;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(497664490)
	@:hash_compatibility(null)
	@:nativeName("get_faces")
	public function get_faces():godot.PackedVector3Array;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_surface_count")
	public function get_surface_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("surface_get_arrays")
	@:argMeta(0, ":meta"("int32"))
	public function surface_get_arrays(@:meta("int32") surf_idx:Int):GodotArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("surface_get_blend_shape_arrays")
	@:argMeta(0, ":meta"("int32"))
	public function surface_get_blend_shape_arrays(@:meta("int32") surf_idx:Int):Array<GodotArray>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3671737478.)
	@:hash_compatibility(null)
	@:nativeName("surface_set_material")
	@:argMeta(0, ":meta"("int32"))
	public function surface_set_material(@:meta("int32") surf_idx:Int, material:godot.Material):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2897466400.)
	@:hash_compatibility(null)
	@:nativeName("surface_get_material")
	@:argMeta(0, ":meta"("int32"))
	public function surface_get_material(@:meta("int32") surf_idx:Int):godot.Material;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(121922552)
	@:hash_compatibility(null)
	@:nativeName("create_placeholder")
	public function create_placeholder():godot.Resource;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4160111210.)
	@:hash_compatibility(null)
	@:nativeName("create_trimesh_shape")
	public function create_trimesh_shape():godot.ConcavePolygonShape3D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2529984628.)
	@:hash_compatibility(null)
	@:nativeName("create_convex_shape")
	@:argMeta(0, ":default_value"("true"))
	#if gdscript @:argMeta(0, ":noNullPad"("true")) #end
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function create_convex_shape(@:default_value("true") #if gdscript @:noNullPad("true") #end clean:Bool = true, @:default_value("false") #if gdscript @:noNullPad("false") #end simplify:Bool = false):godot.ConvexPolygonShape3D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1208642001)
	@:hash_compatibility(null)
	@:nativeName("create_outline")
	@:argMeta(0, ":meta"("float"))
	public function create_outline(@:meta("float") margin:Float):godot.Mesh;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3476533166.)
	@:hash_compatibility(null)
	@:nativeName("generate_triangle_mesh")
	public function generate_triangle_mesh():godot.TriangleMesh;
}