/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class NativeMenu extends godot.Object {
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1708975490)
	@:hash_compatibility(null)
	@:nativeName("has_feature")
	public static function has_feature(feature:godot.NativeMenu_Feature):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(718213027)
	@:hash_compatibility(null)
	@:nativeName("has_system_menu")
	public static function has_system_menu(menu_id:godot.NativeMenu_SystemMenus):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(469707506)
	@:hash_compatibility(null)
	@:nativeName("get_system_menu")
	public static function get_system_menu(menu_id:godot.NativeMenu_SystemMenus):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1281499290)
	@:hash_compatibility(null)
	@:nativeName("get_system_menu_name")
	public static function get_system_menu_name(menu_id:godot.NativeMenu_SystemMenus):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1281499290)
	@:hash_compatibility(null)
	@:nativeName("get_system_menu_text")
	public static function get_system_menu_text(menu_id:godot.NativeMenu_SystemMenus):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3925225603.)
	@:hash_compatibility(null)
	@:nativeName("set_system_menu_text")
	public static function set_system_menu_text(menu_id:godot.NativeMenu_SystemMenus, name:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("create_menu")
	public static function create_menu():godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("has_menu")
	public static function has_menu(rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_menu")
	public static function free_menu(rid:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2440833711.)
	@:hash_compatibility(null)
	@:nativeName("get_size")
	public static function get_size(rid:godot.RID):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2450610377.)
	@:hash_compatibility(null)
	@:nativeName("popup")
	public static function popup(rid:godot.RID, position:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("set_interface_direction")
	public static function set_interface_direction(rid:godot.RID, is_rtl:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("set_popup_open_callback")
	public static function set_popup_open_callback(rid:godot.RID, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3170603026.)
	@:hash_compatibility(null)
	@:nativeName("get_popup_open_callback")
	public static function get_popup_open_callback(rid:godot.RID):godot.Callable;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("set_popup_close_callback")
	public static function set_popup_close_callback(rid:godot.RID, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3170603026.)
	@:hash_compatibility(null)
	@:nativeName("get_popup_close_callback")
	public static function get_popup_close_callback(rid:godot.RID):godot.Callable;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("set_minimum_width")
	@:argMeta(1, ":meta"("float"))
	public static function set_minimum_width(rid:godot.RID, @:meta("float") width:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("get_minimum_width")
	public static function get_minimum_width(rid:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("is_opened")
	public static function is_opened(rid:godot.RID):Bool;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1002030223)
	@:hash_compatibility(null)
	@:nativeName("add_submenu_item")
	@:argMeta(3, ":default_value"("null"))
	#if gdscript @:argMeta(3, ":noNullPad"("null")) #end
	@:argMeta(4, ":meta"("int32"))
	@:argMeta(4, ":default_value"("-1"))
	#if gdscript @:argMeta(4, ":noNullPad"("-1")) #end
	public static function add_submenu_item(rid:godot.RID, label:String, submenu_rid:godot.RID, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(980552939)
	@:hash_compatibility([2553375659.])
	@:nativeName("add_item")
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	@:argMeta(4, ":default_value"("null"))
	#if gdscript @:argMeta(4, ":noNullPad"("null")) #end
	@:argMeta(5, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(5, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(6, ":meta"("int32"))
	@:argMeta(6, ":default_value"("-1"))
	#if gdscript @:argMeta(6, ":noNullPad"("-1")) #end
	public static function add_item(rid:godot.RID, label:String, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(980552939)
	@:hash_compatibility([2553375659.])
	@:nativeName("add_check_item")
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	@:argMeta(4, ":default_value"("null"))
	#if gdscript @:argMeta(4, ":noNullPad"("null")) #end
	@:argMeta(5, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(5, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(6, ":meta"("int32"))
	@:argMeta(6, ":default_value"("-1"))
	#if gdscript @:argMeta(6, ":noNullPad"("-1")) #end
	public static function add_check_item(rid:godot.RID, label:String, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1372188274)
	@:hash_compatibility([2987595282.])
	@:nativeName("add_icon_item")
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	@:argMeta(4, ":default_value"("Callable()"))
	#if gdscript @:argMeta(4, ":noNullPad"("Callable()")) #end
	@:argMeta(5, ":default_value"("null"))
	#if gdscript @:argMeta(5, ":noNullPad"("null")) #end
	@:argMeta(6, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(6, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(7, ":meta"("int32"))
	@:argMeta(7, ":default_value"("-1"))
	#if gdscript @:argMeta(7, ":noNullPad"("-1")) #end
	public static function add_icon_item(rid:godot.RID, icon:godot.Texture2D, label:String, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1372188274)
	@:hash_compatibility([2987595282.])
	@:nativeName("add_icon_check_item")
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	@:argMeta(4, ":default_value"("Callable()"))
	#if gdscript @:argMeta(4, ":noNullPad"("Callable()")) #end
	@:argMeta(5, ":default_value"("null"))
	#if gdscript @:argMeta(5, ":noNullPad"("null")) #end
	@:argMeta(6, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(6, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(7, ":meta"("int32"))
	@:argMeta(7, ":default_value"("-1"))
	#if gdscript @:argMeta(7, ":noNullPad"("-1")) #end
	public static function add_icon_check_item(rid:godot.RID, icon:godot.Texture2D, label:String, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(980552939)
	@:hash_compatibility([2553375659.])
	@:nativeName("add_radio_check_item")
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	@:argMeta(4, ":default_value"("null"))
	#if gdscript @:argMeta(4, ":noNullPad"("null")) #end
	@:argMeta(5, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(5, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(6, ":meta"("int32"))
	@:argMeta(6, ":default_value"("-1"))
	#if gdscript @:argMeta(6, ":noNullPad"("-1")) #end
	public static function add_radio_check_item(rid:godot.RID, label:String, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1372188274)
	@:hash_compatibility([2987595282.])
	@:nativeName("add_icon_radio_check_item")
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	@:argMeta(4, ":default_value"("Callable()"))
	#if gdscript @:argMeta(4, ":noNullPad"("Callable()")) #end
	@:argMeta(5, ":default_value"("null"))
	#if gdscript @:argMeta(5, ":noNullPad"("null")) #end
	@:argMeta(6, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(6, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(7, ":meta"("int32"))
	@:argMeta(7, ":default_value"("-1"))
	#if gdscript @:argMeta(7, ":noNullPad"("-1")) #end
	public static function add_icon_radio_check_item(rid:godot.RID, icon:godot.Texture2D, label:String, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2674635658.)
	@:hash_compatibility([1558592568])
	@:nativeName("add_multistate_item")
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(4, ":default_value"("Callable()"))
	#if gdscript @:argMeta(4, ":noNullPad"("Callable()")) #end
	@:argMeta(5, ":default_value"("Callable()"))
	#if gdscript @:argMeta(5, ":noNullPad"("Callable()")) #end
	@:argMeta(6, ":default_value"("null"))
	#if gdscript @:argMeta(6, ":noNullPad"("null")) #end
	@:argMeta(7, ":default_value"("Key.KEY_NONE"))
	#if gdscript @:argMeta(7, ":noNullPad"("Key.KEY_NONE")) #end
	@:argMeta(8, ":meta"("int32"))
	@:argMeta(8, ":default_value"("-1"))
	#if gdscript @:argMeta(8, ":noNullPad"("-1")) #end
	public static function add_multistate_item(rid:godot.RID, label:String, @:meta("int32") max_states:Int, @:meta("int32") default_state:Int, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?key_callback:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end tag:Dynamic = null, @:default_value("Key.KEY_NONE") #if gdscript @:noNullPad("Key.KEY_NONE") #end accelerator:godot.Key = godot.Key.KEY_NONE, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(448810126)
	@:hash_compatibility(null)
	@:nativeName("add_separator")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public static function add_separator(rid:godot.RID, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1362438794)
	@:hash_compatibility(null)
	@:nativeName("find_item_index_with_text")
	public static function find_item_index_with_text(rid:godot.RID, text:String):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1260085030)
	@:hash_compatibility(null)
	@:nativeName("find_item_index_with_tag")
	public static function find_item_index_with_tag(rid:godot.RID, tag:Dynamic):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(893635918)
	@:hash_compatibility(null)
	@:nativeName("find_item_index_with_submenu")
	public static function find_item_index_with_submenu(rid:godot.RID, submenu_rid:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("is_item_checked")
	@:argMeta(1, ":meta"("int32"))
	public static function is_item_checked(rid:godot.RID, @:meta("int32") idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("is_item_checkable")
	@:argMeta(1, ":meta"("int32"))
	public static function is_item_checkable(rid:godot.RID, @:meta("int32") idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("is_item_radio_checkable")
	@:argMeta(1, ":meta"("int32"))
	public static function is_item_radio_checkable(rid:godot.RID, @:meta("int32") idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1639989698)
	@:hash_compatibility(null)
	@:nativeName("get_item_callback")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_callback(rid:godot.RID, @:meta("int32") idx:Int):godot.Callable;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1639989698)
	@:hash_compatibility(null)
	@:nativeName("get_item_key_callback")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_key_callback(rid:godot.RID, @:meta("int32") idx:Int):godot.Callable;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4069510997.)
	@:hash_compatibility(null)
	@:nativeName("get_item_tag")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_tag(rid:godot.RID, @:meta("int32") idx:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("get_item_text")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_text(rid:godot.RID, @:meta("int32") idx:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("get_item_submenu")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_submenu(rid:godot.RID, @:meta("int32") idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(316800700)
	@:hash_compatibility(null)
	@:nativeName("get_item_accelerator")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_accelerator(rid:godot.RID, @:meta("int32") idx:Int):godot.Key;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("is_item_disabled")
	@:argMeta(1, ":meta"("int32"))
	public static function is_item_disabled(rid:godot.RID, @:meta("int32") idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("is_item_hidden")
	@:argMeta(1, ":meta"("int32"))
	public static function is_item_hidden(rid:godot.RID, @:meta("int32") idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("get_item_tooltip")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_tooltip(rid:godot.RID, @:meta("int32") idx:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("get_item_state")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_state(rid:godot.RID, @:meta("int32") idx:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("get_item_max_states")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_max_states(rid:godot.RID, @:meta("int32") idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3391850701.)
	@:hash_compatibility(null)
	@:nativeName("get_item_icon")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_icon(rid:godot.RID, @:meta("int32") idx:Int):godot.Texture2D;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("get_item_indentation_level")
	@:argMeta(1, ":meta"("int32"))
	public static function get_item_indentation_level(rid:godot.RID, @:meta("int32") idx:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("set_item_checked")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_checked(rid:godot.RID, @:meta("int32") idx:Int, checked:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("set_item_checkable")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_checkable(rid:godot.RID, @:meta("int32") idx:Int, checkable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("set_item_radio_checkable")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_radio_checkable(rid:godot.RID, @:meta("int32") idx:Int, checkable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2779810226.)
	@:hash_compatibility(null)
	@:nativeName("set_item_callback")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_callback(rid:godot.RID, @:meta("int32") idx:Int, callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2779810226.)
	@:hash_compatibility(null)
	@:nativeName("set_item_hover_callbacks")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_hover_callbacks(rid:godot.RID, @:meta("int32") idx:Int, callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2779810226.)
	@:hash_compatibility(null)
	@:nativeName("set_item_key_callback")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_key_callback(rid:godot.RID, @:meta("int32") idx:Int, key_callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2706844827.)
	@:hash_compatibility(null)
	@:nativeName("set_item_tag")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_tag(rid:godot.RID, @:meta("int32") idx:Int, tag:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4153150897.)
	@:hash_compatibility(null)
	@:nativeName("set_item_text")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_text(rid:godot.RID, @:meta("int32") idx:Int, text:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("set_item_submenu")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_submenu(rid:godot.RID, @:meta("int32") idx:Int, submenu_rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(786300043)
	@:hash_compatibility(null)
	@:nativeName("set_item_accelerator")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_accelerator(rid:godot.RID, @:meta("int32") idx:Int, keycode:godot.Key):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("set_item_disabled")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_disabled(rid:godot.RID, @:meta("int32") idx:Int, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("set_item_hidden")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_hidden(rid:godot.RID, @:meta("int32") idx:Int, hidden:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4153150897.)
	@:hash_compatibility(null)
	@:nativeName("set_item_tooltip")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_tooltip(rid:godot.RID, @:meta("int32") idx:Int, tooltip:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4288446313.)
	@:hash_compatibility(null)
	@:nativeName("set_item_state")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function set_item_state(rid:godot.RID, @:meta("int32") idx:Int, @:meta("int32") state:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4288446313.)
	@:hash_compatibility(null)
	@:nativeName("set_item_max_states")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function set_item_max_states(rid:godot.RID, @:meta("int32") idx:Int, @:meta("int32") max_states:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1388763257)
	@:hash_compatibility(null)
	@:nativeName("set_item_icon")
	@:argMeta(1, ":meta"("int32"))
	public static function set_item_icon(rid:godot.RID, @:meta("int32") idx:Int, icon:godot.Texture2D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4288446313.)
	@:hash_compatibility(null)
	@:nativeName("set_item_indentation_level")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function set_item_indentation_level(rid:godot.RID, @:meta("int32") idx:Int, @:meta("int32") level:Int):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(23951185)
	@:hash_compatibility(null)
	@:nativeName("set_item_index")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public static function set_item_index(rid:godot.RID, @:meta("int32") idx:Int, @:meta("int32") target_idx:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("get_item_count")
	public static function get_item_count(rid:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("is_system_menu")
	public static function is_system_menu(rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("remove_item")
	@:argMeta(1, ":meta"("int32"))
	public static function remove_item(rid:godot.RID, @:meta("int32") idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public static function clear(rid:godot.RID):Void;
}