/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("core") @:is_resource(false) @:is_node(false) extern class NavigationServer3D extends godot.Object {
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("get_maps")
	public static function get_maps():Array<godot.RID>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("map_create")
	public static function map_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("map_set_active")
	public static function map_set_active(map:godot.RID, active:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("map_is_active")
	public static function map_is_active(map:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("map_set_up")
	public static function map_set_up(map:godot.RID, up:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("map_get_up")
	public static function map_get_up(map:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("map_set_cell_size")
	@:argMeta(1, ":meta"("float"))
	public static function map_set_cell_size(map:godot.RID, @:meta("float") cell_size:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("map_get_cell_size")
	public static function map_get_cell_size(map:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("map_set_cell_height")
	@:argMeta(1, ":meta"("float"))
	public static function map_set_cell_height(map:godot.RID, @:meta("float") cell_height:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("map_get_cell_height")
	public static function map_get_cell_height(map:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("map_set_merge_rasterizer_cell_scale")
	@:argMeta(1, ":meta"("float"))
	public static function map_set_merge_rasterizer_cell_scale(map:godot.RID, @:meta("float") scale:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("map_get_merge_rasterizer_cell_scale")
	public static function map_get_merge_rasterizer_cell_scale(map:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("map_set_use_edge_connections")
	public static function map_set_use_edge_connections(map:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("map_get_use_edge_connections")
	public static function map_get_use_edge_connections(map:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("map_set_edge_connection_margin")
	@:argMeta(1, ":meta"("float"))
	public static function map_set_edge_connection_margin(map:godot.RID, @:meta("float") margin:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("map_get_edge_connection_margin")
	public static function map_get_edge_connection_margin(map:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("map_set_link_connection_radius")
	@:argMeta(1, ":meta"("float"))
	public static function map_set_link_connection_radius(map:godot.RID, @:meta("float") radius:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("map_get_link_connection_radius")
	public static function map_get_link_connection_radius(map:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(276783190)
	@:hash_compatibility([1187418690, 2121045993])
	@:nativeName("map_get_path")
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(4, ":default_value"("1"))
	#if gdscript @:argMeta(4, ":noNullPad"("1")) #end
	public static function map_get_path(map:godot.RID, origin:godot.Vector3, destination:godot.Vector3, optimize:Bool, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end navigation_layers:Int = 1):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3830095642.)
	@:hash_compatibility(null)
	@:nativeName("map_get_closest_point_to_segment")
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public static function map_get_closest_point_to_segment(map:godot.RID, start:godot.Vector3, end:godot.Vector3, @:default_value("false") #if gdscript @:noNullPad("false") #end use_collision:Bool = false):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2056183332)
	@:hash_compatibility(null)
	@:nativeName("map_get_closest_point")
	public static function map_get_closest_point(map:godot.RID, to_point:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2056183332)
	@:hash_compatibility(null)
	@:nativeName("map_get_closest_point_normal")
	public static function map_get_closest_point_normal(map:godot.RID, to_point:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(553364610)
	@:hash_compatibility(null)
	@:nativeName("map_get_closest_point_owner")
	public static function map_get_closest_point_owner(map:godot.RID, to_point:godot.Vector3):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("map_get_links")
	public static function map_get_links(map:godot.RID):Array<godot.RID>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("map_get_regions")
	public static function map_get_regions(map:godot.RID):Array<godot.RID>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("map_get_agents")
	public static function map_get_agents(map:godot.RID):Array<godot.RID>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("map_get_obstacles")
	public static function map_get_obstacles(map:godot.RID):Array<godot.RID>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("map_force_update")
	public static function map_force_update(map:godot.RID):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("map_get_iteration_id")
	public static function map_get_iteration_id(map:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("map_set_use_async_iterations")
	public static function map_set_use_async_iterations(map:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("map_get_use_async_iterations")
	public static function map_get_use_async_iterations(map:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(722801526)
	@:hash_compatibility(null)
	@:nativeName("map_get_random_point")
	@:argMeta(1, ":meta"("uint32"))
	public static function map_get_random_point(map:godot.RID, @:meta("uint32") navigation_layers:Int, uniformly:Bool):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2146930868)
	@:hash_compatibility([3415008901.])
	@:nativeName("query_path")
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	public static function query_path(parameters:godot.NavigationPathQueryParameters3D, result:godot.NavigationPathQueryResult3D, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("region_create")
	public static function region_create():godot.RID;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("region_get_iteration_id")
	public static function region_get_iteration_id(region:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("region_set_use_async_iterations")
	public static function region_set_use_async_iterations(region:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("region_get_use_async_iterations")
	public static function region_get_use_async_iterations(region:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("region_set_enabled")
	public static function region_set_enabled(region:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("region_get_enabled")
	public static function region_get_enabled(region:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("region_set_use_edge_connections")
	public static function region_set_use_edge_connections(region:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("region_get_use_edge_connections")
	public static function region_get_use_edge_connections(region:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("region_set_enter_cost")
	@:argMeta(1, ":meta"("float"))
	public static function region_set_enter_cost(region:godot.RID, @:meta("float") enter_cost:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("region_get_enter_cost")
	public static function region_get_enter_cost(region:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("region_set_travel_cost")
	@:argMeta(1, ":meta"("float"))
	public static function region_set_travel_cost(region:godot.RID, @:meta("float") travel_cost:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("region_get_travel_cost")
	public static function region_get_travel_cost(region:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("region_set_owner_id")
	@:argMeta(1, ":meta"("uint64"))
	public static function region_set_owner_id(region:godot.RID, @:meta("uint64") owner_id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("region_get_owner_id")
	public static function region_get_owner_id(region:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2360011153.)
	@:hash_compatibility(null)
	@:nativeName("region_owns_point")
	public static function region_owns_point(region:godot.RID, point:godot.Vector3):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("region_set_map")
	public static function region_set_map(region:godot.RID, map:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("region_get_map")
	public static function region_get_map(region:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("region_set_navigation_layers")
	@:argMeta(1, ":meta"("uint32"))
	public static function region_set_navigation_layers(region:godot.RID, @:meta("uint32") navigation_layers:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("region_get_navigation_layers")
	public static function region_get_navigation_layers(region:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3935195649.)
	@:hash_compatibility(null)
	@:nativeName("region_set_transform")
	public static function region_set_transform(region:godot.RID, transform:godot.Transform3D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1128465797)
	@:hash_compatibility(null)
	@:nativeName("region_get_transform")
	public static function region_get_transform(region:godot.RID):godot.Transform3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2764952978.)
	@:hash_compatibility(null)
	@:nativeName("region_set_navigation_mesh")
	public static function region_set_navigation_mesh(region:godot.RID, navigation_mesh:godot.NavigationMesh):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1401173477)
	@:hash_compatibility(null)
	@:nativeName("region_bake_navigation_mesh")
	public static function region_bake_navigation_mesh(navigation_mesh:godot.NavigationMesh, root_node:godot.Node):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("region_get_connections_count")
	public static function region_get_connections_count(region:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3440143363.)
	@:hash_compatibility(null)
	@:nativeName("region_get_connection_pathway_start")
	@:argMeta(1, ":meta"("int32"))
	public static function region_get_connection_pathway_start(region:godot.RID, @:meta("int32") connection:Int):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3440143363.)
	@:hash_compatibility(null)
	@:nativeName("region_get_connection_pathway_end")
	@:argMeta(1, ":meta"("int32"))
	public static function region_get_connection_pathway_end(region:godot.RID, @:meta("int32") connection:Int):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3830095642.)
	@:hash_compatibility(null)
	@:nativeName("region_get_closest_point_to_segment")
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public static function region_get_closest_point_to_segment(region:godot.RID, start:godot.Vector3, end:godot.Vector3, @:default_value("false") #if gdscript @:noNullPad("false") #end use_collision:Bool = false):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2056183332)
	@:hash_compatibility(null)
	@:nativeName("region_get_closest_point")
	public static function region_get_closest_point(region:godot.RID, to_point:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2056183332)
	@:hash_compatibility(null)
	@:nativeName("region_get_closest_point_normal")
	public static function region_get_closest_point_normal(region:godot.RID, to_point:godot.Vector3):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(722801526)
	@:hash_compatibility(null)
	@:nativeName("region_get_random_point")
	@:argMeta(1, ":meta"("uint32"))
	public static function region_get_random_point(region:godot.RID, @:meta("uint32") navigation_layers:Int, uniformly:Bool):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(974181306)
	@:hash_compatibility(null)
	@:nativeName("region_get_bounds")
	public static function region_get_bounds(region:godot.RID):godot.AABB;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("link_create")
	public static function link_create():godot.RID;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("link_get_iteration_id")
	public static function link_get_iteration_id(link:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("link_set_map")
	public static function link_set_map(link:godot.RID, map:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("link_get_map")
	public static function link_get_map(link:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("link_set_enabled")
	public static function link_set_enabled(link:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("link_get_enabled")
	public static function link_get_enabled(link:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("link_set_bidirectional")
	public static function link_set_bidirectional(link:godot.RID, bidirectional:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("link_is_bidirectional")
	public static function link_is_bidirectional(link:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("link_set_navigation_layers")
	@:argMeta(1, ":meta"("uint32"))
	public static function link_set_navigation_layers(link:godot.RID, @:meta("uint32") navigation_layers:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("link_get_navigation_layers")
	public static function link_get_navigation_layers(link:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("link_set_start_position")
	public static function link_set_start_position(link:godot.RID, position:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("link_get_start_position")
	public static function link_get_start_position(link:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("link_set_end_position")
	public static function link_set_end_position(link:godot.RID, position:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("link_get_end_position")
	public static function link_get_end_position(link:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("link_set_enter_cost")
	@:argMeta(1, ":meta"("float"))
	public static function link_set_enter_cost(link:godot.RID, @:meta("float") enter_cost:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("link_get_enter_cost")
	public static function link_get_enter_cost(link:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("link_set_travel_cost")
	@:argMeta(1, ":meta"("float"))
	public static function link_set_travel_cost(link:godot.RID, @:meta("float") travel_cost:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("link_get_travel_cost")
	public static function link_get_travel_cost(link:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("link_set_owner_id")
	@:argMeta(1, ":meta"("uint64"))
	public static function link_set_owner_id(link:godot.RID, @:meta("uint64") owner_id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("link_get_owner_id")
	public static function link_get_owner_id(link:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("agent_create")
	public static function agent_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("agent_set_avoidance_enabled")
	public static function agent_set_avoidance_enabled(agent:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_avoidance_enabled")
	public static function agent_get_avoidance_enabled(agent:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("agent_set_use_3d_avoidance")
	public static function agent_set_use_3d_avoidance(agent:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_use_3d_avoidance")
	public static function agent_get_use_3d_avoidance(agent:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("agent_set_map")
	public static function agent_set_map(agent:godot.RID, map:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_map")
	public static function agent_get_map(agent:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("agent_set_paused")
	public static function agent_set_paused(agent:godot.RID, paused:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_paused")
	public static function agent_get_paused(agent:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_neighbor_distance")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_neighbor_distance(agent:godot.RID, @:meta("float") distance:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_neighbor_distance")
	public static function agent_get_neighbor_distance(agent:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_max_neighbors")
	@:argMeta(1, ":meta"("int32"))
	public static function agent_set_max_neighbors(agent:godot.RID, @:meta("int32") count:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_max_neighbors")
	public static function agent_get_max_neighbors(agent:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_time_horizon_agents")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_time_horizon_agents(agent:godot.RID, @:meta("float") time_horizon:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_time_horizon_agents")
	public static function agent_get_time_horizon_agents(agent:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_time_horizon_obstacles")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_time_horizon_obstacles(agent:godot.RID, @:meta("float") time_horizon:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_time_horizon_obstacles")
	public static function agent_get_time_horizon_obstacles(agent:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_radius")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_radius(agent:godot.RID, @:meta("float") radius:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_radius")
	public static function agent_get_radius(agent:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_height")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_height(agent:godot.RID, @:meta("float") height:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_height")
	public static function agent_get_height(agent:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_max_speed")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_max_speed(agent:godot.RID, @:meta("float") max_speed:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_max_speed")
	public static function agent_get_max_speed(agent:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_velocity_forced")
	public static function agent_set_velocity_forced(agent:godot.RID, velocity:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_velocity")
	public static function agent_set_velocity(agent:godot.RID, velocity:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("agent_get_velocity")
	public static function agent_get_velocity(agent:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_position")
	public static function agent_set_position(agent:godot.RID, position:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("agent_get_position")
	public static function agent_get_position(agent:godot.RID):godot.Vector3;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("agent_is_map_changed")
	public static function agent_is_map_changed(agent:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_avoidance_callback")
	public static function agent_set_avoidance_callback(agent:godot.RID, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("agent_has_avoidance_callback")
	public static function agent_has_avoidance_callback(agent:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_avoidance_layers")
	@:argMeta(1, ":meta"("uint32"))
	public static function agent_set_avoidance_layers(agent:godot.RID, @:meta("uint32") layers:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_avoidance_layers")
	public static function agent_get_avoidance_layers(agent:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("agent_set_avoidance_mask")
	@:argMeta(1, ":meta"("uint32"))
	public static function agent_set_avoidance_mask(agent:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("agent_get_avoidance_mask")
	public static function agent_get_avoidance_mask(agent:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("agent_set_avoidance_priority")
	@:argMeta(1, ":meta"("float"))
	public static function agent_set_avoidance_priority(agent:godot.RID, @:meta("float") priority:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("agent_get_avoidance_priority")
	public static function agent_get_avoidance_priority(agent:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("obstacle_create")
	public static function obstacle_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_avoidance_enabled")
	public static function obstacle_set_avoidance_enabled(obstacle:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_avoidance_enabled")
	public static function obstacle_get_avoidance_enabled(obstacle:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_use_3d_avoidance")
	public static function obstacle_set_use_3d_avoidance(obstacle:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_use_3d_avoidance")
	public static function obstacle_get_use_3d_avoidance(obstacle:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_map")
	public static function obstacle_set_map(obstacle:godot.RID, map:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_map")
	public static function obstacle_get_map(obstacle:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_paused")
	public static function obstacle_set_paused(obstacle:godot.RID, paused:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_paused")
	public static function obstacle_get_paused(obstacle:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_radius")
	@:argMeta(1, ":meta"("float"))
	public static function obstacle_set_radius(obstacle:godot.RID, @:meta("float") radius:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_radius")
	public static function obstacle_get_radius(obstacle:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_height")
	@:argMeta(1, ":meta"("float"))
	public static function obstacle_set_height(obstacle:godot.RID, @:meta("float") height:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_height")
	public static function obstacle_get_height(obstacle:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_velocity")
	public static function obstacle_set_velocity(obstacle:godot.RID, velocity:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_velocity")
	public static function obstacle_get_velocity(obstacle:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_position")
	public static function obstacle_set_position(obstacle:godot.RID, position:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_position")
	public static function obstacle_get_position(obstacle:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4030257846.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_vertices")
	public static function obstacle_set_vertices(obstacle:godot.RID, vertices:godot.PackedVector3Array):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(808965560)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_vertices")
	public static function obstacle_get_vertices(obstacle:godot.RID):godot.PackedVector3Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_set_avoidance_layers")
	@:argMeta(1, ":meta"("uint32"))
	public static function obstacle_set_avoidance_layers(obstacle:godot.RID, @:meta("uint32") layers:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("obstacle_get_avoidance_layers")
	public static function obstacle_get_avoidance_layers(obstacle:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3172802542.)
	@:hash_compatibility([3703028813., 685862123])
	@:nativeName("parse_source_geometry_data")
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	public static function parse_source_geometry_data(navigation_mesh:godot.NavigationMesh, source_geometry_data:godot.NavigationMeshSourceGeometryData3D, root_node:godot.Node, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286748856)
	@:hash_compatibility([3669016597., 2469318639.])
	@:nativeName("bake_from_source_geometry_data")
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	public static function bake_from_source_geometry_data(navigation_mesh:godot.NavigationMesh, source_geometry_data:godot.NavigationMeshSourceGeometryData3D, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286748856)
	@:hash_compatibility([3669016597., 2469318639.])
	@:nativeName("bake_from_source_geometry_data_async")
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	public static function bake_from_source_geometry_data_async(navigation_mesh:godot.NavigationMesh, source_geometry_data:godot.NavigationMeshSourceGeometryData3D, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3142026141.)
	@:hash_compatibility(null)
	@:nativeName("is_baking_navigation_mesh")
	public static function is_baking_navigation_mesh(navigation_mesh:godot.NavigationMesh):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("source_geometry_parser_create")
	public static function source_geometry_parser_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("source_geometry_parser_set_callback")
	public static function source_geometry_parser_set_callback(parser:godot.RID, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2344122170.)
	@:hash_compatibility(null)
	@:nativeName("simplify_path")
	@:argMeta(1, ":meta"("float"))
	public static function simplify_path(path:godot.PackedVector3Array, @:meta("float") epsilon:Float):godot.PackedVector3Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_rid")
	public static function free_rid(rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_active")
	public static function set_active(active:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_debug_enabled")
	public static function set_debug_enabled(enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("get_debug_enabled")
	public static function get_debug_enabled():Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1938440894)
	@:hash_compatibility(null)
	@:nativeName("get_process_info")
	public static function get_process_info(process_info:godot.NavigationServer3D_ProcessInfo):Int;
}