/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class OpenXRRenderModelExtension extends godot.OpenXRExtensionWrapper {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_active")
	public function is_active():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(937000113)
	@:hash_compatibility(null)
	@:nativeName("render_model_create")
	@:argMeta(0, ":meta"("uint64"))
	public function render_model_create(@:meta("uint64") render_model_id:Int):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("render_model_destroy")
	public function render_model_destroy(render_model:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_all")
	public function render_model_get_all():Array<godot.RID>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(788010739)
	@:hash_compatibility(null)
	@:nativeName("render_model_new_scene_instance")
	public function render_model_new_scene_instance(render_model:godot.RID):godot.Node3D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2801473409.)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_subaction_paths")
	public function render_model_get_subaction_paths(render_model:godot.RID):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642473191)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_top_level_path")
	public function render_model_get_top_level_path(render_model:godot.RID):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2350330949.)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_confidence")
	public function render_model_get_confidence(render_model:godot.RID):godot.XRPose_TrackingConfidence;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1128465797)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_root_transform")
	public function render_model_get_root_transform(render_model:godot.RID):godot.Transform3D;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_animatable_node_count")
	public function render_model_get_animatable_node_count(render_model:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_animatable_node_name")
	@:argMeta(1, ":meta"("uint32"))
	public function render_model_get_animatable_node_name(render_model:godot.RID, @:meta("uint32") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("render_model_is_animatable_node_visible")
	@:argMeta(1, ":meta"("uint32"))
	public function render_model_is_animatable_node_visible(render_model:godot.RID, @:meta("uint32") index:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1050775521)
	@:hash_compatibility(null)
	@:nativeName("render_model_get_animatable_node_transform")
	@:argMeta(1, ":meta"("uint32"))
	public function render_model_get_animatable_node_transform(render_model:godot.RID, @:meta("uint32") index:Int):godot.Transform3D;
}