/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class OpenXRSpatialEntityExtension extends godot.OpenXRExtensionWrapper {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1940837202)
	@:hash_compatibility(null)
	@:nativeName("supports_capability")
	public function supports_capability(capability:godot.OpenXRSpatialEntityExtension_Capability):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(26842779)
	@:hash_compatibility(null)
	@:nativeName("supports_component_type")
	public function supports_component_type(capability:godot.OpenXRSpatialEntityExtension_Capability, component_type:godot.OpenXRSpatialEntityExtension_ComponentType):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1874506473)
	@:hash_compatibility(null)
	@:nativeName("create_spatial_context")
	@:argMeta(1, ":default_value"("null"))
	#if gdscript @:argMeta(1, ":noNullPad"("null")) #end
	@:argMeta(2, ":default_value"("Callable()"))
	#if gdscript @:argMeta(2, ":noNullPad"("Callable()")) #end
	public function create_spatial_context(capability_configurations:Array<godot.OpenXRSpatialCapabilityConfigurationBaseHeader>, @:default_value("null") #if gdscript @:noNullPad("null") #end next:godot.OpenXRStructureBase = null, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?user_callback:godot.Callable):godot.OpenXRFutureResult;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("get_spatial_context_ready")
	public function get_spatial_context_ready(spatial_context:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_spatial_context")
	public function free_spatial_context(spatial_context:godot.RID):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("get_spatial_context_handle")
	public function get_spatial_context_handle(spatial_context:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1830928590)
	@:hash_compatibility(null)
	@:nativeName("discover_spatial_entities_with_component_data")
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	public function discover_spatial_entities_with_component_data(spatial_context:godot.RID, component_data:Array<godot.OpenXRSpatialComponentData>, @:default_value("null") #if gdscript @:noNullPad("null") #end next:godot.OpenXRStructureBase = null, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?user_callback:godot.Callable):godot.OpenXRFutureResult;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2252833536.)
	@:hash_compatibility(null)
	@:nativeName("discover_spatial_entities")
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	@:argMeta(3, ":default_value"("Callable()"))
	#if gdscript @:argMeta(3, ":noNullPad"("Callable()")) #end
	public function discover_spatial_entities(spatial_context:godot.RID, component_types:godot.PackedInt64Array, @:default_value("null") #if gdscript @:noNullPad("null") #end next:godot.OpenXRStructureBase = null, @:default_value("Callable()") #if gdscript @:noNullPad("Callable()") #end ?user_callback:godot.Callable):godot.OpenXRFutureResult;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3446086438.)
	@:hash_compatibility(null)
	@:nativeName("update_spatial_entities")
	@:argMeta(3, ":default_value"("null"))
	#if gdscript @:argMeta(3, ":noNullPad"("null")) #end
	public function update_spatial_entities(spatial_context:godot.RID, entities:Array<godot.RID>, component_types:godot.PackedInt64Array, @:default_value("null") #if gdscript @:noNullPad("null") #end next:godot.OpenXRStructureBase = null):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_spatial_snapshot")
	public function free_spatial_snapshot(spatial_snapshot:godot.RID):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("get_spatial_snapshot_handle")
	public function get_spatial_snapshot_handle(spatial_snapshot:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("get_spatial_snapshot_context")
	public function get_spatial_snapshot_context(spatial_snapshot:godot.RID):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(641015484)
	@:hash_compatibility(null)
	@:nativeName("query_snapshot")
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public function query_snapshot(spatial_snapshot:godot.RID, component_data:Array<godot.OpenXRSpatialComponentData>, @:default_value("null") #if gdscript @:noNullPad("null") #end next:godot.OpenXRStructureBase = null):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("get_string")
	@:argMeta(1, ":meta"("uint64"))
	public function get_string(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3570600051.)
	@:hash_compatibility(null)
	@:nativeName("get_uint8_buffer")
	@:argMeta(1, ":meta"("uint64"))
	public function get_uint8_buffer(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3393655756.)
	@:hash_compatibility(null)
	@:nativeName("get_uint16_buffer")
	@:argMeta(1, ":meta"("uint64"))
	public function get_uint16_buffer(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3393655756.)
	@:hash_compatibility(null)
	@:nativeName("get_uint32_buffer")
	@:argMeta(1, ":meta"("uint64"))
	public function get_uint32_buffer(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2313216651.)
	@:hash_compatibility(null)
	@:nativeName("get_float_buffer")
	@:argMeta(1, ":meta"("uint64"))
	public function get_float_buffer(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):godot.PackedFloat32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(110850971)
	@:hash_compatibility(null)
	@:nativeName("get_vector2_buffer")
	@:argMeta(1, ":meta"("uint64"))
	public function get_vector2_buffer(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):godot.PackedVector2Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1166453791)
	@:hash_compatibility(null)
	@:nativeName("get_vector3_buffer")
	@:argMeta(1, ":meta"("uint64"))
	public function get_vector3_buffer(spatial_snapshot:godot.RID, @:meta("uint64") buffer_id:Int):godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(937000113)
	@:hash_compatibility(null)
	@:nativeName("find_spatial_entity")
	@:argMeta(0, ":meta"("uint64"))
	public function find_spatial_entity(@:meta("uint64") entity_id:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2256026069.)
	@:hash_compatibility(null)
	@:nativeName("add_spatial_entity")
	@:argMeta(1, ":meta"("uint64"))
	@:argMeta(2, ":meta"("uint64"))
	public function add_spatial_entity(spatial_context:godot.RID, @:meta("uint64") entity_id:Int, @:meta("uint64") entity:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2233757277.)
	@:hash_compatibility(null)
	@:nativeName("make_spatial_entity")
	@:argMeta(1, ":meta"("uint64"))
	public function make_spatial_entity(spatial_context:godot.RID, @:meta("uint64") entity_id:Int):godot.RID;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("get_spatial_entity_id")
	public function get_spatial_entity_id(entity:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("get_spatial_entity_context")
	public function get_spatial_entity_context(entity:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_spatial_entity")
	public function free_spatial_entity(entity:godot.RID):Void;
}