/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class OpenXRAPIExtension extends godot.RefCounted {
	public function new();
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_openxr_version")
	public function get_openxr_version():Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_instance")
	public function get_instance():Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_system_id")
	public function get_system_id():Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_session")
	public function get_session():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3886436197.)
	@:hash_compatibility(null)
	@:nativeName("xr_result")
	@:argMeta(0, ":meta"("uint64"))
	public function xr_result(@:meta("uint64") result:Int, format:String, args:GodotArray):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2703660260.)
	@:hash_compatibility(null)
	@:nativeName("openxr_is_enabled")
	public static function openxr_is_enabled(check_run_in_editor:Bool):Bool;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1597066294)
	@:hash_compatibility(null)
	@:nativeName("get_instance_proc_addr")
	public function get_instance_proc_addr(name:String):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(990163283)
	@:hash_compatibility(null)
	@:nativeName("get_error_string")
	@:argMeta(0, ":meta"("uint64"))
	public function get_error_string(@:meta("uint64") result:Int):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(990163283)
	@:hash_compatibility(null)
	@:nativeName("get_swapchain_format_name")
	@:argMeta(0, ":meta"("int64"))
	public function get_swapchain_format_name(@:meta("int64") swapchain_format:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2285447957.)
	@:hash_compatibility(null)
	@:nativeName("set_object_name")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("uint64"))
	public function set_object_name(@:meta("int64") object_type:Int, @:meta("uint64") object_handle:Int, object_name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("begin_debug_label_region")
	public function begin_debug_label_region(label_name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("end_debug_label_region")
	public function end_debug_label_region():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("insert_debug_label")
	public function insert_debug_label(label_name:String):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_view_count")
	public function get_view_count():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_view_configuration")
	public function get_view_configuration():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_initialized")
	public function is_initialized():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_running")
	public function is_running():Bool;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_play_space")
	public function get_play_space():Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_predicted_display_time")
	public function get_predicted_display_time():Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_next_frame_time")
	public function get_next_frame_time():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("can_render")
	public function can_render():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4106179378.)
	@:hash_compatibility(null)
	@:nativeName("find_action")
	public function find_action(name:String, action_set:godot.RID):godot.RID;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3917799429.)
	@:hash_compatibility(null)
	@:nativeName("action_get_handle")
	public function action_get_handle(action:godot.RID):Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_hand_tracker")
	@:argMeta(0, ":meta"("int32"))
	public function get_hand_tracker(@:meta("int32") hand_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility([1997997368])
	@:nativeName("register_composition_layer_provider")
	public function register_composition_layer_provider(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility([1997997368])
	@:nativeName("unregister_composition_layer_provider")
	public function unregister_composition_layer_provider(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility([1997997368])
	@:nativeName("register_projection_views_extension")
	public function register_projection_views_extension(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility([1997997368])
	@:nativeName("unregister_projection_views_extension")
	public function unregister_projection_views_extension(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility(null)
	@:nativeName("register_frame_info_extension")
	public function register_frame_info_extension(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility(null)
	@:nativeName("unregister_frame_info_extension")
	public function unregister_frame_info_extension(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility(null)
	@:nativeName("register_projection_layer_extension")
	public function register_projection_layer_extension(extension:godot.OpenXRExtensionWrapper):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1477360496)
	@:hash_compatibility(null)
	@:nativeName("unregister_projection_layer_extension")
	public function unregister_projection_layer_extension(extension:godot.OpenXRExtensionWrapper):Void;
	@:return_value_meta("double")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(191475506)
	@:hash_compatibility(null)
	@:nativeName("get_render_state_z_near")
	public function get_render_state_z_near():Float;
	@:return_value_meta("double")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(191475506)
	@:hash_compatibility(null)
	@:nativeName("get_render_state_z_far")
	public function get_render_state_z_far():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("set_velocity_texture")
	public function set_velocity_texture(render_target:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("set_velocity_depth_texture")
	public function set_velocity_depth_texture(render_target:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1130785943)
	@:hash_compatibility(null)
	@:nativeName("set_velocity_target_size")
	public function set_velocity_target_size(target_size:godot.Vector2i):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3851388692.)
	@:hash_compatibility(null)
	@:nativeName("get_supported_swapchain_formats")
	public function get_supported_swapchain_formats():godot.PackedInt64Array;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2162228999.)
	@:hash_compatibility(null)
	@:nativeName("openxr_swapchain_create")
	@:argMeta(0, ":meta"("uint64"))
	@:argMeta(1, ":meta"("uint64"))
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(5, ":meta"("uint32"))
	@:argMeta(6, ":meta"("uint32"))
	public function openxr_swapchain_create(@:meta("uint64") create_flags:Int, @:meta("uint64") usage_flags:Int, @:meta("int64") swapchain_format:Int, @:meta("uint32") width:Int, @:meta("uint32") height:Int, @:meta("uint32") sample_count:Int, @:meta("uint32") array_size:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("openxr_swapchain_free")
	@:argMeta(0, ":meta"("uint64"))
	public function openxr_swapchain_free(@:meta("uint64") swapchain:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("openxr_swapchain_get_swapchain")
	@:argMeta(0, ":meta"("uint64"))
	public function openxr_swapchain_get_swapchain(@:meta("uint64") swapchain:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("openxr_swapchain_acquire")
	@:argMeta(0, ":meta"("uint64"))
	public function openxr_swapchain_acquire(@:meta("uint64") swapchain:Int):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(937000113)
	@:hash_compatibility(null)
	@:nativeName("openxr_swapchain_get_image")
	@:argMeta(0, ":meta"("uint64"))
	public function openxr_swapchain_get_image(@:meta("uint64") swapchain:Int):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("openxr_swapchain_release")
	@:argMeta(0, ":meta"("uint64"))
	public function openxr_swapchain_release(@:meta("uint64") swapchain:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_projection_layer")
	public function get_projection_layer():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1763793166)
	@:hash_compatibility(null)
	@:nativeName("set_render_region")
	public function set_render_region(render_region:godot.Rect2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_emulate_environment_blend_mode_alpha_blend")
	public function set_emulate_environment_blend_mode_alpha_blend(enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1579290861)
	@:hash_compatibility(null)
	@:nativeName("is_environment_blend_mode_alpha_supported")
	public function is_environment_blend_mode_alpha_supported():godot.OpenXRAPIExtension_OpenXRAlphaBlendModeSupport;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("update_main_swapchain_size")
	public function update_main_swapchain_size():Void;
}