/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("OpenXRInterface.HandJoints") #end @:is_bitfield(false) extern enum OpenXRInterface_HandJoints {
	HAND_JOINT_PALM();
	HAND_JOINT_WRIST();
	HAND_JOINT_THUMB_METACARPAL();
	HAND_JOINT_THUMB_PROXIMAL();
	HAND_JOINT_THUMB_DISTAL();
	HAND_JOINT_THUMB_TIP();
	HAND_JOINT_INDEX_METACARPAL();
	HAND_JOINT_INDEX_PROXIMAL();
	HAND_JOINT_INDEX_INTERMEDIATE();
	HAND_JOINT_INDEX_DISTAL();
	HAND_JOINT_INDEX_TIP();
	HAND_JOINT_MIDDLE_METACARPAL();
	HAND_JOINT_MIDDLE_PROXIMAL();
	HAND_JOINT_MIDDLE_INTERMEDIATE();
	HAND_JOINT_MIDDLE_DISTAL();
	HAND_JOINT_MIDDLE_TIP();
	HAND_JOINT_RING_METACARPAL();
	HAND_JOINT_RING_PROXIMAL();
	HAND_JOINT_RING_INTERMEDIATE();
	HAND_JOINT_RING_DISTAL();
	HAND_JOINT_RING_TIP();
	HAND_JOINT_LITTLE_METACARPAL();
	HAND_JOINT_LITTLE_PROXIMAL();
	HAND_JOINT_LITTLE_INTERMEDIATE();
	HAND_JOINT_LITTLE_DISTAL();
	HAND_JOINT_LITTLE_TIP();
	HAND_JOINT_MAX();
}