/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class OpenXRExtensionWrapper extends godot.Object {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3554694381.)
	@:hash_compatibility([2382534195.])
	@:nativeName("_get_requested_extensions")
	@:argMeta(0, ":meta"("uint64"))
	public function _get_requested_extensions(@:meta("uint64") xr_version:Int):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("_prepare_view_configuration")
	@:argMeta(0, ":meta"("int32"))
	public function _prepare_view_configuration(@:meta("int32") view_count:Int):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(998575451)
	@:hash_compatibility(null)
	@:nativeName("_print_view_configuration_info")
	@:argMeta(0, ":meta"("int32"))
	public function _print_view_configuration_info(@:meta("int32") view:Int):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("_get_composition_layer_count")
	public function _get_composition_layer_count():Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("_get_composition_layer")
	@:argMeta(0, ":meta"("int32"))
	public function _get_composition_layer(@:meta("int32") index:Int):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("_get_composition_layer_order")
	@:argMeta(0, ":meta"("int32"))
	public function _get_composition_layer_order(@:meta("int32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("_get_suggested_tracker_names")
	public function _get_suggested_tracker_names():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(309044627)
	@:hash_compatibility([3218959716.])
	@:nativeName("_on_register_metadata")
	public function _on_register_metadata(interaction_profile_metadata:godot.OpenXRInteractionProfileMetadata):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_before_instance_created")
	public function _on_before_instance_created():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("_on_instance_created")
	@:argMeta(0, ":meta"("uint64"))
	public function _on_instance_created(@:meta("uint64") instance:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_instance_destroyed")
	public function _on_instance_destroyed():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("_on_session_created")
	@:argMeta(0, ":meta"("uint64"))
	public function _on_session_created(@:meta("uint64") session:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_process")
	public function _on_process():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_sync_actions")
	public function _on_sync_actions():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_pre_render")
	public function _on_pre_render():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_main_swapchains_created")
	public function _on_main_swapchains_created():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_on_pre_draw_viewport")
	public function _on_pre_draw_viewport(viewport:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_on_post_draw_viewport")
	public function _on_post_draw_viewport(viewport:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_session_destroyed")
	public function _on_session_destroyed():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_idle")
	public function _on_state_idle():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_ready")
	public function _on_state_ready():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_synchronized")
	public function _on_state_synchronized():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_visible")
	public function _on_state_visible():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_focused")
	public function _on_state_focused():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_stopping")
	public function _on_state_stopping():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_loss_pending")
	public function _on_state_loss_pending():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_on_state_exiting")
	public function _on_state_exiting():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("_get_viewport_composition_layer_extension_properties")
	public function _get_viewport_composition_layer_extension_properties():Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2382534195.)
	@:hash_compatibility(null)
	@:nativeName("_get_viewport_composition_layer_extension_property_defaults")
	public function _get_viewport_composition_layer_extension_property_defaults():godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1637791613)
	@:hash_compatibility(null)
	@:nativeName("get_openxr_api")
	public function get_openxr_api():godot.OpenXRAPIExtension;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("register_extension_wrapper")
	public function register_extension_wrapper():Void;
}