/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class OS extends godot.Object {
#if use_properties
	@:index(null)
	@:getter("is_in_low_processor_usage_mode")
	@:setter("set_low_processor_usage_mode")
	public static var low_processor_usage_mode(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_in_low_processor_usage_mode")
	@:setter("set_low_processor_usage_mode")
	public static var low_processor_usage_mode : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("get_low_processor_usage_mode_sleep_usec")
	@:setter("set_low_processor_usage_mode_sleep_usec")
	public static var low_processor_usage_mode_sleep_usec(get, set) : Int;
#else

	@:index(null)
	@:getter("get_low_processor_usage_mode_sleep_usec")
	@:setter("set_low_processor_usage_mode_sleep_usec")
	public static var low_processor_usage_mode_sleep_usec : Int;
#end
#if use_properties
	@:index(null)
	@:getter("is_delta_smoothing_enabled")
	@:setter("set_delta_smoothing")
	public static var delta_smoothing(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_delta_smoothing_enabled")
	@:setter("set_delta_smoothing")
	public static var delta_smoothing : Bool;
#end
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(47165747)
	@:hash_compatibility(null)
	@:nativeName("get_entropy")
	@:argMeta(0, ":meta"("int32"))
	public static function get_entropy(@:meta("int32") size:Int):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2841200299.)
	@:hash_compatibility(null)
	@:nativeName("get_system_ca_certificates")
	public static function get_system_ca_certificates():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("get_connected_midi_inputs")
	public static function get_connected_midi_inputs():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("open_midi_inputs")
	public static function open_midi_inputs():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("close_midi_inputs")
	public static function close_midi_inputs():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1783970740)
	@:hash_compatibility([233059325])
	@:nativeName("alert")
	@:argMeta(1, ":default_value"("\"Alert!\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"Alert!\"")) #end
	public static function alert(text:String, @:default_value("\"Alert!\"") #if gdscript @:noNullPad("\"Alert!\"") #end title:String = "\"Alert!\""):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("crash")
	public static function crash(message:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_low_processor_usage_mode")
	public static function set_low_processor_usage_mode(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_in_low_processor_usage_mode")
	public static function get_low_processor_usage_mode():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_low_processor_usage_mode_sleep_usec")
	@:argMeta(0, ":meta"("int32"))
	public static function set_low_processor_usage_mode_sleep_usec(@:meta("int32") usec:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_low_processor_usage_mode_sleep_usec")
	public static function get_low_processor_usage_mode_sleep_usec():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_delta_smoothing")
	public static function set_delta_smoothing(delta_smoothing_enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_delta_smoothing_enabled")
	public static function get_delta_smoothing():Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_processor_count")
	public static function get_processor_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_processor_name")
	public static function get_processor_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_system_fonts")
	public static function get_system_fonts():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(626580860)
	@:hash_compatibility([2262142305.])
	@:nativeName("get_system_font_path")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("400"))
	#if gdscript @:argMeta(1, ":noNullPad"("400")) #end
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("100"))
	#if gdscript @:argMeta(2, ":noNullPad"("100")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public static function get_system_font_path(font_name:String, @:meta("int32") @:default_value("400") #if gdscript @:noNullPad("400") #end weight:Int = 400, @:meta("int32") @:default_value("100") #if gdscript @:noNullPad("100") #end stretch:Int = 100, @:default_value("false") #if gdscript @:noNullPad("false") #end italic:Bool = false):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(197317981)
	@:hash_compatibility([3824042574.])
	@:nativeName("get_system_font_path_for_text")
	@:argMeta(2, ":default_value"("\"\""))
	#if gdscript @:argMeta(2, ":noNullPad"("\"\"")) #end
	@:argMeta(3, ":default_value"("\"\""))
	#if gdscript @:argMeta(3, ":noNullPad"("\"\"")) #end
	@:argMeta(4, ":meta"("int32"))
	@:argMeta(4, ":default_value"("400"))
	#if gdscript @:argMeta(4, ":noNullPad"("400")) #end
	@:argMeta(5, ":meta"("int32"))
	@:argMeta(5, ":default_value"("100"))
	#if gdscript @:argMeta(5, ":noNullPad"("100")) #end
	@:argMeta(6, ":default_value"("false"))
	#if gdscript @:argMeta(6, ":noNullPad"("false")) #end
	public static function get_system_font_path_for_text(font_name:String, text:String, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end locale:String = "\"\"", @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end script:String = "\"\"", @:meta("int32") @:default_value("400") #if gdscript @:noNullPad("400") #end weight:Int = 400, @:meta("int32") @:default_value("100") #if gdscript @:noNullPad("100") #end stretch:Int = 100, @:default_value("false") #if gdscript @:noNullPad("false") #end italic:Bool = false):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_executable_path")
	public static function get_executable_path():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(723587915)
	@:hash_compatibility([990163283, 2841200299.])
	@:nativeName("read_string_from_stdin")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(0, ":default_value"("1024"))
	#if gdscript @:argMeta(0, ":noNullPad"("1024")) #end
	public static function read_string_from_stdin(@:meta("int64") @:default_value("1024") #if gdscript @:noNullPad("1024") #end buffer_size:Int = 1024):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3249455752.)
	@:hash_compatibility([47165747])
	@:nativeName("read_buffer_from_stdin")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(0, ":default_value"("1024"))
	#if gdscript @:argMeta(0, ":noNullPad"("1024")) #end
	public static function read_buffer_from_stdin(@:meta("int64") @:default_value("1024") #if gdscript @:noNullPad("1024") #end buffer_size:Int = 1024):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1704816237)
	@:hash_compatibility(null)
	@:nativeName("get_stdin_type")
	public static function get_stdin_type():godot.OS_StdHandleType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1704816237)
	@:hash_compatibility(null)
	@:nativeName("get_stdout_type")
	public static function get_stdout_type():godot.OS_StdHandleType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1704816237)
	@:hash_compatibility(null)
	@:nativeName("get_stderr_type")
	public static function get_stderr_type():godot.OS_StdHandleType;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1488299882)
	@:hash_compatibility([2881709059.])
	@:nativeName("execute")
	@:argMeta(2, ":default_value"("[]"))
	#if gdscript @:argMeta(2, ":noNullPad"("[]")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public static function execute(path:String, arguments:godot.PackedStringArray, @:default_value("[]") #if gdscript @:noNullPad("[]") #end ?output:GodotArray, @:default_value("false") #if gdscript @:noNullPad("false") #end read_stderr:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end open_console:Bool = false):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2851312030.)
	@:hash_compatibility([3845631403.])
	@:nativeName("execute_with_pipe")
	@:argMeta(2, ":default_value"("true"))
	#if gdscript @:argMeta(2, ":noNullPad"("true")) #end
	public static function execute_with_pipe(path:String, arguments:godot.PackedStringArray, @:default_value("true") #if gdscript @:noNullPad("true") #end blocking:Bool = true):godot.Dictionary;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2903767230.)
	@:hash_compatibility(null)
	@:nativeName("create_process")
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public static function create_process(path:String, arguments:godot.PackedStringArray, @:default_value("false") #if gdscript @:noNullPad("false") #end open_console:Bool = false):Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1080601263)
	@:hash_compatibility(null)
	@:nativeName("create_instance")
	public static function create_instance(arguments:godot.PackedStringArray):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2848259907.)
	@:hash_compatibility(null)
	@:nativeName("open_with_program")
	public static function open_with_program(program_path:String, paths:godot.PackedStringArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844576869)
	@:hash_compatibility(null)
	@:nativeName("kill")
	@:argMeta(0, ":meta"("int32"))
	public static function kill(@:meta("int32") pid:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166001499)
	@:hash_compatibility(null)
	@:nativeName("shell_open")
	public static function shell_open(uri:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3565188097.)
	@:hash_compatibility([885841341])
	@:nativeName("shell_show_in_file_manager")
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public static function shell_show_in_file_manager(file_or_dir_path:String, @:default_value("true") #if gdscript @:noNullPad("true") #end open_folder:Bool = true):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_process_running")
	@:argMeta(0, ":meta"("int32"))
	public static function is_process_running(@:meta("int32") pid:Int):Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_process_exit_code")
	@:argMeta(0, ":meta"("int32"))
	public static function get_process_exit_code(@:meta("int32") pid:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_process_id")
	public static function get_process_id():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("has_environment")
	public static function has_environment(variable:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("get_environment")
	public static function get_environment(variable:String):String;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3605043004.)
	@:hash_compatibility(null)
	@:nativeName("set_environment")
	public static function set_environment(variable:String, value:String):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3089850668.)
	@:hash_compatibility(null)
	@:nativeName("unset_environment")
	public static function unset_environment(variable:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_name")
	public static function get_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_distribution_name")
	public static function get_distribution_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_version")
	public static function get_version():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_version_alias")
	public static function get_version_alias():String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("get_cmdline_args")
	public static function get_cmdline_args():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("get_cmdline_user_args")
	public static function get_cmdline_user_args():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_video_adapter_driver_info")
	public static function get_video_adapter_driver_info():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3331453935.)
	@:hash_compatibility([611198603])
	@:nativeName("set_restart_on_exit")
	@:argMeta(1, ":default_value"("PackedStringArray()"))
	#if gdscript @:argMeta(1, ":noNullPad"("PackedStringArray()")) #end
	public static function set_restart_on_exit(restart:Bool, @:default_value("PackedStringArray()") #if gdscript @:noNullPad("PackedStringArray()") #end ?arguments:godot.PackedStringArray):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_restart_on_exit_set")
	public static function is_restart_on_exit_set():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_restart_on_exit_arguments")
	public static function get_restart_on_exit_arguments():godot.PackedStringArray;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(998575451)
	@:hash_compatibility(null)
	@:nativeName("delay_usec")
	@:argMeta(0, ":meta"("int32"))
	public static function delay_usec(@:meta("int32") usec:Int):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(998575451)
	@:hash_compatibility(null)
	@:nativeName("delay_msec")
	@:argMeta(0, ":meta"("int32"))
	public static function delay_msec(@:meta("int32") msec:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_locale")
	public static function get_locale():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_locale_language")
	public static function get_locale_language():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_model_name")
	public static function get_model_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_userfs_persistent")
	public static function is_userfs_persistent():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_stdout_verbose")
	public static function is_stdout_verbose():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_debug_build")
	public static function is_debug_build():Bool;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_static_memory_usage")
	public static function get_static_memory_usage():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_static_memory_peak_usage")
	public static function get_static_memory_peak_usage():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3102165223.)
	@:hash_compatibility(null)
	@:nativeName("get_memory_info")
	public static function get_memory_info():godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2113323047)
	@:hash_compatibility(null)
	@:nativeName("move_to_trash")
	public static function move_to_trash(path:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_user_data_dir")
	public static function get_user_data_dir():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3073895123.)
	@:hash_compatibility([1965199849])
	@:nativeName("get_system_dir")
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public static function get_system_dir(dir:godot.OS_SystemDir, @:default_value("true") #if gdscript @:noNullPad("true") #end shared_storage:Bool = true):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_config_dir")
	public static function get_config_dir():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_data_dir")
	public static function get_data_dir():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_cache_dir")
	public static function get_cache_dir():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_temp_dir")
	public static function get_temp_dir():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_unique_id")
	public static function get_unique_id():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2261993717.)
	@:hash_compatibility(null)
	@:nativeName("get_keycode_string")
	public static function get_keycode_string(code:godot.Key):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_keycode_unicode")
	@:argMeta(0, ":meta"("char32"))
	public static function is_keycode_unicode(@:meta("char32") code:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1084858572)
	@:hash_compatibility(null)
	@:nativeName("find_keycode_from_string")
	public static function find_keycode_from_string(string:String):godot.Key;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_use_file_access_save_and_swap")
	public static function set_use_file_access_save_and_swap(enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166001499)
	@:hash_compatibility(null)
	@:nativeName("set_thread_name")
	public static function set_thread_name(name:String):godot.Error;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_thread_caller_id")
	public static function get_thread_caller_id():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_main_thread_id")
	public static function get_main_thread_id():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("has_feature")
	public static function has_feature(tag_name:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_sandboxed")
	public static function is_sandboxed():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("request_permission")
	public static function request_permission(name:String):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("request_permissions")
	public static function request_permissions():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_granted_permissions")
	public static function get_granted_permissions():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("revoke_granted_permissions")
	public static function revoke_granted_permissions():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4261188958.)
	@:hash_compatibility(null)
	@:nativeName("add_logger")
	@:argMeta(0, ":meta"("required"))
	public static function add_logger(@:meta("required") logger:godot.Logger):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4261188958.)
	@:hash_compatibility(null)
	@:nativeName("remove_logger")
	@:argMeta(0, ":meta"("required"))
	public static function remove_logger(@:meta("required") logger:godot.Logger):Void;
}