/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class PacketPeerUDP extends godot.PacketPeer {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4051239242.)
	@:hash_compatibility([4290438434.])
	@:nativeName("bind")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":default_value"("\"*\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"*\"")) #end
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("65536"))
	#if gdscript @:argMeta(2, ":noNullPad"("65536")) #end
	public function bind(@:meta("int32") port:Int, @:default_value("\"*\"") #if gdscript @:noNullPad("\"*\"") #end bind_address:String = "\"*\"", @:meta("int32") @:default_value("65536") #if gdscript @:noNullPad("65536") #end recv_buf_size:Int = 65536):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("close")
	public function close():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("wait")
	public function wait():godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_bound")
	public function is_bound():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(993915709)
	@:hash_compatibility(null)
	@:nativeName("connect_to_host")
	@:argMeta(1, ":meta"("int32"))
	public function connect_to_host(host:String, @:meta("int32") port:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_socket_connected")
	public function is_socket_connected():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_packet_ip")
	public function get_packet_ip():String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_packet_port")
	public function get_packet_port():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_local_port")
	public function get_local_port():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(993915709)
	@:hash_compatibility(null)
	@:nativeName("set_dest_address")
	@:argMeta(1, ":meta"("int32"))
	public function set_dest_address(host:String, @:meta("int32") port:Int):godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_broadcast_enabled")
	public function set_broadcast_enabled(enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("join_multicast_group")
	public function join_multicast_group(multicast_address:String, interface_name:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("leave_multicast_group")
	public function leave_multicast_group(multicast_address:String, interface_name:String):godot.Error;
}