/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("builtin_classes") @:indexing_return_type("int") @:is_keyed(false) @:has_destructor(true) @:copyType @:noCompletion @:avoid_temporaries @:nativeName("PackedByteArray") extern class PackedByteArray_Fields {
	@:overload(function(from:godot.PackedByteArray):Void { })
	@:overload(function(from:GodotArray):Void { })
	public function new();
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("get")
	public function get(@:default_value(null) index:Int):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("set")
	public function set(@:default_value(null) index:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("size")
	public function size():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_empty")
	public function is_empty():Bool;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(694024632)
	@:nativeName("push_back")
	public function push_back(@:default_value(null) value:Int):Bool;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(694024632)
	@:nativeName("append")
	public function append(@:default_value(null) value:Int):Bool;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(791097111)
	@:nativeName("append_array")
	public function append_array(@:default_value(null) array:godot.PackedByteArray):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(2823966027.)
	@:nativeName("remove_at")
	public function remove_at(@:default_value(null) index:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(1487112728)
	@:nativeName("insert")
	public function insert(@:default_value(null) at_index:Int, @:default_value(null) value:Int):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(2823966027.)
	@:nativeName("fill")
	public function fill(@:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(848867239)
	@:nativeName("resize")
	public function resize(@:default_value(null) new_size:Int):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("clear")
	public function clear():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(931488181)
	@:nativeName("has")
	public function has(@:default_value(null) value:Int):Bool;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("reverse")
	public function reverse():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2278869132.)
	@:nativeName("slice")
	public function slice(@:default_value(null) begin:Int, @:default_value("2147483647") ?end:Int):godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3218959716.)
	@:nativeName("sort")
	public function sort():Void;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(954237325)
	@:nativeName("bsearch")
	public function bsearch(@:default_value(null) value:Int, @:default_value("true") ?before:Bool):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("duplicate")
	public function duplicate():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2984303840.)
	@:nativeName("find")
	public function find(@:default_value(null) value:Int, @:default_value("0") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2984303840.)
	@:nativeName("rfind")
	public function rfind(@:default_value(null) value:Int, @:default_value("-1") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("count")
	public function count(@:default_value(null) value:Int):Int;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(694024632)
	@:nativeName("erase")
	public function erase(@:default_value(null) value:Int):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_string_from_ascii")
	public function get_string_from_ascii():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_string_from_utf8")
	public function get_string_from_utf8():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_string_from_utf16")
	public function get_string_from_utf16():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_string_from_utf32")
	public function get_string_from_utf32():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_string_from_wchar")
	public function get_string_from_wchar():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("get_string_from_multibyte_char")
	public function get_string_from_multibyte_char(@:default_value("\"\"") ?encoding:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("hex_encode")
	public function hex_encode():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1845905913)
	@:nativeName("compress")
	public function compress(@:default_value("0") ?compression_mode:Int):godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2278869132.)
	@:nativeName("decompress")
	public function decompress(@:default_value(null) buffer_size:Int, @:default_value("0") ?compression_mode:Int):godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2278869132.)
	@:nativeName("decompress_dynamic")
	public function decompress_dynamic(@:default_value(null) max_output_size:Int, @:default_value("0") ?compression_mode:Int):godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_u8")
	public function decode_u8(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_s8")
	public function decode_s8(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_u16")
	public function decode_u16(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_s16")
	public function decode_s16(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_u32")
	public function decode_u32(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_s32")
	public function decode_s32(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_u64")
	public function decode_u64(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("decode_s64")
	public function decode_s64(@:default_value(null) byte_offset:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1401583798)
	@:nativeName("decode_half")
	public function decode_half(@:default_value(null) byte_offset:Int):Float;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1401583798)
	@:nativeName("decode_float")
	public function decode_float(@:default_value(null) byte_offset:Int):Float;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1401583798)
	@:nativeName("decode_double")
	public function decode_double(@:default_value(null) byte_offset:Int):Float;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2914632957.)
	@:nativeName("has_encoded_var")
	public function has_encoded_var(@:default_value(null) byte_offset:Int, @:default_value("false") ?allow_objects:Bool):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1740420038)
	@:nativeName("decode_var")
	public function decode_var(@:default_value(null) byte_offset:Int, @:default_value("false") ?allow_objects:Bool):Dynamic;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(954237325)
	@:nativeName("decode_var_size")
	public function decode_var_size(@:default_value(null) byte_offset:Int, @:default_value("false") ?allow_objects:Bool):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3158844420.)
	@:nativeName("to_int32_array")
	public function to_int32_array():godot.PackedInt32Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1961294120)
	@:nativeName("to_int64_array")
	public function to_int64_array():godot.PackedInt64Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3575107827.)
	@:nativeName("to_float32_array")
	public function to_float32_array():godot.PackedFloat32Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1627308337)
	@:nativeName("to_float64_array")
	public function to_float64_array():godot.PackedFloat64Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1660374357)
	@:nativeName("to_vector2_array")
	public function to_vector2_array():godot.PackedVector2Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4171207452.)
	@:nativeName("to_vector3_array")
	public function to_vector3_array():godot.PackedVector3Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(146203628)
	@:nativeName("to_vector4_array")
	public function to_vector4_array():godot.PackedVector4Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3072026941.)
	@:nativeName("to_color_array")
	public function to_color_array():godot.PackedColorArray;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("bswap16")
	public function bswap16(@:default_value("0") ?offset:Int, @:default_value("-1") ?count:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("bswap32")
	public function bswap32(@:default_value("0") ?offset:Int, @:default_value("-1") ?count:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("bswap64")
	public function bswap64(@:default_value("0") ?offset:Int, @:default_value("-1") ?count:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_u8")
	public function encode_u8(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_s8")
	public function encode_s8(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_u16")
	public function encode_u16(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_s16")
	public function encode_s16(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_u32")
	public function encode_u32(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_s32")
	public function encode_s32(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_u64")
	public function encode_u64(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(3638975848.)
	@:nativeName("encode_s64")
	public function encode_s64(@:default_value(null) byte_offset:Int, @:default_value(null) value:Int):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(1113000516)
	@:nativeName("encode_half")
	public function encode_half(@:default_value(null) byte_offset:Int, @:default_value(null) value:Float):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(1113000516)
	@:nativeName("encode_float")
	public function encode_float(@:default_value(null) byte_offset:Int, @:default_value(null) value:Float):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(1113000516)
	@:nativeName("encode_double")
	public function encode_double(@:default_value(null) byte_offset:Int, @:default_value(null) value:Float):Void;
	@:is_vararg(false)
	@:is_const(false)
	@:is_static(false)
	@:hash(2604460497.)
	@:nativeName("encode_var")
	public function encode_var(@:default_value(null) byte_offset:Int, @:default_value(null) value:Dynamic, @:default_value("false") ?allow_objects:Bool):Int;
}