/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("core") @:is_resource(false) @:is_node(false) extern class PhysicsServer2D extends godot.Object {
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("world_boundary_shape_create")
	public static function world_boundary_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("separation_ray_shape_create")
	public static function separation_ray_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("segment_shape_create")
	public static function segment_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("circle_shape_create")
	public static function circle_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("rectangle_shape_create")
	public static function rectangle_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("capsule_shape_create")
	public static function capsule_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("convex_polygon_shape_create")
	public static function convex_polygon_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("concave_polygon_shape_create")
	public static function concave_polygon_shape_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175752987.)
	@:hash_compatibility(null)
	@:nativeName("shape_set_data")
	public static function shape_set_data(shape:godot.RID, data:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1240598777)
	@:hash_compatibility(null)
	@:nativeName("shape_get_type")
	public static function shape_get_type(shape:godot.RID):godot.PhysicsServer2D_ShapeType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4171304767.)
	@:hash_compatibility(null)
	@:nativeName("shape_get_data")
	public static function shape_get_data(shape:godot.RID):Dynamic;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("space_create")
	public static function space_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("space_set_active")
	public static function space_set_active(space:godot.RID, active:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("space_is_active")
	public static function space_is_active(space:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(949194586)
	@:hash_compatibility(null)
	@:nativeName("space_set_param")
	@:argMeta(2, ":meta"("float"))
	public static function space_set_param(space:godot.RID, param:godot.PhysicsServer2D_SpaceParameter, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(874111783)
	@:hash_compatibility(null)
	@:nativeName("space_get_param")
	public static function space_get_param(space:godot.RID, param:godot.PhysicsServer2D_SpaceParameter):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3160173886.)
	@:hash_compatibility(null)
	@:nativeName("space_get_direct_state")
	public static function space_get_direct_state(space:godot.RID):godot.PhysicsDirectSpaceState2D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("area_create")
	public static function area_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("area_set_space")
	public static function area_set_space(area:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("area_get_space")
	public static function area_get_space(area:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(339056240)
	@:hash_compatibility([754862190])
	@:nativeName("area_add_shape")
	@:argMeta(2, ":default_value"("Transform2D(1, 0, 0, 1, 0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Transform2D(1, 0, 0, 1, 0, 0)")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public static function area_add_shape(area:godot.RID, shape:godot.RID, @:default_value("Transform2D(1, 0, 0, 1, 0, 0)") #if gdscript @:noNullPad("Transform2D(1, 0, 0, 1, 0, 0)") #end ?transform:godot.Transform2D, @:default_value("false") #if gdscript @:noNullPad("false") #end disabled:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("area_set_shape")
	@:argMeta(1, ":meta"("int32"))
	public static function area_set_shape(area:godot.RID, @:meta("int32") shape_idx:Int, shape:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(736082694)
	@:hash_compatibility(null)
	@:nativeName("area_set_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public static function area_set_shape_transform(area:godot.RID, @:meta("int32") shape_idx:Int, transform:godot.Transform2D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("area_set_shape_disabled")
	@:argMeta(1, ":meta"("int32"))
	public static function area_set_shape_disabled(area:godot.RID, @:meta("int32") shape_idx:Int, disabled:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("area_get_shape_count")
	public static function area_get_shape_count(area:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("area_get_shape")
	@:argMeta(1, ":meta"("int32"))
	public static function area_get_shape(area:godot.RID, @:meta("int32") shape_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1324854622)
	@:hash_compatibility(null)
	@:nativeName("area_get_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public static function area_get_shape_transform(area:godot.RID, @:meta("int32") shape_idx:Int):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("area_remove_shape")
	@:argMeta(1, ":meta"("int32"))
	public static function area_remove_shape(area:godot.RID, @:meta("int32") shape_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("area_clear_shapes")
	public static function area_clear_shapes(area:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("area_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public static function area_set_collision_layer(area:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("area_get_collision_layer")
	public static function area_get_collision_layer(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("area_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public static function area_set_collision_mask(area:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("area_get_collision_mask")
	public static function area_get_collision_mask(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1257146028)
	@:hash_compatibility(null)
	@:nativeName("area_set_param")
	public static function area_set_param(area:godot.RID, param:godot.PhysicsServer2D_AreaParameter, value:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1246044741)
	@:hash_compatibility(null)
	@:nativeName("area_set_transform")
	public static function area_set_transform(area:godot.RID, transform:godot.Transform2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3047435120.)
	@:hash_compatibility(null)
	@:nativeName("area_get_param")
	public static function area_get_param(area:godot.RID, param:godot.PhysicsServer2D_AreaParameter):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(213527486)
	@:hash_compatibility(null)
	@:nativeName("area_get_transform")
	public static function area_get_transform(area:godot.RID):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("area_attach_object_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public static function area_attach_object_instance_id(area:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("area_get_object_instance_id")
	public static function area_get_object_instance_id(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("area_attach_canvas_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public static function area_attach_canvas_instance_id(area:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("area_get_canvas_instance_id")
	public static function area_get_canvas_instance_id(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("area_set_monitor_callback")
	public static function area_set_monitor_callback(area:godot.RID, callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("area_set_area_monitor_callback")
	public static function area_set_area_monitor_callback(area:godot.RID, callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("area_set_monitorable")
	public static function area_set_monitorable(area:godot.RID, monitorable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("body_create")
	public static function body_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("body_set_space")
	public static function body_set_space(body:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("body_get_space")
	public static function body_get_space(body:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1658067650)
	@:hash_compatibility(null)
	@:nativeName("body_set_mode")
	public static function body_set_mode(body:godot.RID, mode:godot.PhysicsServer2D_BodyMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3261702585.)
	@:hash_compatibility(null)
	@:nativeName("body_get_mode")
	public static function body_get_mode(body:godot.RID):godot.PhysicsServer2D_BodyMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(339056240)
	@:hash_compatibility([754862190])
	@:nativeName("body_add_shape")
	@:argMeta(2, ":default_value"("Transform2D(1, 0, 0, 1, 0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Transform2D(1, 0, 0, 1, 0, 0)")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public static function body_add_shape(body:godot.RID, shape:godot.RID, @:default_value("Transform2D(1, 0, 0, 1, 0, 0)") #if gdscript @:noNullPad("Transform2D(1, 0, 0, 1, 0, 0)") #end ?transform:godot.Transform2D, @:default_value("false") #if gdscript @:noNullPad("false") #end disabled:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("body_set_shape")
	@:argMeta(1, ":meta"("int32"))
	public static function body_set_shape(body:godot.RID, @:meta("int32") shape_idx:Int, shape:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(736082694)
	@:hash_compatibility(null)
	@:nativeName("body_set_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public static function body_set_shape_transform(body:godot.RID, @:meta("int32") shape_idx:Int, transform:godot.Transform2D):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("body_get_shape_count")
	public static function body_get_shape_count(body:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("body_get_shape")
	@:argMeta(1, ":meta"("int32"))
	public static function body_get_shape(body:godot.RID, @:meta("int32") shape_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1324854622)
	@:hash_compatibility(null)
	@:nativeName("body_get_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public static function body_get_shape_transform(body:godot.RID, @:meta("int32") shape_idx:Int):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("body_remove_shape")
	@:argMeta(1, ":meta"("int32"))
	public static function body_remove_shape(body:godot.RID, @:meta("int32") shape_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("body_clear_shapes")
	public static function body_clear_shapes(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("body_set_shape_disabled")
	@:argMeta(1, ":meta"("int32"))
	public static function body_set_shape_disabled(body:godot.RID, @:meta("int32") shape_idx:Int, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2389283141.)
	@:hash_compatibility([2556489974.])
	@:nativeName("body_set_shape_as_one_way_collision")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(4, ":default_value"("Vector2(0, 1)"))
	#if gdscript @:argMeta(4, ":noNullPad"("Vector2(0, 1)")) #end
	public static function body_set_shape_as_one_way_collision(body:godot.RID, @:meta("int32") shape_idx:Int, enable:Bool, @:meta("float") margin:Float, @:default_value("Vector2(0, 1)") #if gdscript @:noNullPad("Vector2(0, 1)") #end ?direction:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("body_attach_object_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public static function body_attach_object_instance_id(body:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("body_get_object_instance_id")
	public static function body_get_object_instance_id(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("body_attach_canvas_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public static function body_attach_canvas_instance_id(body:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("body_get_canvas_instance_id")
	public static function body_get_canvas_instance_id(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1882257015)
	@:hash_compatibility(null)
	@:nativeName("body_set_continuous_collision_detection_mode")
	public static function body_set_continuous_collision_detection_mode(body:godot.RID, mode:godot.PhysicsServer2D_CCDMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2661282217.)
	@:hash_compatibility(null)
	@:nativeName("body_get_continuous_collision_detection_mode")
	public static function body_get_continuous_collision_detection_mode(body:godot.RID):godot.PhysicsServer2D_CCDMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("body_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public static function body_set_collision_layer(body:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("body_get_collision_layer")
	public static function body_get_collision_layer(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("body_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public static function body_set_collision_mask(body:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("body_get_collision_mask")
	public static function body_get_collision_mask(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("body_set_collision_priority")
	@:argMeta(1, ":meta"("float"))
	public static function body_set_collision_priority(body:godot.RID, @:meta("float") priority:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("body_get_collision_priority")
	public static function body_get_collision_priority(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2715630609.)
	@:hash_compatibility(null)
	@:nativeName("body_set_param")
	public static function body_set_param(body:godot.RID, param:godot.PhysicsServer2D_BodyParameter, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3208033526.)
	@:hash_compatibility(null)
	@:nativeName("body_get_param")
	public static function body_get_param(body:godot.RID, param:godot.PhysicsServer2D_BodyParameter):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("body_reset_mass_properties")
	public static function body_reset_mass_properties(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1706355209)
	@:hash_compatibility(null)
	@:nativeName("body_set_state")
	public static function body_set_state(body:godot.RID, state:godot.PhysicsServer2D_BodyState, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4036367961.)
	@:hash_compatibility(null)
	@:nativeName("body_get_state")
	public static function body_get_state(body:godot.RID, state:godot.PhysicsServer2D_BodyState):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("body_apply_central_impulse")
	public static function body_apply_central_impulse(body:godot.RID, impulse:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("body_apply_torque_impulse")
	@:argMeta(1, ":meta"("float"))
	public static function body_apply_torque_impulse(body:godot.RID, @:meta("float") impulse:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(205485391)
	@:hash_compatibility([34330743])
	@:nativeName("body_apply_impulse")
	@:argMeta(2, ":default_value"("Vector2(0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Vector2(0, 0)")) #end
	public static function body_apply_impulse(body:godot.RID, impulse:godot.Vector2, @:default_value("Vector2(0, 0)") #if gdscript @:noNullPad("Vector2(0, 0)") #end ?position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("body_apply_central_force")
	public static function body_apply_central_force(body:godot.RID, force:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(205485391)
	@:hash_compatibility([34330743])
	@:nativeName("body_apply_force")
	@:argMeta(2, ":default_value"("Vector2(0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Vector2(0, 0)")) #end
	public static function body_apply_force(body:godot.RID, force:godot.Vector2, @:default_value("Vector2(0, 0)") #if gdscript @:noNullPad("Vector2(0, 0)") #end ?position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("body_apply_torque")
	@:argMeta(1, ":meta"("float"))
	public static function body_apply_torque(body:godot.RID, @:meta("float") torque:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("body_add_constant_central_force")
	public static function body_add_constant_central_force(body:godot.RID, force:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(205485391)
	@:hash_compatibility([34330743])
	@:nativeName("body_add_constant_force")
	@:argMeta(2, ":default_value"("Vector2(0, 0)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Vector2(0, 0)")) #end
	public static function body_add_constant_force(body:godot.RID, force:godot.Vector2, @:default_value("Vector2(0, 0)") #if gdscript @:noNullPad("Vector2(0, 0)") #end ?position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("body_add_constant_torque")
	@:argMeta(1, ":meta"("float"))
	public static function body_add_constant_torque(body:godot.RID, @:meta("float") torque:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("body_set_constant_force")
	public static function body_set_constant_force(body:godot.RID, force:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2440833711.)
	@:hash_compatibility(null)
	@:nativeName("body_get_constant_force")
	public static function body_get_constant_force(body:godot.RID):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("body_set_constant_torque")
	@:argMeta(1, ":meta"("float"))
	public static function body_set_constant_torque(body:godot.RID, @:meta("float") torque:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("body_get_constant_torque")
	public static function body_get_constant_torque(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("body_set_axis_velocity")
	public static function body_set_axis_velocity(body:godot.RID, axis_velocity:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("body_add_collision_exception")
	public static function body_add_collision_exception(body:godot.RID, excepted_body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("body_remove_collision_exception")
	public static function body_remove_collision_exception(body:godot.RID, excepted_body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("body_set_max_contacts_reported")
	@:argMeta(1, ":meta"("int32"))
	public static function body_set_max_contacts_reported(body:godot.RID, @:meta("int32") amount:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("body_get_max_contacts_reported")
	public static function body_get_max_contacts_reported(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("body_set_omit_force_integration")
	public static function body_set_omit_force_integration(body:godot.RID, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("body_is_omitting_force_integration")
	public static function body_is_omitting_force_integration(body:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("body_set_state_sync_callback")
	public static function body_set_state_sync_callback(body:godot.RID, callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3059434249.)
	@:hash_compatibility(null)
	@:nativeName("body_set_force_integration_callback")
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public static function body_set_force_integration_callback(body:godot.RID, callable:godot.Callable, @:default_value("null") #if gdscript @:noNullPad("null") #end userdata:Dynamic = null):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1699844009)
	@:hash_compatibility(null)
	@:nativeName("body_test_motion")
	@:argMeta(1, ":meta"("required"))
	@:argMeta(2, ":default_value"("null"))
	#if gdscript @:argMeta(2, ":noNullPad"("null")) #end
	public static function body_test_motion(body:godot.RID, @:meta("required") parameters:godot.PhysicsTestMotionParameters2D, @:default_value("null") #if gdscript @:noNullPad("null") #end result:godot.PhysicsTestMotionResult2D = null):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1191931871)
	@:hash_compatibility(null)
	@:nativeName("body_get_direct_state")
	public static function body_get_direct_state(body:godot.RID):godot.PhysicsDirectBodyState2D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("joint_create")
	public static function joint_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("joint_clear")
	public static function joint_clear(joint:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3972556514.)
	@:hash_compatibility(null)
	@:nativeName("joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public static function joint_set_param(joint:godot.RID, param:godot.PhysicsServer2D_JointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4016448949.)
	@:hash_compatibility(null)
	@:nativeName("joint_get_param")
	public static function joint_get_param(joint:godot.RID, param:godot.PhysicsServer2D_JointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("joint_disable_collisions_between_bodies")
	public static function joint_disable_collisions_between_bodies(joint:godot.RID, disable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("joint_is_disabled_collisions_between_bodies")
	public static function joint_is_disabled_collisions_between_bodies(joint:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1612646186)
	@:hash_compatibility([2288600450.])
	@:nativeName("joint_make_pin")
	@:argMeta(3, ":default_value"("RID()"))
	#if gdscript @:argMeta(3, ":noNullPad"("RID()")) #end
	public static function joint_make_pin(joint:godot.RID, anchor:godot.Vector2, body_a:godot.RID, @:default_value("RID()") #if gdscript @:noNullPad("RID()") #end ?body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(481430435)
	@:hash_compatibility([3573265764.])
	@:nativeName("joint_make_groove")
	@:argMeta(4, ":default_value"("RID()"))
	#if gdscript @:argMeta(4, ":noNullPad"("RID()")) #end
	@:argMeta(5, ":default_value"("RID()"))
	#if gdscript @:argMeta(5, ":noNullPad"("RID()")) #end
	public static function joint_make_groove(joint:godot.RID, groove1_a:godot.Vector2, groove2_a:godot.Vector2, anchor_b:godot.Vector2, @:default_value("RID()") #if gdscript @:noNullPad("RID()") #end ?body_a:godot.RID, @:default_value("RID()") #if gdscript @:noNullPad("RID()") #end ?body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1994657646)
	@:hash_compatibility([206603952])
	@:nativeName("joint_make_damped_spring")
	@:argMeta(4, ":default_value"("RID()"))
	#if gdscript @:argMeta(4, ":noNullPad"("RID()")) #end
	public static function joint_make_damped_spring(joint:godot.RID, anchor_a:godot.Vector2, anchor_b:godot.Vector2, body_a:godot.RID, @:default_value("RID()") #if gdscript @:noNullPad("RID()") #end ?body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3520002352.)
	@:hash_compatibility(null)
	@:nativeName("pin_joint_set_flag")
	public static function pin_joint_set_flag(joint:godot.RID, flag:godot.PhysicsServer2D_PinJointFlag, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2647867364.)
	@:hash_compatibility(null)
	@:nativeName("pin_joint_get_flag")
	public static function pin_joint_get_flag(joint:godot.RID, flag:godot.PhysicsServer2D_PinJointFlag):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(550574241)
	@:hash_compatibility(null)
	@:nativeName("pin_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public static function pin_joint_set_param(joint:godot.RID, param:godot.PhysicsServer2D_PinJointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(348281383)
	@:hash_compatibility(null)
	@:nativeName("pin_joint_get_param")
	public static function pin_joint_get_param(joint:godot.RID, param:godot.PhysicsServer2D_PinJointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(220564071)
	@:hash_compatibility(null)
	@:nativeName("damped_spring_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public static function damped_spring_joint_set_param(joint:godot.RID, param:godot.PhysicsServer2D_DampedSpringParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2075871277)
	@:hash_compatibility(null)
	@:nativeName("damped_spring_joint_get_param")
	public static function damped_spring_joint_get_param(joint:godot.RID, param:godot.PhysicsServer2D_DampedSpringParam):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4262502231.)
	@:hash_compatibility(null)
	@:nativeName("joint_get_type")
	public static function joint_get_type(joint:godot.RID):godot.PhysicsServer2D_JointType;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_rid")
	public static function free_rid(rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_active")
	public static function set_active(active:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(576496006)
	@:hash_compatibility(null)
	@:nativeName("get_process_info")
	public static function get_process_info(process_info:godot.PhysicsServer2D_ProcessInfo):Int;
}