/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("PhysicsServer3D.G6DOFJointAxisParam") #end @:is_bitfield(false) extern enum PhysicsServer3D_G6DOFJointAxisParam {
	G6DOF_JOINT_LINEAR_LOWER_LIMIT();
	G6DOF_JOINT_LINEAR_UPPER_LIMIT();
	G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS();
	G6DOF_JOINT_LINEAR_RESTITUTION();
	G6DOF_JOINT_LINEAR_DAMPING();
	G6DOF_JOINT_LINEAR_MOTOR_TARGET_VELOCITY();
	G6DOF_JOINT_LINEAR_MOTOR_FORCE_LIMIT();
	G6DOF_JOINT_LINEAR_SPRING_STIFFNESS();
	G6DOF_JOINT_LINEAR_SPRING_DAMPING();
	G6DOF_JOINT_LINEAR_SPRING_EQUILIBRIUM_POINT();
	G6DOF_JOINT_ANGULAR_LOWER_LIMIT();
	G6DOF_JOINT_ANGULAR_UPPER_LIMIT();
	G6DOF_JOINT_ANGULAR_LIMIT_SOFTNESS();
	G6DOF_JOINT_ANGULAR_DAMPING();
	G6DOF_JOINT_ANGULAR_RESTITUTION();
	G6DOF_JOINT_ANGULAR_FORCE_LIMIT();
	G6DOF_JOINT_ANGULAR_ERP();
	G6DOF_JOINT_ANGULAR_MOTOR_TARGET_VELOCITY();
	G6DOF_JOINT_ANGULAR_MOTOR_FORCE_LIMIT();
	G6DOF_JOINT_ANGULAR_SPRING_STIFFNESS();
	G6DOF_JOINT_ANGULAR_SPRING_DAMPING();
	G6DOF_JOINT_ANGULAR_SPRING_EQUILIBRIUM_POINT();
	G6DOF_JOINT_MAX();
}