/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class PhysicsDirectBodyState2DExtension extends godot.PhysicsDirectBodyState2D {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3341600327.)
	@:hash_compatibility(null)
	@:nativeName("_get_total_gravity")
	public function _get_total_gravity():godot.Vector2;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_total_linear_damp")
	public function _get_total_linear_damp():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_total_angular_damp")
	public function _get_total_angular_damp():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3341600327.)
	@:hash_compatibility(null)
	@:nativeName("_get_center_of_mass")
	public function _get_center_of_mass():godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3341600327.)
	@:hash_compatibility(null)
	@:nativeName("_get_center_of_mass_local")
	public function _get_center_of_mass_local():godot.Vector2;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_inverse_mass")
	public function _get_inverse_mass():Float;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_inverse_inertia")
	public function _get_inverse_inertia():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("_set_linear_velocity")
	public function _set_linear_velocity(velocity:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3341600327.)
	@:hash_compatibility(null)
	@:nativeName("_get_linear_velocity")
	public function _get_linear_velocity():godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_set_angular_velocity")
	@:argMeta(0, ":meta"("float"))
	public function _set_angular_velocity(@:meta("float") velocity:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_angular_velocity")
	public function _get_angular_velocity():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2761652528.)
	@:hash_compatibility(null)
	@:nativeName("_set_transform")
	public function _set_transform(transform:godot.Transform2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814499831.)
	@:hash_compatibility(null)
	@:nativeName("_get_transform")
	public function _get_transform():godot.Transform2D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2656412154.)
	@:hash_compatibility(null)
	@:nativeName("_get_velocity_at_local_position")
	public function _get_velocity_at_local_position(local_position:godot.Vector2):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("_apply_central_impulse")
	public function _apply_central_impulse(impulse:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3108078480.)
	@:hash_compatibility(null)
	@:nativeName("_apply_impulse")
	public function _apply_impulse(impulse:godot.Vector2, position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_apply_torque_impulse")
	@:argMeta(0, ":meta"("float"))
	public function _apply_torque_impulse(@:meta("float") impulse:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("_apply_central_force")
	public function _apply_central_force(force:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3108078480.)
	@:hash_compatibility(null)
	@:nativeName("_apply_force")
	public function _apply_force(force:godot.Vector2, position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_apply_torque")
	@:argMeta(0, ":meta"("float"))
	public function _apply_torque(@:meta("float") torque:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("_add_constant_central_force")
	public function _add_constant_central_force(force:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3108078480.)
	@:hash_compatibility(null)
	@:nativeName("_add_constant_force")
	public function _add_constant_force(force:godot.Vector2, position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_add_constant_torque")
	@:argMeta(0, ":meta"("float"))
	public function _add_constant_torque(@:meta("float") torque:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("_set_constant_force")
	public function _set_constant_force(force:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3341600327.)
	@:hash_compatibility(null)
	@:nativeName("_get_constant_force")
	public function _get_constant_force():godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_set_constant_torque")
	@:argMeta(0, ":meta"("float"))
	public function _set_constant_torque(@:meta("float") torque:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_constant_torque")
	public function _get_constant_torque():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_set_sleep_state")
	public function _set_sleep_state(enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_sleeping")
	public function _is_sleeping():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("_set_collision_layer")
	@:argMeta(0, ":meta"("uint32"))
	public function _set_collision_layer(@:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_collision_layer")
	public function _get_collision_layer():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("_set_collision_mask")
	@:argMeta(0, ":meta"("uint32"))
	public function _set_collision_mask(@:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_collision_mask")
	public function _get_collision_mask():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_count")
	public function _get_contact_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_local_position")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_local_position(@:meta("int32") contact_idx:Int):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_local_normal")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_local_normal(@:meta("int32") contact_idx:Int):godot.Vector2;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_local_shape")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_local_shape(@:meta("int32") contact_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_local_velocity_at_position")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_local_velocity_at_position(@:meta("int32") contact_idx:Int):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(495598643)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_collider")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_collider(@:meta("int32") contact_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_collider_position")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_collider_position(@:meta("int32") contact_idx:Int):godot.Vector2;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_collider_id")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_collider_id(@:meta("int32") contact_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3332903315.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_collider_object")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_collider_object(@:meta("int32") contact_idx:Int):godot.Object;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_collider_shape")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_collider_shape(@:meta("int32") contact_idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_collider_velocity_at_position")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_collider_velocity_at_position(@:meta("int32") contact_idx:Int):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2299179447.)
	@:hash_compatibility(null)
	@:nativeName("_get_contact_impulse")
	@:argMeta(0, ":meta"("int32"))
	public function _get_contact_impulse(@:meta("int32") contact_idx:Int):godot.Vector2;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_step")
	public function _get_step():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_integrate_forces")
	public function _integrate_forces():Void;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2506717822.)
	@:hash_compatibility(null)
	@:nativeName("_get_space_state")
	public function _get_space_state():godot.PhysicsDirectSpaceState2D;
}