/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class PhysicsServer2DExtension extends godot.PhysicsServer2D {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_world_boundary_shape_create")
	public function _world_boundary_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_separation_ray_shape_create")
	public function _separation_ray_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_segment_shape_create")
	public function _segment_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_circle_shape_create")
	public function _circle_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_rectangle_shape_create")
	public function _rectangle_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_capsule_shape_create")
	public function _capsule_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_convex_polygon_shape_create")
	public function _convex_polygon_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_concave_polygon_shape_create")
	public function _concave_polygon_shape_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3175752987.)
	@:hash_compatibility(null)
	@:nativeName("_shape_set_data")
	public function _shape_set_data(shape:godot.RID, data:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_shape_set_custom_solver_bias")
	@:argMeta(1, ":meta"("float"))
	public function _shape_set_custom_solver_bias(shape:godot.RID, @:meta("float") bias:Float):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1240598777)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_type")
	public function _shape_get_type(shape:godot.RID):godot.PhysicsServer2D_ShapeType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4171304767.)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_data")
	public function _shape_get_data(shape:godot.RID):Dynamic;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_custom_solver_bias")
	public function _shape_get_custom_solver_bias(shape:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_space_create")
	public function _space_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_space_set_active")
	public function _space_set_active(space:godot.RID, active:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_space_is_active")
	public function _space_is_active(space:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(949194586)
	@:hash_compatibility(null)
	@:nativeName("_space_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _space_set_param(space:godot.RID, param:godot.PhysicsServer2D_SpaceParameter, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(874111783)
	@:hash_compatibility(null)
	@:nativeName("_space_get_param")
	public function _space_get_param(space:godot.RID, param:godot.PhysicsServer2D_SpaceParameter):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3160173886.)
	@:hash_compatibility(null)
	@:nativeName("_space_get_direct_state")
	public function _space_get_direct_state(space:godot.RID):godot.PhysicsDirectSpaceState2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_space_set_debug_contacts")
	@:argMeta(1, ":meta"("int32"))
	public function _space_set_debug_contacts(space:godot.RID, @:meta("int32") max_contacts:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2222557395.)
	@:hash_compatibility(null)
	@:nativeName("_space_get_contacts")
	public function _space_get_contacts(space:godot.RID):godot.PackedVector2Array;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_space_get_contact_count")
	public function _space_get_contact_count(space:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_area_create")
	public function _area_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_area_set_space")
	public function _area_set_space(area:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_space")
	public function _area_get_space(area:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(888317420)
	@:hash_compatibility(null)
	@:nativeName("_area_add_shape")
	public function _area_add_shape(area:godot.RID, shape:godot.RID, transform:godot.Transform2D, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _area_set_shape(area:godot.RID, @:meta("int32") shape_idx:Int, shape:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(736082694)
	@:hash_compatibility(null)
	@:nativeName("_area_set_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _area_set_shape_transform(area:godot.RID, @:meta("int32") shape_idx:Int, transform:godot.Transform2D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_shape_disabled")
	@:argMeta(1, ":meta"("int32"))
	public function _area_set_shape_disabled(area:godot.RID, @:meta("int32") shape_idx:Int, disabled:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_shape_count")
	public function _area_get_shape_count(area:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("_area_get_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _area_get_shape(area:godot.RID, @:meta("int32") shape_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1324854622)
	@:hash_compatibility(null)
	@:nativeName("_area_get_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _area_get_shape_transform(area:godot.RID, @:meta("int32") shape_idx:Int):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_remove_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _area_remove_shape(area:godot.RID, @:meta("int32") shape_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_area_clear_shapes")
	public function _area_clear_shapes(area:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_attach_object_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public function _area_attach_object_instance_id(area:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_object_instance_id")
	public function _area_get_object_instance_id(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_attach_canvas_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public function _area_attach_canvas_instance_id(area:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_canvas_instance_id")
	public function _area_get_canvas_instance_id(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1257146028)
	@:hash_compatibility(null)
	@:nativeName("_area_set_param")
	public function _area_set_param(area:godot.RID, param:godot.PhysicsServer2D_AreaParameter, value:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1246044741)
	@:hash_compatibility(null)
	@:nativeName("_area_set_transform")
	public function _area_set_transform(area:godot.RID, transform:godot.Transform2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3047435120.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_param")
	public function _area_get_param(area:godot.RID, param:godot.PhysicsServer2D_AreaParameter):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(213527486)
	@:hash_compatibility(null)
	@:nativeName("_area_get_transform")
	public function _area_get_transform(area:godot.RID):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public function _area_set_collision_layer(area:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_collision_layer")
	public function _area_get_collision_layer(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public function _area_set_collision_mask(area:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_collision_mask")
	public function _area_get_collision_mask(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_area_set_monitorable")
	public function _area_set_monitorable(area:godot.RID, monitorable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_area_set_pickable")
	public function _area_set_pickable(area:godot.RID, pickable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_monitor_callback")
	public function _area_set_monitor_callback(area:godot.RID, callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_area_monitor_callback")
	public function _area_set_area_monitor_callback(area:godot.RID, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_body_create")
	public function _body_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_body_set_space")
	public function _body_set_space(body:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_space")
	public function _body_get_space(body:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1658067650)
	@:hash_compatibility(null)
	@:nativeName("_body_set_mode")
	public function _body_set_mode(body:godot.RID, mode:godot.PhysicsServer2D_BodyMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3261702585.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_mode")
	public function _body_get_mode(body:godot.RID):godot.PhysicsServer2D_BodyMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(888317420)
	@:hash_compatibility(null)
	@:nativeName("_body_add_shape")
	public function _body_add_shape(body:godot.RID, shape:godot.RID, transform:godot.Transform2D, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_shape(body:godot.RID, @:meta("int32") shape_idx:Int, shape:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(736082694)
	@:hash_compatibility(null)
	@:nativeName("_body_set_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_shape_transform(body:godot.RID, @:meta("int32") shape_idx:Int, transform:godot.Transform2D):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_shape_count")
	public function _body_get_shape_count(body:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("_body_get_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _body_get_shape(body:godot.RID, @:meta("int32") shape_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1324854622)
	@:hash_compatibility(null)
	@:nativeName("_body_get_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _body_get_shape_transform(body:godot.RID, @:meta("int32") shape_idx:Int):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_shape_disabled")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_shape_disabled(body:godot.RID, @:meta("int32") shape_idx:Int, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2042146392)
	@:hash_compatibility([2556489974.])
	@:nativeName("_body_set_shape_as_one_way_collision")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(3, ":meta"("float"))
	public function _body_set_shape_as_one_way_collision(body:godot.RID, @:meta("int32") shape_idx:Int, enable:Bool, @:meta("float") margin:Float, direction:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_remove_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _body_remove_shape(body:godot.RID, @:meta("int32") shape_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_body_clear_shapes")
	public function _body_clear_shapes(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_attach_object_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public function _body_attach_object_instance_id(body:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_object_instance_id")
	public function _body_get_object_instance_id(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_attach_canvas_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public function _body_attach_canvas_instance_id(body:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_canvas_instance_id")
	public function _body_get_canvas_instance_id(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1882257015)
	@:hash_compatibility(null)
	@:nativeName("_body_set_continuous_collision_detection_mode")
	public function _body_set_continuous_collision_detection_mode(body:godot.RID, mode:godot.PhysicsServer2D_CCDMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2661282217.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_continuous_collision_detection_mode")
	public function _body_get_continuous_collision_detection_mode(body:godot.RID):godot.PhysicsServer2D_CCDMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public function _body_set_collision_layer(body:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_layer")
	public function _body_get_collision_layer(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public function _body_set_collision_mask(body:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_mask")
	public function _body_get_collision_mask(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_set_collision_priority")
	@:argMeta(1, ":meta"("float"))
	public function _body_set_collision_priority(body:godot.RID, @:meta("float") priority:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_priority")
	public function _body_get_collision_priority(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2715630609.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_param")
	public function _body_set_param(body:godot.RID, param:godot.PhysicsServer2D_BodyParameter, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3208033526.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_param")
	public function _body_get_param(body:godot.RID, param:godot.PhysicsServer2D_BodyParameter):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_body_reset_mass_properties")
	public function _body_reset_mass_properties(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1706355209)
	@:hash_compatibility(null)
	@:nativeName("_body_set_state")
	public function _body_set_state(body:godot.RID, state:godot.PhysicsServer2D_BodyState, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4036367961.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_state")
	public function _body_get_state(body:godot.RID, state:godot.PhysicsServer2D_BodyState):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_central_impulse")
	public function _body_apply_central_impulse(body:godot.RID, impulse:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_torque_impulse")
	@:argMeta(1, ":meta"("float"))
	public function _body_apply_torque_impulse(body:godot.RID, @:meta("float") impulse:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2762675110.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_impulse")
	public function _body_apply_impulse(body:godot.RID, impulse:godot.Vector2, position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_central_force")
	public function _body_apply_central_force(body:godot.RID, force:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2762675110.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_force")
	public function _body_apply_force(body:godot.RID, force:godot.Vector2, position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_torque")
	@:argMeta(1, ":meta"("float"))
	public function _body_apply_torque(body:godot.RID, @:meta("float") torque:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("_body_add_constant_central_force")
	public function _body_add_constant_central_force(body:godot.RID, force:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2762675110.)
	@:hash_compatibility(null)
	@:nativeName("_body_add_constant_force")
	public function _body_add_constant_force(body:godot.RID, force:godot.Vector2, position:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_add_constant_torque")
	@:argMeta(1, ":meta"("float"))
	public function _body_add_constant_torque(body:godot.RID, @:meta("float") torque:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_constant_force")
	public function _body_set_constant_force(body:godot.RID, force:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2440833711.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_constant_force")
	public function _body_get_constant_force(body:godot.RID):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_set_constant_torque")
	@:argMeta(1, ":meta"("float"))
	public function _body_set_constant_torque(body:godot.RID, @:meta("float") torque:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_body_get_constant_torque")
	public function _body_get_constant_torque(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3201125042.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_axis_velocity")
	public function _body_set_axis_velocity(body:godot.RID, axis_velocity:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_body_add_collision_exception")
	public function _body_add_collision_exception(body:godot.RID, excepted_body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_body_remove_collision_exception")
	public function _body_remove_collision_exception(body:godot.RID, excepted_body:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_exceptions")
	public function _body_get_collision_exceptions(body:godot.RID):Array<godot.RID>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_max_contacts_reported")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_max_contacts_reported(body:godot.RID, @:meta("int32") amount:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_max_contacts_reported")
	public function _body_get_max_contacts_reported(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_set_contacts_reported_depth_threshold")
	@:argMeta(1, ":meta"("float"))
	public function _body_set_contacts_reported_depth_threshold(body:godot.RID, @:meta("float") threshold:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_body_get_contacts_reported_depth_threshold")
	public function _body_get_contacts_reported_depth_threshold(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_body_set_omit_force_integration")
	public function _body_set_omit_force_integration(body:godot.RID, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_body_is_omitting_force_integration")
	public function _body_is_omitting_force_integration(body:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_state_sync_callback")
	public function _body_set_state_sync_callback(body:godot.RID, callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2828036238.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_force_integration_callback")
	public function _body_set_force_integration_callback(body:godot.RID, callable:godot.Callable, userdata:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_body_set_pickable")
	public function _body_set_pickable(body:godot.RID, pickable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1191931871)
	@:hash_compatibility(null)
	@:nativeName("_body_get_direct_state")
	public function _body_get_direct_state(body:godot.RID):godot.PhysicsDirectBodyState2D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_joint_create")
	public function _joint_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_joint_clear")
	public function _joint_clear(joint:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3972556514.)
	@:hash_compatibility(null)
	@:nativeName("_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _joint_set_param(joint:godot.RID, param:godot.PhysicsServer2D_JointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4016448949.)
	@:hash_compatibility(null)
	@:nativeName("_joint_get_param")
	public function _joint_get_param(joint:godot.RID, param:godot.PhysicsServer2D_JointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_joint_disable_collisions_between_bodies")
	public function _joint_disable_collisions_between_bodies(joint:godot.RID, disable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_joint_is_disabled_collisions_between_bodies")
	public function _joint_is_disabled_collisions_between_bodies(joint:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2607799521.)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_pin")
	public function _joint_make_pin(joint:godot.RID, anchor:godot.Vector2, body_a:godot.RID, body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(438649616)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_groove")
	public function _joint_make_groove(joint:godot.RID, a_groove1:godot.Vector2, a_groove2:godot.Vector2, b_anchor:godot.Vector2, body_a:godot.RID, body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1276049561)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_damped_spring")
	public function _joint_make_damped_spring(joint:godot.RID, anchor_a:godot.Vector2, anchor_b:godot.Vector2, body_a:godot.RID, body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3520002352.)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_set_flag")
	public function _pin_joint_set_flag(joint:godot.RID, flag:godot.PhysicsServer2D_PinJointFlag, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2647867364.)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_get_flag")
	public function _pin_joint_get_flag(joint:godot.RID, flag:godot.PhysicsServer2D_PinJointFlag):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(550574241)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _pin_joint_set_param(joint:godot.RID, param:godot.PhysicsServer2D_PinJointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(348281383)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_get_param")
	public function _pin_joint_get_param(joint:godot.RID, param:godot.PhysicsServer2D_PinJointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(220564071)
	@:hash_compatibility(null)
	@:nativeName("_damped_spring_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _damped_spring_joint_set_param(joint:godot.RID, param:godot.PhysicsServer2D_DampedSpringParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2075871277)
	@:hash_compatibility(null)
	@:nativeName("_damped_spring_joint_get_param")
	public function _damped_spring_joint_get_param(joint:godot.RID, param:godot.PhysicsServer2D_DampedSpringParam):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4262502231.)
	@:hash_compatibility(null)
	@:nativeName("_joint_get_type")
	public function _joint_get_type(joint:godot.RID):godot.PhysicsServer2D_JointType;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_free_rid")
	public function _free_rid(rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_set_active")
	public function _set_active(active:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_init")
	public function _init():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_step")
	@:argMeta(0, ":meta"("float"))
	public function _step(@:meta("float") step:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_sync")
	public function _sync():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_flush_queries")
	public function _flush_queries():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_end_sync")
	public function _end_sync():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_finish")
	public function _finish():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_flushing_queries")
	public function _is_flushing_queries():Bool;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(576496006)
	@:hash_compatibility(null)
	@:nativeName("_get_process_info")
	public function _get_process_info(process_info:godot.PhysicsServer2D_ProcessInfo):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("body_test_motion_is_excluding_body")
	public function body_test_motion_is_excluding_body(body:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("body_test_motion_is_excluding_object")
	@:argMeta(0, ":meta"("uint64"))
	public function body_test_motion_is_excluding_object(@:meta("uint64") object:Int):Bool;
}