/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("PhysicsServer3D.SliderJointParam") #end @:is_bitfield(false) extern enum PhysicsServer3D_SliderJointParam {
	SLIDER_JOINT_LINEAR_LIMIT_UPPER();
	SLIDER_JOINT_LINEAR_LIMIT_LOWER();
	SLIDER_JOINT_LINEAR_LIMIT_SOFTNESS();
	SLIDER_JOINT_LINEAR_LIMIT_RESTITUTION();
	SLIDER_JOINT_LINEAR_LIMIT_DAMPING();
	SLIDER_JOINT_LINEAR_MOTION_SOFTNESS();
	SLIDER_JOINT_LINEAR_MOTION_RESTITUTION();
	SLIDER_JOINT_LINEAR_MOTION_DAMPING();
	SLIDER_JOINT_LINEAR_ORTHOGONAL_SOFTNESS();
	SLIDER_JOINT_LINEAR_ORTHOGONAL_RESTITUTION();
	SLIDER_JOINT_LINEAR_ORTHOGONAL_DAMPING();
	SLIDER_JOINT_ANGULAR_LIMIT_UPPER();
	SLIDER_JOINT_ANGULAR_LIMIT_LOWER();
	SLIDER_JOINT_ANGULAR_LIMIT_SOFTNESS();
	SLIDER_JOINT_ANGULAR_LIMIT_RESTITUTION();
	SLIDER_JOINT_ANGULAR_LIMIT_DAMPING();
	SLIDER_JOINT_ANGULAR_MOTION_SOFTNESS();
	SLIDER_JOINT_ANGULAR_MOTION_RESTITUTION();
	SLIDER_JOINT_ANGULAR_MOTION_DAMPING();
	SLIDER_JOINT_ANGULAR_ORTHOGONAL_SOFTNESS();
	SLIDER_JOINT_ANGULAR_ORTHOGONAL_RESTITUTION();
	SLIDER_JOINT_ANGULAR_ORTHOGONAL_DAMPING();
	SLIDER_JOINT_MAX();
}