/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class PhysicsServer3DExtension extends godot.PhysicsServer3D {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_world_boundary_shape_create")
	public function _world_boundary_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_separation_ray_shape_create")
	public function _separation_ray_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_sphere_shape_create")
	public function _sphere_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_box_shape_create")
	public function _box_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_capsule_shape_create")
	public function _capsule_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_cylinder_shape_create")
	public function _cylinder_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_convex_polygon_shape_create")
	public function _convex_polygon_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_concave_polygon_shape_create")
	public function _concave_polygon_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_heightmap_shape_create")
	public function _heightmap_shape_create():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_custom_shape_create")
	public function _custom_shape_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3175752987.)
	@:hash_compatibility(null)
	@:nativeName("_shape_set_data")
	public function _shape_set_data(shape:godot.RID, data:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_shape_set_custom_solver_bias")
	@:argMeta(1, ":meta"("float"))
	public function _shape_set_custom_solver_bias(shape:godot.RID, @:meta("float") bias:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_shape_set_margin")
	@:argMeta(1, ":meta"("float"))
	public function _shape_set_margin(shape:godot.RID, @:meta("float") margin:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_margin")
	public function _shape_get_margin(shape:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3418923367.)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_type")
	public function _shape_get_type(shape:godot.RID):godot.PhysicsServer3D_ShapeType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4171304767.)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_data")
	public function _shape_get_data(shape:godot.RID):Dynamic;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shape_get_custom_solver_bias")
	public function _shape_get_custom_solver_bias(shape:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_space_create")
	public function _space_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_space_set_active")
	public function _space_set_active(space:godot.RID, active:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_space_is_active")
	public function _space_is_active(space:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2406017470.)
	@:hash_compatibility(null)
	@:nativeName("_space_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _space_set_param(space:godot.RID, param:godot.PhysicsServer3D_SpaceParameter, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1523206731)
	@:hash_compatibility(null)
	@:nativeName("_space_get_param")
	public function _space_get_param(space:godot.RID, param:godot.PhysicsServer3D_SpaceParameter):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2048616813)
	@:hash_compatibility(null)
	@:nativeName("_space_get_direct_state")
	public function _space_get_direct_state(space:godot.RID):godot.PhysicsDirectSpaceState3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_space_set_debug_contacts")
	@:argMeta(1, ":meta"("int32"))
	public function _space_set_debug_contacts(space:godot.RID, @:meta("int32") max_contacts:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(808965560)
	@:hash_compatibility(null)
	@:nativeName("_space_get_contacts")
	public function _space_get_contacts(space:godot.RID):godot.PackedVector3Array;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_space_get_contact_count")
	public function _space_get_contact_count(space:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_area_create")
	public function _area_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_area_set_space")
	public function _area_set_space(area:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_space")
	public function _area_get_space(area:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2153848567.)
	@:hash_compatibility(null)
	@:nativeName("_area_add_shape")
	public function _area_add_shape(area:godot.RID, shape:godot.RID, transform:godot.Transform3D, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _area_set_shape(area:godot.RID, @:meta("int32") shape_idx:Int, shape:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(675327471)
	@:hash_compatibility(null)
	@:nativeName("_area_set_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _area_set_shape_transform(area:godot.RID, @:meta("int32") shape_idx:Int, transform:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_shape_disabled")
	@:argMeta(1, ":meta"("int32"))
	public function _area_set_shape_disabled(area:godot.RID, @:meta("int32") shape_idx:Int, disabled:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_shape_count")
	public function _area_get_shape_count(area:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("_area_get_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _area_get_shape(area:godot.RID, @:meta("int32") shape_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1050775521)
	@:hash_compatibility(null)
	@:nativeName("_area_get_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _area_get_shape_transform(area:godot.RID, @:meta("int32") shape_idx:Int):godot.Transform3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_remove_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _area_remove_shape(area:godot.RID, @:meta("int32") shape_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_area_clear_shapes")
	public function _area_clear_shapes(area:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_attach_object_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public function _area_attach_object_instance_id(area:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_object_instance_id")
	public function _area_get_object_instance_id(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2980114638.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_param")
	public function _area_set_param(area:godot.RID, param:godot.PhysicsServer3D_AreaParameter, value:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3935195649.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_transform")
	public function _area_set_transform(area:godot.RID, transform:godot.Transform3D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(890056067)
	@:hash_compatibility(null)
	@:nativeName("_area_get_param")
	public function _area_get_param(area:godot.RID, param:godot.PhysicsServer3D_AreaParameter):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1128465797)
	@:hash_compatibility(null)
	@:nativeName("_area_get_transform")
	public function _area_get_transform(area:godot.RID):godot.Transform3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public function _area_set_collision_layer(area:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_collision_layer")
	public function _area_get_collision_layer(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public function _area_set_collision_mask(area:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_area_get_collision_mask")
	public function _area_get_collision_mask(area:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_area_set_monitorable")
	public function _area_set_monitorable(area:godot.RID, monitorable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_area_set_ray_pickable")
	public function _area_set_ray_pickable(area:godot.RID, enable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_monitor_callback")
	public function _area_set_monitor_callback(area:godot.RID, callback:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("_area_set_area_monitor_callback")
	public function _area_set_area_monitor_callback(area:godot.RID, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_body_create")
	public function _body_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_body_set_space")
	public function _body_set_space(body:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_space")
	public function _body_get_space(body:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(606803466)
	@:hash_compatibility(null)
	@:nativeName("_body_set_mode")
	public function _body_set_mode(body:godot.RID, mode:godot.PhysicsServer3D_BodyMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2488819728.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_mode")
	public function _body_get_mode(body:godot.RID):godot.PhysicsServer3D_BodyMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2153848567.)
	@:hash_compatibility(null)
	@:nativeName("_body_add_shape")
	public function _body_add_shape(body:godot.RID, shape:godot.RID, transform:godot.Transform3D, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2310537182.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_shape(body:godot.RID, @:meta("int32") shape_idx:Int, shape:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(675327471)
	@:hash_compatibility(null)
	@:nativeName("_body_set_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_shape_transform(body:godot.RID, @:meta("int32") shape_idx:Int, transform:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_shape_disabled")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_shape_disabled(body:godot.RID, @:meta("int32") shape_idx:Int, disabled:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_shape_count")
	public function _body_get_shape_count(body:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("_body_get_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _body_get_shape(body:godot.RID, @:meta("int32") shape_idx:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1050775521)
	@:hash_compatibility(null)
	@:nativeName("_body_get_shape_transform")
	@:argMeta(1, ":meta"("int32"))
	public function _body_get_shape_transform(body:godot.RID, @:meta("int32") shape_idx:Int):godot.Transform3D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_remove_shape")
	@:argMeta(1, ":meta"("int32"))
	public function _body_remove_shape(body:godot.RID, @:meta("int32") shape_idx:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_body_clear_shapes")
	public function _body_clear_shapes(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_attach_object_instance_id")
	@:argMeta(1, ":meta"("uint64"))
	public function _body_attach_object_instance_id(body:godot.RID, @:meta("uint64") id:Int):Void;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_object_instance_id")
	public function _body_get_object_instance_id(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_body_set_enable_continuous_collision_detection")
	public function _body_set_enable_continuous_collision_detection(body:godot.RID, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_body_is_continuous_collision_detection_enabled")
	public function _body_is_continuous_collision_detection_enabled(body:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public function _body_set_collision_layer(body:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_layer")
	public function _body_get_collision_layer(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public function _body_set_collision_mask(body:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_mask")
	public function _body_get_collision_mask(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_set_collision_priority")
	@:argMeta(1, ":meta"("float"))
	public function _body_set_collision_priority(body:godot.RID, @:meta("float") priority:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_priority")
	public function _body_get_collision_priority(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_user_flags")
	@:argMeta(1, ":meta"("uint32"))
	public function _body_set_user_flags(body:godot.RID, @:meta("uint32") flags:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_user_flags")
	public function _body_get_user_flags(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(910941953)
	@:hash_compatibility(null)
	@:nativeName("_body_set_param")
	public function _body_set_param(body:godot.RID, param:godot.PhysicsServer3D_BodyParameter, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3385027841.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_param")
	public function _body_get_param(body:godot.RID, param:godot.PhysicsServer3D_BodyParameter):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_body_reset_mass_properties")
	public function _body_reset_mass_properties(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(599977762)
	@:hash_compatibility(null)
	@:nativeName("_body_set_state")
	public function _body_set_state(body:godot.RID, state:godot.PhysicsServer3D_BodyState, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1850449534)
	@:hash_compatibility(null)
	@:nativeName("_body_get_state")
	public function _body_get_state(body:godot.RID, state:godot.PhysicsServer3D_BodyState):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_central_impulse")
	public function _body_apply_central_impulse(body:godot.RID, impulse:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3214966418.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_impulse")
	public function _body_apply_impulse(body:godot.RID, impulse:godot.Vector3, position:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_torque_impulse")
	public function _body_apply_torque_impulse(body:godot.RID, impulse:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_central_force")
	public function _body_apply_central_force(body:godot.RID, force:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3214966418.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_force")
	public function _body_apply_force(body:godot.RID, force:godot.Vector3, position:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_apply_torque")
	public function _body_apply_torque(body:godot.RID, torque:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_add_constant_central_force")
	public function _body_add_constant_central_force(body:godot.RID, force:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3214966418.)
	@:hash_compatibility(null)
	@:nativeName("_body_add_constant_force")
	public function _body_add_constant_force(body:godot.RID, force:godot.Vector3, position:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_add_constant_torque")
	public function _body_add_constant_torque(body:godot.RID, torque:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_constant_force")
	public function _body_set_constant_force(body:godot.RID, force:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("_body_get_constant_force")
	public function _body_get_constant_force(body:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_constant_torque")
	public function _body_set_constant_torque(body:godot.RID, torque:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("_body_get_constant_torque")
	public function _body_get_constant_torque(body:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_axis_velocity")
	public function _body_set_axis_velocity(body:godot.RID, axis_velocity:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2020836892)
	@:hash_compatibility(null)
	@:nativeName("_body_set_axis_lock")
	public function _body_set_axis_lock(body:godot.RID, axis:godot.PhysicsServer3D_BodyAxis, lock:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(587853580)
	@:hash_compatibility(null)
	@:nativeName("_body_is_axis_locked")
	public function _body_is_axis_locked(body:godot.RID, axis:godot.PhysicsServer3D_BodyAxis):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_body_add_collision_exception")
	public function _body_add_collision_exception(body:godot.RID, excepted_body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_body_remove_collision_exception")
	public function _body_remove_collision_exception(body:godot.RID, excepted_body:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_collision_exceptions")
	public function _body_get_collision_exceptions(body:godot.RID):Array<godot.RID>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_max_contacts_reported")
	@:argMeta(1, ":meta"("int32"))
	public function _body_set_max_contacts_reported(body:godot.RID, @:meta("int32") amount:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_max_contacts_reported")
	public function _body_get_max_contacts_reported(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_body_set_contacts_reported_depth_threshold")
	@:argMeta(1, ":meta"("float"))
	public function _body_set_contacts_reported_depth_threshold(body:godot.RID, @:meta("float") threshold:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_body_get_contacts_reported_depth_threshold")
	public function _body_get_contacts_reported_depth_threshold(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_body_set_omit_force_integration")
	public function _body_set_omit_force_integration(body:godot.RID, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_body_is_omitting_force_integration")
	public function _body_is_omitting_force_integration(body:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3379118538.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_state_sync_callback")
	public function _body_set_state_sync_callback(body:godot.RID, callable:godot.Callable):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2828036238.)
	@:hash_compatibility(null)
	@:nativeName("_body_set_force_integration_callback")
	public function _body_set_force_integration_callback(body:godot.RID, callable:godot.Callable, userdata:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_body_set_ray_pickable")
	public function _body_set_ray_pickable(body:godot.RID, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3029727957.)
	@:hash_compatibility(null)
	@:nativeName("_body_get_direct_state")
	public function _body_get_direct_state(body:godot.RID):godot.PhysicsDirectBodyState3D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_create")
	public function _soft_body_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2218179753.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_update_rendering_server")
	@:argMeta(1, ":meta"("required"))
	public function _soft_body_update_rendering_server(body:godot.RID, @:meta("required") rendering_server_handler:godot.PhysicsServer3DRenderingServerHandler):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_space")
	public function _soft_body_set_space(body:godot.RID, space:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_space")
	public function _soft_body_get_space(body:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_ray_pickable")
	public function _soft_body_set_ray_pickable(body:godot.RID, enable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_collision_layer")
	@:argMeta(1, ":meta"("uint32"))
	public function _soft_body_set_collision_layer(body:godot.RID, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_collision_layer")
	public function _soft_body_get_collision_layer(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_collision_mask")
	@:argMeta(1, ":meta"("uint32"))
	public function _soft_body_set_collision_mask(body:godot.RID, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_collision_mask")
	public function _soft_body_get_collision_mask(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_add_collision_exception")
	public function _soft_body_add_collision_exception(body:godot.RID, body_b:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_remove_collision_exception")
	public function _soft_body_remove_collision_exception(body:godot.RID, body_b:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_collision_exceptions")
	public function _soft_body_get_collision_exceptions(body:godot.RID):Array<godot.RID>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(599977762)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_state")
	public function _soft_body_set_state(body:godot.RID, state:godot.PhysicsServer3D_BodyState, variant:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1850449534)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_state")
	public function _soft_body_get_state(body:godot.RID, state:godot.PhysicsServer3D_BodyState):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3935195649.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_transform")
	public function _soft_body_set_transform(body:godot.RID, transform:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_simulation_precision")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_set_simulation_precision(body:godot.RID, @:meta("int32") simulation_precision:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_simulation_precision")
	public function _soft_body_get_simulation_precision(body:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_total_mass")
	@:argMeta(1, ":meta"("float"))
	public function _soft_body_set_total_mass(body:godot.RID, @:meta("float") total_mass:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_total_mass")
	public function _soft_body_get_total_mass(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_linear_stiffness")
	@:argMeta(1, ":meta"("float"))
	public function _soft_body_set_linear_stiffness(body:godot.RID, @:meta("float") linear_stiffness:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_linear_stiffness")
	public function _soft_body_get_linear_stiffness(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_shrinking_factor")
	@:argMeta(1, ":meta"("float"))
	public function _soft_body_set_shrinking_factor(body:godot.RID, @:meta("float") shrinking_factor:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_shrinking_factor")
	public function _soft_body_get_shrinking_factor(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_pressure_coefficient")
	@:argMeta(1, ":meta"("float"))
	public function _soft_body_set_pressure_coefficient(body:godot.RID, @:meta("float") pressure_coefficient:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_pressure_coefficient")
	public function _soft_body_get_pressure_coefficient(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_damping_coefficient")
	@:argMeta(1, ":meta"("float"))
	public function _soft_body_set_damping_coefficient(body:godot.RID, @:meta("float") damping_coefficient:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_damping_coefficient")
	public function _soft_body_get_damping_coefficient(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_drag_coefficient")
	@:argMeta(1, ":meta"("float"))
	public function _soft_body_set_drag_coefficient(body:godot.RID, @:meta("float") drag_coefficient:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_drag_coefficient")
	public function _soft_body_get_drag_coefficient(body:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(395945892)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_set_mesh")
	public function _soft_body_set_mesh(body:godot.RID, mesh:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(974181306)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_bounds")
	public function _soft_body_get_bounds(body:godot.RID):godot.AABB;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(831953689)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_move_point")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_move_point(body:godot.RID, @:meta("int32") point_index:Int, global_position:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3440143363.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_get_point_global_position")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_get_point_global_position(body:godot.RID, @:meta("int32") point_index:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_remove_all_pinned_points")
	public function _soft_body_remove_all_pinned_points(body:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2658558584.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_pin_point")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_pin_point(body:godot.RID, @:meta("int32") point_index:Int, pin:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_is_point_pinned")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_is_point_pinned(body:godot.RID, @:meta("int32") point_index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(831953689)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_apply_point_impulse")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_apply_point_impulse(body:godot.RID, @:meta("int32") point_index:Int, impulse:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(831953689)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_apply_point_force")
	@:argMeta(1, ":meta"("int32"))
	public function _soft_body_apply_point_force(body:godot.RID, @:meta("int32") point_index:Int, force:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_apply_central_impulse")
	public function _soft_body_apply_central_impulse(body:godot.RID, impulse:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_soft_body_apply_central_force")
	public function _soft_body_apply_central_force(body:godot.RID, force:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_joint_create")
	public function _joint_create():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_joint_clear")
	public function _joint_clear(joint:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4280171926.)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_pin")
	public function _joint_make_pin(joint:godot.RID, body_A:godot.RID, local_A:godot.Vector3, body_B:godot.RID, local_B:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(810685294)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _pin_joint_set_param(joint:godot.RID, param:godot.PhysicsServer3D_PinJointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2817972347.)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_get_param")
	public function _pin_joint_get_param(joint:godot.RID, param:godot.PhysicsServer3D_PinJointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_set_local_a")
	public function _pin_joint_set_local_a(joint:godot.RID, local_A:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_get_local_a")
	public function _pin_joint_get_local_a(joint:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3227306858.)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_set_local_b")
	public function _pin_joint_set_local_b(joint:godot.RID, local_B:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(531438156)
	@:hash_compatibility(null)
	@:nativeName("_pin_joint_get_local_b")
	public function _pin_joint_get_local_b(joint:godot.RID):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1684107643)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_hinge")
	public function _joint_make_hinge(joint:godot.RID, body_A:godot.RID, hinge_A:godot.Transform3D, body_B:godot.RID, hinge_B:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069547571.)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_hinge_simple")
	public function _joint_make_hinge_simple(joint:godot.RID, body_A:godot.RID, pivot_A:godot.Vector3, axis_A:godot.Vector3, body_B:godot.RID, pivot_B:godot.Vector3, axis_B:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3165502333.)
	@:hash_compatibility(null)
	@:nativeName("_hinge_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _hinge_joint_set_param(joint:godot.RID, param:godot.PhysicsServer3D_HingeJointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2129207581)
	@:hash_compatibility(null)
	@:nativeName("_hinge_joint_get_param")
	public function _hinge_joint_get_param(joint:godot.RID, param:godot.PhysicsServer3D_HingeJointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1601626188)
	@:hash_compatibility(null)
	@:nativeName("_hinge_joint_set_flag")
	public function _hinge_joint_set_flag(joint:godot.RID, flag:godot.PhysicsServer3D_HingeJointFlag, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4165147865.)
	@:hash_compatibility(null)
	@:nativeName("_hinge_joint_get_flag")
	public function _hinge_joint_get_flag(joint:godot.RID, flag:godot.PhysicsServer3D_HingeJointFlag):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1684107643)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_slider")
	public function _joint_make_slider(joint:godot.RID, body_A:godot.RID, local_ref_A:godot.Transform3D, body_B:godot.RID, local_ref_B:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2264833593.)
	@:hash_compatibility(null)
	@:nativeName("_slider_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _slider_joint_set_param(joint:godot.RID, param:godot.PhysicsServer3D_SliderJointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3498644957.)
	@:hash_compatibility(null)
	@:nativeName("_slider_joint_get_param")
	public function _slider_joint_get_param(joint:godot.RID, param:godot.PhysicsServer3D_SliderJointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1684107643)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_cone_twist")
	public function _joint_make_cone_twist(joint:godot.RID, body_A:godot.RID, local_ref_A:godot.Transform3D, body_B:godot.RID, local_ref_B:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(808587618)
	@:hash_compatibility(null)
	@:nativeName("_cone_twist_joint_set_param")
	@:argMeta(2, ":meta"("float"))
	public function _cone_twist_joint_set_param(joint:godot.RID, param:godot.PhysicsServer3D_ConeTwistJointParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1134789658)
	@:hash_compatibility(null)
	@:nativeName("_cone_twist_joint_get_param")
	public function _cone_twist_joint_get_param(joint:godot.RID, param:godot.PhysicsServer3D_ConeTwistJointParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1684107643)
	@:hash_compatibility(null)
	@:nativeName("_joint_make_generic_6dof")
	public function _joint_make_generic_6dof(joint:godot.RID, body_A:godot.RID, local_ref_A:godot.Transform3D, body_B:godot.RID, local_ref_B:godot.Transform3D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2600081391.)
	@:hash_compatibility(null)
	@:nativeName("_generic_6dof_joint_set_param")
	@:argMeta(3, ":meta"("float"))
	public function _generic_6dof_joint_set_param(joint:godot.RID, axis:godot.Vector3_Axis, param:godot.PhysicsServer3D_G6DOFJointAxisParam, @:meta("float") value:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(467122058)
	@:hash_compatibility(null)
	@:nativeName("_generic_6dof_joint_get_param")
	public function _generic_6dof_joint_get_param(joint:godot.RID, axis:godot.Vector3_Axis, param:godot.PhysicsServer3D_G6DOFJointAxisParam):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3570926903.)
	@:hash_compatibility(null)
	@:nativeName("_generic_6dof_joint_set_flag")
	public function _generic_6dof_joint_set_flag(joint:godot.RID, axis:godot.Vector3_Axis, flag:godot.PhysicsServer3D_G6DOFJointAxisFlag, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4158090196.)
	@:hash_compatibility(null)
	@:nativeName("_generic_6dof_joint_get_flag")
	public function _generic_6dof_joint_get_flag(joint:godot.RID, axis:godot.Vector3_Axis, flag:godot.PhysicsServer3D_G6DOFJointAxisFlag):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4290791900.)
	@:hash_compatibility(null)
	@:nativeName("_joint_get_type")
	public function _joint_get_type(joint:godot.RID):godot.PhysicsServer3D_JointType;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_joint_set_solver_priority")
	@:argMeta(1, ":meta"("int32"))
	public function _joint_set_solver_priority(joint:godot.RID, @:meta("int32") priority:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_joint_get_solver_priority")
	public function _joint_get_solver_priority(joint:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_joint_disable_collisions_between_bodies")
	public function _joint_disable_collisions_between_bodies(joint:godot.RID, disable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_joint_is_disabled_collisions_between_bodies")
	public function _joint_is_disabled_collisions_between_bodies(joint:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_free_rid")
	public function _free_rid(rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_set_active")
	public function _set_active(active:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_init")
	public function _init():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_step")
	@:argMeta(0, ":meta"("float"))
	public function _step(@:meta("float") step:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_sync")
	public function _sync():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_flush_queries")
	public function _flush_queries():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_end_sync")
	public function _end_sync():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_finish")
	public function _finish():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_flushing_queries")
	public function _is_flushing_queries():Bool;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1332958745)
	@:hash_compatibility(null)
	@:nativeName("_get_process_info")
	public function _get_process_info(process_info:godot.PhysicsServer3D_ProcessInfo):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("body_test_motion_is_excluding_body")
	public function body_test_motion_is_excluding_body(body:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("body_test_motion_is_excluding_object")
	@:argMeta(0, ":meta"("uint64"))
	public function body_test_motion_is_excluding_object(@:meta("uint64") object:Int):Bool;
}