/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("RenderingDevice.DriverResource") #end @:is_bitfield(false) extern enum RenderingDevice_DriverResource {
	DRIVER_RESOURCE_LOGICAL_DEVICE();
	DRIVER_RESOURCE_PHYSICAL_DEVICE();
	DRIVER_RESOURCE_TOPMOST_OBJECT();
	DRIVER_RESOURCE_COMMAND_QUEUE();
	DRIVER_RESOURCE_QUEUE_FAMILY();
	DRIVER_RESOURCE_TEXTURE();
	DRIVER_RESOURCE_TEXTURE_VIEW();
	DRIVER_RESOURCE_TEXTURE_DATA_FORMAT();
	DRIVER_RESOURCE_SAMPLER();
	DRIVER_RESOURCE_UNIFORM_SET();
	DRIVER_RESOURCE_BUFFER();
	DRIVER_RESOURCE_COMPUTE_PIPELINE();
	DRIVER_RESOURCE_RENDER_PIPELINE();
	DRIVER_RESOURCE_VULKAN_DEVICE();
	DRIVER_RESOURCE_VULKAN_PHYSICAL_DEVICE();
	DRIVER_RESOURCE_VULKAN_INSTANCE();
	DRIVER_RESOURCE_VULKAN_QUEUE();
	DRIVER_RESOURCE_VULKAN_QUEUE_FAMILY_INDEX();
	DRIVER_RESOURCE_VULKAN_IMAGE();
	DRIVER_RESOURCE_VULKAN_IMAGE_VIEW();
	DRIVER_RESOURCE_VULKAN_IMAGE_NATIVE_TEXTURE_FORMAT();
	DRIVER_RESOURCE_VULKAN_SAMPLER();
	DRIVER_RESOURCE_VULKAN_DESCRIPTOR_SET();
	DRIVER_RESOURCE_VULKAN_BUFFER();
	DRIVER_RESOURCE_VULKAN_COMPUTE_PIPELINE();
	DRIVER_RESOURCE_VULKAN_RENDER_PIPELINE();
}