/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class RenderSceneBuffersRD extends godot.RenderSceneBuffers {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_texture")
	public function has_texture(context:godot.StringName, name:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2950875024.)
	@:hash_compatibility([3559915770.])
	@:nativeName("create_texture")
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(6, ":meta"("uint32"))
	@:argMeta(7, ":meta"("uint32"))
	public function create_texture(context:godot.StringName, name:godot.StringName, data_format:godot.RenderingDevice_DataFormat, @:meta("uint32") usage_bits:Int, texture_samples:godot.RenderingDevice_TextureSamples, size:godot.Vector2i, @:meta("uint32") layers:Int, @:meta("uint32") mipmaps:Int, unique:Bool, discardable:Bool):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3344669382.)
	@:hash_compatibility(null)
	@:nativeName("create_texture_from_format")
	public function create_texture_from_format(context:godot.StringName, name:godot.StringName, format:godot.RDTextureFormat, view:godot.RDTextureView, unique:Bool):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(283055834)
	@:hash_compatibility(null)
	@:nativeName("create_texture_view")
	public function create_texture_view(context:godot.StringName, name:godot.StringName, view_name:godot.StringName, view:godot.RDTextureView):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(750006389)
	@:hash_compatibility(null)
	@:nativeName("get_texture")
	public function get_texture(context:godot.StringName, name:godot.StringName):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(371461758)
	@:hash_compatibility(null)
	@:nativeName("get_texture_format")
	public function get_texture_format(context:godot.StringName, name:godot.StringName):godot.RDTextureFormat;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(588440706)
	@:hash_compatibility(null)
	@:nativeName("get_texture_slice")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(5, ":meta"("uint32"))
	public function get_texture_slice(context:godot.StringName, name:godot.StringName, @:meta("uint32") layer:Int, @:meta("uint32") mipmap:Int, @:meta("uint32") layers:Int, @:meta("uint32") mipmaps:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(682451778)
	@:hash_compatibility(null)
	@:nativeName("get_texture_slice_view")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(5, ":meta"("uint32"))
	public function get_texture_slice_view(context:godot.StringName, name:godot.StringName, @:meta("uint32") layer:Int, @:meta("uint32") mipmap:Int, @:meta("uint32") layers:Int, @:meta("uint32") mipmaps:Int, view:godot.RDTextureView):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2617625368.)
	@:hash_compatibility(null)
	@:nativeName("get_texture_slice_size")
	@:argMeta(2, ":meta"("uint32"))
	public function get_texture_slice_size(context:godot.StringName, name:godot.StringName, @:meta("uint32") mipmap:Int):godot.Vector2i;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("clear_context")
	public function clear_context(context:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3050822880.)
	@:hash_compatibility([529393457])
	@:nativeName("get_color_texture")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_color_texture(@:default_value("false") #if gdscript @:noNullPad("false") #end msaa:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3087988589.)
	@:hash_compatibility([937000113])
	@:nativeName("get_color_layer")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function get_color_layer(@:meta("uint32") layer:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end msaa:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3050822880.)
	@:hash_compatibility([529393457])
	@:nativeName("get_depth_texture")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_depth_texture(@:default_value("false") #if gdscript @:noNullPad("false") #end msaa:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3087988589.)
	@:hash_compatibility([937000113])
	@:nativeName("get_depth_layer")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function get_depth_layer(@:meta("uint32") layer:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end msaa:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3050822880.)
	@:hash_compatibility([529393457])
	@:nativeName("get_velocity_texture")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_velocity_texture(@:default_value("false") #if gdscript @:noNullPad("false") #end msaa:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3087988589.)
	@:hash_compatibility([937000113])
	@:nativeName("get_velocity_layer")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function get_velocity_layer(@:meta("uint32") layer:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end msaa:Bool = false):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2944877500.)
	@:hash_compatibility(null)
	@:nativeName("get_render_target")
	public function get_render_target():godot.RID;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_view_count")
	public function get_view_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3690982128.)
	@:hash_compatibility(null)
	@:nativeName("get_internal_size")
	public function get_internal_size():godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3690982128.)
	@:hash_compatibility(null)
	@:nativeName("get_target_size")
	public function get_target_size():godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(976778074)
	@:hash_compatibility(null)
	@:nativeName("get_scaling_3d_mode")
	public function get_scaling_3d_mode():godot.RenderingServer_ViewportScaling3DMode;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_fsr_sharpness")
	public function get_fsr_sharpness():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3109158617.)
	@:hash_compatibility(null)
	@:nativeName("get_msaa_3d")
	public function get_msaa_3d():godot.RenderingServer_ViewportMSAA;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(407791724)
	@:hash_compatibility(null)
	@:nativeName("get_texture_samples")
	public function get_texture_samples():godot.RenderingDevice_TextureSamples;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(641513172)
	@:hash_compatibility(null)
	@:nativeName("get_screen_space_aa")
	public function get_screen_space_aa():godot.RenderingServer_ViewportScreenSpaceAA;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("get_use_taa")
	public function get_use_taa():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("get_use_debanding")
	public function get_use_debanding():Bool;
}