/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("core") @:is_resource(false) @:is_node(false) extern class RenderingDevice extends godot.Object {
	public function new();
	public static var INVALID_ID : Int;
	public static var INVALID_FORMAT_ID : Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3709173589.)
	@:hash_compatibility([3011278298.])
	@:nativeName("texture_create")
	@:argMeta(2, ":default_value"("[]"))
	#if gdscript @:argMeta(2, ":noNullPad"("[]")) #end
	public function texture_create(format:godot.RDTextureFormat, view:godot.RDTextureView, @:default_value("[]") #if gdscript @:noNullPad("[]") #end ?data:Array<godot.PackedByteArray>):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3178156134.)
	@:hash_compatibility(null)
	@:nativeName("texture_create_shared")
	public function texture_create_shared(view:godot.RDTextureView, with_texture:godot.RID):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1808971279)
	@:hash_compatibility([864132525])
	@:nativeName("texture_create_shared_from_slice")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(4, ":default_value"("1"))
	#if gdscript @:argMeta(4, ":noNullPad"("1")) #end
	@:argMeta(5, ":default_value"("RenderingDevice.TextureSliceType.TEXTURE_SLICE_2D"))
	#if gdscript @:argMeta(5, ":noNullPad"("RenderingDevice.TextureSliceType.TEXTURE_SLICE_2D")) #end
	public function texture_create_shared_from_slice(view:godot.RDTextureView, with_texture:godot.RID, @:meta("uint32") layer:Int, @:meta("uint32") mipmap:Int, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end mipmaps:Int = 1, @:default_value("RenderingDevice.TextureSliceType.TEXTURE_SLICE_2D") #if gdscript @:noNullPad("RenderingDevice.TextureSliceType.TEXTURE_SLICE_2D") #end slice_type:godot.RenderingDevice_TextureSliceType = godot.RenderingDevice_TextureSliceType.TEXTURE_SLICE_2D):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3732868568.)
	@:hash_compatibility([1397171480])
	@:nativeName("texture_create_from_extension")
	@:argMeta(4, ":meta"("uint64"))
	@:argMeta(5, ":meta"("uint64"))
	@:argMeta(6, ":meta"("uint64"))
	@:argMeta(7, ":meta"("uint64"))
	@:argMeta(8, ":meta"("uint64"))
	@:argMeta(9, ":meta"("uint64"))
	@:argMeta(9, ":default_value"("1"))
	#if gdscript @:argMeta(9, ":noNullPad"("1")) #end
	public function texture_create_from_extension(type:godot.RenderingDevice_TextureType, format:godot.RenderingDevice_DataFormat, samples:godot.RenderingDevice_TextureSamples, usage_flags:godot.RenderingDevice_TextureUsageBits, @:meta("uint64") image:Int, @:meta("uint64") width:Int, @:meta("uint64") height:Int, @:meta("uint64") depth:Int, @:meta("uint64") layers:Int, @:meta("uint64") @:default_value("1") #if gdscript @:noNullPad("1") #end mipmaps:Int = 1):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1349464008)
	@:hash_compatibility([2096463824, 2736912341.])
	@:nativeName("texture_update")
	@:argMeta(1, ":meta"("uint32"))
	public function texture_update(texture:godot.RID, @:meta("uint32") layer:Int, data:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1859412099)
	@:hash_compatibility(null)
	@:nativeName("texture_get_data")
	@:argMeta(1, ":meta"("uint32"))
	public function texture_get_data(texture:godot.RID, @:meta("uint32") layer:Int):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(498832090)
	@:hash_compatibility(null)
	@:nativeName("texture_get_data_async")
	@:argMeta(1, ":meta"("uint32"))
	public function texture_get_data_async(texture:godot.RID, @:meta("uint32") layer:Int, callback:godot.Callable):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2592520478.)
	@:hash_compatibility(null)
	@:nativeName("texture_is_format_supported_for_usage")
	public function texture_is_format_supported_for_usage(format:godot.RenderingDevice_DataFormat, usage_flags:godot.RenderingDevice_TextureUsageBits):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("texture_is_shared")
	public function texture_is_shared(texture:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("texture_is_valid")
	public function texture_is_valid(texture:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("texture_set_discardable")
	public function texture_set_discardable(texture:godot.RID, discardable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("texture_is_discardable")
	public function texture_is_discardable(texture:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2859522160.)
	@:hash_compatibility([2339493201., 3741367532.])
	@:nativeName("texture_copy")
	@:argMeta(5, ":meta"("uint32"))
	@:argMeta(6, ":meta"("uint32"))
	@:argMeta(7, ":meta"("uint32"))
	@:argMeta(8, ":meta"("uint32"))
	public function texture_copy(from_texture:godot.RID, to_texture:godot.RID, from_pos:godot.Vector3, to_pos:godot.Vector3, size:godot.Vector3, @:meta("uint32") src_mipmap:Int, @:meta("uint32") dst_mipmap:Int, @:meta("uint32") src_layer:Int, @:meta("uint32") dst_layer:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3477703247.)
	@:hash_compatibility([3396867530., 3423681478.])
	@:nativeName("texture_clear")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(5, ":meta"("uint32"))
	public function texture_clear(texture:godot.RID, color:godot.Color, @:meta("uint32") base_mipmap:Int, @:meta("uint32") mipmap_count:Int, @:meta("uint32") base_layer:Int, @:meta("uint32") layer_count:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3181288260.)
	@:hash_compatibility([594679454, 2126834943])
	@:nativeName("texture_resolve_multisample")
	public function texture_resolve_multisample(from_texture:godot.RID, to_texture:godot.RID):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1374471690)
	@:hash_compatibility(null)
	@:nativeName("texture_get_format")
	public function texture_get_format(texture:godot.RID):godot.RDTextureFormat;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3917799429.)
	@:hash_compatibility(null)
	@:nativeName("texture_get_native_handle")
	public function texture_get_native_handle(texture:godot.RID):Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(697032759)
	@:hash_compatibility([2635475316.])
	@:nativeName("framebuffer_format_create")
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("1"))
	#if gdscript @:argMeta(1, ":noNullPad"("1")) #end
	public function framebuffer_format_create(attachments:Array<godot.RDAttachmentFormat>, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end view_count:Int = 1):Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2647479094.)
	@:hash_compatibility([1992489524])
	@:nativeName("framebuffer_format_create_multipass")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(2, ":default_value"("1"))
	#if gdscript @:argMeta(2, ":noNullPad"("1")) #end
	public function framebuffer_format_create_multipass(attachments:Array<godot.RDAttachmentFormat>, passes:Array<godot.RDFramebufferPass>, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end view_count:Int = 1):Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(555930169)
	@:hash_compatibility(null)
	@:nativeName("framebuffer_format_create_empty")
	@:argMeta(0, ":default_value"("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1"))
	#if gdscript @:argMeta(0, ":noNullPad"("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1")) #end
	public function framebuffer_format_create_empty(@:default_value("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1") #if gdscript @:noNullPad("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1") #end samples:godot.RenderingDevice_TextureSamples = godot.RenderingDevice_TextureSamples.TEXTURE_SAMPLES_1):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4223391010.)
	@:hash_compatibility([1036806638])
	@:nativeName("framebuffer_format_get_texture_samples")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	public function framebuffer_format_get_texture_samples(@:meta("int64") format:Int, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end render_pass:Int = 0):godot.RenderingDevice_TextureSamples;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3284231055.)
	@:hash_compatibility([1884747791])
	@:nativeName("framebuffer_create")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(2, ":default_value"("1"))
	#if gdscript @:argMeta(2, ":noNullPad"("1")) #end
	public function framebuffer_create(textures:Array<godot.RID>, @:meta("int64") @:default_value("-1") #if gdscript @:noNullPad("-1") #end validate_with_format:Int = -1, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end view_count:Int = 1):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1750306695)
	@:hash_compatibility([452534725])
	@:nativeName("framebuffer_create_multipass")
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(2, ":default_value"("-1"))
	#if gdscript @:argMeta(2, ":noNullPad"("-1")) #end
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(3, ":default_value"("1"))
	#if gdscript @:argMeta(3, ":noNullPad"("1")) #end
	public function framebuffer_create_multipass(textures:Array<godot.RID>, passes:Array<godot.RDFramebufferPass>, @:meta("int64") @:default_value("-1") #if gdscript @:noNullPad("-1") #end validate_with_format:Int = -1, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end view_count:Int = 1):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3058360618.)
	@:hash_compatibility([382373098])
	@:nativeName("framebuffer_create_empty")
	@:argMeta(1, ":default_value"("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1"))
	#if gdscript @:argMeta(1, ":noNullPad"("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1")) #end
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(2, ":default_value"("-1"))
	#if gdscript @:argMeta(2, ":noNullPad"("-1")) #end
	public function framebuffer_create_empty(size:godot.Vector2i, @:default_value("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1") #if gdscript @:noNullPad("RenderingDevice.TextureSamples.TEXTURE_SAMPLES_1") #end samples:godot.RenderingDevice_TextureSamples = godot.RenderingDevice_TextureSamples.TEXTURE_SAMPLES_1, @:meta("int64") @:default_value("-1") #if gdscript @:noNullPad("-1") #end validate_with_format:Int = -1):godot.RID;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3917799429.)
	@:hash_compatibility(null)
	@:nativeName("framebuffer_get_format")
	public function framebuffer_get_format(framebuffer:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("framebuffer_is_valid")
	public function framebuffer_is_valid(framebuffer:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2327892535.)
	@:hash_compatibility(null)
	@:nativeName("sampler_create")
	public function sampler_create(state:godot.RDSamplerState):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2247922238.)
	@:hash_compatibility(null)
	@:nativeName("sampler_is_format_supported_for_filter")
	public function sampler_is_format_supported_for_filter(format:godot.RenderingDevice_DataFormat, sampler_filter:godot.RenderingDevice_SamplerFilter):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2089548973)
	@:hash_compatibility([3410049843., 3491282828.])
	@:nativeName("vertex_buffer_create")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("PackedByteArray()"))
	#if gdscript @:argMeta(1, ":noNullPad"("PackedByteArray()")) #end
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	public function vertex_buffer_create(@:meta("uint32") size_bytes:Int, @:default_value("PackedByteArray()") #if gdscript @:noNullPad("PackedByteArray()") #end ?data:godot.PackedByteArray, @:default_value("0") #if gdscript @:noNullPad("0") #end ?creation_bits:godot.RenderingDevice_BufferCreationBits):godot.RID;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1242678479)
	@:hash_compatibility(null)
	@:nativeName("vertex_format_create")
	public function vertex_format_create(vertex_descriptions:Array<godot.RDVertexAttribute>):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3799816279.)
	@:hash_compatibility([3137892244.])
	@:nativeName("vertex_array_create")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(3, ":default_value"("PackedInt64Array()"))
	#if gdscript @:argMeta(3, ":noNullPad"("PackedInt64Array()")) #end
	public function vertex_array_create(@:meta("uint32") vertex_count:Int, @:meta("int64") vertex_format:Int, src_buffers:Array<godot.RID>, @:default_value("PackedInt64Array()") #if gdscript @:noNullPad("PackedInt64Array()") #end ?offsets:godot.PackedInt64Array):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2368684885.)
	@:hash_compatibility([3935920523., 975915977])
	@:nativeName("index_buffer_create")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(2, ":default_value"("PackedByteArray()"))
	#if gdscript @:argMeta(2, ":noNullPad"("PackedByteArray()")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	@:argMeta(4, ":default_value"("0"))
	#if gdscript @:argMeta(4, ":noNullPad"("0")) #end
	public function index_buffer_create(@:meta("uint32") size_indices:Int, format:godot.RenderingDevice_IndexBufferFormat, @:default_value("PackedByteArray()") #if gdscript @:noNullPad("PackedByteArray()") #end ?data:godot.PackedByteArray, @:default_value("false") #if gdscript @:noNullPad("false") #end use_restart_indices:Bool = false, @:default_value("0") #if gdscript @:noNullPad("0") #end ?creation_bits:godot.RenderingDevice_BufferCreationBits):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2256026069.)
	@:hash_compatibility(null)
	@:nativeName("index_array_create")
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(2, ":meta"("uint32"))
	public function index_array_create(index_buffer:godot.RID, @:meta("uint32") index_offset:Int, @:meta("uint32") index_count:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1178973306)
	@:hash_compatibility([3459523685.])
	@:nativeName("shader_compile_spirv_from_source")
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public function shader_compile_spirv_from_source(shader_source:godot.RDShaderSource, @:default_value("true") #if gdscript @:noNullPad("true") #end allow_cache:Bool = true):godot.RDShaderSPIRV;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(134910450)
	@:hash_compatibility([1395027180])
	@:nativeName("shader_compile_binary_from_spirv")
	@:argMeta(1, ":default_value"("\"\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"\"")) #end
	public function shader_compile_binary_from_spirv(spirv_data:godot.RDShaderSPIRV, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end name:String = "\"\""):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(342949005)
	@:hash_compatibility([3297482566.])
	@:nativeName("shader_create_from_spirv")
	@:argMeta(1, ":default_value"("\"\""))
	#if gdscript @:argMeta(1, ":noNullPad"("\"\"")) #end
	public function shader_create_from_spirv(spirv_data:godot.RDShaderSPIRV, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end name:String = "\"\""):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1687031350)
	@:hash_compatibility([3049171473., 2078349841])
	@:nativeName("shader_create_from_bytecode")
	@:argMeta(1, ":default_value"("RID()"))
	#if gdscript @:argMeta(1, ":noNullPad"("RID()")) #end
	public function shader_create_from_bytecode(binary_data:godot.PackedByteArray, @:default_value("RID()") #if gdscript @:noNullPad("RID()") #end ?placeholder_rid:godot.RID):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("shader_create_placeholder")
	public function shader_create_placeholder():godot.RID;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3917799429.)
	@:hash_compatibility(null)
	@:nativeName("shader_get_vertex_input_attribute_mask")
	public function shader_get_vertex_input_attribute_mask(shader:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2089548973)
	@:hash_compatibility([34556762, 1453158401])
	@:nativeName("uniform_buffer_create")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("PackedByteArray()"))
	#if gdscript @:argMeta(1, ":noNullPad"("PackedByteArray()")) #end
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	public function uniform_buffer_create(@:meta("uint32") size_bytes:Int, @:default_value("PackedByteArray()") #if gdscript @:noNullPad("PackedByteArray()") #end ?data:godot.PackedByteArray, @:default_value("0") #if gdscript @:noNullPad("0") #end ?creation_bits:godot.RenderingDevice_BufferCreationBits):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1609052553)
	@:hash_compatibility([2316365934., 1173156076])
	@:nativeName("storage_buffer_create")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("PackedByteArray()"))
	#if gdscript @:argMeta(1, ":noNullPad"("PackedByteArray()")) #end
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function storage_buffer_create(@:meta("uint32") size_bytes:Int, @:default_value("PackedByteArray()") #if gdscript @:noNullPad("PackedByteArray()") #end ?data:godot.PackedByteArray, @:default_value("0") #if gdscript @:noNullPad("0") #end ?usage:godot.RenderingDevice_StorageBufferUsage, @:default_value("0") #if gdscript @:noNullPad("0") #end ?creation_bits:godot.RenderingDevice_BufferCreationBits):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1470338698)
	@:hash_compatibility([2344087557.])
	@:nativeName("texture_buffer_create")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(2, ":default_value"("PackedByteArray()"))
	#if gdscript @:argMeta(2, ":noNullPad"("PackedByteArray()")) #end
	public function texture_buffer_create(@:meta("uint32") size_bytes:Int, format:godot.RenderingDevice_DataFormat, @:default_value("PackedByteArray()") #if gdscript @:noNullPad("PackedByteArray()") #end ?data:godot.PackedByteArray):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2280795797.)
	@:hash_compatibility(null)
	@:nativeName("uniform_set_create")
	@:argMeta(2, ":meta"("uint32"))
	public function uniform_set_create(uniforms:Array<godot.RDUniform>, shader:godot.RID, @:meta("uint32") shader_set:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("uniform_set_is_valid")
	public function uniform_set_is_valid(uniform_set:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(864257779)
	@:hash_compatibility(null)
	@:nativeName("buffer_copy")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	public function buffer_copy(src_buffer:godot.RID, dst_buffer:godot.RID, @:meta("uint32") src_offset:Int, @:meta("uint32") dst_offset:Int, @:meta("uint32") size:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3454956949.)
	@:hash_compatibility([3793150683., 652628289])
	@:nativeName("buffer_update")
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(2, ":meta"("uint32"))
	public function buffer_update(buffer:godot.RID, @:meta("uint32") offset:Int, @:meta("uint32") size_bytes:Int, data:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2452320800.)
	@:hash_compatibility([2797041220., 1645170096])
	@:nativeName("buffer_clear")
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(2, ":meta"("uint32"))
	public function buffer_clear(buffer:godot.RID, @:meta("uint32") offset:Int, @:meta("uint32") size_bytes:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3101830688.)
	@:hash_compatibility([125363422])
	@:nativeName("buffer_get_data")
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	public function buffer_get_data(buffer:godot.RID, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end offset_bytes:Int = 0, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end size_bytes:Int = 0):godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2370287848.)
	@:hash_compatibility(null)
	@:nativeName("buffer_get_data_async")
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function buffer_get_data_async(buffer:godot.RID, callback:godot.Callable, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end offset_bytes:Int = 0, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end size_bytes:Int = 0):godot.Error;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3917799429.)
	@:hash_compatibility(null)
	@:nativeName("buffer_get_device_address")
	public function buffer_get_device_address(buffer:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2385451958.)
	@:hash_compatibility([2911419500.])
	@:nativeName("render_pipeline_create")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(8, ":default_value"("0"))
	#if gdscript @:argMeta(8, ":noNullPad"("0")) #end
	@:argMeta(9, ":meta"("uint32"))
	@:argMeta(9, ":default_value"("0"))
	#if gdscript @:argMeta(9, ":noNullPad"("0")) #end
	@:argMeta(10, ":default_value"("Array[RDPipelineSpecializationConstant]([])"))
	#if gdscript @:argMeta(10, ":noNullPad"("[]")) #end
	public function render_pipeline_create(shader:godot.RID, @:meta("int64") framebuffer_format:Int, @:meta("int64") vertex_format:Int, primitive:godot.RenderingDevice_RenderPrimitive, rasterization_state:godot.RDPipelineRasterizationState, multisample_state:godot.RDPipelineMultisampleState, stencil_state:godot.RDPipelineDepthStencilState, color_blend_state:godot.RDPipelineColorBlendState, @:default_value("0") #if gdscript @:noNullPad("0") #end ?dynamic_state_flags:godot.RenderingDevice_PipelineDynamicStateFlags, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end for_render_pass:Int = 0, @:default_value("Array[RDPipelineSpecializationConstant]([])") #if gdscript @:noNullPad("[]") #end ?specialization_constants:Array<godot.RDPipelineSpecializationConstant>):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("render_pipeline_is_valid")
	public function render_pipeline_is_valid(render_pipeline:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1448838280)
	@:hash_compatibility([403593840])
	@:nativeName("compute_pipeline_create")
	@:argMeta(1, ":default_value"("Array[RDPipelineSpecializationConstant]([])"))
	#if gdscript @:argMeta(1, ":noNullPad"("[]")) #end
	public function compute_pipeline_create(shader:godot.RID, @:default_value("Array[RDPipelineSpecializationConstant]([])") #if gdscript @:noNullPad("[]") #end ?specialization_constants:Array<godot.RDPipelineSpecializationConstant>):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("compute_pipeline_is_valid")
	public function compute_pipeline_is_valid(compute_pipeline:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1489129684)
	@:hash_compatibility(null)
	@:nativeName("raytracing_pipeline_create")
	@:argMeta(3, ":meta"("uint32"))
	public function raytracing_pipeline_create(raygen_shaders:Array<godot.RDPipelineShader>, miss_shaders:Array<godot.RDPipelineShader>, hit_groups:Array<godot.RDHitGroup>, @:meta("uint32") max_trace_recursion_depth:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("raytracing_pipeline_is_valid")
	public function raytracing_pipeline_is_valid(raytracing_pipeline:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1010940044)
	@:hash_compatibility(null)
	@:nativeName("blas_create")
	public function blas_create(geometries:Array<godot.RDAccelerationStructureGeometry>, flags:godot.RenderingDevice_AccelerationStructureFlagBits):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(592780330)
	@:hash_compatibility(null)
	@:nativeName("tlas_create")
	@:argMeta(0, ":meta"("uint32"))
	public function tlas_create(@:meta("uint32") max_instance_count:Int, flags:godot.RenderingDevice_AccelerationStructureFlagBits):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(813180755)
	@:hash_compatibility(null)
	@:nativeName("blas_build")
	public function blas_build(blas:godot.RID):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(261981775)
	@:hash_compatibility(null)
	@:nativeName("tlas_build")
	public function tlas_build(tlas:godot.RID, instances:Array<godot.RDAccelerationStructureInstance>):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2233757277.)
	@:hash_compatibility(null)
	@:nativeName("hit_sbt_create")
	@:argMeta(1, ":meta"("uint32"))
	public function hit_sbt_create(raytracing_pipeline:godot.RID, @:meta("uint32") initial_hit_group_capacity:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3181288260.)
	@:hash_compatibility(null)
	@:nativeName("hit_sbt_set_pipeline")
	public function hit_sbt_set_pipeline(hit_sbt:godot.RID, raytracing_pipeline:godot.RID):godot.Error;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722015314.)
	@:hash_compatibility(null)
	@:nativeName("hit_sbt_range_alloc")
	@:argMeta(1, ":meta"("uint32"))
	public function hit_sbt_range_alloc(hit_sbt:godot.RID, @:meta("uint32") hit_group_count:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3804025326.)
	@:hash_compatibility(null)
	@:nativeName("hit_sbt_range_free")
	@:argMeta(1, ":meta"("int64"))
	public function hit_sbt_range_free(hit_sbt:godot.RID, @:meta("int64") range:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1332346675)
	@:hash_compatibility(null)
	@:nativeName("hit_sbt_range_update")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function hit_sbt_range_update(hit_sbt:godot.RID, @:meta("int64") range:Int, @:meta("uint32") offset:Int, hit_group_indices:godot.PackedInt32Array):godot.Error;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1591665591)
	@:hash_compatibility(null)
	@:nativeName("screen_get_width")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public function screen_get_width(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end screen:Int = 0):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1591665591)
	@:hash_compatibility(null)
	@:nativeName("screen_get_height")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public function screen_get_height(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end screen:Int = 0):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1591665591)
	@:hash_compatibility([3905245786.])
	@:nativeName("screen_get_framebuffer_format")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public function screen_get_framebuffer_format(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end screen:Int = 0):Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3988079995.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_begin_for_screen")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	@:argMeta(1, ":default_value"("Color(0, 0, 0, 1)"))
	#if gdscript @:argMeta(1, ":noNullPad"("Color(0, 0, 0, 1)")) #end
	public function draw_list_begin_for_screen(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end screen:Int = 0, @:default_value("Color(0, 0, 0, 1)") #if gdscript @:noNullPad("Color(0, 0, 0, 1)") #end ?clear_color:godot.Color):Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1317926357)
	@:hash_compatibility([2468082605., 2686605154., 3140542288., 4252992020.])
	@:nativeName("draw_list_begin")
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	@:argMeta(2, ":default_value"("PackedColorArray()"))
	#if gdscript @:argMeta(2, ":noNullPad"("PackedColorArray()")) #end
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("1.0"))
	#if gdscript @:argMeta(3, ":noNullPad"("1.0")) #end
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(4, ":default_value"("0"))
	#if gdscript @:argMeta(4, ":noNullPad"("0")) #end
	@:argMeta(5, ":default_value"("Rect2(0, 0, 0, 0)"))
	#if gdscript @:argMeta(5, ":noNullPad"("Rect2(0, 0, 0, 0)")) #end
	@:argMeta(6, ":meta"("uint32"))
	@:argMeta(6, ":default_value"("0"))
	#if gdscript @:argMeta(6, ":noNullPad"("0")) #end
	public function draw_list_begin(framebuffer:godot.RID, @:default_value("0") #if gdscript @:noNullPad("0") #end ?draw_flags:godot.RenderingDevice_DrawFlags, @:default_value("PackedColorArray()") #if gdscript @:noNullPad("PackedColorArray()") #end ?clear_color_values:godot.PackedColorArray, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end clear_depth_value:Float = 1., @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end clear_stencil_value:Int = 0, @:default_value("Rect2(0, 0, 0, 0)") #if gdscript @:noNullPad("Rect2(0, 0, 0, 0)") #end ?region:godot.Rect2, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end breadcrumb:Int = 0):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2406300660.)
	@:hash_compatibility([832527510])
	@:nativeName("draw_list_begin_split")
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(6, ":default_value"("PackedColorArray()"))
	#if gdscript @:argMeta(6, ":noNullPad"("PackedColorArray()")) #end
	@:argMeta(7, ":meta"("float"))
	@:argMeta(7, ":default_value"("1.0"))
	#if gdscript @:argMeta(7, ":noNullPad"("1.0")) #end
	@:argMeta(8, ":meta"("uint32"))
	@:argMeta(8, ":default_value"("0"))
	#if gdscript @:argMeta(8, ":noNullPad"("0")) #end
	@:argMeta(9, ":default_value"("Rect2(0, 0, 0, 0)"))
	#if gdscript @:argMeta(9, ":noNullPad"("Rect2(0, 0, 0, 0)")) #end
	@:argMeta(10, ":default_value"("Array[RID]([])"))
	#if gdscript @:argMeta(10, ":noNullPad"("[]")) #end
	public function draw_list_begin_split(framebuffer:godot.RID, @:meta("uint32") splits:Int, initial_color_action:godot.RenderingDevice_InitialAction, final_color_action:godot.RenderingDevice_FinalAction, initial_depth_action:godot.RenderingDevice_InitialAction, final_depth_action:godot.RenderingDevice_FinalAction, @:default_value("PackedColorArray()") #if gdscript @:noNullPad("PackedColorArray()") #end ?clear_color_values:godot.PackedColorArray, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end clear_depth:Float = 1., @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end clear_stencil:Int = 0, @:default_value("Rect2(0, 0, 0, 0)") #if gdscript @:noNullPad("Rect2(0, 0, 0, 0)") #end ?region:godot.Rect2, @:default_value("Array[RID]([])") #if gdscript @:noNullPad("[]") #end ?storage_textures:Array<godot.RID>):godot.PackedInt64Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_set_blend_constants")
	@:argMeta(0, ":meta"("int64"))
	public function draw_list_set_blend_constants(@:meta("int64") draw_list:Int, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4040184819.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_bind_render_pipeline")
	@:argMeta(0, ":meta"("int64"))
	public function draw_list_bind_render_pipeline(@:meta("int64") draw_list:Int, render_pipeline:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(749655778)
	@:hash_compatibility(null)
	@:nativeName("draw_list_bind_uniform_set")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function draw_list_bind_uniform_set(@:meta("int64") draw_list:Int, uniform_set:godot.RID, @:meta("uint32") set_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4040184819.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_bind_vertex_array")
	@:argMeta(0, ":meta"("int64"))
	public function draw_list_bind_vertex_array(@:meta("int64") draw_list:Int, vertex_array:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2008628980)
	@:hash_compatibility(null)
	@:nativeName("draw_list_bind_vertex_buffers_format")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(4, ":default_value"("PackedInt64Array()"))
	#if gdscript @:argMeta(4, ":noNullPad"("PackedInt64Array()")) #end
	public function draw_list_bind_vertex_buffers_format(@:meta("int64") draw_list:Int, @:meta("int64") vertex_format:Int, @:meta("uint32") vertex_count:Int, vertex_buffers:Array<godot.RID>, @:default_value("PackedInt64Array()") #if gdscript @:noNullPad("PackedInt64Array()") #end ?offsets:godot.PackedInt64Array):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4040184819.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_bind_index_array")
	@:argMeta(0, ":meta"("int64"))
	public function draw_list_bind_index_array(@:meta("int64") draw_list:Int, index_array:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2772371345.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_set_push_constant")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function draw_list_set_push_constant(@:meta("int64") draw_list:Int, buffer:godot.PackedByteArray, @:meta("uint32") size_bytes:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4230067973.)
	@:hash_compatibility([3710874499.])
	@:nativeName("draw_list_draw")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	public function draw_list_draw(@:meta("int64") draw_list:Int, use_indices:Bool, @:meta("uint32") instances:Int, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end procedural_vertex_count:Int = 0):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1092133571)
	@:hash_compatibility(null)
	@:nativeName("draw_list_draw_indirect")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(3, ":default_value"("0"))
	#if gdscript @:argMeta(3, ":noNullPad"("0")) #end
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(4, ":default_value"("1"))
	#if gdscript @:argMeta(4, ":noNullPad"("1")) #end
	@:argMeta(5, ":meta"("uint32"))
	@:argMeta(5, ":default_value"("0"))
	#if gdscript @:argMeta(5, ":noNullPad"("0")) #end
	public function draw_list_draw_indirect(@:meta("int64") draw_list:Int, use_indices:Bool, buffer:godot.RID, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end offset:Int = 0, @:meta("uint32") @:default_value("1") #if gdscript @:noNullPad("1") #end draw_count:Int = 1, @:meta("uint32") @:default_value("0") #if gdscript @:noNullPad("0") #end stride:Int = 0):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(244650101)
	@:hash_compatibility([338791288])
	@:nativeName("draw_list_enable_scissor")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":default_value"("Rect2(0, 0, 0, 0)"))
	#if gdscript @:argMeta(1, ":noNullPad"("Rect2(0, 0, 0, 0)")) #end
	public function draw_list_enable_scissor(@:meta("int64") draw_list:Int, @:default_value("Rect2(0, 0, 0, 0)") #if gdscript @:noNullPad("Rect2(0, 0, 0, 0)") #end ?rect:godot.Rect2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("draw_list_disable_scissor")
	@:argMeta(0, ":meta"("int64"))
	public function draw_list_disable_scissor(@:meta("int64") draw_list:Int):Void;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_switch_to_next_pass")
	public function draw_list_switch_to_next_pass():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2865087369.)
	@:hash_compatibility(null)
	@:nativeName("draw_list_switch_to_next_pass_split")
	@:argMeta(0, ":meta"("uint32"))
	public function draw_list_switch_to_next_pass_split(@:meta("uint32") splits:Int):godot.PackedInt64Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility([422991495, 3920951950.])
	@:nativeName("draw_list_end")
	public function draw_list_end():Void;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility([968564752])
	@:nativeName("compute_list_begin")
	public function compute_list_begin():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4040184819.)
	@:hash_compatibility(null)
	@:nativeName("compute_list_bind_compute_pipeline")
	@:argMeta(0, ":meta"("int64"))
	public function compute_list_bind_compute_pipeline(@:meta("int64") compute_list:Int, compute_pipeline:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2772371345.)
	@:hash_compatibility(null)
	@:nativeName("compute_list_set_push_constant")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function compute_list_set_push_constant(@:meta("int64") compute_list:Int, buffer:godot.PackedByteArray, @:meta("uint32") size_bytes:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(749655778)
	@:hash_compatibility(null)
	@:nativeName("compute_list_bind_uniform_set")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function compute_list_bind_uniform_set(@:meta("int64") compute_list:Int, uniform_set:godot.RID, @:meta("uint32") set_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4275841770.)
	@:hash_compatibility(null)
	@:nativeName("compute_list_dispatch")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(2, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	public function compute_list_dispatch(@:meta("int64") compute_list:Int, @:meta("uint32") x_groups:Int, @:meta("uint32") y_groups:Int, @:meta("uint32") z_groups:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(749655778)
	@:hash_compatibility(null)
	@:nativeName("compute_list_dispatch_indirect")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function compute_list_dispatch_indirect(@:meta("int64") compute_list:Int, buffer:godot.RID, @:meta("uint32") offset:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("compute_list_add_barrier")
	@:argMeta(0, ":meta"("int64"))
	public function compute_list_add_barrier(@:meta("int64") compute_list:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility([422991495, 3920951950.])
	@:nativeName("compute_list_end")
	public function compute_list_end():Void;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("raytracing_list_begin")
	public function raytracing_list_begin():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4040184819.)
	@:hash_compatibility(null)
	@:nativeName("raytracing_list_bind_raytracing_pipeline")
	@:argMeta(0, ":meta"("int64"))
	public function raytracing_list_bind_raytracing_pipeline(@:meta("int64") raytracing_list:Int, raytracing_pipeline:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2772371345.)
	@:hash_compatibility(null)
	@:nativeName("raytracing_list_set_push_constant")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function raytracing_list_set_push_constant(@:meta("int64") raytracing_list:Int, buffer:godot.PackedByteArray, @:meta("uint32") size_bytes:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(749655778)
	@:hash_compatibility(null)
	@:nativeName("raytracing_list_bind_uniform_set")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(2, ":meta"("uint32"))
	public function raytracing_list_bind_uniform_set(@:meta("int64") raytracing_list:Int, uniform_set:godot.RID, @:meta("uint32") set_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2559472681.)
	@:hash_compatibility(null)
	@:nativeName("raytracing_list_trace_rays")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("uint32"))
	@:argMeta(3, ":meta"("uint32"))
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(5, ":meta"("uint32"))
	public function raytracing_list_trace_rays(@:meta("int64") raytracing_list:Int, @:meta("uint32") raygen_shader_index:Int, hit_sbt:godot.RID, @:meta("uint32") width:Int, @:meta("uint32") height:Int, @:meta("uint32") depth:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("raytracing_list_end")
	public function raytracing_list_end():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("free_rid")
	public function free_rid(rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("capture_timestamp")
	public function capture_timestamp(name:String):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_captured_timestamps_count")
	public function get_captured_timestamps_count():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_captured_timestamps_frame")
	public function get_captured_timestamps_frame():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_captured_timestamp_gpu_time")
	@:argMeta(0, ":meta"("uint32"))
	public function get_captured_timestamp_gpu_time(@:meta("uint32") index:Int):Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_captured_timestamp_cpu_time")
	@:argMeta(0, ":meta"("uint32"))
	public function get_captured_timestamp_cpu_time(@:meta("uint32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_captured_timestamp_name")
	@:argMeta(0, ":meta"("uint32"))
	public function get_captured_timestamp_name(@:meta("uint32") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1772728326)
	@:hash_compatibility(null)
	@:nativeName("has_feature")
	public function has_feature(feature:godot.RenderingDevice_Features):Bool;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1559202131)
	@:hash_compatibility(null)
	@:nativeName("limit_get")
	public function limit_get(limit:godot.RenderingDevice_Limit):Int;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_frame_delay")
	public function get_frame_delay():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("submit")
	public function submit():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("sync")
	public function sync():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3718155691.)
	@:hash_compatibility([266666049])
	@:nativeName("barrier")
	@:argMeta(0, ":default_value"("32767"))
	#if gdscript @:argMeta(0, ":noNullPad"("32767")) #end
	@:argMeta(1, ":default_value"("32767"))
	#if gdscript @:argMeta(1, ":noNullPad"("32767")) #end
	public function barrier(@:default_value("32767") #if gdscript @:noNullPad("32767") #end ?from:godot.RenderingDevice_BarrierMask, @:default_value("32767") #if gdscript @:noNullPad("32767") #end ?to:godot.RenderingDevice_BarrierMask):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("full_barrier")
	public function full_barrier():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2846302423.)
	@:hash_compatibility(null)
	@:nativeName("create_local_device")
	public function create_local_device():godot.RenderingDevice;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("set_resource_name")
	public function set_resource_name(id:godot.RID, name:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1636512886)
	@:hash_compatibility(null)
	@:nativeName("draw_command_begin_label")
	public function draw_command_begin_label(name:String, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1636512886)
	@:hash_compatibility(null)
	@:nativeName("draw_command_insert_label")
	public function draw_command_insert_label(name:String, color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("draw_command_end_label")
	public function draw_command_end_label():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_device_vendor_name")
	public function get_device_vendor_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_device_name")
	public function get_device_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_device_pipeline_cache_uuid")
	public function get_device_pipeline_cache_uuid():String;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(251690689)
	@:hash_compatibility(null)
	@:nativeName("get_memory_usage")
	public function get_memory_usage(type:godot.RenderingDevice_MemoryType):Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501815484)
	@:hash_compatibility(null)
	@:nativeName("get_driver_resource")
	@:argMeta(2, ":meta"("uint64"))
	public function get_driver_resource(resource:godot.RenderingDevice_DriverResource, rid:godot.RID, @:meta("uint64") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_perf_report")
	public function get_perf_report():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_driver_and_device_memory_report")
	public function get_driver_and_device_memory_report():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_tracked_object_name")
	@:argMeta(0, ":meta"("uint32"))
	public function get_tracked_object_name(@:meta("uint32") type_index:Int):String;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_tracked_object_type_count")
	public function get_tracked_object_type_count():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_driver_total_memory")
	public function get_driver_total_memory():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_driver_allocation_count")
	public function get_driver_allocation_count():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_driver_memory_by_object_type")
	@:argMeta(0, ":meta"("uint32"))
	public function get_driver_memory_by_object_type(@:meta("uint32") type:Int):Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_driver_allocs_by_object_type")
	@:argMeta(0, ":meta"("uint32"))
	public function get_driver_allocs_by_object_type(@:meta("uint32") type:Int):Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_device_total_memory")
	public function get_device_total_memory():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_device_allocation_count")
	public function get_device_allocation_count():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_device_memory_by_object_type")
	@:argMeta(0, ":meta"("uint32"))
	public function get_device_memory_by_object_type(@:meta("uint32") type:Int):Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_device_allocs_by_object_type")
	@:argMeta(0, ":meta"("uint32"))
	public function get_device_allocs_by_object_type(@:meta("uint32") type:Int):Int;
}