/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class ResourceFormatLoader extends godot.RefCounted {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_recognized_extensions")
	public function _get_recognized_extensions():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2594487047.)
	@:hash_compatibility(null)
	@:nativeName("_recognize_path")
	public function _recognize_path(path:String, type:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("_handles_type")
	public function _handles_type(type:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("_get_resource_type")
	public function _get_resource_type(path:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("_get_resource_script_class")
	public function _get_resource_script_class(path:String):String;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1321353865)
	@:hash_compatibility(null)
	@:nativeName("_get_resource_uid")
	public function _get_resource_uid(path:String):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(6257701)
	@:hash_compatibility(null)
	@:nativeName("_get_dependencies")
	public function _get_dependencies(path:String, add_types:Bool):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(223715120)
	@:hash_compatibility(null)
	@:nativeName("_rename_dependencies")
	public function _rename_dependencies(path:String, renames:godot.Dictionary):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_exists")
	public function _exists(path:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("_get_classes_used")
	public function _get_classes_used(path:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2885906527.)
	@:hash_compatibility(null)
	@:nativeName("_load")
	@:argMeta(3, ":meta"("int32"))
	public function _load(path:String, original_path:String, use_sub_threads:Bool, @:meta("int32") cache_mode:Int):Dynamic;
}