/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class SceneReplicationConfig extends godot.Resource {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("get_properties")
	public function get_properties():Array<godot.NodePath>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4094619021.)
	@:hash_compatibility([3818401521.])
	@:nativeName("add_property")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public function add_property(path:godot.NodePath, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(861721659)
	@:hash_compatibility(null)
	@:nativeName("has_property")
	public function has_property(path:godot.NodePath):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1348162250)
	@:hash_compatibility(null)
	@:nativeName("remove_property")
	public function remove_property(path:godot.NodePath):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1382022557)
	@:hash_compatibility(null)
	@:nativeName("property_get_index")
	public function property_get_index(path:godot.NodePath):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3456846888.)
	@:hash_compatibility(null)
	@:nativeName("property_get_spawn")
	public function property_get_spawn(path:godot.NodePath):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3868023870.)
	@:hash_compatibility(null)
	@:nativeName("property_set_spawn")
	public function property_set_spawn(path:godot.NodePath, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2870606336.)
	@:hash_compatibility(null)
	@:nativeName("property_get_replication_mode")
	public function property_get_replication_mode(path:godot.NodePath):godot.SceneReplicationConfig_ReplicationMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3200083865.)
	@:hash_compatibility(null)
	@:nativeName("property_set_replication_mode")
	public function property_set_replication_mode(path:godot.NodePath, mode:godot.SceneReplicationConfig_ReplicationMode):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3456846888.)
	@:hash_compatibility(null)
	@:nativeName("property_get_sync")
	public function property_get_sync(path:godot.NodePath):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3868023870.)
	@:hash_compatibility(null)
	@:nativeName("property_set_sync")
	public function property_set_sync(path:godot.NodePath, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3456846888.)
	@:hash_compatibility(null)
	@:nativeName("property_get_watch")
	public function property_get_watch(path:godot.NodePath):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3868023870.)
	@:hash_compatibility(null)
	@:nativeName("property_set_watch")
	public function property_set_watch(path:godot.NodePath, enabled:Bool):Void;
}