/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(false) @:api_type("core") @:is_resource(true) @:is_node(false) extern class SceneState extends godot.RefCounted {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("get_path")
	public function get_path():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3479783971.)
	@:hash_compatibility(null)
	@:nativeName("get_base_scene_state")
	public function get_base_scene_state():godot.SceneState;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_node_count")
	public function get_node_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(659327637)
	@:hash_compatibility(null)
	@:nativeName("get_node_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_type(@:meta("int32") idx:Int):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(659327637)
	@:hash_compatibility(null)
	@:nativeName("get_node_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_name(@:meta("int32") idx:Int):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2272487792.)
	@:hash_compatibility(null)
	@:nativeName("get_node_path")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function get_node_path(@:meta("int32") idx:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end for_parent:Bool = false):godot.NodePath;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_node_owner_path")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_owner_path(@:meta("int32") idx:Int):godot.NodePath;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_node_instance_placeholder")
	@:argMeta(0, ":meta"("int32"))
	public function is_node_instance_placeholder(@:meta("int32") idx:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_node_instance_placeholder")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_instance_placeholder(@:meta("int32") idx:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(511017218)
	@:hash_compatibility(null)
	@:nativeName("get_node_instance")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_instance(@:meta("int32") idx:Int):godot.PackedScene;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(647634434)
	@:hash_compatibility(null)
	@:nativeName("get_node_groups")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_groups(@:meta("int32") idx:Int):godot.PackedStringArray;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_node_index")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_index(@:meta("int32") idx:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_node_property_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_node_property_count(@:meta("int32") idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(351665558)
	@:hash_compatibility(null)
	@:nativeName("get_node_property_name")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_node_property_name(@:meta("int32") idx:Int, @:meta("int32") prop_idx:Int):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(678354945)
	@:hash_compatibility(null)
	@:nativeName("get_node_property_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_node_property_value(@:meta("int32") idx:Int, @:meta("int32") prop_idx:Int):Dynamic;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_connection_count")
	public function get_connection_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_connection_source")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_source(@:meta("int32") idx:Int):godot.NodePath;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(659327637)
	@:hash_compatibility(null)
	@:nativeName("get_connection_signal")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_signal(@:meta("int32") idx:Int):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_connection_target")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_target(@:meta("int32") idx:Int):godot.NodePath;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(659327637)
	@:hash_compatibility(null)
	@:nativeName("get_connection_method")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_method(@:meta("int32") idx:Int):godot.StringName;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_connection_flags")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_flags(@:meta("int32") idx:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("get_connection_binds")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_binds(@:meta("int32") idx:Int):GodotArray;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_connection_unbinds")
	@:argMeta(0, ":meta"("int32"))
	public function get_connection_unbinds(@:meta("int32") idx:Int):Int;
}