/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class ScriptLanguageExtension extends godot.ScriptLanguage {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_name")
	public function _get_name():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_init")
	public function _init():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_type")
	public function _get_type():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_extension")
	public function _get_extension():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_finish")
	public function _finish():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_reserved_words")
	public function _get_reserved_words():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_is_control_flow_keyword")
	public function _is_control_flow_keyword(keyword:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_comment_delimiters")
	public function _get_comment_delimiters():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_doc_comment_delimiters")
	public function _get_doc_comment_delimiters():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_string_delimiters")
	public function _get_string_delimiters():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3583744548.)
	@:hash_compatibility(null)
	@:nativeName("_make_template")
	public function _make_template(template:String, class_name:String, base_class_name:String):godot.Script;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3147814860.)
	@:hash_compatibility(null)
	@:nativeName("_get_built_in_templates")
	public function _get_built_in_templates(object:godot.StringName):Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_is_using_templates")
	public function _is_using_templates():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1697887509)
	@:hash_compatibility(null)
	@:nativeName("_validate")
	public function _validate(script:String, path:String, validate_functions:Bool, validate_errors:Bool, validate_warnings:Bool, validate_safe_lines:Bool):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("_validate_path")
	public function _validate_path(path:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1981248198)
	@:hash_compatibility(null)
	@:nativeName("_create_script")
	public function _create_script():godot.Object;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_has_named_classes")
	public function _has_named_classes():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_supports_builtin_mode")
	public function _supports_builtin_mode():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_supports_documentation")
	public function _supports_documentation():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_can_inherit_from_file")
	public function _can_inherit_from_file():Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2878152881.)
	@:hash_compatibility(null)
	@:nativeName("_find_function")
	public function _find_function(_function:String, code:String):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1243061914)
	@:hash_compatibility(null)
	@:nativeName("_make_function")
	public function _make_function(class_name:String, function_name:String, function_args:godot.PackedStringArray):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_can_make_function")
	public function _can_make_function():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(552845695)
	@:hash_compatibility(null)
	@:nativeName("_open_in_external_editor")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function _open_in_external_editor(script:godot.Script, @:meta("int32") line:Int, @:meta("int32") column:Int):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_overrides_external_editor")
	public function _overrides_external_editor():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2969522789.)
	@:hash_compatibility(null)
	@:nativeName("_preferred_file_name_casing")
	public function _preferred_file_name_casing():godot.ScriptLanguage_ScriptNameCasing;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(950756616)
	@:hash_compatibility(null)
	@:nativeName("_complete_code")
	public function _complete_code(code:String, path:String, owner:godot.Object):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3143837309.)
	@:hash_compatibility(null)
	@:nativeName("_lookup_code")
	public function _lookup_code(code:String, symbol:String, path:String, owner:godot.Object):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2531480354.)
	@:hash_compatibility(null)
	@:nativeName("_auto_indent_code")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function _auto_indent_code(code:String, @:meta("int32") from_line:Int, @:meta("int32") to_line:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3776071444.)
	@:hash_compatibility(null)
	@:nativeName("_add_global_constant")
	public function _add_global_constant(name:godot.StringName, value:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3776071444.)
	@:hash_compatibility(null)
	@:nativeName("_add_named_global_constant")
	public function _add_named_global_constant(name:godot.StringName, value:Dynamic):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("_remove_named_global_constant")
	public function _remove_named_global_constant(name:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_thread_enter")
	public function _thread_enter():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_thread_exit")
	public function _thread_exit():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_error")
	public function _debug_get_error():String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_stack_level_count")
	public function _debug_get_stack_level_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_stack_level_line")
	@:argMeta(0, ":meta"("int32"))
	public function _debug_get_stack_level_line(@:meta("int32") level:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_stack_level_function")
	@:argMeta(0, ":meta"("int32"))
	public function _debug_get_stack_level_function(@:meta("int32") level:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_stack_level_source")
	@:argMeta(0, ":meta"("int32"))
	public function _debug_get_stack_level_source(@:meta("int32") level:Int):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(335235777)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_stack_level_locals")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function _debug_get_stack_level_locals(@:meta("int32") level:Int, @:meta("int32") max_subitems:Int, @:meta("int32") max_depth:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(335235777)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_stack_level_members")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function _debug_get_stack_level_members(@:meta("int32") level:Int, @:meta("int32") max_subitems:Int, @:meta("int32") max_depth:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4123630098.)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_globals")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function _debug_get_globals(@:meta("int32") max_subitems:Int, @:meta("int32") max_depth:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1135811067)
	@:hash_compatibility(null)
	@:nativeName("_debug_parse_stack_level_expression")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(3, ":meta"("int32"))
	public function _debug_parse_stack_level_expression(@:meta("int32") level:Int, expression:String, @:meta("int32") max_subitems:Int, @:meta("int32") max_depth:Int):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("_debug_get_current_stack_info")
	public function _debug_get_current_stack_info():Array<godot.Dictionary>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_reload_all_scripts")
	public function _reload_all_scripts():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3156113851.)
	@:hash_compatibility(null)
	@:nativeName("_reload_scripts")
	public function _reload_scripts(scripts:GodotArray, soft_reload:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1957307671)
	@:hash_compatibility(null)
	@:nativeName("_reload_tool_script")
	public function _reload_tool_script(script:godot.Script, soft_reload:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_recognized_extensions")
	public function _get_recognized_extensions():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_public_functions")
	public function _get_public_functions():Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3102165223.)
	@:hash_compatibility(null)
	@:nativeName("_get_public_constants")
	public function _get_public_constants():godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_public_annotations")
	public function _get_public_annotations():Array<godot.Dictionary>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_profiling_start")
	public function _profiling_start():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_profiling_stop")
	public function _profiling_stop():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_profiling_set_save_native_calls")
	public function _profiling_set_save_native_calls(enable:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_frame")
	public function _frame():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_handles_global_class_type")
	public function _handles_global_class_type(type:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2248993622.)
	@:hash_compatibility(null)
	@:nativeName("_get_global_class_name")
	public function _get_global_class_name(path:String):godot.Dictionary;
}