/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class ScriptExtension extends godot.Script {
	public function new();
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_editor_can_reload_from_file")
	public function _editor_can_reload_from_file():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_can_instantiate")
	public function _can_instantiate():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(278624046)
	@:hash_compatibility(null)
	@:nativeName("_get_base_script")
	public function _get_base_script():godot.Script;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2002593661)
	@:hash_compatibility(null)
	@:nativeName("_get_global_name")
	public function _get_global_name():godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3669307804.)
	@:hash_compatibility(null)
	@:nativeName("_inherits_script")
	public function _inherits_script(script:godot.Script):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2002593661)
	@:hash_compatibility(null)
	@:nativeName("_get_instance_base_type")
	public function _get_instance_base_type():godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_has_source_code")
	public function _has_source_code():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_source_code")
	public function _get_source_code():String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("_set_source_code")
	public function _set_source_code(code:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1413768114)
	@:hash_compatibility(null)
	@:nativeName("_reload")
	public function _reload(keep_state:Bool):godot.Error;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2002593661)
	@:hash_compatibility(null)
	@:nativeName("_get_doc_class_name")
	public function _get_doc_class_name():godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_documentation")
	public function _get_documentation():Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_class_icon_path")
	public function _get_class_icon_path():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("_has_method")
	public function _has_method(method:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("_has_static_method")
	public function _has_static_method(method:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2760726917.)
	@:hash_compatibility(null)
	@:nativeName("_get_script_method_argument_count")
	public function _get_script_method_argument_count(method:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4028089122.)
	@:hash_compatibility(null)
	@:nativeName("_get_method_info")
	public function _get_method_info(method:godot.StringName):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_tool")
	public function _is_tool():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_valid")
	public function _is_valid():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_abstract")
	public function _is_abstract():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3096237657.)
	@:hash_compatibility(null)
	@:nativeName("_get_language")
	public function _get_language():godot.ScriptLanguage;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("_has_script_signal")
	public function _has_script_signal(signal:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_script_signal_list")
	public function _get_script_signal_list():Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("_has_property_default_value")
	public function _has_property_default_value(property:godot.StringName):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2760726917.)
	@:hash_compatibility(null)
	@:nativeName("_get_property_default_value")
	public function _get_property_default_value(property:godot.StringName):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_update_exports")
	public function _update_exports():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_script_method_list")
	public function _get_script_method_list():Array<godot.Dictionary>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_script_property_list")
	public function _get_script_property_list():Array<godot.Dictionary>;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2458036349.)
	@:hash_compatibility(null)
	@:nativeName("_get_member_line")
	public function _get_member_line(member:godot.StringName):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3102165223.)
	@:hash_compatibility(null)
	@:nativeName("_get_constants")
	public function _get_constants():godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("_get_members")
	public function _get_members():Array<godot.StringName>;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_placeholder_fallback_enabled")
	public function _is_placeholder_fallback_enabled():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1214101251)
	@:hash_compatibility(null)
	@:nativeName("_get_rpc_config")
	public function _get_rpc_config():Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(397768994)
	@:hash_compatibility(null)
	@:nativeName("_instance_has")
	public function _instance_has(object:godot.Object):Bool;
}