/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("editor") @:is_resource(false) @:is_node(true) extern class ScriptEditor extends godot.PanelContainer {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1906266726)
	@:hash_compatibility(null)
	@:nativeName("get_current_editor")
	public function get_current_editor():godot.ScriptEditorBase;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("get_open_script_editors")
	public function get_open_script_editors():Array<godot.ScriptEditorBase>;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2981934095.)
	@:hash_compatibility(null)
	@:nativeName("get_breakpoints")
	public function get_breakpoints():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1092774468)
	@:hash_compatibility(null)
	@:nativeName("register_syntax_highlighter")
	public function register_syntax_highlighter(syntax_highlighter:godot.EditorSyntaxHighlighter):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1092774468)
	@:hash_compatibility(null)
	@:nativeName("unregister_syntax_highlighter")
	public function unregister_syntax_highlighter(syntax_highlighter:godot.EditorSyntaxHighlighter):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("goto_line")
	@:argMeta(0, ":meta"("int32"))
	public function goto_line(@:meta("int32") line_number:Int):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2146468882)
	@:hash_compatibility(null)
	@:nativeName("get_current_script")
	public function get_current_script():godot.Script;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3995934104.)
	@:hash_compatibility(null)
	@:nativeName("get_open_scripts")
	public function get_open_scripts():Array<godot.Script>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3186203200.)
	@:hash_compatibility(null)
	@:nativeName("open_script_create_dialog")
	public function open_script_create_dialog(base_name:String, base_path:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("reload_open_files")
	public function reload_open_files():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("goto_help")
	public function goto_help(topic:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3657522847.)
	@:hash_compatibility(null)
	@:nativeName("update_docs_from_script")
	public function update_docs_from_script(script:godot.Script):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3657522847.)
	@:hash_compatibility(null)
	@:nativeName("clear_docs_from_script")
	public function clear_docs_from_script(script:godot.Script):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_unsaved_files")
	public function get_unsaved_files():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("save_all_scripts")
	public function save_all_scripts():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166001499)
	@:hash_compatibility(null)
	@:nativeName("close_file")
	public function close_file(path:String):godot.Error;
}