/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("SliderJoint3D.Param") #end @:is_bitfield(false) extern enum SliderJoint3D_Param {
	PARAM_LINEAR_LIMIT_UPPER();
	PARAM_LINEAR_LIMIT_LOWER();
	PARAM_LINEAR_LIMIT_SOFTNESS();
	PARAM_LINEAR_LIMIT_RESTITUTION();
	PARAM_LINEAR_LIMIT_DAMPING();
	PARAM_LINEAR_MOTION_SOFTNESS();
	PARAM_LINEAR_MOTION_RESTITUTION();
	PARAM_LINEAR_MOTION_DAMPING();
	PARAM_LINEAR_ORTHOGONAL_SOFTNESS();
	PARAM_LINEAR_ORTHOGONAL_RESTITUTION();
	PARAM_LINEAR_ORTHOGONAL_DAMPING();
	PARAM_ANGULAR_LIMIT_UPPER();
	PARAM_ANGULAR_LIMIT_LOWER();
	PARAM_ANGULAR_LIMIT_SOFTNESS();
	PARAM_ANGULAR_LIMIT_RESTITUTION();
	PARAM_ANGULAR_LIMIT_DAMPING();
	PARAM_ANGULAR_MOTION_SOFTNESS();
	PARAM_ANGULAR_MOTION_RESTITUTION();
	PARAM_ANGULAR_MOTION_DAMPING();
	PARAM_ANGULAR_ORTHOGONAL_SOFTNESS();
	PARAM_ANGULAR_ORTHOGONAL_RESTITUTION();
	PARAM_ANGULAR_ORTHOGONAL_DAMPING();
	PARAM_MAX();
}