/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class SpriteFrames extends godot.Resource {
	public function new();
#if !use_properties
	@:index(null)
	@:getter("_get_animations")
	@:setter("_set_animations")
	public var animations : GodotArray;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("add_animation")
	public function add_animation(anim:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("has_animation")
	public function has_animation(anim:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("duplicate_animation")
	public function duplicate_animation(anim_from:godot.StringName, anim_to:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("remove_animation")
	public function remove_animation(anim:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("rename_animation")
	public function rename_animation(anim:godot.StringName, newname:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_animation_names")
	public function get_animation_names():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4135858297.)
	@:hash_compatibility(null)
	@:nativeName("set_animation_speed")
	@:argMeta(1, ":meta"("double"))
	public function set_animation_speed(anim:godot.StringName, @:meta("double") fps:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2349060816.)
	@:hash_compatibility(null)
	@:nativeName("get_animation_speed")
	public function get_animation_speed(anim:godot.StringName):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2524380260.)
	@:hash_compatibility(null)
	@:nativeName("set_animation_loop")
	public function set_animation_loop(anim:godot.StringName, loop:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2619796661.)
	@:hash_compatibility(null)
	@:nativeName("get_animation_loop")
	public function get_animation_loop(anim:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(918068248)
	@:hash_compatibility(null)
	@:nativeName("set_animation_loop_mode")
	public function set_animation_loop_mode(anim:godot.StringName, loop_mode:godot.SpriteFrames_LoopMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3606360228.)
	@:hash_compatibility(null)
	@:nativeName("get_animation_loop_mode")
	public function get_animation_loop_mode(anim:godot.StringName):godot.SpriteFrames_LoopMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1351332740)
	@:hash_compatibility([407562921])
	@:nativeName("add_frame")
	@:argMeta(2, ":meta"("float"))
	@:argMeta(2, ":default_value"("1.0"))
	#if gdscript @:argMeta(2, ":noNullPad"("1.0")) #end
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(3, ":default_value"("-1"))
	#if gdscript @:argMeta(3, ":noNullPad"("-1")) #end
	public function add_frame(anim:godot.StringName, texture:godot.Texture2D, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end duration:Float = 1., @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end at_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(56804795)
	@:hash_compatibility([3155743884.])
	@:nativeName("set_frame")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(3, ":meta"("float"))
	@:argMeta(3, ":default_value"("1.0"))
	#if gdscript @:argMeta(3, ":noNullPad"("1.0")) #end
	public function set_frame(anim:godot.StringName, @:meta("int32") idx:Int, texture:godot.Texture2D, @:meta("float") @:default_value("1.0") #if gdscript @:noNullPad("1.0") #end duration:Float = 1.):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2415702435.)
	@:hash_compatibility(null)
	@:nativeName("remove_frame")
	@:argMeta(1, ":meta"("int32"))
	public function remove_frame(anim:godot.StringName, @:meta("int32") idx:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2458036349.)
	@:hash_compatibility(null)
	@:nativeName("get_frame_count")
	public function get_frame_count(anim:godot.StringName):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2900517879.)
	@:hash_compatibility(null)
	@:nativeName("get_frame_texture")
	@:argMeta(1, ":meta"("int32"))
	public function get_frame_texture(anim:godot.StringName, @:meta("int32") idx:Int):godot.Texture2D;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1129309260)
	@:hash_compatibility(null)
	@:nativeName("get_frame_duration")
	@:argMeta(1, ":meta"("int32"))
	public function get_frame_duration(anim:godot.StringName, @:meta("int32") idx:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear(anim:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_all")
	public function clear_all():Void;
}