/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class SpringBoneSimulator3D extends godot.SkeletonModifier3D {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_external_force")
	@:setter("set_external_force")
	@:reassignOnSubfieldEdit(set_external_force_impl, x, y, z)
	public var external_force(get, set) : godot.Vector3;
#else

	@:index(null)
	@:getter("get_external_force")
	@:setter("set_external_force")
	public var external_force : godot.Vector3;
#end
#if use_properties
	@:index(null)
	@:getter("are_bone_axes_mutable")
	@:setter("set_mutable_bone_axes")
	public var mutable_bone_axes(get, set) : Bool;
#else

	@:index(null)
	@:getter("are_bone_axes_mutable")
	@:setter("set_mutable_bone_axes")
	public var mutable_bone_axes : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count(get, set) : Int;
#else

	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_root_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_root_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_root_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_root_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_root_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_root_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_root_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_root_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_end_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_end_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_extend_end_bone")
	@:argMeta(0, ":meta"("int32"))
	public function set_extend_end_bone(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_end_bone_extended")
	@:argMeta(0, ":meta"("int32"))
	public function is_end_bone_extended(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2838484201.)
	@:hash_compatibility([204796492])
	@:nativeName("set_end_bone_direction")
	@:argMeta(0, ":meta"("int32"))
	public function set_end_bone_direction(@:meta("int32") index:Int, bone_direction:godot.SkeletonModifier3D_BoneDirection):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1843036459)
	@:hash_compatibility([2438315700.])
	@:nativeName("get_end_bone_direction")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_direction(@:meta("int32") index:Int):godot.SkeletonModifier3D_BoneDirection;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_length")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_end_bone_length(@:meta("int32") index:Int, @:meta("float") length:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_length")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_length(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2551505749.)
	@:hash_compatibility(null)
	@:nativeName("set_center_from")
	@:argMeta(0, ":meta"("int32"))
	public function set_center_from(@:meta("int32") index:Int, center_from:godot.SpringBoneSimulator3D_CenterFrom):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2721930813.)
	@:hash_compatibility(null)
	@:nativeName("get_center_from")
	@:argMeta(0, ":meta"("int32"))
	public function get_center_from(@:meta("int32") index:Int):godot.SpringBoneSimulator3D_CenterFrom;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2761262315.)
	@:hash_compatibility(null)
	@:nativeName("set_center_node")
	@:argMeta(0, ":meta"("int32"))
	public function set_center_node(@:meta("int32") index:Int, node_path:godot.NodePath):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_center_node")
	@:argMeta(0, ":meta"("int32"))
	public function get_center_node(@:meta("int32") index:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_center_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_center_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_center_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_center_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_center_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_center_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_center_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_center_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_radius")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_radius(@:meta("int32") index:Int, @:meta("float") radius:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_radius")
	@:argMeta(0, ":meta"("int32"))
	public function get_radius(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1539703856)
	@:hash_compatibility([3534169209.])
	@:nativeName("set_rotation_axis")
	@:argMeta(0, ":meta"("int32"))
	public function set_rotation_axis(@:meta("int32") index:Int, axis:godot.SkeletonModifier3D_RotationAxis):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2844851118.)
	@:hash_compatibility([748837671])
	@:nativeName("get_rotation_axis")
	@:argMeta(0, ":meta"("int32"))
	public function get_rotation_axis(@:meta("int32") index:Int):godot.SkeletonModifier3D_RotationAxis;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530502735)
	@:hash_compatibility(null)
	@:nativeName("set_rotation_axis_vector")
	@:argMeta(0, ":meta"("int32"))
	public function set_rotation_axis_vector(@:meta("int32") index:Int, vector:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_rotation_axis_vector")
	@:argMeta(0, ":meta"("int32"))
	public function get_rotation_axis_vector(@:meta("int32") index:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1447180063)
	@:hash_compatibility(null)
	@:nativeName("set_radius_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function set_radius_damping_curve(@:meta("int32") index:Int, curve:godot.Curve):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(747537754)
	@:hash_compatibility(null)
	@:nativeName("get_radius_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function get_radius_damping_curve(@:meta("int32") index:Int):godot.Curve;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_stiffness")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_stiffness(@:meta("int32") index:Int, @:meta("float") stiffness:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_stiffness")
	@:argMeta(0, ":meta"("int32"))
	public function get_stiffness(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1447180063)
	@:hash_compatibility(null)
	@:nativeName("set_stiffness_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function set_stiffness_damping_curve(@:meta("int32") index:Int, curve:godot.Curve):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(747537754)
	@:hash_compatibility(null)
	@:nativeName("get_stiffness_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function get_stiffness_damping_curve(@:meta("int32") index:Int):godot.Curve;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_drag")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_drag(@:meta("int32") index:Int, @:meta("float") drag:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_drag")
	@:argMeta(0, ":meta"("int32"))
	public function get_drag(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1447180063)
	@:hash_compatibility(null)
	@:nativeName("set_drag_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function set_drag_damping_curve(@:meta("int32") index:Int, curve:godot.Curve):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(747537754)
	@:hash_compatibility(null)
	@:nativeName("get_drag_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function get_drag_damping_curve(@:meta("int32") index:Int):godot.Curve;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_gravity")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_gravity(@:meta("int32") index:Int, @:meta("float") gravity:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_gravity")
	@:argMeta(0, ":meta"("int32"))
	public function get_gravity(@:meta("int32") index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1447180063)
	@:hash_compatibility(null)
	@:nativeName("set_gravity_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function set_gravity_damping_curve(@:meta("int32") index:Int, curve:godot.Curve):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(747537754)
	@:hash_compatibility(null)
	@:nativeName("get_gravity_damping_curve")
	@:argMeta(0, ":meta"("int32"))
	public function get_gravity_damping_curve(@:meta("int32") index:Int):godot.Curve;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530502735)
	@:hash_compatibility(null)
	@:nativeName("set_gravity_direction")
	@:argMeta(0, ":meta"("int32"))
	public function set_gravity_direction(@:meta("int32") index:Int, gravity_direction:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_gravity_direction")
	@:argMeta(0, ":meta"("int32"))
	public function get_gravity_direction(@:meta("int32") index:Int):godot.Vector3;
#if use_properties
	public extern inline function set_setting_count(v: Int): Int {
		set_setting_count_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_setting_count")
	@:native("set_setting_count")
	@:argMeta(0, ":meta"("int32"))
	public function set_setting_count_impl(@:meta("int32") count:Int):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_setting_count")
	@:argMeta(0, ":meta"("int32"))
	public function set_setting_count(@:meta("int32") count:Int):Void;

#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_setting_count")
	public function get_setting_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_settings")
	public function clear_settings():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_individual_config")
	@:argMeta(0, ":meta"("int32"))
	public function set_individual_config(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_config_individual")
	@:argMeta(0, ":meta"("int32"))
	public function is_config_individual(@:meta("int32") index:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1391810591)
	@:hash_compatibility(null)
	@:nativeName("get_joint_bone_name")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_bone_name(@:meta("int32") index:Int, @:meta("int32") joint:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_bone(@:meta("int32") index:Int, @:meta("int32") joint:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1391134969)
	@:hash_compatibility([4224018032.])
	@:nativeName("set_joint_rotation_axis")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_joint_rotation_axis(@:meta("int32") index:Int, @:meta("int32") joint:Int, axis:godot.SkeletonModifier3D_RotationAxis):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3312594080.)
	@:hash_compatibility([2488679199.])
	@:nativeName("get_joint_rotation_axis")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_rotation_axis(@:meta("int32") index:Int, @:meta("int32") joint:Int):godot.SkeletonModifier3D_RotationAxis;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2866752138.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_rotation_axis_vector")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_joint_rotation_axis_vector(@:meta("int32") index:Int, @:meta("int32") joint:Int, vector:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1592972041)
	@:hash_compatibility(null)
	@:nativeName("get_joint_rotation_axis_vector")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_rotation_axis_vector(@:meta("int32") index:Int, @:meta("int32") joint:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_radius")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function set_joint_radius(@:meta("int32") index:Int, @:meta("int32") joint:Int, @:meta("float") radius:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_radius")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_radius(@:meta("int32") index:Int, @:meta("int32") joint:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_stiffness")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function set_joint_stiffness(@:meta("int32") index:Int, @:meta("int32") joint:Int, @:meta("float") stiffness:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_stiffness")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_stiffness(@:meta("int32") index:Int, @:meta("int32") joint:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_drag")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function set_joint_drag(@:meta("int32") index:Int, @:meta("int32") joint:Int, @:meta("float") drag:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_drag")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_drag(@:meta("int32") index:Int, @:meta("int32") joint:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3506521499.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_gravity")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("float"))
	public function set_joint_gravity(@:meta("int32") index:Int, @:meta("int32") joint:Int, @:meta("float") gravity:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3085491603.)
	@:hash_compatibility(null)
	@:nativeName("get_joint_gravity")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_gravity(@:meta("int32") index:Int, @:meta("int32") joint:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2866752138.)
	@:hash_compatibility(null)
	@:nativeName("set_joint_gravity_direction")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_joint_gravity_direction(@:meta("int32") index:Int, @:meta("int32") joint:Int, gravity_direction:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1592972041)
	@:hash_compatibility(null)
	@:nativeName("get_joint_gravity_direction")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_joint_gravity_direction(@:meta("int32") index:Int, @:meta("int32") joint:Int):godot.Vector3;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_joint_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_joint_count(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_enable_all_child_collisions")
	@:argMeta(0, ":meta"("int32"))
	public function set_enable_all_child_collisions(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("are_all_child_collisions_enabled")
	@:argMeta(0, ":meta"("int32"))
	public function are_all_child_collisions_enabled(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(132481804)
	@:hash_compatibility(null)
	@:nativeName("set_exclude_collision_path")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_exclude_collision_path(@:meta("int32") index:Int, @:meta("int32") collision:Int, node_path:godot.NodePath):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(464924783)
	@:hash_compatibility(null)
	@:nativeName("get_exclude_collision_path")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_exclude_collision_path(@:meta("int32") index:Int, @:meta("int32") collision:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_exclude_collision_count")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_exclude_collision_count(@:meta("int32") index:Int, @:meta("int32") count:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_exclude_collision_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_exclude_collision_count(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_exclude_collisions")
	@:argMeta(0, ":meta"("int32"))
	public function clear_exclude_collisions(@:meta("int32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(132481804)
	@:hash_compatibility(null)
	@:nativeName("set_collision_path")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_collision_path(@:meta("int32") index:Int, @:meta("int32") collision:Int, node_path:godot.NodePath):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(464924783)
	@:hash_compatibility(null)
	@:nativeName("get_collision_path")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_collision_path(@:meta("int32") index:Int, @:meta("int32") collision:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_collision_count")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_collision_count(@:meta("int32") index:Int, @:meta("int32") count:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_collision_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_collision_count(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_collisions")
	@:argMeta(0, ":meta"("int32"))
	public function clear_collisions(@:meta("int32") index:Int):Void;
#if use_properties
	public extern inline function set_external_force(v: godot.Vector3): godot.Vector3 {
		set_external_force_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_external_force")
	@:native("set_external_force")
	public function set_external_force_impl(force:godot.Vector3):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_external_force")
	public function set_external_force(force:godot.Vector3):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3360562783.)
	@:hash_compatibility(null)
	@:nativeName("get_external_force")
	public function get_external_force():godot.Vector3;
#if use_properties
	public extern inline function set_mutable_bone_axes(v: Bool): Bool {
		set_mutable_bone_axes_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_mutable_bone_axes")
	@:native("set_mutable_bone_axes")
	public function set_mutable_bone_axes_impl(enabled:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_mutable_bone_axes")
	public function set_mutable_bone_axes(enabled:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("are_bone_axes_mutable")
	@:native("are_bone_axes_mutable")
	public function get_mutable_bone_axes():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("reset")
	public function reset():Void;
}