/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(false) @:api_type("core") @:is_resource(true) @:is_node(false) extern class StreamPeer extends godot.RefCounted {
	public function new();
#if use_properties
	@:index(null)
	@:getter("is_big_endian_enabled")
	@:setter("set_big_endian")
	public var big_endian(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_big_endian_enabled")
	@:setter("set_big_endian")
	public var big_endian : Bool;
#end
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(680677267)
	@:hash_compatibility(null)
	@:nativeName("put_data")
	public function put_data(data:godot.PackedByteArray):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2934048347.)
	@:hash_compatibility(null)
	@:nativeName("put_partial_data")
	public function put_partial_data(data:godot.PackedByteArray):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1171824711)
	@:hash_compatibility(null)
	@:nativeName("get_data")
	@:argMeta(0, ":meta"("int32"))
	public function get_data(@:meta("int32") bytes:Int):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1171824711)
	@:hash_compatibility(null)
	@:nativeName("get_partial_data")
	@:argMeta(0, ":meta"("int32"))
	public function get_partial_data(@:meta("int32") bytes:Int):GodotArray;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_available_bytes")
	public function get_available_bytes():Int;
#if use_properties
	public extern inline function set_big_endian(v: Bool): Bool {
		set_big_endian_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_big_endian")
	@:native("set_big_endian")
	public function set_big_endian_impl(enable:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_big_endian")
	public function set_big_endian(enable:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_big_endian_enabled")
	@:native("is_big_endian_enabled")
	public function get_big_endian():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_8")
	@:argMeta(0, ":meta"("int8"))
	public function put_8(@:meta("int8") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_u8")
	@:argMeta(0, ":meta"("uint8"))
	public function put_u8(@:meta("uint8") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_16")
	@:argMeta(0, ":meta"("int16"))
	public function put_16(@:meta("int16") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_u16")
	@:argMeta(0, ":meta"("uint16"))
	public function put_u16(@:meta("uint16") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_32")
	@:argMeta(0, ":meta"("int32"))
	public function put_32(@:meta("int32") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_u32")
	@:argMeta(0, ":meta"("uint32"))
	public function put_u32(@:meta("uint32") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_64")
	@:argMeta(0, ":meta"("int64"))
	public function put_64(@:meta("int64") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("put_u64")
	@:argMeta(0, ":meta"("uint64"))
	public function put_u64(@:meta("uint64") value:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("put_half")
	@:argMeta(0, ":meta"("float"))
	public function put_half(@:meta("float") value:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("put_float")
	@:argMeta(0, ":meta"("float"))
	public function put_float(@:meta("float") value:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("put_double")
	@:argMeta(0, ":meta"("double"))
	public function put_double(@:meta("double") value:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("put_string")
	public function put_string(value:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(83702148)
	@:hash_compatibility(null)
	@:nativeName("put_utf8_string")
	public function put_utf8_string(value:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(738511890)
	@:hash_compatibility(null)
	@:nativeName("put_var")
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public function put_var(value:Dynamic, @:default_value("false") #if gdscript @:noNullPad("false") #end full_objects:Bool = false):Void;
	@:return_value_meta("int8")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_8")
	public function get_8():Int;
	@:return_value_meta("uint8")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_u8")
	public function get_u8():Int;
	@:return_value_meta("int16")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_16")
	public function get_16():Int;
	@:return_value_meta("uint16")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_u16")
	public function get_u16():Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_32")
	public function get_32():Int;
	@:return_value_meta("uint32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_u32")
	public function get_u32():Int;
	@:return_value_meta("int64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_64")
	public function get_64():Int;
	@:return_value_meta("uint64")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_u64")
	public function get_u64():Int;
	@:return_value_meta("float")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(191475506)
	@:hash_compatibility(null)
	@:nativeName("get_half")
	public function get_half():Float;
	@:return_value_meta("float")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(191475506)
	@:hash_compatibility(null)
	@:nativeName("get_float")
	public function get_float():Float;
	@:return_value_meta("double")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(191475506)
	@:hash_compatibility(null)
	@:nativeName("get_double")
	public function get_double():Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2309358862.)
	@:hash_compatibility(null)
	@:nativeName("get_string")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function get_string(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end bytes:Int = -1):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2309358862.)
	@:hash_compatibility(null)
	@:nativeName("get_utf8_string")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function get_utf8_string(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end bytes:Int = -1):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3442865206.)
	@:hash_compatibility(null)
	@:nativeName("get_var")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_var(@:default_value("false") #if gdscript @:noNullPad("false") #end allow_objects:Bool = false):Dynamic;
}