/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("builtin_classes") @:indexing_return_type(null) @:is_keyed(false) @:has_destructor(true) @:copyType @:noCompletion @:avoid_temporaries @:nativeName("StringName") extern class StringName_Fields {
	@:overload(function(from:godot.StringName):Void { })
	@:overload(function(from:String):Void { })
	public function new();
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("casecmp_to")
	public function casecmp_to(@:default_value(null) to:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("nocasecmp_to")
	public function nocasecmp_to(@:default_value(null) to:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("naturalcasecmp_to")
	public function naturalcasecmp_to(@:default_value(null) to:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("naturalnocasecmp_to")
	public function naturalnocasecmp_to(@:default_value(null) to:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("filecasecmp_to")
	public function filecasecmp_to(@:default_value(null) to:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("filenocasecmp_to")
	public function filenocasecmp_to(@:default_value(null) to:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("length")
	public function length():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(787537301)
	@:nativeName("substr")
	public function substr(@:default_value(null) from:Int, @:default_value("-1") ?len:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3535100402.)
	@:nativeName("get_slice")
	public function get_slice(@:default_value(null) delimiter:String, @:default_value(null) slice:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(787537301)
	@:nativeName("get_slicec")
	public function get_slicec(@:default_value(null) delimiter:Int, @:default_value(null) slice:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2920860731.)
	@:nativeName("get_slice_count")
	public function get_slice_count(@:default_value(null) delimiter:String):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1760645412)
	@:nativeName("find")
	public function find(@:default_value(null) what:String, @:default_value("0") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1760645412)
	@:nativeName("findn")
	public function findn(@:default_value(null) what:String, @:default_value("0") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2343087891.)
	@:nativeName("count")
	public function count(@:default_value(null) what:String, @:default_value("0") ?from:Int, @:default_value("0") ?to:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2343087891.)
	@:nativeName("countn")
	public function countn(@:default_value(null) what:String, @:default_value("0") ?from:Int, @:default_value("0") ?to:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1760645412)
	@:nativeName("rfind")
	public function rfind(@:default_value(null) what:String, @:default_value("-1") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1760645412)
	@:nativeName("rfindn")
	public function rfindn(@:default_value(null) what:String, @:default_value("-1") ?from:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("match")
	public function match(@:default_value(null) expr:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("matchn")
	public function matchn(@:default_value(null) expr:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("begins_with")
	public function begins_with(@:default_value(null) text:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("ends_with")
	public function ends_with(@:default_value(null) text:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("is_subsequence_of")
	public function is_subsequence_of(@:default_value(null) text:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("is_subsequence_ofn")
	public function is_subsequence_ofn(@:default_value(null) text:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(747180633)
	@:nativeName("bigrams")
	public function bigrams():godot.PackedStringArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2697460964.)
	@:nativeName("similarity")
	public function similarity(@:default_value(null) text:String):Float;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3212199029.)
	@:nativeName("format")
	public function format(@:default_value(null) values:Dynamic, @:default_value("\"{_}\"") ?placeholder:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1340436205)
	@:nativeName("replace")
	public function replace(@:default_value(null) what:String, @:default_value(null) forwhat:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1340436205)
	@:nativeName("replacen")
	public function replacen(@:default_value(null) what:String, @:default_value(null) forwhat:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(787537301)
	@:nativeName("replace_char")
	public function replace_char(@:default_value(null) key:Int, @:default_value(null) with:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3535100402.)
	@:nativeName("replace_chars")
	public function replace_chars(@:default_value(null) keys:String, @:default_value(null) with:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2162347432.)
	@:nativeName("remove_char")
	public function remove_char(@:default_value(null) what:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("remove_chars")
	public function remove_chars(@:default_value(null) chars:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2162347432.)
	@:nativeName("repeat")
	public function repeat(@:default_value(null) count:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("reverse")
	public function reverse():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(248737229)
	@:nativeName("insert")
	public function insert(@:default_value(null) position:Int, @:default_value(null) what:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(787537301)
	@:nativeName("erase")
	public function erase(@:default_value(null) position:Int, @:default_value("1") ?chars:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("capitalize")
	public function capitalize():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("to_camel_case")
	public function to_camel_case():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("to_pascal_case")
	public function to_pascal_case():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("to_snake_case")
	public function to_snake_case():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("to_kebab_case")
	public function to_kebab_case():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1252735785)
	@:nativeName("split")
	public function split(@:default_value("\"\"") ?delimiter:String, @:default_value("true") ?allow_empty:Bool, @:default_value("0") ?maxsplit:Int):godot.PackedStringArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(1252735785)
	@:nativeName("rsplit")
	public function rsplit(@:default_value("\"\"") ?delimiter:String, @:default_value("true") ?allow_empty:Bool, @:default_value("0") ?maxsplit:Int):godot.PackedStringArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2092079095)
	@:nativeName("split_floats")
	public function split_floats(@:default_value(null) delimiter:String, @:default_value("true") ?allow_empty:Bool):godot.PackedFloat64Array;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3595973238.)
	@:nativeName("join")
	public function join(@:default_value(null) parts:godot.PackedStringArray):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("to_upper")
	public function to_upper():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("to_lower")
	public function to_lower():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2162347432.)
	@:nativeName("left")
	public function left(@:default_value(null) length:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2162347432.)
	@:nativeName("right")
	public function right(@:default_value(null) length:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(907855311)
	@:nativeName("strip_edges")
	public function strip_edges(@:default_value("true") ?left:Bool, @:default_value("true") ?right:Bool):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("strip_escapes")
	public function strip_escapes():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("lstrip")
	public function lstrip(@:default_value(null) chars:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("rstrip")
	public function rstrip(@:default_value(null) chars:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_extension")
	public function get_extension():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_basename")
	public function get_basename():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("path_join")
	public function path_join(@:default_value(null) path:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(4103005248.)
	@:nativeName("unicode_at")
	public function unicode_at(@:default_value(null) at:Int):Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("indent")
	public function indent(@:default_value(null) prefix:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("dedent")
	public function dedent():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("md5_text")
	public function md5_text():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("sha1_text")
	public function sha1_text():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("sha256_text")
	public function sha256_text():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("md5_buffer")
	public function md5_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("sha1_buffer")
	public function sha1_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("sha256_buffer")
	public function sha256_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_empty")
	public function is_empty():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("contains")
	public function contains(@:default_value(null) what:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2566493496.)
	@:nativeName("containsn")
	public function containsn(@:default_value(null) what:String):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_absolute_path")
	public function is_absolute_path():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_relative_path")
	public function is_relative_path():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("simplify_path")
	public function simplify_path():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_base_dir")
	public function get_base_dir():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("get_file")
	public function get_file():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3429816538.)
	@:nativeName("xml_escape")
	public function xml_escape(@:default_value("false") ?escape_quotes:Bool):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("xml_unescape")
	public function xml_unescape():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("uri_encode")
	public function uri_encode():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("uri_decode")
	public function uri_decode():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("uri_file_decode")
	public function uri_file_decode():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("c_escape")
	public function c_escape():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("c_unescape")
	public function c_unescape():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("json_escape")
	public function json_escape():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("validate_node_name")
	public function validate_node_name():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3942272618.)
	@:nativeName("validate_filename")
	public function validate_filename():String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_ascii_identifier")
	public function is_valid_ascii_identifier():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_unicode_identifier")
	public function is_valid_unicode_identifier():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_identifier")
	public function is_valid_identifier():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_int")
	public function is_valid_int():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_float")
	public function is_valid_float():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(593672999)
	@:nativeName("is_valid_hex_number")
	public function is_valid_hex_number(@:default_value("false") ?with_prefix:Bool):Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_html_color")
	public function is_valid_html_color():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_ip_address")
	public function is_valid_ip_address():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3918633141.)
	@:nativeName("is_valid_filename")
	public function is_valid_filename():Bool;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("to_int")
	public function to_int():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(466405837)
	@:nativeName("to_float")
	public function to_float():Float;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("hex_to_int")
	public function hex_to_int():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("bin_to_int")
	public function bin_to_int():Int;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(248737229)
	@:nativeName("lpad")
	public function lpad(@:default_value(null) min_length:Int, @:default_value("\" \"") ?character:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(248737229)
	@:nativeName("rpad")
	public function rpad(@:default_value(null) min_length:Int, @:default_value("\" \"") ?character:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2162347432.)
	@:nativeName("pad_decimals")
	public function pad_decimals(@:default_value(null) digits:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(2162347432.)
	@:nativeName("pad_zeros")
	public function pad_zeros(@:default_value(null) digits:Int):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("trim_prefix")
	public function trim_prefix(@:default_value(null) prefix:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3134094431.)
	@:nativeName("trim_suffix")
	public function trim_suffix(@:default_value(null) suffix:String):String;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("to_ascii_buffer")
	public function to_ascii_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("to_utf8_buffer")
	public function to_utf8_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("to_utf16_buffer")
	public function to_utf16_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("to_utf32_buffer")
	public function to_utf32_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("to_wchar_buffer")
	public function to_wchar_buffer():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3055765187.)
	@:nativeName("to_multibyte_char_buffer")
	public function to_multibyte_char_buffer(@:default_value("\"\"") ?encoding:String):godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(247621236)
	@:nativeName("hex_decode")
	public function hex_decode():godot.PackedByteArray;
	@:is_vararg(false)
	@:is_const(true)
	@:is_static(false)
	@:hash(3173160232.)
	@:nativeName("hash")
	public function hash():Int;
}