/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class SurfaceTool extends godot.RefCounted {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(618679515)
	@:hash_compatibility(null)
	@:nativeName("set_skin_weight_count")
	public function set_skin_weight_count(count:godot.SurfaceTool_SkinWeightCount):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1072401130)
	@:hash_compatibility(null)
	@:nativeName("get_skin_weight_count")
	public function get_skin_weight_count():godot.SurfaceTool_SkinWeightCount;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4087759856.)
	@:hash_compatibility(null)
	@:nativeName("set_custom_format")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_format(@:meta("int32") channel_index:Int, format:godot.SurfaceTool_CustomFormat):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(839863283)
	@:hash_compatibility(null)
	@:nativeName("get_custom_format")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_format(@:meta("int32") channel_index:Int):godot.SurfaceTool_CustomFormat;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2230304113.)
	@:hash_compatibility(null)
	@:nativeName("begin")
	public function begin(primitive:godot.Mesh_PrimitiveType):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("add_vertex")
	public function add_vertex(vertex:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2920490490.)
	@:hash_compatibility(null)
	@:nativeName("set_color")
	public function set_color(color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3460891852.)
	@:hash_compatibility(null)
	@:nativeName("set_normal")
	public function set_normal(normal:godot.Vector3):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3505987427.)
	@:hash_compatibility(null)
	@:nativeName("set_tangent")
	public function set_tangent(tangent:godot.Plane):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("set_uv")
	public function set_uv(uv:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(743155724)
	@:hash_compatibility(null)
	@:nativeName("set_uv2")
	public function set_uv2(uv2:godot.Vector2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3614634198.)
	@:hash_compatibility(null)
	@:nativeName("set_bones")
	public function set_bones(bones:godot.PackedInt32Array):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2899603908.)
	@:hash_compatibility(null)
	@:nativeName("set_weights")
	public function set_weights(weights:godot.PackedFloat32Array):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_custom")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom(@:meta("int32") channel_index:Int, custom_color:godot.Color):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_smooth_group")
	@:argMeta(0, ":meta"("uint32"))
	public function set_smooth_group(@:meta("uint32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2235017613.)
	@:hash_compatibility([297960074])
	@:nativeName("add_triangle_fan")
	@:argMeta(1, ":default_value"("PackedVector2Array()"))
	#if gdscript @:argMeta(1, ":noNullPad"("PackedVector2Array()")) #end
	@:argMeta(2, ":default_value"("PackedColorArray()"))
	#if gdscript @:argMeta(2, ":noNullPad"("PackedColorArray()")) #end
	@:argMeta(3, ":default_value"("PackedVector2Array()"))
	#if gdscript @:argMeta(3, ":noNullPad"("PackedVector2Array()")) #end
	@:argMeta(4, ":default_value"("PackedVector3Array()"))
	#if gdscript @:argMeta(4, ":noNullPad"("PackedVector3Array()")) #end
	@:argMeta(5, ":default_value"("Array[Plane]([])"))
	#if gdscript @:argMeta(5, ":noNullPad"("[]")) #end
	public function add_triangle_fan(vertices:godot.PackedVector3Array, @:default_value("PackedVector2Array()") #if gdscript @:noNullPad("PackedVector2Array()") #end ?uvs:godot.PackedVector2Array, @:default_value("PackedColorArray()") #if gdscript @:noNullPad("PackedColorArray()") #end ?colors:godot.PackedColorArray, @:default_value("PackedVector2Array()") #if gdscript @:noNullPad("PackedVector2Array()") #end ?uv2s:godot.PackedVector2Array, @:default_value("PackedVector3Array()") #if gdscript @:noNullPad("PackedVector3Array()") #end ?normals:godot.PackedVector3Array, @:default_value("Array[Plane]([])") #if gdscript @:noNullPad("[]") #end ?tangents:Array<godot.Plane>):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("add_index")
	@:argMeta(0, ":meta"("int32"))
	public function add_index(@:meta("int32") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("index")
	public function index():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("deindex")
	public function deindex():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(107499316)
	@:hash_compatibility(null)
	@:nativeName("generate_normals")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function generate_normals(@:default_value("false") #if gdscript @:noNullPad("false") #end flip:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("generate_tangents")
	public function generate_tangents():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("optimize_indices_for_cache")
	public function optimize_indices_for_cache():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1068685055)
	@:hash_compatibility(null)
	@:nativeName("get_aabb")
	public function get_aabb():godot.AABB;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1938056459)
	@:hash_compatibility([1894448909])
	@:nativeName("generate_lod")
	@:argMeta(0, ":meta"("float"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("3"))
	#if gdscript @:argMeta(1, ":noNullPad"("3")) #end
	public function generate_lod(@:meta("float") nd_threshold:Float, @:meta("int32") @:default_value("3") #if gdscript @:noNullPad("3") #end target_index_count:Int = 3):godot.PackedInt32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2757459619.)
	@:hash_compatibility(null)
	@:nativeName("set_material")
	public function set_material(material:godot.Material):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(768822145)
	@:hash_compatibility(null)
	@:nativeName("get_primitive_type")
	public function get_primitive_type():godot.Mesh_PrimitiveType;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1767024570)
	@:hash_compatibility(null)
	@:nativeName("create_from")
	@:argMeta(1, ":meta"("int32"))
	public function create_from(existing:godot.Mesh, @:meta("int32") surface:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1894639680)
	@:hash_compatibility(null)
	@:nativeName("create_from_arrays")
	@:argMeta(1, ":default_value"("Mesh.PrimitiveType.PRIMITIVE_TRIANGLES"))
	#if gdscript @:argMeta(1, ":noNullPad"("Mesh.PrimitiveType.PRIMITIVE_TRIANGLES")) #end
	public function create_from_arrays(arrays:GodotArray, @:default_value("Mesh.PrimitiveType.PRIMITIVE_TRIANGLES") #if gdscript @:noNullPad("Mesh.PrimitiveType.PRIMITIVE_TRIANGLES") #end primitive_type:godot.Mesh_PrimitiveType = godot.Mesh_PrimitiveType.PRIMITIVE_TRIANGLES):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1306185582)
	@:hash_compatibility(null)
	@:nativeName("create_from_blend_shape")
	@:argMeta(1, ":meta"("int32"))
	public function create_from_blend_shape(existing:godot.Mesh, @:meta("int32") surface:Int, blend_shape:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2217967155.)
	@:hash_compatibility(null)
	@:nativeName("append_from")
	@:argMeta(1, ":meta"("int32"))
	public function append_from(existing:godot.Mesh, @:meta("int32") surface:Int, transform:godot.Transform3D):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4107864055.)
	@:hash_compatibility(null)
	@:nativeName("commit")
	@:argMeta(0, ":default_value"("null"))
	#if gdscript @:argMeta(0, ":noNullPad"("null")) #end
	@:argMeta(1, ":meta"("uint64"))
	@:argMeta(1, ":default_value"("0"))
	#if gdscript @:argMeta(1, ":noNullPad"("0")) #end
	public function commit(@:default_value("null") #if gdscript @:noNullPad("null") #end existing:godot.ArrayMesh = null, @:meta("uint64") @:default_value("0") #if gdscript @:noNullPad("0") #end flags:Int = 0):godot.ArrayMesh;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("commit_to_arrays")
	public function commit_to_arrays():GodotArray;
}