/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class TextServerExtension extends godot.TextServer {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3967367083.)
	@:hash_compatibility(null)
	@:nativeName("_has_feature")
	public function _has_feature(feature:godot.TextServer_Feature):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_name")
	public function _get_name():String;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_features")
	public function _get_features():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_free_rid")
	public function _free_rid(rid:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("_has")
	public function _has(rid:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2323990056.)
	@:hash_compatibility(null)
	@:nativeName("_load_support_data")
	public function _load_support_data(filename:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_support_data_filename")
	public function _get_support_data_filename():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_support_data_info")
	public function _get_support_data_info():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_save_support_data")
	public function _save_support_data(filename:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2362200018.)
	@:hash_compatibility(null)
	@:nativeName("_get_support_data")
	public function _get_support_data():godot.PackedByteArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_is_locale_using_support_data")
	public function _is_locale_using_support_data(locale:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_is_locale_right_to_left")
	public function _is_locale_right_to_left(locale:String):Bool;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1321353865)
	@:hash_compatibility(null)
	@:nativeName("_name_to_tag")
	public function _name_to_tag(name:String):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_tag_to_name")
	@:argMeta(0, ":meta"("int64"))
	public function _tag_to_name(@:meta("int64") tag:Int):String;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_create_font")
	public function _create_font():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(41030802)
	@:hash_compatibility(null)
	@:nativeName("_create_font_linked_variation")
	public function _create_font_linked_variation(font_rid:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1355495400)
	@:hash_compatibility(null)
	@:nativeName("_font_set_data")
	public function _font_set_data(font_rid:godot.RID, data:godot.PackedByteArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_face_index")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_face_index(font_rid:godot.RID, @:meta("int64") face_index:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_face_index")
	public function _font_get_face_index(font_rid:godot.RID):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_face_count")
	public function _font_get_face_count(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(898466325)
	@:hash_compatibility(null)
	@:nativeName("_font_set_style")
	public function _font_set_style(font_rid:godot.RID, style:godot.TextServer_FontStyle):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3082502592.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_style")
	public function _font_get_style(font_rid:godot.RID):godot.TextServer_FontStyle;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_name")
	public function _font_set_name(font_rid:godot.RID, name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(642473191)
	@:hash_compatibility(null)
	@:nativeName("_font_get_name")
	public function _font_get_name(font_rid:godot.RID):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1882737106)
	@:hash_compatibility(null)
	@:nativeName("_font_get_ot_name_strings")
	public function _font_get_ot_name_strings(font_rid:godot.RID):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_style_name")
	public function _font_set_style_name(font_rid:godot.RID, name_style:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(642473191)
	@:hash_compatibility(null)
	@:nativeName("_font_get_style_name")
	public function _font_get_style_name(font_rid:godot.RID):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_weight")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_weight(font_rid:godot.RID, @:meta("int64") weight:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_weight")
	public function _font_get_weight(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_stretch")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_stretch(font_rid:godot.RID, @:meta("int64") stretch:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_stretch")
	public function _font_get_stretch(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(958337235)
	@:hash_compatibility(null)
	@:nativeName("_font_set_antialiasing")
	public function _font_set_antialiasing(font_rid:godot.RID, antialiasing:godot.TextServer_FontAntialiasing):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3389420495.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_antialiasing")
	public function _font_get_antialiasing(font_rid:godot.RID):godot.TextServer_FontAntialiasing;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_disable_embedded_bitmaps")
	public function _font_set_disable_embedded_bitmaps(font_rid:godot.RID, disable_embedded_bitmaps:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_disable_embedded_bitmaps")
	public function _font_get_disable_embedded_bitmaps(font_rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_generate_mipmaps")
	public function _font_set_generate_mipmaps(font_rid:godot.RID, generate_mipmaps:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_generate_mipmaps")
	public function _font_get_generate_mipmaps(font_rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_multichannel_signed_distance_field")
	public function _font_set_multichannel_signed_distance_field(font_rid:godot.RID, msdf:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_is_multichannel_signed_distance_field")
	public function _font_is_multichannel_signed_distance_field(font_rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_msdf_pixel_range")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_msdf_pixel_range(font_rid:godot.RID, @:meta("int64") msdf_pixel_range:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_msdf_pixel_range")
	public function _font_get_msdf_pixel_range(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_msdf_size")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_msdf_size(font_rid:godot.RID, @:meta("int64") msdf_size:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_msdf_size")
	public function _font_get_msdf_size(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_fixed_size")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_fixed_size(font_rid:godot.RID, @:meta("int64") fixed_size:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_fixed_size")
	public function _font_get_fixed_size(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1029390307)
	@:hash_compatibility(null)
	@:nativeName("_font_set_fixed_size_scale_mode")
	public function _font_set_fixed_size_scale_mode(font_rid:godot.RID, fixed_size_scale_mode:godot.TextServer_FixedSizeScaleMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4113120379.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_fixed_size_scale_mode")
	public function _font_get_fixed_size_scale_mode(font_rid:godot.RID):godot.TextServer_FixedSizeScaleMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_allow_system_fallback")
	public function _font_set_allow_system_fallback(font_rid:godot.RID, allow_system_fallback:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_is_allow_system_fallback")
	public function _font_is_allow_system_fallback(font_rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_font_clear_system_fallback_cache")
	public function _font_clear_system_fallback_cache():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_force_autohinter")
	public function _font_set_force_autohinter(font_rid:godot.RID, force_autohinter:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_is_force_autohinter")
	public function _font_is_force_autohinter(font_rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_modulate_color_glyphs")
	public function _font_set_modulate_color_glyphs(font_rid:godot.RID, modulate:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_is_modulate_color_glyphs")
	public function _font_is_modulate_color_glyphs(font_rid:godot.RID):Bool;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_palette_count")
	public function _font_get_palette_count(font_rid:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("_font_get_palette_name")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_palette_name(font_rid:godot.RID, @:meta("int64") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1595517857)
	@:hash_compatibility(null)
	@:nativeName("_font_get_palette_colors")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_palette_colors(font_rid:godot.RID, @:meta("int64") index:Int):godot.PackedColorArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4037098590.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_palette_custom_colors")
	public function _font_set_palette_custom_colors(font_rid:godot.RID, colors:godot.PackedColorArray):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1569415609)
	@:hash_compatibility(null)
	@:nativeName("_font_get_palette_custom_colors")
	public function _font_get_palette_custom_colors(font_rid:godot.RID):godot.PackedColorArray;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_used_palette")
	public function _font_get_used_palette(font_rid:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_used_palette")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_used_palette(font_rid:godot.RID, @:meta("int64") index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1520010864)
	@:hash_compatibility(null)
	@:nativeName("_font_set_hinting")
	public function _font_set_hinting(font_rid:godot.RID, hinting:godot.TextServer_Hinting):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3971592737.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_hinting")
	public function _font_get_hinting(font_rid:godot.RID):godot.TextServer_Hinting;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3830459669.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_subpixel_positioning")
	public function _font_set_subpixel_positioning(font_rid:godot.RID, subpixel_positioning:godot.TextServer_SubpixelPositioning):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2752233671.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_subpixel_positioning")
	public function _font_get_subpixel_positioning(font_rid:godot.RID):godot.TextServer_SubpixelPositioning;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_font_set_keep_rounding_remainders")
	public function _font_set_keep_rounding_remainders(font_rid:godot.RID, keep_rounding_remainders:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_keep_rounding_remainders")
	public function _font_get_keep_rounding_remainders(font_rid:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_font_set_embolden")
	@:argMeta(1, ":meta"("double"))
	public function _font_set_embolden(font_rid:godot.RID, @:meta("double") strength:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_font_get_embolden")
	public function _font_get_embolden(font_rid:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1307259930)
	@:hash_compatibility(null)
	@:nativeName("_font_set_spacing")
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_spacing(font_rid:godot.RID, spacing:godot.TextServer_SpacingType, @:meta("int64") value:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1213653558)
	@:hash_compatibility(null)
	@:nativeName("_font_get_spacing")
	public function _font_get_spacing(font_rid:godot.RID, spacing:godot.TextServer_SpacingType):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_font_set_baseline_offset")
	@:argMeta(1, ":meta"("double"))
	public function _font_set_baseline_offset(font_rid:godot.RID, @:meta("double") baseline_offset:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_font_get_baseline_offset")
	public function _font_get_baseline_offset(font_rid:godot.RID):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1246044741)
	@:hash_compatibility(null)
	@:nativeName("_font_set_transform")
	public function _font_set_transform(font_rid:godot.RID, transform:godot.Transform2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(213527486)
	@:hash_compatibility(null)
	@:nativeName("_font_get_transform")
	public function _font_get_transform(font_rid:godot.RID):godot.Transform2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1217542888)
	@:hash_compatibility(null)
	@:nativeName("_font_set_variation_coordinates")
	public function _font_set_variation_coordinates(font_rid:godot.RID, variation_coordinates:godot.Dictionary):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1882737106)
	@:hash_compatibility(null)
	@:nativeName("_font_get_variation_coordinates")
	public function _font_get_variation_coordinates(font_rid:godot.RID):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1794382983)
	@:hash_compatibility(null)
	@:nativeName("_font_set_oversampling")
	@:argMeta(1, ":meta"("double"))
	public function _font_set_oversampling(font_rid:godot.RID, @:meta("double") oversampling:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_font_get_oversampling")
	public function _font_get_oversampling(font_rid:godot.RID):Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_size_cache_list")
	public function _font_get_size_cache_list(font_rid:godot.RID):Array<godot.Vector2i>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_font_clear_size_cache")
	public function _font_clear_size_cache(font_rid:godot.RID):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2450610377.)
	@:hash_compatibility(null)
	@:nativeName("_font_remove_size_cache")
	public function _font_remove_size_cache(font_rid:godot.RID, size:godot.Vector2i):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_size_cache_info")
	public function _font_get_size_cache_info(font_rid:godot.RID):Array<godot.Dictionary>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1892459533)
	@:hash_compatibility(null)
	@:nativeName("_font_set_ascent")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("double"))
	public function _font_set_ascent(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("double") ascent:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(755457166)
	@:hash_compatibility(null)
	@:nativeName("_font_get_ascent")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_ascent(font_rid:godot.RID, @:meta("int64") size:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1892459533)
	@:hash_compatibility(null)
	@:nativeName("_font_set_descent")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("double"))
	public function _font_set_descent(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("double") descent:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(755457166)
	@:hash_compatibility(null)
	@:nativeName("_font_get_descent")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_descent(font_rid:godot.RID, @:meta("int64") size:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1892459533)
	@:hash_compatibility(null)
	@:nativeName("_font_set_underline_position")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("double"))
	public function _font_set_underline_position(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("double") underline_position:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(755457166)
	@:hash_compatibility(null)
	@:nativeName("_font_get_underline_position")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_underline_position(font_rid:godot.RID, @:meta("int64") size:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1892459533)
	@:hash_compatibility(null)
	@:nativeName("_font_set_underline_thickness")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("double"))
	public function _font_set_underline_thickness(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("double") underline_thickness:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(755457166)
	@:hash_compatibility(null)
	@:nativeName("_font_get_underline_thickness")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_underline_thickness(font_rid:godot.RID, @:meta("int64") size:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1892459533)
	@:hash_compatibility(null)
	@:nativeName("_font_set_scale")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("double"))
	public function _font_set_scale(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("double") scale:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(755457166)
	@:hash_compatibility(null)
	@:nativeName("_font_get_scale")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_scale(font_rid:godot.RID, @:meta("int64") size:Int):Float;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1311001310)
	@:hash_compatibility(null)
	@:nativeName("_font_get_texture_count")
	public function _font_get_texture_count(font_rid:godot.RID, size:godot.Vector2i):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2450610377.)
	@:hash_compatibility(null)
	@:nativeName("_font_clear_textures")
	public function _font_clear_textures(font_rid:godot.RID, size:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3810512262.)
	@:hash_compatibility(null)
	@:nativeName("_font_remove_texture")
	@:argMeta(2, ":meta"("int64"))
	public function _font_remove_texture(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") texture_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2354485091.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_texture_image")
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_texture_image(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") texture_index:Int, image:godot.Image):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2451761155.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_texture_image")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_texture_image(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") texture_index:Int):godot.Image;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3005398047.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_texture_offsets")
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_texture_offsets(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") texture_index:Int, offset:godot.PackedInt32Array):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3420028887.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_texture_offsets")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_texture_offsets(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") texture_index:Int):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(46086620)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_list")
	public function _font_get_glyph_list(font_rid:godot.RID, size:godot.Vector2i):godot.PackedInt32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2450610377.)
	@:hash_compatibility(null)
	@:nativeName("_font_clear_glyphs")
	public function _font_clear_glyphs(font_rid:godot.RID, size:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3810512262.)
	@:hash_compatibility(null)
	@:nativeName("_font_remove_glyph")
	@:argMeta(2, ":meta"("int64"))
	public function _font_remove_glyph(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2555689501.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_advance")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_advance(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("int64") glyph:Int):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3219397315.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_glyph_advance")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_glyph_advance(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("int64") glyph:Int, advance:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(513728628)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_offset")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_offset(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1812632090)
	@:hash_compatibility(null)
	@:nativeName("_font_set_glyph_offset")
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_glyph_offset(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int, offset:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(513728628)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_size")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_size(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):godot.Vector2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1812632090)
	@:hash_compatibility(null)
	@:nativeName("_font_set_glyph_size")
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_glyph_size(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int, gl_size:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2274268786.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_uv_rect")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_uv_rect(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):godot.Rect2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1973324081)
	@:hash_compatibility(null)
	@:nativeName("_font_set_glyph_uv_rect")
	@:argMeta(2, ":meta"("int64"))
	public function _font_set_glyph_uv_rect(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int, uv_rect:godot.Rect2):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4292800474.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_texture_idx")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_texture_idx(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4254580980.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_glyph_texture_idx")
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(3, ":meta"("int64"))
	public function _font_set_glyph_texture_idx(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int, @:meta("int64") texture_idx:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1451696141)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_texture_rid")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_texture_rid(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(513728628)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_texture_size")
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_texture_size(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") glyph:Int):godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2903964473.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_contours")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_glyph_contours(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("int64") index:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1778388067)
	@:hash_compatibility(null)
	@:nativeName("_font_get_kerning_list")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_kerning_list(font_rid:godot.RID, @:meta("int64") size:Int):Array<godot.Vector2i>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_font_clear_kerning_map")
	@:argMeta(1, ":meta"("int64"))
	public function _font_clear_kerning_map(font_rid:godot.RID, @:meta("int64") size:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2141860016)
	@:hash_compatibility(null)
	@:nativeName("_font_remove_kerning")
	@:argMeta(1, ":meta"("int64"))
	public function _font_remove_kerning(font_rid:godot.RID, @:meta("int64") size:Int, glyph_pair:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3630965883.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_kerning")
	@:argMeta(1, ":meta"("int64"))
	public function _font_set_kerning(font_rid:godot.RID, @:meta("int64") size:Int, glyph_pair:godot.Vector2i, kerning:godot.Vector2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1019980169)
	@:hash_compatibility(null)
	@:nativeName("_font_get_kerning")
	@:argMeta(1, ":meta"("int64"))
	public function _font_get_kerning(font_rid:godot.RID, @:meta("int64") size:Int, glyph_pair:godot.Vector2i):godot.Vector2;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1765635060)
	@:hash_compatibility(null)
	@:nativeName("_font_get_glyph_index")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(3, ":meta"("int64"))
	public function _font_get_glyph_index(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("int64") char:Int, @:meta("int64") variation_selector:Int):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2156738276.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_char_from_glyph_index")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _font_get_char_from_glyph_index(font_rid:godot.RID, @:meta("int64") size:Int, @:meta("int64") glyph_index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3120086654.)
	@:hash_compatibility(null)
	@:nativeName("_font_has_char")
	@:argMeta(1, ":meta"("int64"))
	public function _font_has_char(font_rid:godot.RID, @:meta("int64") char:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(642473191)
	@:hash_compatibility(null)
	@:nativeName("_font_get_supported_chars")
	public function _font_get_supported_chars(font_rid:godot.RID):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(788230395)
	@:hash_compatibility(null)
	@:nativeName("_font_get_supported_glyphs")
	public function _font_get_supported_glyphs(font_rid:godot.RID):godot.PackedInt32Array;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4254580980.)
	@:hash_compatibility(null)
	@:nativeName("_font_render_range")
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(3, ":meta"("int64"))
	public function _font_render_range(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") start:Int, @:meta("int64") end:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3810512262.)
	@:hash_compatibility(null)
	@:nativeName("_font_render_glyph")
	@:argMeta(2, ":meta"("int64"))
	public function _font_render_glyph(font_rid:godot.RID, size:godot.Vector2i, @:meta("int64") index:Int):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(404525066)
	@:hash_compatibility([309868464])
	@:nativeName("_font_draw_glyph")
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(4, ":meta"("int64"))
	@:argMeta(6, ":meta"("float"))
	public function _font_draw_glyph(font_rid:godot.RID, canvas:godot.RID, @:meta("int64") size:Int, pos:godot.Vector2, @:meta("int64") index:Int, color:godot.Color, @:meta("float") oversampling:Float):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(940535541)
	@:hash_compatibility([3090733778.])
	@:nativeName("_font_draw_glyph_outline")
	@:argMeta(2, ":meta"("int64"))
	@:argMeta(3, ":meta"("int64"))
	@:argMeta(5, ":meta"("int64"))
	@:argMeta(7, ":meta"("float"))
	public function _font_draw_glyph_outline(font_rid:godot.RID, canvas:godot.RID, @:meta("int64") size:Int, @:meta("int64") outline_size:Int, pos:godot.Vector2, @:meta("int64") index:Int, color:godot.Color, @:meta("float") oversampling:Float):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3199320846.)
	@:hash_compatibility(null)
	@:nativeName("_font_is_language_supported")
	public function _font_is_language_supported(font_rid:godot.RID, language:String):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2313957094.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_language_support_override")
	public function _font_set_language_support_override(font_rid:godot.RID, language:String, supported:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2829184646.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_language_support_override")
	public function _font_get_language_support_override(font_rid:godot.RID, language:String):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("_font_remove_language_support_override")
	public function _font_remove_language_support_override(font_rid:godot.RID, language:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2801473409.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_language_support_overrides")
	public function _font_get_language_support_overrides(font_rid:godot.RID):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3199320846.)
	@:hash_compatibility(null)
	@:nativeName("_font_is_script_supported")
	public function _font_is_script_supported(font_rid:godot.RID, script:String):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2313957094.)
	@:hash_compatibility(null)
	@:nativeName("_font_set_script_support_override")
	public function _font_set_script_support_override(font_rid:godot.RID, script:String, supported:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2829184646.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_script_support_override")
	public function _font_get_script_support_override(font_rid:godot.RID, script:String):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("_font_remove_script_support_override")
	public function _font_remove_script_support_override(font_rid:godot.RID, script:String):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2801473409.)
	@:hash_compatibility(null)
	@:nativeName("_font_get_script_support_overrides")
	public function _font_get_script_support_overrides(font_rid:godot.RID):godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1217542888)
	@:hash_compatibility(null)
	@:nativeName("_font_set_opentype_feature_overrides")
	public function _font_set_opentype_feature_overrides(font_rid:godot.RID, overrides:godot.Dictionary):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1882737106)
	@:hash_compatibility(null)
	@:nativeName("_font_get_opentype_feature_overrides")
	public function _font_get_opentype_feature_overrides(font_rid:godot.RID):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1882737106)
	@:hash_compatibility(null)
	@:nativeName("_font_supported_feature_list")
	public function _font_supported_feature_list(font_rid:godot.RID):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1882737106)
	@:hash_compatibility(null)
	@:nativeName("_font_supported_variation_list")
	public function _font_supported_variation_list(font_rid:godot.RID):godot.Dictionary;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_font_get_global_oversampling")
	public function _font_get_global_oversampling():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_font_set_global_oversampling")
	@:argMeta(0, ":meta"("double"))
	public function _font_set_global_oversampling(@:meta("double") oversampling:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_reference_oversampling_level")
	@:argMeta(0, ":meta"("double"))
	public function _reference_oversampling_level(@:meta("double") oversampling:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_unreference_oversampling_level")
	@:argMeta(0, ":meta"("double"))
	public function _unreference_oversampling_level(@:meta("double") oversampling:Float):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3016396712.)
	@:hash_compatibility(null)
	@:nativeName("_get_hex_code_box_size")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":meta"("int64"))
	public function _get_hex_code_box_size(@:meta("int64") size:Int, @:meta("int64") index:Int):godot.Vector2;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1602046441)
	@:hash_compatibility(null)
	@:nativeName("_draw_hex_code_box")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(3, ":meta"("int64"))
	public function _draw_hex_code_box(canvas:godot.RID, @:meta("int64") size:Int, pos:godot.Vector2, @:meta("int64") index:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1431128392)
	@:hash_compatibility(null)
	@:nativeName("_create_shaped_text")
	public function _create_shaped_text(direction:godot.TextServer_Direction, orientation:godot.TextServer_Orientation):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2722037293.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_clear")
	public function _shaped_text_clear(shaped:godot.RID):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(41030802)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_duplicate")
	public function _shaped_text_duplicate(shaped:godot.RID):godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4276135416.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_direction")
	public function _shaped_text_set_direction(shaped:godot.RID, direction:godot.TextServer_Direction):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3065904362.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_direction")
	public function _shaped_text_get_direction(shaped:godot.RID):godot.TextServer_Direction;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3065904362.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_inferred_direction")
	public function _shaped_text_get_inferred_direction(shaped:godot.RID):godot.TextServer_Direction;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(684822712)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_bidi_override")
	public function _shaped_text_set_bidi_override(shaped:godot.RID, _override:GodotArray):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2726140452.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_custom_punctuation")
	public function _shaped_text_set_custom_punctuation(shaped:godot.RID, punct:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(642473191)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_custom_punctuation")
	public function _shaped_text_get_custom_punctuation(shaped:godot.RID):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3411492887.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_custom_ellipsis")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_set_custom_ellipsis(shaped:godot.RID, @:meta("int64") char:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_custom_ellipsis")
	public function _shaped_text_get_custom_ellipsis(shaped:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2306444742.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_orientation")
	public function _shaped_text_set_orientation(shaped:godot.RID, orientation:godot.TextServer_Orientation):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3142708106.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_orientation")
	public function _shaped_text_get_orientation(shaped:godot.RID):godot.TextServer_Orientation;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_preserve_invalid")
	public function _shaped_text_set_preserve_invalid(shaped:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_preserve_invalid")
	public function _shaped_text_get_preserve_invalid(shaped:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1265174801)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_preserve_control")
	public function _shaped_text_set_preserve_control(shaped:godot.RID, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_preserve_control")
	public function _shaped_text_get_preserve_control(shaped:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1307259930)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_set_spacing")
	@:argMeta(2, ":meta"("int64"))
	public function _shaped_text_set_spacing(shaped:godot.RID, spacing:godot.TextServer_SpacingType, @:meta("int64") value:Int):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1213653558)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_spacing")
	public function _shaped_text_get_spacing(shaped:godot.RID, spacing:godot.TextServer_SpacingType):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(875249313)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_add_string")
	@:argMeta(3, ":meta"("int64"))
	public function _shaped_text_add_string(shaped:godot.RID, text:String, fonts:Array<godot.RID>, @:meta("int64") size:Int, opentype_features:godot.Dictionary, language:String, meta:Dynamic):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2452224230.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_add_object")
	@:argMeta(4, ":meta"("int64"))
	@:argMeta(5, ":meta"("double"))
	public function _shaped_text_add_object(shaped:godot.RID, key:Dynamic, size:godot.Vector2, inline_align:godot.InlineAlignment, @:meta("int64") length:Int, @:meta("double") baseline:Float):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2747466775.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_resize_object")
	@:argMeta(4, ":meta"("double"))
	public function _shaped_text_resize_object(shaped:godot.RID, key:Dynamic, size:godot.Vector2, inline_align:godot.InlineAlignment, @:meta("double") baseline:Float):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2360964694.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_has_object")
	public function _shaped_text_has_object(shaped:godot.RID, key:Dynamic):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(642473191)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_text")
	public function _shaped_get_text(shaped:godot.RID):String;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_span_count")
	public function _shaped_get_span_count(shaped:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069510997.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_span_meta")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_span_meta(shaped:godot.RID, @:meta("int64") index:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069510997.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_span_embedded_object")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_span_embedded_object(shaped:godot.RID, @:meta("int64") index:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_span_text")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_span_text(shaped:godot.RID, @:meta("int64") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069510997.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_span_object")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_span_object(shaped:godot.RID, @:meta("int64") index:Int):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2569459151.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_set_span_update_font")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(3, ":meta"("int64"))
	public function _shaped_set_span_update_font(shaped:godot.RID, @:meta("int64") index:Int, fonts:Array<godot.RID>, @:meta("int64") size:Int, opentype_features:godot.Dictionary):Void;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_count")
	public function _shaped_get_run_count(shaped:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_text")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_text(shaped:godot.RID, @:meta("int64") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069534484.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_range")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_range(shaped:godot.RID, @:meta("int64") index:Int):godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069534484.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_glyph_range")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_glyph_range(shaped:godot.RID, @:meta("int64") index:Int):godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1066463050)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_font_rid")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_font_rid(shaped:godot.RID, @:meta("int64") index:Int):godot.RID;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_font_size")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_font_size(shaped:godot.RID, @:meta("int64") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1464764419)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_language")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_language(shaped:godot.RID, @:meta("int64") index:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2413896864.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_direction")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_direction(shaped:godot.RID, @:meta("int64") index:Int):godot.TextServer_Direction;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4069510997.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_get_run_object")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_get_run_object(shaped:godot.RID, @:meta("int64") index:Int):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1937682086)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_substr")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _shaped_text_substr(shaped:godot.RID, @:meta("int64") start:Int, @:meta("int64") length:Int):godot.RID;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3814569979.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_parent")
	public function _shaped_text_get_parent(shaped:godot.RID):godot.RID;
	@:return_value_meta("double")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1426448222)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_fit_to_width")
	@:argMeta(1, ":meta"("double"))
	public function _shaped_text_fit_to_width(shaped:godot.RID, @:meta("double") width:Float, justification_flags:godot.TextServer_JustificationFlag):Float;
	@:return_value_meta("double")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1283669550)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_tab_align")
	public function _shaped_text_tab_align(shaped:godot.RID, tab_stops:godot.PackedFloat32Array):Float;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_shape")
	public function _shaped_text_shape(shaped:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_update_breaks")
	public function _shaped_text_update_breaks(shaped:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_update_justification_ops")
	public function _shaped_text_update_justification_ops(shaped:godot.RID):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4155700596.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_is_ready")
	public function _shaped_text_is_ready(shaped:godot.RID):Bool;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_glyph_count")
	public function _shaped_text_get_glyph_count(shaped:godot.RID):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(733700038)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_range")
	public function _shaped_text_get_range(shaped:godot.RID):godot.Vector2i;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1488467363)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_line_breaks_adv")
	@:argMeta(2, ":meta"("int64"))
	public function _shaped_text_get_line_breaks_adv(shaped:godot.RID, width:godot.PackedFloat32Array, @:meta("int64") start:Int, once:Bool, break_flags:godot.TextServer_LineBreakFlag):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3131311977.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_line_breaks")
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("int64"))
	public function _shaped_text_get_line_breaks(shaped:godot.RID, @:meta("double") width:Float, @:meta("int64") start:Int, break_flags:godot.TextServer_LineBreakFlag):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2423529412.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_word_breaks")
	public function _shaped_text_get_word_breaks(shaped:godot.RID, grapheme_flags:godot.TextServer_GraphemeFlag, skip_grapheme_flags:godot.TextServer_GraphemeFlag):godot.PackedInt32Array;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_trim_pos")
	public function _shaped_text_get_trim_pos(shaped:godot.RID):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_ellipsis_pos")
	public function _shaped_text_get_ellipsis_pos(shaped:godot.RID):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2198884583.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_ellipsis_glyph_count")
	public function _shaped_text_get_ellipsis_glyph_count(shaped:godot.RID):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3364950921.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_overrun_trim_to_width")
	@:argMeta(1, ":meta"("double"))
	public function _shaped_text_overrun_trim_to_width(shaped:godot.RID, @:meta("double") width:Float, trim_flags:godot.TextServer_TextOverrunFlag):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2684255073.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_objects")
	public function _shaped_text_get_objects(shaped:godot.RID):GodotArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(447978354)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_object_rect")
	public function _shaped_text_get_object_rect(shaped:godot.RID, key:Dynamic):godot.Rect2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2524675647.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_object_range")
	public function _shaped_text_get_object_range(shaped:godot.RID, key:Dynamic):godot.Vector2i;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1260085030)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_object_glyph")
	public function _shaped_text_get_object_glyph(shaped:godot.RID, key:Dynamic):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2440833711.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_size")
	public function _shaped_text_get_size(shaped:godot.RID):godot.Vector2;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_ascent")
	public function _shaped_text_get_ascent(shaped:godot.RID):Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_descent")
	public function _shaped_text_get_descent(shaped:godot.RID):Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_width")
	public function _shaped_text_get_width(shaped:godot.RID):Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_underline_position")
	public function _shaped_text_get_underline_position(shaped:godot.RID):Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(866169185)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_underline_thickness")
	public function _shaped_text_get_underline_thickness(shaped:godot.RID):Float;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2156738276.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_dominant_direction_in_range")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _shaped_text_get_dominant_direction_in_range(shaped:godot.RID, @:meta("int64") start:Int, @:meta("int64") end:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3714187733.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_selection")
	@:argMeta(1, ":meta"("int64"))
	@:argMeta(2, ":meta"("int64"))
	public function _shaped_text_get_selection(shaped:godot.RID, @:meta("int64") start:Int, @:meta("int64") end:Int):godot.PackedVector2Array;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3149310417.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_hit_test_grapheme")
	@:argMeta(1, ":meta"("double"))
	public function _shaped_text_hit_test_grapheme(shaped:godot.RID, @:meta("double") coord:Float):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3149310417.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_hit_test_position")
	@:argMeta(1, ":meta"("double"))
	public function _shaped_text_hit_test_position(shaped:godot.RID, @:meta("double") coord:Float):Int;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2079930245)
	@:hash_compatibility([2453262187.])
	@:nativeName("_shaped_text_draw")
	@:argMeta(3, ":meta"("double"))
	@:argMeta(4, ":meta"("double"))
	@:argMeta(6, ":meta"("float"))
	public function _shaped_text_draw(shaped:godot.RID, canvas:godot.RID, pos:godot.Vector2, @:meta("double") clip_l:Float, @:meta("double") clip_r:Float, color:godot.Color, @:meta("float") oversampling:Float):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(601976754)
	@:hash_compatibility([1686767567])
	@:nativeName("_shaped_text_draw_outline")
	@:argMeta(3, ":meta"("double"))
	@:argMeta(4, ":meta"("double"))
	@:argMeta(5, ":meta"("int64"))
	@:argMeta(7, ":meta"("float"))
	public function _shaped_text_draw_outline(shaped:godot.RID, canvas:godot.RID, pos:godot.Vector2, @:meta("double") clip_l:Float, @:meta("double") clip_r:Float, @:meta("int64") outline_size:Int, color:godot.Color, @:meta("float") oversampling:Float):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2546185844.)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_grapheme_bounds")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_get_grapheme_bounds(shaped:godot.RID, @:meta("int64") pos:Int):godot.Vector2;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_next_grapheme_pos")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_next_grapheme_pos(shaped:godot.RID, @:meta("int64") pos:Int):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_prev_grapheme_pos")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_prev_grapheme_pos(shaped:godot.RID, @:meta("int64") pos:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(788230395)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_get_character_breaks")
	public function _shaped_text_get_character_breaks(shaped:godot.RID):godot.PackedInt32Array;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_next_character_pos")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_next_character_pos(shaped:godot.RID, @:meta("int64") pos:Int):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_prev_character_pos")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_prev_character_pos(shaped:godot.RID, @:meta("int64") pos:Int):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1120910005)
	@:hash_compatibility(null)
	@:nativeName("_shaped_text_closest_character_pos")
	@:argMeta(1, ":meta"("int64"))
	public function _shaped_text_closest_character_pos(shaped:godot.RID, @:meta("int64") pos:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(315676799)
	@:hash_compatibility(null)
	@:nativeName("_format_number")
	public function _format_number(number:String, language:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(315676799)
	@:hash_compatibility(null)
	@:nativeName("_parse_number")
	public function _parse_number(number:String, language:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("_percent_sign")
	public function _percent_sign(language:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3135753539.)
	@:hash_compatibility(null)
	@:nativeName("_strip_diacritics")
	public function _strip_diacritics(string:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_is_valid_identifier")
	public function _is_valid_identifier(string:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("_is_valid_letter")
	@:argMeta(0, ":meta"("uint64"))
	public function _is_valid_letter(@:meta("uint64") unicode:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3658450588.)
	@:hash_compatibility(null)
	@:nativeName("_string_get_word_breaks")
	@:argMeta(2, ":meta"("int64"))
	public function _string_get_word_breaks(string:String, language:String, @:meta("int64") chars_per_line:Int):godot.PackedInt32Array;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2509056759.)
	@:hash_compatibility(null)
	@:nativeName("_string_get_character_breaks")
	public function _string_get_character_breaks(string:String, language:String):godot.PackedInt32Array;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1433197768)
	@:hash_compatibility(null)
	@:nativeName("_is_confusable")
	public function _is_confusable(string:String, dict:godot.PackedStringArray):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("_spoof_check")
	public function _spoof_check(string:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(315676799)
	@:hash_compatibility(null)
	@:nativeName("_string_to_upper")
	public function _string_to_upper(string:String, language:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(315676799)
	@:hash_compatibility(null)
	@:nativeName("_string_to_lower")
	public function _string_to_lower(string:String, language:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(315676799)
	@:hash_compatibility(null)
	@:nativeName("_string_to_title")
	public function _string_to_title(string:String, language:String):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3310685015.)
	@:hash_compatibility(null)
	@:nativeName("_parse_structured_text")
	public function _parse_structured_text(parser_type:godot.TextServer_StructuredTextParser, args:GodotArray, text:String):Array<godot.Vector3i>;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_cleanup")
	public function _cleanup():Void;
}