/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class Texture2D extends godot.Texture {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4190603485.)
	@:hash_compatibility(null)
	@:nativeName("_get_image")
	public function _get_image():godot.Image;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3847873762.)
	@:hash_compatibility(null)
	@:nativeName("_get_format")
	public function _get_format():godot.Image_Format;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_mipmap_count")
	public function _get_mipmap_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_width")
	public function _get_width():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_height")
	public function _get_height():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2522259332.)
	@:hash_compatibility(null)
	@:nativeName("_is_pixel_opaque")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function _is_pixel_opaque(@:meta("int32") x:Int, @:meta("int32") y:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_has_alpha")
	public function _has_alpha():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_has_mipmaps")
	public function _has_mipmaps():Bool;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1384643611)
	@:hash_compatibility(null)
	@:nativeName("_draw")
	public function _draw(to_canvas_item:godot.RID, pos:godot.Vector2, modulate:godot.Color, transpose:Bool):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3819628907.)
	@:hash_compatibility(null)
	@:nativeName("_draw_rect")
	public function _draw_rect(to_canvas_item:godot.RID, rect:godot.Rect2, tile:Bool, modulate:godot.Color, transpose:Bool):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4094143664.)
	@:hash_compatibility(null)
	@:nativeName("_draw_rect_region")
	public function _draw_rect_region(to_canvas_item:godot.RID, rect:godot.Rect2, src_rect:godot.Rect2, modulate:godot.Color, transpose:Bool, clip_uv:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3847873762.)
	@:hash_compatibility(null)
	@:nativeName("get_format")
	public function get_format():godot.Image_Format;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_mipmap_count")
	public function get_mipmap_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_width")
	public function get_width():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_height")
	public function get_height():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3341600327.)
	@:hash_compatibility(null)
	@:nativeName("get_size")
	public function get_size():godot.Vector2;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_alpha")
	public function has_alpha():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_mipmaps")
	public function has_mipmaps():Bool;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2729649137.)
	@:hash_compatibility([1115460088])
	@:nativeName("draw")
	@:argMeta(2, ":default_value"("Color(1, 1, 1, 1)"))
	#if gdscript @:argMeta(2, ":noNullPad"("Color(1, 1, 1, 1)")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	public function draw(canvas_item:godot.RID, position:godot.Vector2, @:default_value("Color(1, 1, 1, 1)") #if gdscript @:noNullPad("Color(1, 1, 1, 1)") #end ?modulate:godot.Color, @:default_value("false") #if gdscript @:noNullPad("false") #end transpose:Bool = false):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3499451691.)
	@:hash_compatibility([575156982])
	@:nativeName("draw_rect")
	@:argMeta(3, ":default_value"("Color(1, 1, 1, 1)"))
	#if gdscript @:argMeta(3, ":noNullPad"("Color(1, 1, 1, 1)")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public function draw_rect(canvas_item:godot.RID, rect:godot.Rect2, tile:Bool, @:default_value("Color(1, 1, 1, 1)") #if gdscript @:noNullPad("Color(1, 1, 1, 1)") #end ?modulate:godot.Color, @:default_value("false") #if gdscript @:noNullPad("false") #end transpose:Bool = false):Void;
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2963678660.)
	@:hash_compatibility([1066564656])
	@:nativeName("draw_rect_region")
	@:argMeta(3, ":default_value"("Color(1, 1, 1, 1)"))
	#if gdscript @:argMeta(3, ":noNullPad"("Color(1, 1, 1, 1)")) #end
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	@:argMeta(5, ":default_value"("true"))
	#if gdscript @:argMeta(5, ":noNullPad"("true")) #end
	public function draw_rect_region(canvas_item:godot.RID, rect:godot.Rect2, src_rect:godot.Rect2, @:default_value("Color(1, 1, 1, 1)") #if gdscript @:noNullPad("Color(1, 1, 1, 1)") #end ?modulate:godot.Color, @:default_value("false") #if gdscript @:noNullPad("false") #end transpose:Bool = false, @:default_value("true") #if gdscript @:noNullPad("true") #end clip_uv:Bool = true):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4190603485.)
	@:hash_compatibility(null)
	@:nativeName("get_image")
	public function get_image():godot.Image;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(121922552)
	@:hash_compatibility(null)
	@:nativeName("create_placeholder")
	public function create_placeholder():godot.Resource;
}