/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class Theme extends godot.Resource {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_default_base_scale")
	@:setter("set_default_base_scale")
	public var default_base_scale(get, set) : Float;
#else

	@:index(null)
	@:getter("get_default_base_scale")
	@:setter("set_default_base_scale")
	public var default_base_scale : Float;
#end
#if use_properties
	@:index(null)
	@:getter("get_default_font")
	@:setter("set_default_font")
	public var default_font(get, set) : godot.Font;
#else

	@:index(null)
	@:getter("get_default_font")
	@:setter("set_default_font")
	public var default_font : godot.Font;
#end
#if use_properties
	@:index(null)
	@:getter("get_default_font_size")
	@:setter("set_default_font_size")
	public var default_font_size(get, set) : Int;
#else

	@:index(null)
	@:getter("get_default_font_size")
	@:setter("set_default_font_size")
	public var default_font_size : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2188371082.)
	@:hash_compatibility(null)
	@:nativeName("set_icon")
	public function set_icon(name:godot.StringName, theme_type:godot.StringName, texture:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(934555193)
	@:hash_compatibility(null)
	@:nativeName("get_icon")
	public function get_icon(name:godot.StringName, theme_type:godot.StringName):godot.Texture2D;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_icon")
	public function has_icon(name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642128662)
	@:hash_compatibility(null)
	@:nativeName("rename_icon")
	public function rename_icon(old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("clear_icon")
	public function clear_icon(name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("get_icon_list")
	public function get_icon_list(theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_icon_type_list")
	public function get_icon_type_list():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2075907568)
	@:hash_compatibility(null)
	@:nativeName("set_stylebox")
	public function set_stylebox(name:godot.StringName, theme_type:godot.StringName, texture:godot.StyleBox):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3405608165.)
	@:hash_compatibility(null)
	@:nativeName("get_stylebox")
	public function get_stylebox(name:godot.StringName, theme_type:godot.StringName):godot.StyleBox;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_stylebox")
	public function has_stylebox(name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642128662)
	@:hash_compatibility(null)
	@:nativeName("rename_stylebox")
	public function rename_stylebox(old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("clear_stylebox")
	public function clear_stylebox(name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("get_stylebox_list")
	public function get_stylebox_list(theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_stylebox_type_list")
	public function get_stylebox_type_list():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(177292320)
	@:hash_compatibility(null)
	@:nativeName("set_font")
	public function set_font(name:godot.StringName, theme_type:godot.StringName, font:godot.Font):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3445063586.)
	@:hash_compatibility(null)
	@:nativeName("get_font")
	public function get_font(name:godot.StringName, theme_type:godot.StringName):godot.Font;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_font")
	public function has_font(name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642128662)
	@:hash_compatibility(null)
	@:nativeName("rename_font")
	public function rename_font(old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("clear_font")
	public function clear_font(name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("get_font_list")
	public function get_font_list(theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_font_type_list")
	public function get_font_type_list():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(281601298)
	@:hash_compatibility(null)
	@:nativeName("set_font_size")
	@:argMeta(2, ":meta"("int32"))
	public function set_font_size(name:godot.StringName, theme_type:godot.StringName, @:meta("int32") font_size:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2419549490.)
	@:hash_compatibility(null)
	@:nativeName("get_font_size")
	public function get_font_size(name:godot.StringName, theme_type:godot.StringName):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_font_size")
	public function has_font_size(name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642128662)
	@:hash_compatibility(null)
	@:nativeName("rename_font_size")
	public function rename_font_size(old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("clear_font_size")
	public function clear_font_size(name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("get_font_size_list")
	public function get_font_size_list(theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_font_size_type_list")
	public function get_font_size_type_list():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4111215154.)
	@:hash_compatibility(null)
	@:nativeName("set_color")
	public function set_color(name:godot.StringName, theme_type:godot.StringName, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2015923404)
	@:hash_compatibility(null)
	@:nativeName("get_color")
	public function get_color(name:godot.StringName, theme_type:godot.StringName):godot.Color;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_color")
	public function has_color(name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642128662)
	@:hash_compatibility(null)
	@:nativeName("rename_color")
	public function rename_color(old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("clear_color")
	public function clear_color(name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("get_color_list")
	public function get_color_list(theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_color_type_list")
	public function get_color_type_list():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(281601298)
	@:hash_compatibility(null)
	@:nativeName("set_constant")
	@:argMeta(2, ":meta"("int32"))
	public function set_constant(name:godot.StringName, theme_type:godot.StringName, @:meta("int32") constant:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2419549490.)
	@:hash_compatibility(null)
	@:nativeName("get_constant")
	public function get_constant(name:godot.StringName, theme_type:godot.StringName):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("has_constant")
	public function has_constant(name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(642128662)
	@:hash_compatibility(null)
	@:nativeName("rename_constant")
	public function rename_constant(old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("clear_constant")
	public function clear_constant(name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4291131558.)
	@:hash_compatibility(null)
	@:nativeName("get_constant_list")
	public function get_constant_list(theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_constant_type_list")
	public function get_constant_type_list():godot.PackedStringArray;
#if use_properties
	public extern inline function set_default_base_scale(v: Float): Float {
		set_default_base_scale_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_default_base_scale")
	@:native("set_default_base_scale")
	@:argMeta(0, ":meta"("float"))
	public function set_default_base_scale_impl(@:meta("float") base_scale:Float):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("set_default_base_scale")
	@:argMeta(0, ":meta"("float"))
	public function set_default_base_scale(@:meta("float") base_scale:Float):Void;

#end
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_default_base_scale")
	public function get_default_base_scale():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_default_base_scale")
	public function has_default_base_scale():Bool;
#if use_properties
	public extern inline function set_default_font(v: godot.Font): godot.Font {
		set_default_font_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1262170328)
	@:hash_compatibility(null)
	@:nativeName("set_default_font")
	@:native("set_default_font")
	public function set_default_font_impl(font:godot.Font):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1262170328)
	@:hash_compatibility(null)
	@:nativeName("set_default_font")
	public function set_default_font(font:godot.Font):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3229501585.)
	@:hash_compatibility(null)
	@:nativeName("get_default_font")
	public function get_default_font():godot.Font;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_default_font")
	public function has_default_font():Bool;
#if use_properties
	public extern inline function set_default_font_size(v: Int): Int {
		set_default_font_size_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_default_font_size")
	@:native("set_default_font_size")
	@:argMeta(0, ":meta"("int32"))
	public function set_default_font_size_impl(@:meta("int32") font_size:Int):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_default_font_size")
	@:argMeta(0, ":meta"("int32"))
	public function set_default_font_size(@:meta("int32") font_size:Int):Void;

#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_default_font_size")
	public function get_default_font_size():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_default_font_size")
	public function has_default_font_size():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2492983623.)
	@:hash_compatibility(null)
	@:nativeName("set_theme_item")
	public function set_theme_item(data_type:godot.Theme_DataType, name:godot.StringName, theme_type:godot.StringName, value:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2191024021.)
	@:hash_compatibility(null)
	@:nativeName("get_theme_item")
	public function get_theme_item(data_type:godot.Theme_DataType, name:godot.StringName, theme_type:godot.StringName):Dynamic;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1739311056)
	@:hash_compatibility(null)
	@:nativeName("has_theme_item")
	public function has_theme_item(data_type:godot.Theme_DataType, name:godot.StringName, theme_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3900867553.)
	@:hash_compatibility(null)
	@:nativeName("rename_theme_item")
	public function rename_theme_item(data_type:godot.Theme_DataType, old_name:godot.StringName, name:godot.StringName, theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2965505587.)
	@:hash_compatibility(null)
	@:nativeName("clear_theme_item")
	public function clear_theme_item(data_type:godot.Theme_DataType, name:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3726716710.)
	@:hash_compatibility(null)
	@:nativeName("get_theme_item_list")
	public function get_theme_item_list(data_type:godot.Theme_DataType, theme_type:String):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1316004935)
	@:hash_compatibility(null)
	@:nativeName("get_theme_item_type_list")
	public function get_theme_item_type_list(data_type:godot.Theme_DataType):godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("set_type_variation")
	public function set_type_variation(theme_type:godot.StringName, base_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(471820014)
	@:hash_compatibility(null)
	@:nativeName("is_type_variation")
	public function is_type_variation(theme_type:godot.StringName, base_type:godot.StringName):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("clear_type_variation")
	public function clear_type_variation(theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1965194235)
	@:hash_compatibility(null)
	@:nativeName("get_type_variation_base")
	public function get_type_variation_base(theme_type:godot.StringName):godot.StringName;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1761182771)
	@:hash_compatibility(null)
	@:nativeName("get_type_variation_list")
	public function get_type_variation_list(base_type:godot.StringName):godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("add_type")
	public function add_type(theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("remove_type")
	public function remove_type(theme_type:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3740211285.)
	@:hash_compatibility(null)
	@:nativeName("rename_type")
	public function rename_type(old_theme_type:godot.StringName, theme_type:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("get_type_list")
	public function get_type_list():godot.PackedStringArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2326690814.)
	@:hash_compatibility(null)
	@:nativeName("merge_with")
	public function merge_with(other:godot.Theme):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear")
	public function clear():Void;
}