/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class TileSet extends godot.Resource {
	public function new();
#if !use_properties
	@:index(null)
	@:getter("get_tile_shape")
	@:setter("set_tile_shape")
	public var tile_shape : Int;
#end
#if !use_properties
	@:index(null)
	@:getter("get_tile_layout")
	@:setter("set_tile_layout")
	public var tile_layout : Int;
#end
#if !use_properties
	@:index(null)
	@:getter("get_tile_offset_axis")
	@:setter("set_tile_offset_axis")
	public var tile_offset_axis : Int;
#end
#if use_properties
	@:index(null)
	@:getter("get_tile_size")
	@:setter("set_tile_size")
	@:reassignOnSubfieldEdit(set_tile_size_impl, x, y)
	public var tile_size(get, set) : godot.Vector2i;
#else

	@:index(null)
	@:getter("get_tile_size")
	@:setter("set_tile_size")
	public var tile_size : godot.Vector2i;
#end
#if use_properties
	@:index(null)
	@:getter("is_uv_clipping")
	@:setter("set_uv_clipping")
	public var uv_clipping(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_uv_clipping")
	@:setter("set_uv_clipping")
	public var uv_clipping : Bool;
#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_next_source_id")
	public function get_next_source_id():Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1059186179)
	@:hash_compatibility([276991387])
	@:nativeName("add_source")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public function add_source(source:godot.TileSetSource, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end atlas_source_id_override:Int = -1):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_source")
	@:argMeta(0, ":meta"("int32"))
	public function remove_source(@:meta("int32") source_id:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_source_id")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_source_id(@:meta("int32") source_id:Int, @:meta("int32") new_source_id:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_source_count")
	public function get_source_count():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_source_id")
	@:argMeta(0, ":meta"("int32"))
	public function get_source_id(@:meta("int32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("has_source")
	@:argMeta(0, ":meta"("int32"))
	public function has_source(@:meta("int32") source_id:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1763540252)
	@:hash_compatibility(null)
	@:nativeName("get_source")
	@:argMeta(0, ":meta"("int32"))
	public function get_source(@:meta("int32") source_id:Int):godot.TileSetSource;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2131427112)
	@:hash_compatibility(null)
	@:nativeName("set_tile_shape")
	public function set_tile_shape(shape:godot.TileSet_TileShape):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(716918169)
	@:hash_compatibility(null)
	@:nativeName("get_tile_shape")
	public function get_tile_shape():godot.TileSet_TileShape;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1071216679)
	@:hash_compatibility(null)
	@:nativeName("set_tile_layout")
	public function set_tile_layout(layout:godot.TileSet_TileLayout):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(194628839)
	@:hash_compatibility(null)
	@:nativeName("get_tile_layout")
	public function get_tile_layout():godot.TileSet_TileLayout;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3300198521.)
	@:hash_compatibility(null)
	@:nativeName("set_tile_offset_axis")
	public function set_tile_offset_axis(alignment:godot.TileSet_TileOffsetAxis):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(762494114)
	@:hash_compatibility(null)
	@:nativeName("get_tile_offset_axis")
	public function get_tile_offset_axis():godot.TileSet_TileOffsetAxis;
#if use_properties
	public extern inline function set_tile_size(v: godot.Vector2i): godot.Vector2i {
		set_tile_size_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1130785943)
	@:hash_compatibility(null)
	@:nativeName("set_tile_size")
	@:native("set_tile_size")
	public function set_tile_size_impl(size:godot.Vector2i):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1130785943)
	@:hash_compatibility(null)
	@:nativeName("set_tile_size")
	public function set_tile_size(size:godot.Vector2i):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3690982128.)
	@:hash_compatibility(null)
	@:nativeName("get_tile_size")
	public function get_tile_size():godot.Vector2i;
#if use_properties
	public extern inline function set_uv_clipping(v: Bool): Bool {
		set_uv_clipping_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_uv_clipping")
	@:native("set_uv_clipping")
	public function set_uv_clipping_impl(uv_clipping:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_uv_clipping")
	public function set_uv_clipping(uv_clipping:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_uv_clipping")
	@:native("is_uv_clipping")
	public function get_uv_clipping():Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_occlusion_layers_count")
	public function get_occlusion_layers_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025054187)
	@:hash_compatibility(null)
	@:nativeName("add_occlusion_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function add_occlusion_layer(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end to_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("move_occlusion_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function move_occlusion_layer(@:meta("int32") layer_index:Int, @:meta("int32") to_position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_occlusion_layer")
	@:argMeta(0, ":meta"("int32"))
	public function remove_occlusion_layer(@:meta("int32") layer_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_occlusion_layer_light_mask")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_occlusion_layer_light_mask(@:meta("int32") layer_index:Int, @:meta("int32") light_mask:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_occlusion_layer_light_mask")
	@:argMeta(0, ":meta"("int32"))
	public function get_occlusion_layer_light_mask(@:meta("int32") layer_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_occlusion_layer_sdf_collision")
	@:argMeta(0, ":meta"("int32"))
	public function set_occlusion_layer_sdf_collision(@:meta("int32") layer_index:Int, sdf_collision:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("get_occlusion_layer_sdf_collision")
	@:argMeta(0, ":meta"("int32"))
	public function get_occlusion_layer_sdf_collision(@:meta("int32") layer_index:Int):Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_physics_layers_count")
	public function get_physics_layers_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025054187)
	@:hash_compatibility(null)
	@:nativeName("add_physics_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function add_physics_layer(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end to_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("move_physics_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function move_physics_layer(@:meta("int32") layer_index:Int, @:meta("int32") to_position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_physics_layer")
	@:argMeta(0, ":meta"("int32"))
	public function remove_physics_layer(@:meta("int32") layer_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_physics_layer_collision_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("uint32"))
	public function set_physics_layer_collision_layer(@:meta("int32") layer_index:Int, @:meta("uint32") layer:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_physics_layer_collision_layer")
	@:argMeta(0, ":meta"("int32"))
	public function get_physics_layer_collision_layer(@:meta("int32") layer_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_physics_layer_collision_mask")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("uint32"))
	public function set_physics_layer_collision_mask(@:meta("int32") layer_index:Int, @:meta("uint32") mask:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_physics_layer_collision_mask")
	@:argMeta(0, ":meta"("int32"))
	public function get_physics_layer_collision_mask(@:meta("int32") layer_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_physics_layer_collision_priority")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_physics_layer_collision_priority(@:meta("int32") layer_index:Int, @:meta("float") priority:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_physics_layer_collision_priority")
	@:argMeta(0, ":meta"("int32"))
	public function get_physics_layer_collision_priority(@:meta("int32") layer_index:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1018687357)
	@:hash_compatibility(null)
	@:nativeName("set_physics_layer_physics_material")
	@:argMeta(0, ":meta"("int32"))
	public function set_physics_layer_physics_material(@:meta("int32") layer_index:Int, physics_material:godot.PhysicsMaterial):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(788318639)
	@:hash_compatibility(null)
	@:nativeName("get_physics_layer_physics_material")
	@:argMeta(0, ":meta"("int32"))
	public function get_physics_layer_physics_material(@:meta("int32") layer_index:Int):godot.PhysicsMaterial;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_terrain_sets_count")
	public function get_terrain_sets_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025054187)
	@:hash_compatibility(null)
	@:nativeName("add_terrain_set")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function add_terrain_set(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end to_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("move_terrain_set")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function move_terrain_set(@:meta("int32") terrain_set:Int, @:meta("int32") to_position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_terrain_set")
	@:argMeta(0, ":meta"("int32"))
	public function remove_terrain_set(@:meta("int32") terrain_set:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3943003916.)
	@:hash_compatibility(null)
	@:nativeName("set_terrain_set_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_terrain_set_mode(@:meta("int32") terrain_set:Int, mode:godot.TileSet_TerrainMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2084469411)
	@:hash_compatibility(null)
	@:nativeName("get_terrain_set_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_terrain_set_mode(@:meta("int32") terrain_set:Int):godot.TileSet_TerrainMode;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_terrains_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_terrains_count(@:meta("int32") terrain_set:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1230568737)
	@:hash_compatibility([3023605688.])
	@:nativeName("add_terrain")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public function add_terrain(@:meta("int32") terrain_set:Int, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end to_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1649997291)
	@:hash_compatibility(null)
	@:nativeName("move_terrain")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function move_terrain(@:meta("int32") terrain_set:Int, @:meta("int32") terrain_index:Int, @:meta("int32") to_position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("remove_terrain")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function remove_terrain(@:meta("int32") terrain_set:Int, @:meta("int32") terrain_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_terrains")
	@:argMeta(0, ":meta"("int32"))
	public function clear_terrains(@:meta("int32") terrain_set:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2285447957.)
	@:hash_compatibility(null)
	@:nativeName("set_terrain_name")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_terrain_name(@:meta("int32") terrain_set:Int, @:meta("int32") terrain_index:Int, name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1391810591)
	@:hash_compatibility(null)
	@:nativeName("get_terrain_name")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_terrain_name(@:meta("int32") terrain_set:Int, @:meta("int32") terrain_index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3733378741.)
	@:hash_compatibility(null)
	@:nativeName("set_terrain_color")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_terrain_color(@:meta("int32") terrain_set:Int, @:meta("int32") terrain_index:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2165839948.)
	@:hash_compatibility(null)
	@:nativeName("get_terrain_color")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_terrain_color(@:meta("int32") terrain_set:Int, @:meta("int32") terrain_index:Int):godot.Color;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_navigation_layers_count")
	public function get_navigation_layers_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025054187)
	@:hash_compatibility(null)
	@:nativeName("add_navigation_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function add_navigation_layer(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end to_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("move_navigation_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function move_navigation_layer(@:meta("int32") layer_index:Int, @:meta("int32") to_position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_navigation_layer")
	@:argMeta(0, ":meta"("int32"))
	public function remove_navigation_layer(@:meta("int32") layer_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_navigation_layer_layers")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("uint32"))
	public function set_navigation_layer_layers(@:meta("int32") layer_index:Int, @:meta("uint32") layers:Int):Void;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_navigation_layer_layers")
	@:argMeta(0, ":meta"("int32"))
	public function get_navigation_layer_layers(@:meta("int32") layer_index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1383440665)
	@:hash_compatibility(null)
	@:nativeName("set_navigation_layer_layer_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_navigation_layer_layer_value(@:meta("int32") layer_index:Int, @:meta("int32") layer_number:Int, value:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2522259332.)
	@:hash_compatibility(null)
	@:nativeName("get_navigation_layer_layer_value")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_navigation_layer_layer_value(@:meta("int32") layer_index:Int, @:meta("int32") layer_number:Int):Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_data_layers_count")
	public function get_custom_data_layers_count():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1025054187)
	@:hash_compatibility(null)
	@:nativeName("add_custom_data_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function add_custom_data_layer(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end to_position:Int = -1):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("move_custom_data_layer")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function move_custom_data_layer(@:meta("int32") layer_index:Int, @:meta("int32") to_position:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_custom_data_layer")
	@:argMeta(0, ":meta"("int32"))
	public function remove_custom_data_layer(@:meta("int32") layer_index:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1321353865)
	@:hash_compatibility(null)
	@:nativeName("get_custom_data_layer_by_name")
	public function get_custom_data_layer_by_name(layer_name:String):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_custom_data_layer_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_data_layer_name(@:meta("int32") layer_index:Int, layer_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3927539163.)
	@:hash_compatibility(null)
	@:nativeName("has_custom_data_layer_by_name")
	public function has_custom_data_layer_by_name(layer_name:String):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_custom_data_layer_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_data_layer_name(@:meta("int32") layer_index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3492912874.)
	@:hash_compatibility(null)
	@:nativeName("set_custom_data_layer_type")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_data_layer_type(@:meta("int32") layer_index:Int, layer_type:godot.Variant_Type):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2990820875.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_data_layer_type")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_data_layer_type(@:meta("int32") layer_index:Int):godot.Variant_Type;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_source_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_source_level_tile_proxy(@:meta("int32") source_from:Int, @:meta("int32") source_to:Int):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_source_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	public function get_source_level_tile_proxy(@:meta("int32") source_from:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility(null)
	@:nativeName("has_source_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	public function has_source_level_tile_proxy(@:meta("int32") source_from:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_source_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	public function remove_source_level_tile_proxy(@:meta("int32") source_from:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1769939278)
	@:hash_compatibility(null)
	@:nativeName("set_coords_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function set_coords_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i, @:meta("int32") source_to:Int, coords_to:godot.Vector2i):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2856536371.)
	@:hash_compatibility(null)
	@:nativeName("get_coords_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	public function get_coords_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3957903770.)
	@:hash_compatibility(null)
	@:nativeName("has_coords_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	public function has_coords_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2311374912.)
	@:hash_compatibility(null)
	@:nativeName("remove_coords_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	public function remove_coords_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3862385460.)
	@:hash_compatibility(null)
	@:nativeName("set_alternative_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(3, ":meta"("int32"))
	@:argMeta(5, ":meta"("int32"))
	public function set_alternative_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i, @:meta("int32") alternative_from:Int, @:meta("int32") source_to:Int, coords_to:godot.Vector2i, @:meta("int32") alternative_to:Int):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2303761075.)
	@:hash_compatibility(null)
	@:nativeName("get_alternative_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function get_alternative_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i, @:meta("int32") alternative_from:Int):GodotArray;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(180086755)
	@:hash_compatibility(null)
	@:nativeName("has_alternative_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function has_alternative_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i, @:meta("int32") alternative_from:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2328951467.)
	@:hash_compatibility(null)
	@:nativeName("remove_alternative_level_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function remove_alternative_level_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i, @:meta("int32") alternative_from:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4267935328.)
	@:hash_compatibility(null)
	@:nativeName("map_tile_proxy")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	public function map_tile_proxy(@:meta("int32") source_from:Int, coords_from:godot.Vector2i, @:meta("int32") alternative_from:Int):GodotArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("cleanup_invalid_tile_proxies")
	public function cleanup_invalid_tile_proxies():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_tile_proxies")
	public function clear_tile_proxies():Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(763712015)
	@:hash_compatibility([3009264082.])
	@:nativeName("add_pattern")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public function add_pattern(pattern:godot.TileMapPattern, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4207737510.)
	@:hash_compatibility(null)
	@:nativeName("get_pattern")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function get_pattern(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):godot.TileMapPattern;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_pattern")
	@:argMeta(0, ":meta"("int32"))
	public function remove_pattern(@:meta("int32") index:Int):Void;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_patterns_count")
	public function get_patterns_count():Int;
}