/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class TileSetScenesCollectionSource extends godot.TileSetSource {
	public function new();
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_scene_tiles_count")
	public function get_scene_tiles_count():Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3744713108.)
	@:hash_compatibility(null)
	@:nativeName("get_scene_tile_id")
	@:argMeta(0, ":meta"("int32"))
	public function get_scene_tile_id(@:meta("int32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility(null)
	@:nativeName("has_scene_tile_id")
	@:argMeta(0, ":meta"("int32"))
	public function has_scene_tile_id(@:meta("int32") id:Int):Bool;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1117465415)
	@:hash_compatibility([2633389122.])
	@:nativeName("create_scene_tile")
	@:argMeta(1, ":meta"("int32"))
	@:argMeta(1, ":default_value"("-1"))
	#if gdscript @:argMeta(1, ":noNullPad"("-1")) #end
	public function create_scene_tile(packed_scene:godot.PackedScene, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end id_override:Int = -1):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_scene_tile_id")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_scene_tile_id(@:meta("int32") id:Int, @:meta("int32") new_id:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3435852839.)
	@:hash_compatibility(null)
	@:nativeName("set_scene_tile_scene")
	@:argMeta(0, ":meta"("int32"))
	public function set_scene_tile_scene(@:meta("int32") id:Int, packed_scene:godot.PackedScene):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(511017218)
	@:hash_compatibility(null)
	@:nativeName("get_scene_tile_scene")
	@:argMeta(0, ":meta"("int32"))
	public function get_scene_tile_scene(@:meta("int32") id:Int):godot.PackedScene;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_scene_tile_display_placeholder")
	@:argMeta(0, ":meta"("int32"))
	public function set_scene_tile_display_placeholder(@:meta("int32") id:Int, display_placeholder:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("get_scene_tile_display_placeholder")
	@:argMeta(0, ":meta"("int32"))
	public function get_scene_tile_display_placeholder(@:meta("int32") id:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("remove_scene_tile")
	@:argMeta(0, ":meta"("int32"))
	public function remove_scene_tile(@:meta("int32") id:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_next_scene_tile_id")
	public function get_next_scene_tile_id():Int;
}