/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(false) extern class Time extends godot.Object {
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3485342025.)
	@:hash_compatibility(null)
	@:nativeName("get_datetime_dict_from_unix_time")
	@:argMeta(0, ":meta"("int64"))
	public static function get_datetime_dict_from_unix_time(@:meta("int64") unix_time_val:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3485342025.)
	@:hash_compatibility(null)
	@:nativeName("get_date_dict_from_unix_time")
	@:argMeta(0, ":meta"("int64"))
	public static function get_date_dict_from_unix_time(@:meta("int64") unix_time_val:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3485342025.)
	@:hash_compatibility(null)
	@:nativeName("get_time_dict_from_unix_time")
	@:argMeta(0, ":meta"("int64"))
	public static function get_time_dict_from_unix_time(@:meta("int64") unix_time_val:Int):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2311239925.)
	@:hash_compatibility(null)
	@:nativeName("get_datetime_string_from_unix_time")
	@:argMeta(0, ":meta"("int64"))
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function get_datetime_string_from_unix_time(@:meta("int64") unix_time_val:Int, @:default_value("false") #if gdscript @:noNullPad("false") #end use_space:Bool = false):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_date_string_from_unix_time")
	@:argMeta(0, ":meta"("int64"))
	public static function get_date_string_from_unix_time(@:meta("int64") unix_time_val:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_time_string_from_unix_time")
	@:argMeta(0, ":meta"("int64"))
	public static function get_time_string_from_unix_time(@:meta("int64") unix_time_val:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3253569256.)
	@:hash_compatibility(null)
	@:nativeName("get_datetime_dict_from_datetime_string")
	public static function get_datetime_dict_from_datetime_string(datetime:String, weekday:Bool):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1898123706)
	@:hash_compatibility(null)
	@:nativeName("get_datetime_string_from_datetime_dict")
	public static function get_datetime_string_from_datetime_dict(datetime:godot.Dictionary, use_space:Bool):String;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3021115443.)
	@:hash_compatibility(null)
	@:nativeName("get_unix_time_from_datetime_dict")
	public static function get_unix_time_from_datetime_dict(datetime:godot.Dictionary):Int;
	@:return_value_meta("int64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1321353865)
	@:hash_compatibility(null)
	@:nativeName("get_unix_time_from_datetime_string")
	public static function get_unix_time_from_datetime_string(datetime:String):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_offset_string_from_offset_minutes")
	@:argMeta(0, ":meta"("int64"))
	public static function get_offset_string_from_offset_minutes(@:meta("int64") offset_minutes:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(205769976)
	@:hash_compatibility(null)
	@:nativeName("get_datetime_dict_from_system")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public static function get_datetime_dict_from_system(@:default_value("false") #if gdscript @:noNullPad("false") #end utc:Bool = false):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(205769976)
	@:hash_compatibility(null)
	@:nativeName("get_date_dict_from_system")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public static function get_date_dict_from_system(@:default_value("false") #if gdscript @:noNullPad("false") #end utc:Bool = false):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(205769976)
	@:hash_compatibility(null)
	@:nativeName("get_time_dict_from_system")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public static function get_time_dict_from_system(@:default_value("false") #if gdscript @:noNullPad("false") #end utc:Bool = false):godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1136425492)
	@:hash_compatibility(null)
	@:nativeName("get_datetime_string_from_system")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	@:argMeta(1, ":default_value"("false"))
	#if gdscript @:argMeta(1, ":noNullPad"("false")) #end
	public static function get_datetime_string_from_system(@:default_value("false") #if gdscript @:noNullPad("false") #end utc:Bool = false, @:default_value("false") #if gdscript @:noNullPad("false") #end use_space:Bool = false):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1162154673)
	@:hash_compatibility(null)
	@:nativeName("get_date_string_from_system")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public static function get_date_string_from_system(@:default_value("false") #if gdscript @:noNullPad("false") #end utc:Bool = false):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1162154673)
	@:hash_compatibility(null)
	@:nativeName("get_time_string_from_system")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public static function get_time_string_from_system(@:default_value("false") #if gdscript @:noNullPad("false") #end utc:Bool = false):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3102165223.)
	@:hash_compatibility(null)
	@:nativeName("get_time_zone_from_system")
	public static function get_time_zone_from_system():godot.Dictionary;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_unix_time_from_system")
	public static function get_unix_time_from_system():Float;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_ticks_msec")
	public static function get_ticks_msec():Int;
	@:return_value_meta("uint64")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_ticks_usec")
	public static function get_ticks_usec():Int;
}