/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(false) @:api_type("core") @:is_resource(false) @:is_node(false) extern class TreeItem extends godot.Object {
	public function new();
#if use_properties
	@:index(null)
	@:getter("is_collapsed")
	@:setter("set_collapsed")
	public var collapsed(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_collapsed")
	@:setter("set_collapsed")
	public var collapsed : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("is_visible")
	@:setter("set_visible")
	public var visible(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_visible")
	@:setter("set_visible")
	public var visible : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("is_folding_disabled")
	@:setter("set_disable_folding")
	public var disable_folding(get, set) : Bool;
#else

	@:index(null)
	@:getter("is_folding_disabled")
	@:setter("set_disable_folding")
	public var disable_folding : Bool;
#end
#if use_properties
	@:index(null)
	@:getter("get_custom_minimum_height")
	@:setter("set_custom_minimum_height")
	public var custom_minimum_height(get, set) : Int;
#else

	@:index(null)
	@:getter("get_custom_minimum_height")
	@:setter("set_custom_minimum_height")
	public var custom_minimum_height : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(289920701)
	@:hash_compatibility(null)
	@:nativeName("set_cell_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_cell_mode(@:meta("int32") column:Int, mode:godot.TreeItem_TreeCellMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3406114978.)
	@:hash_compatibility(null)
	@:nativeName("get_cell_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_cell_mode(@:meta("int32") column:Int):godot.TreeItem_TreeCellMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(287402019)
	@:hash_compatibility(null)
	@:nativeName("set_auto_translate_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_auto_translate_mode(@:meta("int32") column:Int, mode:godot.Node_AutoTranslateMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(906302372)
	@:hash_compatibility(null)
	@:nativeName("get_auto_translate_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_auto_translate_mode(@:meta("int32") column:Int):godot.Node_AutoTranslateMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_edit_multiline")
	@:argMeta(0, ":meta"("int32"))
	public function set_edit_multiline(@:meta("int32") column:Int, multiline:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_edit_multiline")
	@:argMeta(0, ":meta"("int32"))
	public function is_edit_multiline(@:meta("int32") column:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_checked")
	@:argMeta(0, ":meta"("int32"))
	public function set_checked(@:meta("int32") column:Int, checked:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_indeterminate")
	@:argMeta(0, ":meta"("int32"))
	public function set_indeterminate(@:meta("int32") column:Int, indeterminate:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_checked")
	@:argMeta(0, ":meta"("int32"))
	public function is_checked(@:meta("int32") column:Int):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_indeterminate")
	@:argMeta(0, ":meta"("int32"))
	public function is_indeterminate(@:meta("int32") column:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(972357352)
	@:hash_compatibility([4023243586.])
	@:nativeName("propagate_check")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public function propagate_check(@:meta("int32") column:Int, @:default_value("true") #if gdscript @:noNullPad("true") #end emit_signal:Bool = true):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_text")
	@:argMeta(0, ":meta"("int32"))
	public function set_text(@:meta("int32") column:Int, text:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_text")
	@:argMeta(0, ":meta"("int32"))
	public function get_text(@:meta("int32") column:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_description")
	@:argMeta(0, ":meta"("int32"))
	public function set_description(@:meta("int32") column:Int, description:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_description")
	@:argMeta(0, ":meta"("int32"))
	public function get_description(@:meta("int32") column:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1707680378)
	@:hash_compatibility(null)
	@:nativeName("set_text_direction")
	@:argMeta(0, ":meta"("int32"))
	public function set_text_direction(@:meta("int32") column:Int, direction:godot.Control_TextDirection):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4235602388.)
	@:hash_compatibility(null)
	@:nativeName("get_text_direction")
	@:argMeta(0, ":meta"("int32"))
	public function get_text_direction(@:meta("int32") column:Int):godot.Control_TextDirection;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3633006561.)
	@:hash_compatibility(null)
	@:nativeName("set_autowrap_mode")
	@:argMeta(0, ":meta"("int32"))
	public function set_autowrap_mode(@:meta("int32") column:Int, autowrap_mode:godot.TextServer_AutowrapMode):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2902757236.)
	@:hash_compatibility(null)
	@:nativeName("get_autowrap_mode")
	@:argMeta(0, ":meta"("int32"))
	public function get_autowrap_mode(@:meta("int32") column:Int):godot.TextServer_AutowrapMode;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2186029660.)
	@:hash_compatibility(null)
	@:nativeName("set_autowrap_trim_flags")
	@:argMeta(0, ":meta"("int32"))
	public function set_autowrap_trim_flags(@:meta("int32") column:Int, flags:godot.TextServer_LineBreakFlag):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3513056523.)
	@:hash_compatibility(null)
	@:nativeName("get_autowrap_trim_flags")
	@:argMeta(0, ":meta"("int32"))
	public function get_autowrap_trim_flags(@:meta("int32") column:Int):godot.TextServer_LineBreakFlag;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1940772195)
	@:hash_compatibility(null)
	@:nativeName("set_text_overrun_behavior")
	@:argMeta(0, ":meta"("int32"))
	public function set_text_overrun_behavior(@:meta("int32") column:Int, overrun_behavior:godot.TextServer_OverrunBehavior):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3782727860.)
	@:hash_compatibility(null)
	@:nativeName("get_text_overrun_behavior")
	@:argMeta(0, ":meta"("int32"))
	public function get_text_overrun_behavior(@:meta("int32") column:Int):godot.TextServer_OverrunBehavior;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(868756907)
	@:hash_compatibility(null)
	@:nativeName("set_structured_text_bidi_override")
	@:argMeta(0, ":meta"("int32"))
	public function set_structured_text_bidi_override(@:meta("int32") column:Int, parser:godot.TextServer_StructuredTextParser):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3377823772.)
	@:hash_compatibility(null)
	@:nativeName("get_structured_text_bidi_override")
	@:argMeta(0, ":meta"("int32"))
	public function get_structured_text_bidi_override(@:meta("int32") column:Int):godot.TextServer_StructuredTextParser;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(537221740)
	@:hash_compatibility(null)
	@:nativeName("set_structured_text_bidi_override_options")
	@:argMeta(0, ":meta"("int32"))
	public function set_structured_text_bidi_override_options(@:meta("int32") column:Int, args:GodotArray):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(663333327)
	@:hash_compatibility(null)
	@:nativeName("get_structured_text_bidi_override_options")
	@:argMeta(0, ":meta"("int32"))
	public function get_structured_text_bidi_override_options(@:meta("int32") column:Int):GodotArray;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_language")
	@:argMeta(0, ":meta"("int32"))
	public function set_language(@:meta("int32") column:Int, language:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_language")
	@:argMeta(0, ":meta"("int32"))
	public function get_language(@:meta("int32") column:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_suffix")
	@:argMeta(0, ":meta"("int32"))
	public function set_suffix(@:meta("int32") column:Int, text:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_suffix")
	@:argMeta(0, ":meta"("int32"))
	public function get_suffix(@:meta("int32") column:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(666127730)
	@:hash_compatibility(null)
	@:nativeName("set_icon")
	@:argMeta(0, ":meta"("int32"))
	public function set_icon(@:meta("int32") column:Int, texture:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3536238170.)
	@:hash_compatibility(null)
	@:nativeName("get_icon")
	@:argMeta(0, ":meta"("int32"))
	public function get_icon(@:meta("int32") column:Int):godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(666127730)
	@:hash_compatibility(null)
	@:nativeName("set_icon_overlay")
	@:argMeta(0, ":meta"("int32"))
	public function set_icon_overlay(@:meta("int32") column:Int, texture:godot.Texture2D):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3536238170.)
	@:hash_compatibility(null)
	@:nativeName("get_icon_overlay")
	@:argMeta(0, ":meta"("int32"))
	public function get_icon_overlay(@:meta("int32") column:Int):godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1356297692)
	@:hash_compatibility(null)
	@:nativeName("set_icon_region")
	@:argMeta(0, ":meta"("int32"))
	public function set_icon_region(@:meta("int32") column:Int, region:godot.Rect2):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3327874267.)
	@:hash_compatibility(null)
	@:nativeName("get_icon_region")
	@:argMeta(0, ":meta"("int32"))
	public function get_icon_region(@:meta("int32") column:Int):godot.Rect2;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_icon_max_width")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_icon_max_width(@:meta("int32") column:Int, @:meta("int32") width:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_icon_max_width")
	@:argMeta(0, ":meta"("int32"))
	public function get_icon_max_width(@:meta("int32") column:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_icon_modulate")
	@:argMeta(0, ":meta"("int32"))
	public function set_icon_modulate(@:meta("int32") column:Int, modulate:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3457211756.)
	@:hash_compatibility(null)
	@:nativeName("get_icon_modulate")
	@:argMeta(0, ":meta"("int32"))
	public function get_icon_modulate(@:meta("int32") column:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_range")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	public function set_range(@:meta("int32") column:Int, @:meta("double") value:Float):Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_range")
	@:argMeta(0, ":meta"("int32"))
	public function get_range(@:meta("int32") column:Int):Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1547181014)
	@:hash_compatibility(null)
	@:nativeName("set_range_config")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("double"))
	@:argMeta(3, ":meta"("double"))
	@:argMeta(4, ":default_value"("false"))
	#if gdscript @:argMeta(4, ":noNullPad"("false")) #end
	public function set_range_config(@:meta("int32") column:Int, @:meta("double") min:Float, @:meta("double") max:Float, @:meta("double") step:Float, @:default_value("false") #if gdscript @:noNullPad("false") #end expr:Bool = false):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3554694381.)
	@:hash_compatibility(null)
	@:nativeName("get_range_config")
	@:argMeta(0, ":meta"("int32"))
	public function get_range_config(@:meta("int32") column:Int):godot.Dictionary;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2152698145.)
	@:hash_compatibility(null)
	@:nativeName("set_metadata")
	@:argMeta(0, ":meta"("int32"))
	public function set_metadata(@:meta("int32") column:Int, meta:Dynamic):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("get_metadata")
	@:argMeta(0, ":meta"("int32"))
	public function get_metadata(@:meta("int32") column:Int):Dynamic;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(272420368)
	@:hash_compatibility(null)
	@:nativeName("set_custom_draw")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_draw(@:meta("int32") column:Int, object:godot.Object, callback:godot.StringName):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(957362965)
	@:hash_compatibility(null)
	@:nativeName("set_custom_draw_callback")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_draw_callback(@:meta("int32") column:Int, callback:godot.Callable):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1317077508)
	@:hash_compatibility(null)
	@:nativeName("get_custom_draw_callback")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_draw_callback(@:meta("int32") column:Int):godot.Callable;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1433009359)
	@:hash_compatibility(null)
	@:nativeName("set_custom_stylebox")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_stylebox(@:meta("int32") column:Int, stylebox:godot.StyleBox):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3362509644.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_stylebox")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_stylebox(@:meta("int32") column:Int):godot.StyleBox;
#if use_properties
	public extern inline function set_collapsed(v: Bool): Bool {
		set_collapsed_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_collapsed")
	@:native("set_collapsed")
	public function set_collapsed_impl(enable:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_collapsed")
	public function set_collapsed(enable:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_collapsed")
	@:native("is_collapsed")
	public function get_collapsed():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_collapsed_recursive")
	public function set_collapsed_recursive(enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2595650253.)
	@:hash_compatibility(null)
	@:nativeName("is_any_collapsed")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function is_any_collapsed(@:default_value("false") #if gdscript @:noNullPad("false") #end only_visible:Bool = false):Bool;
#if use_properties
	public extern inline function set_visible(v: Bool): Bool {
		set_visible_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_visible")
	@:native("set_visible")
	public function set_visible_impl(enable:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_visible")
	public function set_visible(enable:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_visible")
	@:native("is_visible")
	public function get_visible():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_visible_in_tree")
	public function is_visible_in_tree():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("uncollapse_tree")
	public function uncollapse_tree():Void;
#if use_properties
	public extern inline function set_custom_minimum_height(v: Int): Int {
		set_custom_minimum_height_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_custom_minimum_height")
	@:native("set_custom_minimum_height")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_minimum_height_impl(@:meta("int32") height:Int):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("set_custom_minimum_height")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_minimum_height(@:meta("int32") height:Int):Void;

#end
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_minimum_height")
	public function get_custom_minimum_height():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_selectable")
	@:argMeta(0, ":meta"("int32"))
	public function set_selectable(@:meta("int32") column:Int, selectable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_selectable")
	@:argMeta(0, ":meta"("int32"))
	public function is_selectable(@:meta("int32") column:Int):Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility(null)
	@:nativeName("is_selected")
	@:argMeta(0, ":meta"("int32"))
	public function is_selected(@:meta("int32") column:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(972357352)
	@:hash_compatibility([1286410249])
	@:nativeName("select")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":default_value"("true"))
	#if gdscript @:argMeta(1, ":noNullPad"("true")) #end
	public function select(@:meta("int32") column:Int, @:default_value("true") #if gdscript @:noNullPad("true") #end set_as_cursor:Bool = true):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("deselect")
	@:argMeta(0, ":meta"("int32"))
	public function deselect(@:meta("int32") column:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_editable")
	@:argMeta(0, ":meta"("int32"))
	public function set_editable(@:meta("int32") column:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3067735520.)
	@:hash_compatibility(null)
	@:nativeName("is_editable")
	@:argMeta(0, ":meta"("int32"))
	public function is_editable(@:meta("int32") column:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2878471219.)
	@:hash_compatibility(null)
	@:nativeName("set_custom_color")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_color(@:meta("int32") column:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3457211756.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_color")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_color(@:meta("int32") column:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_custom_color")
	@:argMeta(0, ":meta"("int32"))
	public function clear_custom_color(@:meta("int32") column:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2637609184.)
	@:hash_compatibility(null)
	@:nativeName("set_custom_font")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_font(@:meta("int32") column:Int, font:godot.Font):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4244553094.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_font")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_font(@:meta("int32") column:Int):godot.Font;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_custom_font_size")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_custom_font_size(@:meta("int32") column:Int, @:meta("int32") font_size:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_custom_font_size")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_font_size(@:meta("int32") column:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(894174518)
	@:hash_compatibility(null)
	@:nativeName("set_custom_bg_color")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":default_value"("false"))
	#if gdscript @:argMeta(2, ":noNullPad"("false")) #end
	public function set_custom_bg_color(@:meta("int32") column:Int, color:godot.Color, @:default_value("false") #if gdscript @:noNullPad("false") #end just_outline:Bool = false):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("clear_custom_bg_color")
	@:argMeta(0, ":meta"("int32"))
	public function clear_custom_bg_color(@:meta("int32") column:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3457211756.)
	@:hash_compatibility(null)
	@:nativeName("get_custom_bg_color")
	@:argMeta(0, ":meta"("int32"))
	public function get_custom_bg_color(@:meta("int32") column:Int):godot.Color;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_custom_as_button")
	@:argMeta(0, ":meta"("int32"))
	public function set_custom_as_button(@:meta("int32") column:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_custom_set_as_button")
	@:argMeta(0, ":meta"("int32"))
	public function is_custom_set_as_button(@:meta("int32") column:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("clear_buttons")
	public function clear_buttons():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(973481897)
	@:hash_compatibility([1688223362, 1507727907])
	@:nativeName("add_button")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("-1"))
	#if gdscript @:argMeta(2, ":noNullPad"("-1")) #end
	@:argMeta(3, ":default_value"("false"))
	#if gdscript @:argMeta(3, ":noNullPad"("false")) #end
	@:argMeta(4, ":default_value"("\"\""))
	#if gdscript @:argMeta(4, ":noNullPad"("\"\"")) #end
	@:argMeta(5, ":default_value"("\"\""))
	#if gdscript @:argMeta(5, ":noNullPad"("\"\"")) #end
	public function add_button(@:meta("int32") column:Int, button:godot.Texture2D, @:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end id:Int = -1, @:default_value("false") #if gdscript @:noNullPad("false") #end disabled:Bool = false, @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end tooltip_text:String = "\"\"", @:default_value("\"\"") #if gdscript @:noNullPad("\"\"") #end description:String = "\"\""):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_button_count")
	@:argMeta(0, ":meta"("int32"))
	public function get_button_count(@:meta("int32") column:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1391810591)
	@:hash_compatibility(null)
	@:nativeName("get_button_tooltip_text")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_button_tooltip_text(@:meta("int32") column:Int, @:meta("int32") button_index:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_button_id")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_button_id(@:meta("int32") column:Int, @:meta("int32") button_index:Int):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3175239445.)
	@:hash_compatibility(null)
	@:nativeName("get_button_by_id")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_button_by_id(@:meta("int32") column:Int, @:meta("int32") id:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2165839948.)
	@:hash_compatibility(null)
	@:nativeName("get_button_color")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_button_color(@:meta("int32") column:Int, @:meta("int32") id:Int):godot.Color;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2584904275.)
	@:hash_compatibility(null)
	@:nativeName("get_button")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function get_button(@:meta("int32") column:Int, @:meta("int32") button_index:Int):godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2285447957.)
	@:hash_compatibility(null)
	@:nativeName("set_button_tooltip_text")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_button_tooltip_text(@:meta("int32") column:Int, @:meta("int32") button_index:Int, tooltip:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(176101966)
	@:hash_compatibility(null)
	@:nativeName("set_button")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_button(@:meta("int32") column:Int, @:meta("int32") button_index:Int, button:godot.Texture2D):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("erase_button")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function erase_button(@:meta("int32") column:Int, @:meta("int32") button_index:Int):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2285447957.)
	@:hash_compatibility(null)
	@:nativeName("set_button_description")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_button_description(@:meta("int32") column:Int, @:meta("int32") button_index:Int, description:String):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1383440665)
	@:hash_compatibility(null)
	@:nativeName("set_button_disabled")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_button_disabled(@:meta("int32") column:Int, @:meta("int32") button_index:Int, disabled:Bool):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3733378741.)
	@:hash_compatibility(null)
	@:nativeName("set_button_color")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_button_color(@:meta("int32") column:Int, @:meta("int32") button_index:Int, color:godot.Color):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2522259332.)
	@:hash_compatibility(null)
	@:nativeName("is_button_disabled")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function is_button_disabled(@:meta("int32") column:Int, @:meta("int32") button_index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_tooltip_text")
	@:argMeta(0, ":meta"("int32"))
	public function set_tooltip_text(@:meta("int32") column:Int, tooltip:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_tooltip_text")
	@:argMeta(0, ":meta"("int32"))
	public function get_tooltip_text(@:meta("int32") column:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3276431499.)
	@:hash_compatibility(null)
	@:nativeName("set_text_alignment")
	@:argMeta(0, ":meta"("int32"))
	public function set_text_alignment(@:meta("int32") column:Int, text_alignment:godot.HorizontalAlignment):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4171562184.)
	@:hash_compatibility(null)
	@:nativeName("get_text_alignment")
	@:argMeta(0, ":meta"("int32"))
	public function get_text_alignment(@:meta("int32") column:Int):godot.HorizontalAlignment;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_expand_right")
	@:argMeta(0, ":meta"("int32"))
	public function set_expand_right(@:meta("int32") column:Int, enable:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("get_expand_right")
	@:argMeta(0, ":meta"("int32"))
	public function get_expand_right(@:meta("int32") column:Int):Bool;
#if use_properties
	public extern inline function set_disable_folding(v: Bool): Bool {
		set_disable_folding_impl(cast v);
		return v;
	}

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_disable_folding")
	@:native("set_disable_folding")
	public function set_disable_folding_impl(disable:Bool):Void;

#else

	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_disable_folding")
	public function set_disable_folding(disable:Bool):Void;

#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_folding_disabled")
	@:native("is_folding_disabled")
	public function get_disable_folding():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("set_accept_children")
	public function set_accept_children(allowed:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("is_accepting_children")
	public function is_accepting_children():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(954243986)
	@:hash_compatibility(null)
	@:nativeName("create_child")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("-1"))
	#if gdscript @:argMeta(0, ":noNullPad"("-1")) #end
	public function create_child(@:meta("int32") @:default_value("-1") #if gdscript @:noNullPad("-1") #end index:Int = -1):godot.TreeItem;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1819951137)
	@:hash_compatibility(null)
	@:nativeName("add_child")
	public function add_child(child:godot.TreeItem):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1819951137)
	@:hash_compatibility(null)
	@:nativeName("remove_child")
	public function remove_child(child:godot.TreeItem):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2243340556.)
	@:hash_compatibility(null)
	@:nativeName("get_tree")
	public function get_tree():godot.Tree;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1514277247)
	@:hash_compatibility(null)
	@:nativeName("get_next")
	public function get_next():godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2768121250.)
	@:hash_compatibility(null)
	@:nativeName("get_prev")
	public function get_prev():godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1514277247)
	@:hash_compatibility(null)
	@:nativeName("get_parent")
	public function get_parent():godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1514277247)
	@:hash_compatibility(null)
	@:nativeName("get_first_child")
	public function get_first_child():godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1666920593)
	@:hash_compatibility(null)
	@:nativeName("get_next_in_tree")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_next_in_tree(@:default_value("false") #if gdscript @:noNullPad("false") #end wrap:Bool = false):godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1666920593)
	@:hash_compatibility(null)
	@:nativeName("get_prev_in_tree")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_prev_in_tree(@:default_value("false") #if gdscript @:noNullPad("false") #end wrap:Bool = false):godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1666920593)
	@:hash_compatibility(null)
	@:nativeName("get_next_visible")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_next_visible(@:default_value("false") #if gdscript @:noNullPad("false") #end wrap:Bool = false):godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1666920593)
	@:hash_compatibility(null)
	@:nativeName("get_prev_visible")
	@:argMeta(0, ":default_value"("false"))
	#if gdscript @:argMeta(0, ":noNullPad"("false")) #end
	public function get_prev_visible(@:default_value("false") #if gdscript @:noNullPad("false") #end wrap:Bool = false):godot.TreeItem;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(306700752)
	@:hash_compatibility(null)
	@:nativeName("get_child")
	@:argMeta(0, ":meta"("int32"))
	public function get_child(@:meta("int32") index:Int):godot.TreeItem;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_child_count")
	public function get_child_count():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2915620761.)
	@:hash_compatibility(null)
	@:nativeName("get_children")
	public function get_children():Array<godot.TreeItem>;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("get_index")
	public function get_index():Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1819951137)
	@:hash_compatibility(null)
	@:nativeName("move_before")
	public function move_before(item:godot.TreeItem):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1819951137)
	@:hash_compatibility(null)
	@:nativeName("move_after")
	public function move_after(item:godot.TreeItem):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(true)
	@:is_virtual(false)
	@:hash(2866548813.)
	@:hash_compatibility(null)
	@:nativeName("call_recursive")
	public function call_recursive(method:godot.StringName):Void;
}