/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class Tween extends godot.RefCounted {
	public function new();
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4049770449.)
	@:hash_compatibility(null)
	@:nativeName("tween_property")
	@:argMeta(0, ":meta"("required"))
	@:argMeta(3, ":meta"("double"))
	public function tween_property(@:meta("required") object:godot.Object, property:godot.NodePath, final_val:Dynamic, @:meta("double") duration:Float):godot.PropertyTweener;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(413360199)
	@:hash_compatibility(null)
	@:nativeName("tween_interval")
	@:argMeta(0, ":meta"("double"))
	public function tween_interval(@:meta("double") time:Float):godot.IntervalTweener;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1540176488)
	@:hash_compatibility(null)
	@:nativeName("tween_callback")
	public function tween_callback(callback:godot.Callable):godot.CallbackTweener;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2337877153.)
	@:hash_compatibility(null)
	@:nativeName("tween_method")
	@:argMeta(3, ":meta"("double"))
	public function tween_method(method:godot.Callable, from:Dynamic, to:Dynamic, @:meta("double") duration:Float):godot.MethodTweener;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1567358477)
	@:hash_compatibility(null)
	@:nativeName("tween_subtween")
	@:argMeta(0, ":meta"("required"))
	public function tween_subtween(@:meta("required") subtween:godot.Tween):godot.SubtweenTweener;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2242837462.)
	@:hash_compatibility(null)
	@:nativeName("tween_await")
	public function tween_await(signal:godot.Signal):godot.AwaitTweener;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(330693286)
	@:hash_compatibility(null)
	@:nativeName("custom_step")
	@:argMeta(0, ":meta"("double"))
	public function custom_step(@:meta("double") delta:Float):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("stop")
	public function stop():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("pause")
	public function pause():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("play")
	public function play():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("kill")
	public function kill():Void;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("get_total_elapsed_time")
	public function get_total_elapsed_time():Float;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("has_tweeners")
	public function has_tweeners():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_running")
	public function is_running():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("is_valid")
	public function is_valid():Bool;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2946786331.)
	@:hash_compatibility(null)
	@:nativeName("bind_node")
	@:argMeta(0, ":meta"("required"))
	public function bind_node(@:meta("required") node:godot.Node):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(855258840)
	@:hash_compatibility(null)
	@:nativeName("set_process_mode")
	public function set_process_mode(mode:godot.Tween_TweenProcessMode):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3363368837.)
	@:hash_compatibility(null)
	@:nativeName("set_pause_mode")
	public function set_pause_mode(mode:godot.Tween_TweenPauseMode):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1942052223)
	@:hash_compatibility(null)
	@:nativeName("set_ignore_time_scale")
	@:argMeta(0, ":default_value"("true"))
	#if gdscript @:argMeta(0, ":noNullPad"("true")) #end
	public function set_ignore_time_scale(@:default_value("true") #if gdscript @:noNullPad("true") #end ignore:Bool = true):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1942052223)
	@:hash_compatibility(null)
	@:nativeName("set_parallel")
	@:argMeta(0, ":default_value"("true"))
	#if gdscript @:argMeta(0, ":noNullPad"("true")) #end
	public function set_parallel(@:default_value("true") #if gdscript @:noNullPad("true") #end parallel:Bool = true):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2670836414.)
	@:hash_compatibility(null)
	@:nativeName("set_loops")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(0, ":default_value"("0"))
	#if gdscript @:argMeta(0, ":noNullPad"("0")) #end
	public function set_loops(@:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end loops:Int = 0):godot.Tween;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("get_loops_left")
	public function get_loops_left():Int;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3961971106.)
	@:hash_compatibility(null)
	@:nativeName("set_speed_scale")
	@:argMeta(0, ":meta"("float"))
	public function set_speed_scale(@:meta("float") speed:Float):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3965963875.)
	@:hash_compatibility(null)
	@:nativeName("set_trans")
	public function set_trans(trans:godot.Tween_TransitionType):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1208117252)
	@:hash_compatibility(null)
	@:nativeName("set_ease")
	public function set_ease(ease:godot.Tween_EaseType):godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3426978995.)
	@:hash_compatibility(null)
	@:nativeName("parallel")
	public function parallel():godot.Tween;
	@:return_value_meta("required")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3426978995.)
	@:hash_compatibility(null)
	@:nativeName("chain")
	public function chain():godot.Tween;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3452526450.)
	@:hash_compatibility(null)
	@:nativeName("interpolate_value")
	@:argMeta(2, ":meta"("double"))
	@:argMeta(3, ":meta"("double"))
	public static function interpolate_value(initial_value:Dynamic, delta_value:Dynamic, @:meta("double") elapsed_time:Float, @:meta("double") duration:Float, trans_type:godot.Tween_TransitionType, ease_type:godot.Tween_EaseType):Dynamic;
}