/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(false) @:is_instantiable(true) @:api_type("core") @:is_resource(false) @:is_node(true) extern class TwoBoneIK3D extends godot.IKModifier3D {
	public function new();
#if use_properties
	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count(get, set) : Int;
#else

	@:index(null)
	@:getter("get_setting_count")
	@:setter("set_setting_count")
	public var setting_count : Int;
#end
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2761262315.)
	@:hash_compatibility(null)
	@:nativeName("set_target_node")
	@:argMeta(0, ":meta"("int32"))
	public function set_target_node(@:meta("int32") index:Int, target_node:godot.NodePath):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_target_node")
	@:argMeta(0, ":meta"("int32"))
	public function get_target_node(@:meta("int32") index:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2761262315.)
	@:hash_compatibility(null)
	@:nativeName("set_pole_node")
	@:argMeta(0, ":meta"("int32"))
	public function set_pole_node(@:meta("int32") index:Int, pole_node:godot.NodePath):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(408788394)
	@:hash_compatibility(null)
	@:nativeName("get_pole_node")
	@:argMeta(0, ":meta"("int32"))
	public function get_pole_node(@:meta("int32") index:Int):godot.NodePath;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_root_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_root_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_root_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_root_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_root_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_root_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_root_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_root_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_middle_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_middle_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_middle_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_middle_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_middle_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_middle_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_middle_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_middle_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(258741388)
	@:hash_compatibility(null)
	@:nativeName("set_pole_direction")
	@:argMeta(0, ":meta"("int32"))
	public function set_pole_direction(@:meta("int32") index:Int, direction:godot.SkeletonModifier3D_SecondaryDirection):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(377522128)
	@:hash_compatibility(null)
	@:nativeName("get_pole_direction")
	@:argMeta(0, ":meta"("int32"))
	public function get_pole_direction(@:meta("int32") index:Int):godot.SkeletonModifier3D_SecondaryDirection;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1530502735)
	@:hash_compatibility(null)
	@:nativeName("set_pole_direction_vector")
	@:argMeta(0, ":meta"("int32"))
	public function set_pole_direction_vector(@:meta("int32") index:Int, vector:godot.Vector3):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(711720468)
	@:hash_compatibility(null)
	@:nativeName("get_pole_direction_vector")
	@:argMeta(0, ":meta"("int32"))
	public function get_pole_direction_vector(@:meta("int32") index:Int):godot.Vector3;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(501894301)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function set_end_bone_name(@:meta("int32") index:Int, bone_name:String):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_name")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_name(@:meta("int32") index:Int):String;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3937882851.)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("int32"))
	public function set_end_bone(@:meta("int32") index:Int, @:meta("int32") bone:Int):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone(@:meta("int32") index:Int):Int;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_use_virtual_end")
	@:argMeta(0, ":meta"("int32"))
	public function set_use_virtual_end(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_using_virtual_end")
	@:argMeta(0, ":meta"("int32"))
	public function is_using_virtual_end(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(300928843)
	@:hash_compatibility(null)
	@:nativeName("set_extend_end_bone")
	@:argMeta(0, ":meta"("int32"))
	public function set_extend_end_bone(@:meta("int32") index:Int, enabled:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1116898809)
	@:hash_compatibility(null)
	@:nativeName("is_end_bone_extended")
	@:argMeta(0, ":meta"("int32"))
	public function is_end_bone_extended(@:meta("int32") index:Int):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2838484201.)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_direction")
	@:argMeta(0, ":meta"("int32"))
	public function set_end_bone_direction(@:meta("int32") index:Int, bone_direction:godot.SkeletonModifier3D_BoneDirection):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1843036459)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_direction")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_direction(@:meta("int32") index:Int):godot.SkeletonModifier3D_BoneDirection;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1602489585)
	@:hash_compatibility(null)
	@:nativeName("set_end_bone_length")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":meta"("float"))
	public function set_end_bone_length(@:meta("int32") index:Int, @:meta("float") length:Float):Void;
	@:return_value_meta("float")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2339986948.)
	@:hash_compatibility(null)
	@:nativeName("get_end_bone_length")
	@:argMeta(0, ":meta"("int32"))
	public function get_end_bone_length(@:meta("int32") index:Int):Float;
}