/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class VideoStreamPlayback extends godot.Resource {
	public function new();
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_stop")
	public function _stop():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_play")
	public function _play():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_playing")
	public function _is_playing():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_set_paused")
	public function _set_paused(paused:Bool):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_paused")
	public function _is_paused():Bool;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_length")
	public function _get_length():Float;
	@:return_value_meta("double")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1740695150)
	@:hash_compatibility(null)
	@:nativeName("_get_playback_position")
	public function _get_playback_position():Float;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_seek")
	@:argMeta(0, ":meta"("double"))
	public function _seek(@:meta("double") time:Float):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1286410249)
	@:hash_compatibility(null)
	@:nativeName("_set_audio_track")
	@:argMeta(0, ":meta"("int32"))
	public function _set_audio_track(@:meta("int32") idx:Int):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3635182373.)
	@:hash_compatibility(null)
	@:nativeName("_get_texture")
	public function _get_texture():godot.Texture2D;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(373806689)
	@:hash_compatibility(null)
	@:nativeName("_update")
	@:argMeta(0, ":meta"("double"))
	public function _update(@:meta("double") delta:Float):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_channels")
	public function _get_channels():Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_mix_rate")
	public function _get_mix_rate():Int;
	@:return_value_meta("int32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(93876830)
	@:hash_compatibility([1369271885])
	@:nativeName("mix_audio")
	@:argMeta(0, ":meta"("int32"))
	@:argMeta(1, ":default_value"("PackedFloat32Array()"))
	#if gdscript @:argMeta(1, ":noNullPad"("PackedFloat32Array()")) #end
	@:argMeta(2, ":meta"("int32"))
	@:argMeta(2, ":default_value"("0"))
	#if gdscript @:argMeta(2, ":noNullPad"("0")) #end
	public function mix_audio(@:meta("int32") num_frames:Int, @:default_value("PackedFloat32Array()") #if gdscript @:noNullPad("PackedFloat32Array()") #end ?buffer:godot.PackedFloat32Array, @:meta("int32") @:default_value("0") #if gdscript @:noNullPad("0") #end offset:Int = 0):Int;
}