/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("Viewport.DebugDraw") #end @:is_bitfield(false) extern enum Viewport_DebugDraw {
	DEBUG_DRAW_DISABLED();
	DEBUG_DRAW_UNSHADED();
	DEBUG_DRAW_LIGHTING();
	DEBUG_DRAW_OVERDRAW();
	DEBUG_DRAW_WIREFRAME();
	DEBUG_DRAW_NORMAL_BUFFER();
	DEBUG_DRAW_VOXEL_GI_ALBEDO();
	DEBUG_DRAW_VOXEL_GI_LIGHTING();
	DEBUG_DRAW_VOXEL_GI_EMISSION();
	DEBUG_DRAW_SHADOW_ATLAS();
	DEBUG_DRAW_DIRECTIONAL_SHADOW_ATLAS();
	DEBUG_DRAW_SCENE_LUMINANCE();
	DEBUG_DRAW_SSAO();
	DEBUG_DRAW_SSIL();
	DEBUG_DRAW_PSSM_SPLITS();
	DEBUG_DRAW_DECAL_ATLAS();
	DEBUG_DRAW_SDFGI();
	DEBUG_DRAW_SDFGI_PROBES();
	DEBUG_DRAW_GI_BUFFER();
	DEBUG_DRAW_DISABLE_LOD();
	DEBUG_DRAW_CLUSTER_OMNI_LIGHTS();
	DEBUG_DRAW_CLUSTER_SPOT_LIGHTS();
	DEBUG_DRAW_CLUSTER_DECALS();
	DEBUG_DRAW_CLUSTER_REFLECTION_PROBES();
	DEBUG_DRAW_OCCLUDERS();
	DEBUG_DRAW_MOTION_VECTORS();
	DEBUG_DRAW_INTERNAL_BUFFER();
	DEBUG_DRAW_CLUSTER_AREA_LIGHTS();
	DEBUG_DRAW_AREA_LIGHT_ATLAS();
}