/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class VisualShaderNodeCustom extends godot.VisualShaderNode {
	public function new();
#if !use_properties
	@:index(null)
	@:getter("_is_initialized")
	@:setter("_set_initialized")
	public var initialized : Bool;
#end
#if !use_properties
	@:index(null)
	@:getter("_get_properties")
	@:setter("_set_properties")
	public var properties : String;
#end
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_name")
	public function _get_name():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_description")
	public function _get_description():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(201670096)
	@:hash_compatibility(null)
	@:nativeName("_get_category")
	public function _get_category():String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1287173294)
	@:hash_compatibility(null)
	@:nativeName("_get_return_icon_type")
	public function _get_return_icon_type():godot.VisualShaderNode_PortType;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_input_port_count")
	public function _get_input_port_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4102573379.)
	@:hash_compatibility(null)
	@:nativeName("_get_input_port_type")
	@:argMeta(0, ":meta"("int32"))
	public function _get_input_port_type(@:meta("int32") port:Int):godot.VisualShaderNode_PortType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_input_port_name")
	@:argMeta(0, ":meta"("int32"))
	public function _get_input_port_name(@:meta("int32") port:Int):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4227898402.)
	@:hash_compatibility(null)
	@:nativeName("_get_input_port_default_value")
	@:argMeta(0, ":meta"("int32"))
	public function _get_input_port_default_value(@:meta("int32") port:Int):Dynamic;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1894493699)
	@:hash_compatibility(null)
	@:nativeName("_get_default_input_port")
	public function _get_default_input_port(type:godot.VisualShaderNode_PortType):Int;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_output_port_count")
	public function _get_output_port_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4102573379.)
	@:hash_compatibility(null)
	@:nativeName("_get_output_port_type")
	@:argMeta(0, ":meta"("int32"))
	public function _get_output_port_type(@:meta("int32") port:Int):godot.VisualShaderNode_PortType;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_output_port_name")
	@:argMeta(0, ":meta"("int32"))
	public function _get_output_port_name(@:meta("int32") port:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_property_count")
	public function _get_property_count():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(844755477)
	@:hash_compatibility(null)
	@:nativeName("_get_property_name")
	@:argMeta(0, ":meta"("int32"))
	public function _get_property_name(@:meta("int32") index:Int):String;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("_get_property_default_index")
	@:argMeta(0, ":meta"("int32"))
	public function _get_property_default_index(@:meta("int32") index:Int):Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(647634434)
	@:hash_compatibility(null)
	@:nativeName("_get_property_options")
	@:argMeta(0, ":meta"("int32"))
	public function _get_property_options(@:meta("int32") index:Int):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4287175357.)
	@:hash_compatibility(null)
	@:nativeName("_get_code")
	public function _get_code(input_vars:Array<String>, output_vars:Array<String>, mode:godot.Shader_Mode, type:godot.VisualShader_Type):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1924221678)
	@:hash_compatibility(null)
	@:nativeName("_get_func_code")
	public function _get_func_code(mode:godot.Shader_Mode, type:godot.VisualShader_Type):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3956542358.)
	@:hash_compatibility(null)
	@:nativeName("_get_global_code")
	public function _get_global_code(mode:godot.Shader_Mode):String;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_highend")
	public function _is_highend():Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1932120545)
	@:hash_compatibility(null)
	@:nativeName("_is_available")
	public function _is_available(mode:godot.Shader_Mode, type:godot.VisualShader_Type):Bool;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(923996154)
	@:hash_compatibility(null)
	@:nativeName("get_option_index")
	@:argMeta(0, ":meta"("int32"))
	public function get_option_index(@:meta("int32") option:Int):Int;
}