/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class WebRTCPeerConnectionExtension extends godot.WebRTCPeerConnection {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2275710506.)
	@:hash_compatibility(null)
	@:nativeName("_get_connection_state")
	public function _get_connection_state():godot.WebRTCPeerConnection_ConnectionState;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4262591401.)
	@:hash_compatibility(null)
	@:nativeName("_get_gathering_state")
	public function _get_gathering_state():godot.WebRTCPeerConnection_GatheringState;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3342956226.)
	@:hash_compatibility(null)
	@:nativeName("_get_signaling_state")
	public function _get_signaling_state():godot.WebRTCPeerConnection_SignalingState;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1494659981)
	@:hash_compatibility(null)
	@:nativeName("_initialize")
	public function _initialize(config:godot.Dictionary):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4111292546.)
	@:hash_compatibility(null)
	@:nativeName("_create_data_channel")
	public function _create_data_channel(label:String, config:godot.Dictionary):godot.WebRTCDataChannel;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("_create_offer")
	public function _create_offer():godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("_set_remote_description")
	public function _set_remote_description(type:String, sdp:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("_set_local_description")
	public function _set_local_description(type:String, sdp:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3958950400.)
	@:hash_compatibility(null)
	@:nativeName("_add_ice_candidate")
	@:argMeta(1, ":meta"("int32"))
	public function _add_ice_candidate(sdp_mid_name:String, @:meta("int32") sdp_mline_index:Int, sdp_name:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("_poll")
	public function _poll():godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_close")
	public function _close():Void;
}