/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class WebRTCPeerConnection extends godot.RefCounted {
	public function new();
	@:is_const(false)
	@:is_static(true)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3304788590.)
	@:hash_compatibility(null)
	@:nativeName("set_default_extension")
	public static function set_default_extension(extension_class:godot.StringName):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2625064318.)
	@:hash_compatibility(null)
	@:nativeName("initialize")
	@:argMeta(0, ":default_value"("{}"))
	#if gdscript @:argMeta(0, ":noNullPad"("{}")) #end
	public function initialize(@:default_value("{}") #if gdscript @:noNullPad("{}") #end ?configuration:godot.Dictionary):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(1288557393)
	@:hash_compatibility([3997447457.])
	@:nativeName("create_data_channel")
	@:argMeta(1, ":default_value"("{}"))
	#if gdscript @:argMeta(1, ":noNullPad"("{}")) #end
	public function create_data_channel(label:String, @:default_value("{}") #if gdscript @:noNullPad("{}") #end ?options:godot.Dictionary):godot.WebRTCDataChannel;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("create_offer")
	public function create_offer():godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("set_local_description")
	public function set_local_description(type:String, sdp:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(852856452)
	@:hash_compatibility(null)
	@:nativeName("set_remote_description")
	public function set_remote_description(type:String, sdp:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3958950400.)
	@:hash_compatibility(null)
	@:nativeName("add_ice_candidate")
	@:argMeta(1, ":meta"("int32"))
	public function add_ice_candidate(media:String, @:meta("int32") index:Int, name:String):godot.Error;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(166280745)
	@:hash_compatibility(null)
	@:nativeName("poll")
	public function poll():godot.Error;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("close")
	public function close():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(2275710506.)
	@:hash_compatibility(null)
	@:nativeName("get_connection_state")
	public function get_connection_state():godot.WebRTCPeerConnection_ConnectionState;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(4262591401.)
	@:hash_compatibility(null)
	@:nativeName("get_gathering_state")
	public function get_gathering_state():godot.WebRTCPeerConnection_GatheringState;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(3342956226.)
	@:hash_compatibility(null)
	@:nativeName("get_signaling_state")
	public function get_signaling_state():godot.WebRTCPeerConnection_SignalingState;
}