/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:cppEnum @:generated_godot_api @:bindings_api_type("global_enum") #if gdscript @:native("XRHandTracker.HandJoint") #end @:is_bitfield(false) extern enum XRHandTracker_HandJoint {
	HAND_JOINT_PALM();
	HAND_JOINT_WRIST();
	HAND_JOINT_THUMB_METACARPAL();
	HAND_JOINT_THUMB_PHALANX_PROXIMAL();
	HAND_JOINT_THUMB_PHALANX_DISTAL();
	HAND_JOINT_THUMB_TIP();
	HAND_JOINT_INDEX_FINGER_METACARPAL();
	HAND_JOINT_INDEX_FINGER_PHALANX_PROXIMAL();
	HAND_JOINT_INDEX_FINGER_PHALANX_INTERMEDIATE();
	HAND_JOINT_INDEX_FINGER_PHALANX_DISTAL();
	HAND_JOINT_INDEX_FINGER_TIP();
	HAND_JOINT_MIDDLE_FINGER_METACARPAL();
	HAND_JOINT_MIDDLE_FINGER_PHALANX_PROXIMAL();
	HAND_JOINT_MIDDLE_FINGER_PHALANX_INTERMEDIATE();
	HAND_JOINT_MIDDLE_FINGER_PHALANX_DISTAL();
	HAND_JOINT_MIDDLE_FINGER_TIP();
	HAND_JOINT_RING_FINGER_METACARPAL();
	HAND_JOINT_RING_FINGER_PHALANX_PROXIMAL();
	HAND_JOINT_RING_FINGER_PHALANX_INTERMEDIATE();
	HAND_JOINT_RING_FINGER_PHALANX_DISTAL();
	HAND_JOINT_RING_FINGER_TIP();
	HAND_JOINT_PINKY_FINGER_METACARPAL();
	HAND_JOINT_PINKY_FINGER_PHALANX_PROXIMAL();
	HAND_JOINT_PINKY_FINGER_PHALANX_INTERMEDIATE();
	HAND_JOINT_PINKY_FINGER_PHALANX_DISTAL();
	HAND_JOINT_PINKY_FINGER_TIP();
	HAND_JOINT_MAX();
}