/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("core") @:is_resource(true) @:is_node(false) extern class XRInterfaceExtension extends godot.XRInterface {
	public function new();
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2002593661)
	@:hash_compatibility(null)
	@:nativeName("_get_name")
	public function _get_name():godot.StringName;
	@:return_value_meta("uint32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_capabilities")
	public function _get_capabilities():Int;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_is_initialized")
	public function _is_initialized():Bool;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2240911060.)
	@:hash_compatibility(null)
	@:nativeName("_initialize")
	public function _initialize():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_uninitialize")
	public function _uninitialize():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3102165223.)
	@:hash_compatibility(null)
	@:nativeName("_get_system_info")
	public function _get_system_info():godot.Dictionary;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2693703033.)
	@:hash_compatibility(null)
	@:nativeName("_supports_play_area_mode")
	public function _supports_play_area_mode(mode:godot.XRInterface_PlayAreaMode):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1615132885)
	@:hash_compatibility(null)
	@:nativeName("_get_play_area_mode")
	public function _get_play_area_mode():godot.XRInterface_PlayAreaMode;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2693703033.)
	@:hash_compatibility(null)
	@:nativeName("_set_play_area_mode")
	public function _set_play_area_mode(mode:godot.XRInterface_PlayAreaMode):Bool;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(497664490)
	@:hash_compatibility(null)
	@:nativeName("_get_play_area")
	public function _get_play_area():godot.PackedVector3Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1497962370)
	@:hash_compatibility(null)
	@:nativeName("_get_render_target_size")
	public function _get_render_target_size():godot.Vector2;
	@:return_value_meta("uint32")
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2455072627.)
	@:hash_compatibility(null)
	@:nativeName("_get_view_count")
	public function _get_view_count():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4183770049.)
	@:hash_compatibility(null)
	@:nativeName("_get_camera_transform")
	public function _get_camera_transform():godot.Transform3D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(518934792)
	@:hash_compatibility(null)
	@:nativeName("_get_transform_for_view")
	@:argMeta(0, ":meta"("uint32"))
	public function _get_transform_for_view(@:meta("uint32") view:Int, cam_transform:godot.Transform3D):godot.Transform3D;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(4067457445.)
	@:hash_compatibility(null)
	@:nativeName("_get_projection_for_view")
	@:argMeta(0, ":meta"("uint32"))
	@:argMeta(1, ":meta"("double"))
	@:argMeta(2, ":meta"("double"))
	@:argMeta(3, ":meta"("double"))
	public function _get_projection_for_view(@:meta("uint32") view:Int, @:meta("double") aspect:Float, @:meta("double") z_near:Float, @:meta("double") z_far:Float):godot.PackedFloat64Array;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_get_vrs_texture")
	public function _get_vrs_texture():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1500923256)
	@:hash_compatibility(null)
	@:nativeName("_get_vrs_texture_format")
	public function _get_vrs_texture_format():godot.XRInterface_VRSTextureFormat;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_process")
	public function _process():Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_pre_render")
	public function _pre_render():Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3521089500.)
	@:hash_compatibility(null)
	@:nativeName("_pre_draw_viewport")
	public function _pre_draw_viewport(render_target:godot.RID):Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1378122625)
	@:hash_compatibility(null)
	@:nativeName("_post_draw_viewport")
	public function _post_draw_viewport(render_target:godot.RID, screen_rect:godot.Rect2):Void;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3218959716.)
	@:hash_compatibility(null)
	@:nativeName("_end_frame")
	public function _end_frame():Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1139954409)
	@:hash_compatibility(null)
	@:nativeName("_get_suggested_tracker_names")
	public function _get_suggested_tracker_names():godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(1761182771)
	@:hash_compatibility(null)
	@:nativeName("_get_suggested_pose_names")
	public function _get_suggested_pose_names(tracker_name:godot.StringName):godot.PackedStringArray;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(167423259)
	@:hash_compatibility(null)
	@:nativeName("_get_tracking_status")
	public function _get_tracking_status():godot.XRInterface_TrackingStatus;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3752640163.)
	@:hash_compatibility(null)
	@:nativeName("_trigger_haptic_pulse")
	@:argMeta(2, ":meta"("double"))
	@:argMeta(3, ":meta"("double"))
	@:argMeta(4, ":meta"("double"))
	@:argMeta(5, ":meta"("double"))
	public function _trigger_haptic_pulse(action_name:String, tracker_name:godot.StringName, @:meta("double") frequency:Float, @:meta("double") amplitude:Float, @:meta("double") duration_sec:Float, @:meta("double") delay_sec:Float):Void;
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(36873697)
	@:hash_compatibility(null)
	@:nativeName("_get_anchor_detection_is_enabled")
	public function _get_anchor_detection_is_enabled():Bool;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(2586408642.)
	@:hash_compatibility(null)
	@:nativeName("_set_anchor_detection_is_enabled")
	public function _set_anchor_detection_is_enabled(enabled:Bool):Void;
	@:return_value_meta("int32")
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(3905245786.)
	@:hash_compatibility(null)
	@:nativeName("_get_camera_feed_id")
	public function _get_camera_feed_id():Int;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_get_color_texture")
	public function _get_color_texture():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_get_depth_texture")
	public function _get_depth_texture():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("_get_velocity_texture")
	public function _get_velocity_texture():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("get_color_texture")
	public function get_color_texture():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("get_depth_texture")
	public function get_depth_texture():godot.RID;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(529393457)
	@:hash_compatibility(null)
	@:nativeName("get_velocity_texture")
	public function get_velocity_texture():godot.RID;
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(258596971)
	@:hash_compatibility(null)
	@:nativeName("add_blit")
	@:argMeta(4, ":meta"("uint32"))
	@:argMeta(7, ":meta"("double"))
	@:argMeta(8, ":meta"("double"))
	@:argMeta(9, ":meta"("double"))
	@:argMeta(10, ":meta"("double"))
	public function add_blit(render_target:godot.RID, src_rect:godot.Rect2, dst_rect:godot.Rect2i, use_layer:Bool, @:meta("uint32") layer:Int, apply_lens_distortion:Bool, eye_center:godot.Vector2, @:meta("double") k1:Float, @:meta("double") k2:Float, @:meta("double") upscale:Float, @:meta("double") aspect_ratio:Float):Void;
	@:return_value_meta(null)
	@:is_const(false)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(false)
	@:hash(41030802)
	@:hash_compatibility(null)
	@:nativeName("get_render_target_texture")
	public function get_render_target_texture(render_target:godot.RID):godot.RID;
}