package;

// AUTO-GENERATED BY HaxeGD.
// References every Haxe module under source/ so Reflaxe compiles it.
// Do not edit manually.
import entities.player.Flashlight as HaxeGD_Auto_0;
import entities.player.Movement as HaxeGD_Auto_1;
import entities.player.Player as HaxeGD_Auto_2;
import entities.player.Variables as HaxeGD_Auto_3;
import interactables.Door as HaxeGD_Auto_4;
import interactables.FlashlightCharger as HaxeGD_Auto_5;
import interactables.Interactable as HaxeGD_Auto_6;

class ClassAutoLoader
{
    static function main():Void
    {
        HaxeGD_Auto_0;
        HaxeGD_Auto_1;
        HaxeGD_Auto_2;
        HaxeGD_Auto_3;
        HaxeGD_Auto_4;
        HaxeGD_Auto_5;
        HaxeGD_Auto_6;
    }
}
